OPM/ResInsight

- ApplicationCode/Application/RiaPreferences.cpp
- ApplicationCode/Application/RiaPreferences.h
- ApplicationCode/Application/Tools/RiaQDateTimeTools.cpp
- ApplicationCode/Application/Tools/RiaQDateTimeTools.h
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.h
- ApplicationCode/UserInterface/RiuFlowCharacteristicsPlot.cpp
- ApplicationCode/UserInterface/RiuQwtPlotTools.cpp
- ApplicationCode/UserInterface/RiuQwtPlotTools.h
- ApplicationCode/UserInterface/RiuResultQwtPlot.cpp
- ApplicationCode/UserInterface/RiuSummaryQwtPlot.cpp
- ApplicationCode/UserInterface/RiuSummaryQwtPlot.h
- Fwk/AppFwk/cafProjectDataModel/cafPdmXml/cafInternalPdmStreamOperators.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmXml/cafInternalPdmStreamOperators.h
- Fwk/AppFwk/cafUserInterface/CMakeLists.txt
- Fwk/AppFwk/cafUserInterface/cafPdmUiDefaultObjectEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTimeEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTimeEditor.h
Also add setting to summary time axis
> #2082 Support custom date time format

- ApplicationCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlot.cpp
> #4622 Make sure inverted cross plot axis values are assigned correctly

- ApplicationCode/Application/RiaPreferences.cpp
- ApplicationCode/Application/RiaPreferences.h
- ApplicationCode/Commands/PlotTemplateCommands/CMakeLists_files.cmake
- ApplicationCode/Commands/PlotTemplateCommands/RicCreatePlotFromSelectionFeature.cpp
- ApplicationCode/Commands/PlotTemplateCommands/RicCreatePlotFromSelectionFeature.h
- ApplicationCode/Commands/PlotTemplateCommands/RicReloadPlotTemplatesFeature.cpp
- ApplicationCode/Commands/PlotTemplateCommands/RicReloadPlotTemplatesFeature.h
- ApplicationCode/Commands/PlotTemplateCommands/RicSavePlotTemplateFeature.cpp
- ApplicationCode/Commands/PlotTemplateCommands/RicSelectPlotTemplateUi.cpp
- ApplicationCode/Commands/PlotTemplateCommands/RicSelectPlotTemplateUi.h
- ApplicationCode/Commands/PlotTemplateCommands/RicSummaryPlotTemplateTools.cpp
- ApplicationCode/Commands/PlotTemplateCommands/RicSummaryPlotTemplateTools.h
- ApplicationCode/ProjectDataModel/PlotTemplates/RimPlotTemplateFolderItem.cpp
- ApplicationCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationCode/ProjectDataModel/RimDialogData.cpp
- ApplicationCode/ProjectDataModel/RimDialogData.h
- ApplicationCode/ProjectDataModel/RimProject.cpp
- ApplicationCode/UserInterface/RiuSummaryQwtPlot.cpp
Adjust save and load of templates
Add save path to preferences
> #4733 Summary Template : Add reload of templates 

- ApplicationCode/FileInterface/RifEclipseOutputFileTools.cpp
User reports issues with import of dynamic properties for E300 simulation. E100 works as expected. For some reason, the date for all time steps for the E300 simulations is identical. This fix detects the situation, and use the double value from days vector as offset.
> #4770 Incorrect reporting of date for E300 in combination with lab units 

- ApplicationCode/Application/RiaApplication.cpp
- ApplicationCode/Application/RiaGuiApplication.cpp
- ApplicationCode/Application/RiaPreferences.cpp
- ApplicationCode/Application/RiaPreferences.h
- ApplicationCode/Commands/ApplicationCommands/RicLaunchRegressionTestsFeature.cpp
- ApplicationCode/Commands/ExportCommands/RicExportEclipseSectorModelFeature.cpp
- ApplicationCode/Commands/HoloLensCommands/RicHoloLensCreateSessionFeature.cpp
- ApplicationCode/Commands/PlotTemplateCommands/RicCreatePlotFromTemplateByShortcutFeature.cpp
- ApplicationCode/Commands/PlotTemplateCommands/RicSavePlotTemplateFeature.cpp
- ApplicationCode/ProjectDataModel/RimEclipseResultCase.cpp
- ApplicationCode/UserInterface/RiuMainWindow.cpp
> Preferences : More robust storing of data to registry 

- ApplicationCode/ProjectDataModel/Summary/RimEnsembleCurveFilterCollection.cpp
- ApplicationCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp
- ApplicationCode/ProjectDataModel/Summary/RimEnsembleCurveSet.h
> Ensemble Colors : Show color control in curve filter property editor

- ApplicationCode/Application/RiaPreferences.cpp
- ApplicationCode/Application/RiaPreferences.h
- ApplicationCode/ProjectDataModel/Flow/RimFlowCharacteristicsPlot.cpp
- ApplicationCode/ProjectDataModel/Flow/RimWellAllocationPlot.cpp
- ApplicationCode/ProjectDataModel/Flow/RimWellPltPlot.cpp
- ApplicationCode/ProjectDataModel/Flow/RimWellRftPlot.cpp
- ApplicationCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlot.cpp
- ApplicationCode/ProjectDataModel/Rim3dView.cpp
- ApplicationCode/ProjectDataModel/RimPlotInterface.h
- ApplicationCode/ProjectDataModel/RimProject.cpp
- ApplicationCode/ProjectDataModel/RimViewWindow.cpp
- ApplicationCode/ProjectDataModel/RimViewWindow.h
- ApplicationCode/ProjectDataModel/RimWellBoreStabilityPlot.cpp
- ApplicationCode/ProjectDataModel/RimWellLogPlot.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationCode/UserInterface/RiuQwtPlotWidget.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeSelectionEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewEditor.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewQModel.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewQModel.h
* Remove it from property editor
> Add a view id tag to project tree and tooltip

- ApplicationCode/Commands/EclipseCommands/RicAddEclipseInputPropertyFeature.cpp
- ApplicationCode/Commands/ExportCommands/RicSaveEclipseInputPropertyFeature.cpp
- ApplicationCode/FileInterface/CMakeLists_files.cmake
- ApplicationCode/FileInterface/RifEclipseInputFileTools.cpp
- ApplicationCode/FileInterface/RifEclipseInputPropertyLoader.cpp
- ApplicationCode/FileInterface/RifEclipseInputPropertyLoader.h
- ApplicationCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationCode/ProjectDataModel/RimEclipseCase.cpp
- ApplicationCode/ProjectDataModel/RimEclipseCase.h
- ApplicationCode/ProjectDataModel/RimEclipseInputCase.cpp
- ApplicationCode/ProjectDataModel/RimEclipseInputCase.h
- ApplicationCode/ProjectDataModel/RimEclipseResultCase.cpp
- ApplicationCode/ProjectDataModel/RimEclipseResultCase.h
> Import ascii data to simulation case

- ApplicationCode/ProjectDataModel/Flow/RimWellRftPlot.cpp
> Ensemble RFT : Avoid selection of large number of time steps

- ApplicationCode/CMakeLists.txt
- CMakeLists.txt
> AppFwk : Include cafCommandFeatures in ResInsight

- ApplicationCode/Application/Tools/RiaCurveDataTools.h
- ApplicationCode/ProjectDataModel/RimPlotCurve.cpp
- ApplicationCode/ProjectDataModel/RimPlotCurve.h
- ApplicationCode/ProjectDataModel/RimWellLogCurve.cpp
- ApplicationCode/ProjectDataModel/RimWellLogRftCurve.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- ApplicationCode/UserInterface/RiuQwtPlotCurve.cpp
- ApplicationCode/UserInterface/RiuQwtPlotCurve.h
> Curve Error Bars : Move to RimPlotCurve 

- ApplicationCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp
- ApplicationCode/ProjectDataModel/Summary/RimEnsembleStatistics.cpp
- ApplicationCode/ProjectDataModel/Summary/RimEnsembleStatistics.h
- ApplicationCode/ProjectDataModel/Summary/RimEnsembleStatisticsCase.cpp
- ApplicationCode/ProjectDataModel/Summary/RimEnsembleStatisticsCase.h
Fixes a crash in computation
Add support for include of partial curves
Closes #5095 
Closes #4155
> Improve ensemble statistics

- ApplicationCode/Application/Tools/RiaSimWellBranchTools.cpp
> #5146 Make well log curves work on statistics cases

- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationCode/UserInterface/RiuQwtPlotWheelZoomer.cpp
- ApplicationCode/UserInterface/RiuQwtPlotWheelZoomer.h
- ApplicationCode/UserInterface/RiuSummaryQwtPlot.cpp
- ApplicationCode/UserInterface/RiuSummaryQwtPlot.h
* Limit the amount to scroll at one time and set a fixed minimum
> #5150 Improve wheel zoom with logarithmic axes

- ApplicationCode/ProjectDataModel/RimEclipseResultCase.cpp
- ApplicationCode/ProjectDataModel/RimEclipseStatisticsCase.cpp
- ApplicationCode/ProjectDataModel/RimEclipseStatisticsCaseEvaluator.cpp
Support grid cases with no dynamic data present.
Closes #5158
> Grid Case Group: Allow statistics on static data only 

- ApplicationCode/Application/Tools/RiaRegressionTestRunner.cpp
- ApplicationCode/Application/Tools/RiaRegressionTestRunner.h
- ApplicationCode/CommandFileInterface/RicfExportSnapshots.cpp
- ApplicationCode/CommandFileInterface/RicfOpenProject.cpp
- ApplicationCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlotCurve.cpp
- ApplicationCode/UserInterface/RiuMainWindowTools.cpp
> Fix snapshot image size issues

- ApplicationCode/Commands/WellLogCommands/RicNewWellBoreStabilityPlotFeature.cpp
- ApplicationCode/Commands/WellPathCommands/RicImportWellMeasurementsFeature.cpp
- ApplicationCode/ModelVisualization/RivWellPathPartMgr.cpp
- ApplicationCode/ProjectDataModel/CMakeLists_files.cmake
- ApplicationCode/ProjectDataModel/RimEclipseView.cpp
- ApplicationCode/ProjectDataModel/RimGeoMechView.cpp
- ApplicationCode/ProjectDataModel/RimGridView.cpp
- ApplicationCode/ProjectDataModel/RimGridView.h
- ApplicationCode/ProjectDataModel/RimRegularLegendConfig.cpp
- ApplicationCode/ProjectDataModel/RimWellLogCurveCommonDataSource.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurement.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurement.h
- ApplicationCode/ProjectDataModel/RimWellMeasurementCurve.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementCurve.h
- ApplicationCode/ProjectDataModel/RimWellMeasurementInView.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementInView.h
- ApplicationCode/ProjectDataModel/RimWellMeasurementInViewCollection.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementInViewCollection.h
Closes #5001, #5110, and #5125.
> Well measurement reorg

- ApplicationCode/UserInterface/RiuSummaryCurveDefSelection.cpp
The INPUT_ID was not set correctly, and has been removed. The calculation id is
now appended to the vector name, and extracted again when selecting an item.
> #5278 Fix selection of calculated curves in summary selction dialog

- ApplicationCode/Commands/CMakeLists_files.cmake
- ApplicationCode/Commands/CompletionExportCommands/RicExportCompletionsForVisibleWellPathsFeature.cpp
- ApplicationCode/Commands/RicDeleteWellMeasurementFilePathFeature.cpp
- ApplicationCode/Commands/RicDeleteWellMeasurementFilePathFeature.h
- ApplicationCode/Commands/WellPathCommands/RicImportWellMeasurementsFeature.cpp
- ApplicationCode/Commands/WellPathCommands/RicWellPathPickEventHandler.cpp
- ApplicationCode/ProjectDataModel/CMakeLists_files.cmake
- ApplicationCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurement.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurement.h
- ApplicationCode/ProjectDataModel/RimWellMeasurementCollection.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementCollection.h
- ApplicationCode/ProjectDataModel/RimWellMeasurementFilePath.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementFilePath.h
- ApplicationCode/ProjectDataModel/RimWellMeasurementInViewCollection.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementInViewCollection.h
- ApplicationCode/ProjectDataModel/RimWellPathCollection.cpp
- ApplicationCode/ProjectDataModel/RimWellPathCollection.h
> Well measurements delete imported files 5116

- ApplicationCode/Commands/FlowCommands/CMakeLists_files.cmake
- ApplicationCode/Commands/FlowCommands/RicShowCumulativePhasePlotFeature.cpp
- ApplicationCode/Commands/FlowCommands/RicShowCumulativePhasePlotFeature.h
- ApplicationCode/FileInterface/RifEclipseOutputFileTools.cpp
- ApplicationCode/ProjectDataModel/Flow/RimFlowPlotCollection.cpp
- ApplicationCode/ProjectDataModel/Flow/RimFlowPlotCollection.h
- ApplicationCode/ProjectDataModel/Flow/RimWellAllocationPlot.cpp
- ApplicationCode/ProjectDataModel/Flow/RimWellDistributionPlot.cpp
- ApplicationCode/ProjectDataModel/Flow/RimWellDistributionPlot.h
- ApplicationCode/ProjectDataModel/Flow/RimWellDistributionPlotCollection.cpp
- ApplicationCode/ProjectDataModel/Flow/RimWellDistributionPlotCollection.h
- ApplicationCode/ReservoirDataModel/RigTofAccumulatedPhaseFractionsCalculator.cpp
- ApplicationCode/UserInterface/RiuWellAllocationPlot.cpp
> Fix bug in E300

- ApplicationCode/ProjectDataModel/RimEclipseResultDefinition.cpp
- ApplicationCode/ProjectDataModel/RimEclipseResultDefinition.h
> #5043 Input Property: Show file path in result selection panel

- ApplicationCode/Commands/CMakeLists_files.cmake
- ApplicationCode/Commands/RicReloadWellMeasurementsFeature.cpp
- ApplicationCode/Commands/RicReloadWellMeasurementsFeature.h
- ApplicationCode/Commands/RicWellMeasurementImportTools.cpp
- ApplicationCode/Commands/RicWellMeasurementImportTools.h
- ApplicationCode/Commands/WellPathCommands/RicImportWellMeasurementsFeature.cpp
- ApplicationCode/ModelVisualization/RivWellPathPartMgr.cpp
- ApplicationCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementCurve.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementFilter.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementFilter.h
- ApplicationCode/ProjectDataModel/RimWellMeasurementInView.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementInView.h
- ApplicationCode/ProjectDataModel/RimWellMeasurementInViewCollection.cpp
> Well measurement reload file 5111

- ApplicationCode/Application/RiaGuiApplication.cpp
- ApplicationCode/Application/RiaPreferences.cpp
- ApplicationCode/Application/RiaPreferences.h
- ApplicationCode/ProjectDataModel/Rim3dView.cpp
- ApplicationCode/ProjectDataModel/RimEclipseCase.cpp
> Fault preferences

- ApplicationCode/ProjectDataModel/RimEclipseCellColors.cpp
> Color Legend : Set log as default color legend for results based on substring match 

- ApplicationCode/Application/RiaSummaryCurveDefinition.cpp
- ApplicationCode/Commands/SummaryPlotCommands/RicSummaryPlotFeatureImpl.cpp
- ApplicationCode/FileInterface/RifDataSourceForRftPlt.cpp
- ApplicationCode/ProjectDataModel/RimOilField.cpp
- ApplicationCode/ProjectDataModel/RimOilField.h
- ApplicationCode/ProjectDataModel/RimSummaryCalculationVariable.cpp
- ApplicationCode/ProjectDataModel/RimWellLogRftCurve.cpp
- ApplicationCode/ProjectDataModel/Summary/RimDerivedEnsembleCase.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCase.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCase.h
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCurveAutoName.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlotFilterTextCurveSetEditor.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlotNameHelper.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp
- ApplicationCode/UserInterface/RiuSummaryCurveDefSelection.cpp
- ApplicationCode/UserInterface/RiuSummaryQwtPlot.cpp
> Summary Case : Add public methods displayCaseName and nativeCaseName 

- ApplicationCode/GeoMech/GeoMechDataModel/CMakeLists.txt
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.h
- ApplicationCode/GeoMech/GeoMechDataModel/RigHexGradientTools.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigHexGradientTools.h
- ApplicationCode/UnitTests/CMakeLists_files.cmake
- ApplicationCode/UnitTests/RigHexGradientTools-Test.cpp
- Fwk/AppFwk/cafHexInterpolator/cafHexInterpolator.h
> Calculate stress gradients 4669

- ApplicationCode/Commands/EclipseCommands/RicAddEclipseInputPropertyFeature.cpp
- ApplicationCode/Commands/EclipseCommands/RicAddEclipseInputPropertyFeature.h
- ApplicationCode/ProjectDataModel/RimContextCommandBuilder.cpp
> #5068 Add "Input Property" command to menu of Cell Result and 3D view.

- ApplicationCode/Commands/RicWellMeasurementImportTools.cpp
- ApplicationCode/ModelVisualization/RivWellPathPartMgr.cpp
- ApplicationCode/ModelVisualization/RivWellPathPartMgr.h
- ApplicationCode/ModelVisualization/RivWellPathsPartMgr.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementInView.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementInView.h
- ApplicationCode/UserInterface/RiuMainWindow.cpp
> Well measurement ui improvements 5368

- ApplicationCode/Application/RiaApplication.cpp
- ApplicationCode/Application/RiaApplication.h
- ApplicationCode/Application/Tools/RiaRegressionTestRunner.cpp
> Regression : Make sure all project settings are wiped before next run 

- ApplicationCode/Commands/CompletionExportCommands/RicExportFractureCompletionsImpl.cpp
- ApplicationCode/ReservoirDataModel/Completions/RigTransmissibilityCondenser.cpp
- ApplicationCode/ReservoirDataModel/Completions/RigTransmissibilityCondenser.h
> Completions : Set a threshold for transmissibility 

- ApplicationCode/FileInterface/RifDerivedEnsembleReader.cpp
- ApplicationCode/FileInterface/RifDerivedEnsembleReader.h
- ApplicationCode/ProjectDataModel/Summary/RimDerivedSummaryCase.cpp
> Fix derived cases with not identical addresses

- ApplicationCode/Commands/RicNewMultiPlotFeature.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmReferenceHelper.cpp
> Copy plots when creating multiplots

- ApplicationCode/Application/RiaPreferences.cpp
- ApplicationCode/Application/RiaPreferences.h
- ApplicationCode/Commands/ExportCommands/CMakeLists_files.cmake
- ApplicationCode/Commands/ExportCommands/RicSnapshotViewToFileFeature.cpp
- ApplicationCode/Commands/ExportCommands/RicSnapshotViewToPdfFeature.cpp
- ApplicationCode/Commands/ExportCommands/RicSnapshotViewToPdfFeature.h
- ApplicationCode/UserInterface/RiuPlotMainWindow.cpp
> Add export to PDF feature

- ApplicationCode/ModelVisualization/Surfaces/RivSurfaceIntersectionGeometryGenerator.cpp
- ApplicationCode/ModelVisualization/Surfaces/RivSurfacePartMgr.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimSurfaceInView.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimSurfaceInView.h
> Surface : Modification of depth 

- ApplicationCode/ProjectDataModel/RimMultiPlot.cpp
- ApplicationCode/ProjectDataModel/RimMultiPlot.h
- ApplicationCode/ProjectDataModel/RimPlotAxisPropertiesInterface.cpp
- ApplicationCode/ProjectDataModel/RimPlotAxisPropertiesInterface.h
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.h
> Multi Plot : Add attribute for setting tick mark count along x-axis 

- .github/workflows/main.yml
Remove temporary folder inside packaging folder
Run pytest on Windows
> GitHub Actions : Improve packaging and run pytest

- ApplicationCode/GrpcInterface/GrpcProtos/NNCProperties.proto
- ApplicationCode/GrpcInterface/Python/rips/case.py
- ApplicationCode/GrpcInterface/Python/rips/tests/test_nnc_properties.py
- ApplicationCode/GrpcInterface/RiaGrpcNNCPropertiesService.cpp
- ApplicationCode/GrpcInterface/RiaGrpcNNCPropertiesService.h
Equivalent to SetNNCProperty in Octave.
> #4477 Add python method to set NNC connection values.

- .github/workflows/main.yml
Remove the definition of vcpkgResponseFile per step, define the triplet only once in the matrix instead.
> Remove vcpkgResponseFile environment variable

- ApplicationCode/Commands/SummaryPlotCommands/RicNewSummaryCurveFeature.cpp
- ApplicationCode/ProjectDataModel/RimPlotCurve.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlotFilterTextCurveSetEditor.cpp
> Summary fixes

- ApplicationCode/Commands/RicFlyToObjectFeature.cpp
- ApplicationCode/ProjectDataModel/RimSimWellInView.cpp
- ApplicationCode/ProjectDataModel/RimSimWellInView.h
> Simulation wells: Add Fly to Object 

- ApplicationCode/ProjectDataModel/Flow/RimWellAllocationPlot.cpp
- ApplicationCode/ProjectDataModel/Flow/RimWellAllocationPlot.h
- ApplicationCode/ProjectDataModel/RimWellLogTrack.cpp
- ApplicationCode/ReservoirDataModel/RigAccWellFlowCalculator.cpp
Closes #5692 
Closes #5664
Closes #5674
> Bugfix #5664 well allocation plot data

- .github/workflows/main.yml
> Execute unit tests on ResInsight

- ApplicationCode/Commands/SummaryPlotCommands/RicNewDerivedSummaryFeature.cpp
- ApplicationCode/Commands/SummaryPlotCommands/RicNewDerivedSummaryFeature.h
- ApplicationCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationCode/ProjectDataModel/Summary/RimDerivedSummaryCase.cpp
- ApplicationCode/ProjectDataModel/Summary/RimDerivedSummaryCase.h
> Improve naming delta case

- ApplicationCode/Commands/RicNewMultiPlotFeature.cpp
- ApplicationCode/ProjectDataModel/GridCrossPlots/CellFilters/RimPlotCellPropertyFilter.cpp
- ApplicationCode/ProjectDataModel/GridCrossPlots/CellFilters/RimPlotCellPropertyFilter.h
- ApplicationCode/ProjectDataModel/GridCrossPlots/RimSaturationPressurePlot.cpp
- ApplicationCode/ProjectDataModel/GridCrossPlots/RimSaturationPressurePlot.h
> Saturation Pressure Plots : Add workaround for multi plot of SatNumPlots

- ApplicationCode/FileInterface/RifReaderEclipseSummary.cpp
- ApplicationCode/FileInterface/RifReaderEclipseSummary.h
> Summary Address : Add difference if both native and history is present

- ApplicationCode/Commands/RicNewMultiPlotFeature.cpp
- ApplicationCode/ProjectDataModel/GridCrossPlots/CellFilters/RimPlotCellPropertyFilter.cpp
- ApplicationCode/ProjectDataModel/GridCrossPlots/CellFilters/RimPlotCellPropertyFilter.h
- ApplicationCode/ProjectDataModel/GridCrossPlots/RimSaturationPressurePlot.cpp
- ApplicationCode/ProjectDataModel/GridCrossPlots/RimSaturationPressurePlot.h
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlot.h
> Show Plot Data : Increase precision to 8 

- ApplicationCode/ProjectDataModel/RimEclipseCase.cpp
- ApplicationCode/ProjectDataModel/RimEclipseCase.h
- ApplicationCode/ProjectDataModel/RimEclipseInputCase.cpp
- ApplicationCode/ProjectDataModel/RimEclipseInputCase.h
- ApplicationCode/ProjectDataModel/RimEclipseResultCase.cpp
> #5717 Properly reload input properties when reading eclipse result case.

- .github/workflows/main.yml
- ApplicationCode/Application/RiaPreferences.h
- ApplicationCode/Application/Tools/RiaQDateTimeTools.cpp
- ApplicationCode/Application/Tools/RiaQDateTimeTools.h
- ApplicationCode/ModelVisualization/RivWellDiskPartMgr.cpp
- ApplicationCode/ProjectDataModel/Summary/RimDerivedEnsembleCaseCollection.cpp
- ApplicationCode/ProjectDataModel/Summary/RimDerivedEnsembleCaseCollection.h
- ApplicationCode/ProjectDataModel/Summary/RimDerivedSummaryCase.cpp
- ApplicationCode/ProjectDataModel/Summary/RimDerivedSummaryCase.h
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeSelectionEditor.cpp
> Summary Add fixed time step when computing delta values

- ApplicationCode/ProjectDataModel/RimProject.h
> Fix export of unused used path in ReferencedExternalFiles

- .github/workflows/main.yml
fix for: https://github.com/lukka/run-cmake/issues/8#
> consume run-cmake@v1.2 with fix for build on VS16.5 when using vcxproj project files

- ApplicationCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.cpp
- ApplicationCode/ReservoirDataModel/RigTransmissibilityEquations.cpp
> Avoid nan values

- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
- ApplicationCode/ProjectDataModel/RimWbsParameters.cpp
- ApplicationCode/ReservoirDataModel/RigGeoMechWellLogExtractor.cpp
- ApplicationCode/ReservoirDataModel/RigWbsParameter.cpp
Closes #5695.
Closes #5696.
Closes #5665.
> Wbs input fixes

- ApplicationCode/ModelVisualization/RivWellDiskPartMgr.cpp
- ApplicationCode/ModelVisualization/RivWellDiskPartMgr.h
- ApplicationCode/ProjectDataModel/RimEclipseView.cpp
- ApplicationCode/ProjectDataModel/RimSimWellInView.cpp
- ApplicationCode/ProjectDataModel/RimSimWellInView.h
- ApplicationCode/ProjectDataModel/RimSimWellInViewCollection.cpp
- ApplicationCode/ProjectDataModel/RimSimWellInViewCollection.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiColorEditor.cpp
> Well disk fixes

- ApplicationCode/Commands/WellPathCommands/RicImportWellMeasurementsFeature.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurement.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementCollection.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementFilePath.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementInView.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementInViewCollection.cpp
- ApplicationCode/Resources/ResInsight.qrc
> Well Measurements : Add icons

- ApplicationCode/ProjectDataModel/RimProject.cpp
- ApplicationCode/ProjectDataModel/RimProject.h
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCase.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCase.h
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCaseCollection.h
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
> Summary case id 5775

- ApplicationCode/ProjectDataModel/RimWellLogCurve.cpp
- ApplicationCode/ProjectDataModel/RimWellLogTrack.cpp
> Improve the way we decide on autozoom for the X-range in Well Log Tracks

- ApplicationCode/Application/Tools/RiaQDateTimeTools.cpp
- ApplicationCode/Commands/RicImportSummaryCasesFeature.cpp
- ApplicationCode/GrpcInterface/Python/rips/PythonExamples/summary_vectors.py
- ApplicationCode/GrpcInterface/Python/rips/case.py
- ApplicationCode/GrpcInterface/Python/rips/pdmobject.py
- ApplicationCode/GrpcInterface/Python/rips/project.py
- ApplicationCode/GrpcInterface/Python/rips/tests/test_summary_cases.py
- ApplicationCode/GrpcInterface/RiaGrpcPdmObjectService.cpp
- ApplicationCode/ProjectDataModelCommands/CMakeLists_files.cmake
- ApplicationCode/ProjectDataModelCommands/RimcProject.cpp
- ApplicationCode/ProjectDataModelCommands/RimcProject.h
- ApplicationCode/ProjectDataModelCommands/RimcSummaryCase.cpp
- Fwk/AppFwk/cafPdmScripting/cafPdmObjectMethod.h
- docs/rips/case.py
- docs/rips/generated/pdm_objects.py
- docs/rips/pdmobject.py
- docs/rips/project.py
- docs/source/pdm_objects.rst
> Python Summary Case : Import and access to objects

- ApplicationCode/ModelVisualization/CMakeLists_files.cmake
- ApplicationCode/ModelVisualization/RivElementVectorResultPartMgr.cpp
- ApplicationCode/ModelVisualization/RivElementVectorResultPartMgr.h
- ApplicationCode/ModelVisualization/RivReservoirPartMgr.cpp
- ApplicationCode/ModelVisualization/RivReservoirPartMgr.h
- ApplicationCode/ModelVisualization/RivReservoirViewPartMgr.cpp
- ApplicationCode/ModelVisualization/RivReservoirViewPartMgr.h
- ApplicationCode/ProjectDataModel/CMakeLists_files.cmake
- ApplicationCode/ProjectDataModel/RimEclipseView.cpp
- ApplicationCode/ProjectDataModel/RimEclipseView.h
- ApplicationCode/ProjectDataModel/RimElementVectorResult.cpp
- ApplicationCode/ProjectDataModel/RimElementVectorResult.h
> Tensor plot for fluxes 5583

- ApplicationCode/ModelVisualization/RivReservoirViewPartMgr.cpp
- ApplicationCode/ProjectDataModel/RimEclipseView.cpp
- ApplicationCode/ProjectDataModel/RimSimWellInView.cpp
- ApplicationCode/ProjectDataModel/RimSimWellInView.h
- ApplicationCode/ProjectDataModel/RimSimWellInViewCollection.cpp
- ApplicationCode/ProjectDataModel/RimSimWellInViewCollection.h
- ApplicationCode/ProjectDataModel/RimSimWellInViewTools.cpp
> Fix performance issues related to simulation wells and well disks

- ApplicationCode/Application/RiaDefines.cpp
- ApplicationCode/Application/RiaDefines.h
- ApplicationCode/Commands/ExportCommands/RicAdvancedSnapshotExportFeature.cpp
- ApplicationCode/Commands/SurfaceCommands/CMakeLists_files.cmake
- ApplicationCode/Commands/SurfaceCommands/RicExportSurfaceFeature.cpp
- ApplicationCode/Commands/SurfaceCommands/RicExportSurfaceFeature.h
- ApplicationCode/Commands/SurfaceCommands/RicNewGridCaseSurfaceFeature.cpp
- ApplicationCode/Commands/SurfaceCommands/RicNewGridCaseSurfaceFeature.h
- ApplicationCode/ModelVisualization/Surfaces/RivSurfaceIntersectionGeometryGenerator.cpp
- ApplicationCode/ModelVisualization/Surfaces/RivSurfacePartMgr.cpp
- ApplicationCode/ProjectDataModel/RimAdvancedSnapshotExportDefinition.cpp
- ApplicationCode/ProjectDataModel/RimAdvancedSnapshotExportDefinition.h
- ApplicationCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationCode/ProjectDataModel/RimEclipseView.cpp
- ApplicationCode/ProjectDataModel/RimProject.cpp
- ApplicationCode/ProjectDataModel/RimProject.h
- ApplicationCode/ProjectDataModel/Surfaces/CMakeLists_files.cmake
- ApplicationCode/ProjectDataModel/Surfaces/RimFileSurface.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimFileSurface.h
- ApplicationCode/ProjectDataModel/Surfaces/RimGridCaseSurface.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimGridCaseSurface.h
- ApplicationCode/ProjectDataModel/Surfaces/RimSurface.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimSurface.h
- ApplicationCode/ProjectDataModel/Surfaces/RimSurfaceCollection.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimSurfaceInViewCollection.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimSurfaceInViewCollection.h
> Create surface from grid layer

- ApplicationCode/ModelVisualization/RivFaultPartMgr.cpp
- ApplicationCode/ModelVisualization/RivFaultPartMgr.h
> Fault and NNC performance : Build NNC geometry when needed 

- ApplicationCode/ProjectDataModel/RimCellFilter.cpp
- ApplicationCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafQIconProvider.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafQIconProvider.h
- Fwk/AppFwk/cafTests/cafTestCvfApplication/MainWindow.cpp
- Fwk/AppFwk/cafTests/cafTestCvfApplication/TapCvfSpecialization.cpp
- Fwk/AppFwk/cafTests/cafTestCvfApplication/TapCvfSpecialization.h
- Fwk/AppFwk/cafTests/cafTestCvfApplication/TapProject.cpp
- Fwk/AppFwk/cafTests/cafTestCvfApplication/TapProject.h
closes #5883 
closes #5884 
closes #5872
> Refactor icon provider

- ApplicationCode/Application/RiaDefines.cpp
- ApplicationCode/Application/RiaDefines.h
- ApplicationCode/GrpcInterface/Python/rips/tests/test_nnc_properties.py
- ApplicationCode/ModelVisualization/RivFaultPartMgr.cpp
- ApplicationCode/ModelVisualization/RivFaultPartMgr.h
- ApplicationCode/ModelVisualization/RivNNCGeometryGenerator.cpp
- ApplicationCode/ModelVisualization/RivNNCGeometryGenerator.h
- ApplicationCode/ModelVisualization/RivReservoirFaultsPartMgr.cpp
- ApplicationCode/ProjectDataModel/RimEclipseResultDefinition.cpp
- ApplicationCode/ProjectDataModel/RimEclipseView.cpp
- ApplicationCode/ProjectDataModel/RimRegularLegendConfig.cpp
- ApplicationCode/ReservoirDataModel/CMakeLists_files.cmake
- ApplicationCode/ReservoirDataModel/RigAllanDiagramData.cpp
- ApplicationCode/ReservoirDataModel/RigAllanDiagramData.h
- ApplicationCode/ReservoirDataModel/RigCaseCellResultsData.cpp
- ApplicationCode/ReservoirDataModel/RigCaseCellResultsData.h
- ApplicationCode/ReservoirDataModel/RigEclipseAllanFaultsStatCalc.cpp
- ApplicationCode/ReservoirDataModel/RigEclipseAllanFaultsStatCalc.h
- ApplicationCode/ReservoirDataModel/RigEclipseCaseData.cpp
- ApplicationCode/ReservoirDataModel/RigEclipseCaseData.h
- ApplicationCode/UserInterface/RiuResultTextBuilder.cpp
> Fix misspelled Allan diagram (#5906)

- ApplicationCode/FileInterface/RifReaderInterface.cpp
- ApplicationCode/FileInterface/RifReaderInterface.h
- ApplicationCode/FileInterface/RifReaderSettings.cpp
- ApplicationCode/FileInterface/RifReaderSettings.h
- ApplicationCode/ProjectDataModel/RimEclipseCase.cpp
- ApplicationCode/ProjectDataModel/RimEclipseCaseCollection.cpp
- ApplicationCode/ProjectDataModel/RimEclipseResultDefinition.cpp
- ApplicationCode/ReservoirDataModel/RigCaseCellResultsData.cpp
- ApplicationCode/ReservoirDataModel/RigCaseCellResultsData.h
- ApplicationCode/ReservoirDataModel/RigCellFaceGeometryTools.cpp
- ApplicationCode/ReservoirDataModel/RigCellFaceGeometryTools.h
- ApplicationCode/ReservoirDataModel/RigMainGrid.cpp
- ApplicationCode/ReservoirDataModel/RigMainGrid.h
- ApplicationCode/ReservoirDataModel/RigNNCData.cpp
- ApplicationCode/ReservoirDataModel/RigNNCData.h
Closes #5925
Closes #5920
Closes #5914
Closes #5913
> Preferences to control fault and NNC

- ApplicationCode/GeoMech/GeoMechDataModel/CMakeLists.txt
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorStressAnisotropy.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorStressAnisotropy.h
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.h
> #5910 Add calculator for stress anisotropy.

- ApplicationCode/Application/RiaGuiApplication.cpp
- ApplicationCode/CMakeLists.txt
- ApplicationCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.cpp
- ApplicationCode/Commands/HoloLensCommands/VdeArrayDataPacket.cpp
- ApplicationCode/ModelVisualization/Riv3dWellLogCurveGeometryGenerator.cpp
- ApplicationCode/ModelVisualization/RivContourMapProjectionPartMgr.cpp
- ApplicationCode/ModelVisualization/RivReachCircleAnnotationPartMgr.cpp
- ApplicationCode/ModelVisualization/RivWellPathSourceInfo.cpp
- ApplicationCode/ModelVisualization/Surfaces/RivSurfaceIntersectionGeometryGenerator.cpp
- ApplicationCode/ProjectDataModel/Rim3dView.cpp
- ApplicationCode/ProjectDataModel/RimEclipseResultDefinition.cpp
- ApplicationCode/ProjectDataModel/RimFormationNames.cpp
- ApplicationCode/ProjectDataModel/RimWellLogRftCurve.cpp
- ApplicationCode/ProjectDataModel/RimWellLogTrack.cpp
- ApplicationCode/ReservoirDataModel/RigGeoMechBoreHoleStressCalculator.cpp
- ApplicationCode/ReservoirDataModel/RigGeoMechWellLogExtractor.cpp
- ApplicationCode/ReservoirDataModel/RigTofWellDistributionCalculator.cpp
- ApplicationCode/ReservoirDataModel/RigWellPathGeometryTools.cpp
- ApplicationCode/UnitTests/RifEclipseInputFileTools-Test.cpp
- ApplicationCode/UnitTests/RigCellGeometryTools-Test.cpp
- ApplicationCode/UnitTests/RigHexIntersectionTools-Test.cpp
- ApplicationCode/UserInterface/RiuQwtPlotWidget.cpp
- ApplicationCode/UserInterface/RiuQwtScalePicker.cpp
- Fwk/VizFwk/LibGeometry/cvfBoundingBoxTree.cpp
WIP: goal is to remove all warnings on linux.
> Stricter warnings linux

- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorPoreCompressibility.cpp
> #6004 Pore Compressibility: incorrect sign first term in computation.

- ApplicationCode/FileInterface/CMakeLists_files.cmake
- ApplicationCode/FileInterface/RifFaciesPropertiesReader.cpp
- ApplicationCode/FileInterface/RifFaciesPropertiesReader.h
- ApplicationCode/UnitTests/CMakeLists_files.cmake
- ApplicationCode/UnitTests/RifFaciesPropertiesReader-Test.cpp
> #5989 Add parser for facies properties csv file

- ApplicationCode/ModelVisualization/Surfaces/RivSurfacePartMgr.cpp
- ApplicationCode/ModelVisualization/Surfaces/RivSurfacePartMgr.h
- ApplicationCode/ProjectDataModel/RimEclipseView.cpp
- ApplicationCode/ProjectDataModel/Surfaces/CMakeLists_files.cmake
- ApplicationCode/ProjectDataModel/Surfaces/RimFileSurface.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimSurfaceInView.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimSurfaceInView.h
- ApplicationCode/ProjectDataModel/Surfaces/RimSurfaceInViewCollection.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimSurfaceInViewCollection.h
- ApplicationCode/ProjectDataModel/Surfaces/RimSurfaceResultDefinition.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimSurfaceResultDefinition.h
- ApplicationCode/ReservoirDataModel/RigSurface.cpp
- ApplicationCode/ReservoirDataModel/RigSurface.h
- Fwk/AppFwk/cafVizExtensions/cafHexGridIntersectionTools/cafHexGridIntersectionTools.cpp
> Surface properties

- ApplicationCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.cpp
- ApplicationCode/ProjectDataModel/Rim3dWellLogExtractionCurve.cpp
- ApplicationCode/ReservoirDataModel/RigWellPathIntersectionTools.cpp
- ApplicationCode/ReservoirDataModel/RigWellPathIntersectionTools.h
Closes #6076
Closes #6071 
Closes #6072
> Fix MSW and valve export outside grid cells

- ApplicationCode/Application/Tools/RiaEclipseUnitTools.h
- ApplicationCode/Commands/CMakeLists_files.cmake
- ApplicationCode/Commands/CompletionCommands/RicNewFractureModelPlotFeature.cpp
- ApplicationCode/Commands/CompletionCommands/RicNewFractureModelPlotFeature.h
- ApplicationCode/Commands/RicElasticPropertiesImportTools.cpp
- ApplicationCode/Commands/RicExportFractureModelPlotToFileFeature.cpp
- ApplicationCode/Commands/RicExportFractureModelPlotToFileFeature.h
- ApplicationCode/FileInterface/CMakeLists_files.cmake
- ApplicationCode/FileInterface/RifElasticPropertiesReader.cpp
- ApplicationCode/FileInterface/RifElasticPropertiesReader.h
- ApplicationCode/FileInterface/RifFractureModelPlotExporter.cpp
- ApplicationCode/FileInterface/RifFractureModelPlotExporter.h
- ApplicationCode/ProjectDataModel/CMakeLists_files.cmake
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.h
- ApplicationCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationCode/ProjectDataModel/RimElasticProperties.cpp
- ApplicationCode/ProjectDataModel/RimElasticPropertiesCurve.cpp
- ApplicationCode/ProjectDataModel/RimElasticPropertiesCurve.h
- ApplicationCode/ProjectDataModel/RimFractureModelPlot.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelPlot.h
- ApplicationCode/ProjectDataModel/RimLayerCurve.cpp
- ApplicationCode/ProjectDataModel/RimLayerCurve.h
- ApplicationCode/ReservoirDataModel/RigElasticProperties.cpp
- ApplicationCode/ReservoirDataModel/RigElasticProperties.h
- ApplicationCode/UnitTests/RifElasticPropertiesReader-Test.cpp
> Layers fracture model plot 6036

- ApplicationCode/Application/Tools/RiaEclipseUnitTools.h
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorPoreCompressibility.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.h
- ApplicationCode/ProjectDataModel/RimGeoMechResultDefinition.cpp
- ApplicationCode/ProjectDataModel/RimGeoMechResultDefinition.h
> Pore compressibility fix 6031

- .gitignore
- ApplicationCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.cpp
- ApplicationCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.h
- ApplicationCode/FileInterface/RifTextDataTableFormatter.cpp
- ApplicationCode/ModelVisualization/RivWellPathPartMgr.cpp
- ApplicationCode/ModelVisualization/RivWellPathPartMgr.h
- ApplicationCode/ReservoirDataModel/RigWellPathIntersectionTools.cpp
Closes #6128
Closes #6124
Closes #6074
Closes #6093
> Several fixes for MSW and valve export

- ApplicationCode/Commands/CompletionCommands/RicNewFractureModelPlotFeature.cpp
- ApplicationCode/Commands/CompletionCommands/RicNewFractureModelPlotFeature.h
- ApplicationCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorUi.cpp
- ApplicationCode/Commands/WellLogCommands/RicNewWellBoreStabilityPlotFeature.cpp
- ApplicationCode/ProjectDataModel/RimPlotCurve.cpp
- ApplicationCode/ProjectDataModel/RimPlotCurve.h
- ApplicationCode/ProjectDataModel/RimWellLogTrack.cpp
- Fwk/AppFwk/CommonCode/cafColorTable.cpp
- Fwk/AppFwk/CommonCode/cafColorTable.h
> Fracture model plot fixes

- ApplicationCode/GeoMech/GeoMechDataModel/CMakeLists.txt
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorPoreCompressibility.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorPorosityPermeability.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorPorosityPermeability.h
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.h
- ApplicationCode/ProjectDataModel/RimGeoMechCase.cpp
- ApplicationCode/ProjectDataModel/RimGeoMechCase.h
- ApplicationCode/ProjectDataModel/RimGeoMechResultDefinition.cpp
> Porosity permeability calculation 6086

- ApplicationCode/Application/CMakeLists_files.cmake
- ApplicationCode/Application/RiaFractureModelDefines.cpp
- ApplicationCode/Application/RiaFractureModelDefines.h
- ApplicationCode/Commands/CompletionCommands/RicNewFractureModelPlotFeature.cpp
- ApplicationCode/Commands/CompletionCommands/RicNewFractureModelPlotFeature.h
- ApplicationCode/ProjectDataModel/CMakeLists_files.cmake
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.h
- ApplicationCode/ProjectDataModel/RimElasticPropertiesCurve.cpp
- ApplicationCode/ProjectDataModel/RimElasticPropertiesCurve.h
- ApplicationCode/ProjectDataModel/RimFractureModelCurve.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelCurve.h
- ApplicationCode/ProjectDataModel/RimFractureModelPlot.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelPlot.h
- ApplicationCode/ProjectDataModel/RimFractureModelPropertyCurve.h
- ApplicationCode/ProjectDataModel/RimFractureModelStressCurve.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelStressCurve.h
- ApplicationCode/ProjectDataModel/RimLayerCurve.cpp
- ApplicationCode/ProjectDataModel/RimLayerCurve.h
- ApplicationCode/ProjectDataModel/RimWellLogTrack.cpp
- ApplicationCode/ProjectDataModel/RimWellLogTrack.h
Closes #6038.
Closes #6089.
Closes #6113.
> Fracture model plot overburden 6038

- ApplicationCode/Commands/CompletionCommands/RicNewFractureModelPlotFeature.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.h
- ApplicationCode/ProjectDataModel/RimElasticPropertiesCurve.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelCurve.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelCurve.h
- ApplicationCode/ProjectDataModel/RimFractureModelPlot.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelPlot.h
- ApplicationCode/ProjectDataModel/RimLayerCurve.cpp
- ApplicationCode/ProjectDataModel/RimPlotCurve.cpp
- ApplicationCode/ProjectDataModel/RimPlotCurve.h
Closes #6210.
Closes #6217.
Closes #6172.
Closes #6171.
Closes #6090.
> Fracture model plot improvements

- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorPorosityPermeability.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResults.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResults.h
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.h
- ApplicationCode/ProjectDataModel/RimGeoMechCase.cpp
- ApplicationCode/ProjectDataModel/RimGeoMechResultDefinition.cpp
Closes #6170.
Closes #6218.
Closes #6169.
> Geomech calculation fixes

- ApplicationCode/Application/RiaFractureModelDefines.cpp
- ApplicationCode/Application/RiaFractureModelDefines.h
- ApplicationCode/Commands/CompletionCommands/RicNewFractureModelPlotFeature.cpp
- ApplicationCode/Commands/RicExportFractureModelPlotToFileFeature.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.h
- ApplicationCode/ProjectDataModel/RimFractureModelCurve.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelCurve.h
- ApplicationCode/ProjectDataModel/RimFractureModelPlot.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelPlot.h
Closes #6212.
Closes #6221.
Closes #6173.
Closes #6208.
Closes #6131.
> Fracture model plot pressure curves

- ApplicationCode/Commands/CompletionCommands/RicNewFractureModelPlotFeature.cpp
- ApplicationCode/Commands/RicWellLogTools.cpp
- ApplicationCode/ProjectDataModel/RimWellLogRftCurve.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementCurve.cpp
> Fix crash fracture model 6228

- ApplicationCode/CMakeLists.txt
- ApplicationCode/UserInterface/RiuQwtSymbol.cpp
- ThirdParty/nightcharts/nightcharts.cpp
Made some adjustments for upgrading to Qt 5.15.
> Qt 5.15 adjustments

- ApplicationCode/Commands/RicNewContourMapViewFeature.cpp
> Hide surfaces when generating contour map view

- ApplicationCode/Commands/RicStackSelectedCurvesFeature.cpp
- ApplicationCode/Commands/RicStackSelectedCurvesFeature.h
- ApplicationCode/Commands/RicUnstackSelectedCurvesFeature.h
- ApplicationCode/ProjectDataModel/CMakeLists_files.cmake
- ApplicationCode/ProjectDataModel/RimPlotCurve.cpp
- ApplicationCode/ProjectDataModel/RimPlotCurve.h
- ApplicationCode/ProjectDataModel/RimStackablePlotCurve.cpp
- ApplicationCode/ProjectDataModel/RimStackablePlotCurve.h
- ApplicationCode/ProjectDataModel/RimWellLogCurve.h
- ApplicationCode/ProjectDataModel/RimWellLogExtractionCurve.cpp
- ApplicationCode/ProjectDataModel/RimWellLogFileCurve.cpp
- ApplicationCode/ProjectDataModel/RimWellLogRftCurve.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCurve.h
* Well Log Curves and Summary Curves for now.
> #6293 Make sure stacking is only available for some curves

- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorMudWeightWindow.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.h
- ApplicationCode/ProjectDataModel/RimMudWeightWindowParameters.cpp
- ApplicationCode/ProjectDataModel/RimMudWeightWindowParameters.h
- ApplicationCode/ReservoirDataModel/RigGeoMechWellLogExtractor.cpp
- ApplicationCode/ReservoirDataModel/RigGeoMechWellLogExtractor.h
> Mud weight window improvements

- ApplicationCode/Commands/SurfaceCommands/RicExportKLayerToPtlFeature.cpp
- ApplicationCode/FileInterface/RifSurfaceExporter.cpp
- ApplicationCode/FileInterface/RifSurfaceExporter.h
> Fix spelling of "Petrel"

- ApplicationCode/Commands/RicNewContourMapViewFeature.cpp
- ApplicationCode/Commands/SummaryPlotCommands/RicSummaryPlotFeatureImpl.cpp
- ApplicationCode/ProjectDataModel/CorrelationPlots/RimCorrelationMatrixPlot.cpp
- ApplicationCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlotDataSet.cpp
- ApplicationCode/ProjectDataModel/RimColorLegendCollection.cpp
- ApplicationCode/ProjectDataModel/RimContourMapProjection.cpp
- ApplicationCode/ProjectDataModel/RimEclipseCellColors.cpp
- ApplicationCode/ProjectDataModel/RimEclipseResultDefinition.cpp
- ApplicationCode/ProjectDataModel/RimEclipseView.cpp
- ApplicationCode/ProjectDataModel/RimElementVectorResult.cpp
- ApplicationCode/ProjectDataModel/RimGeoMechCellColors.cpp
- ApplicationCode/ProjectDataModel/RimGeoMechResultDefinition.cpp
- ApplicationCode/ProjectDataModel/RimIntersectionResultDefinition.cpp
- ApplicationCode/ProjectDataModel/RimLegendConfig.cpp
- ApplicationCode/ProjectDataModel/RimLegendConfig.h
- ApplicationCode/ProjectDataModel/RimRegularLegendConfig.cpp
- ApplicationCode/ProjectDataModel/RimRegularLegendConfig.h
- ApplicationCode/ProjectDataModel/RimStimPlanColors.cpp
- ApplicationCode/ProjectDataModel/RimTensorResults.cpp
- ApplicationCode/ProjectDataModel/RimTernaryLegendConfig.cpp
- ApplicationCode/ProjectDataModel/RimWellLogTrack.cpp
- ApplicationCode/ProjectDataModel/RimWellMeasurementInView.cpp
- ApplicationCode/ProjectDataModel/Summary/RimEnsembleCurveSetColorManager.cpp
- ApplicationCode/UserInterface/RiuScalarMapperLegendFrame.cpp
- Fwk/AppFwk/cafVizExtensions/cafCategoryLegend.cpp
> Fix color legend category ordering

- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorNormalSE.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorNormalST.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
- ApplicationCode/ProjectDataModel/RimGeoMechResultDefinition.cpp
> #6315 Remove biot factor corrections for calculated stresses.

- ApplicationCode/Commands/WellLogCommands/RicWellLogPlotTrackFeatureImpl.cpp
- ApplicationCode/Commands/WellLogCommands/RicWellLogPlotTrackFeatureImpl.h
- ApplicationCode/ProjectDataModel/RimMultiPlot.cpp
- ApplicationCode/ProjectDataModel/RimMultiPlot.h
- ApplicationCode/UserInterface/RiuDragDrop.cpp
- ApplicationCode/UserInterface/RiuDragDrop.h
* Dropping curves between other curves works much better with this change.
> Disallow dropping curves onto other curves

- ApplicationCode/FileInterface/CMakeLists_files.cmake
- ApplicationCode/FileInterface/RifSurfaceImporter.cpp
- ApplicationCode/FileInterface/RifSurfaceImporter.h
- ApplicationCode/ProjectDataModel/Surfaces/RimFileSurface.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimGridCaseSurface.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimGridCaseSurface.h
- ApplicationCode/ProjectDataModel/Surfaces/RimSurface.cpp
- ApplicationCode/UnitTests/CMakeLists_files.cmake
- ApplicationCode/UnitTests/RifSurfaceImporter-Test.cpp
> Improve PTL export

- ApplicationCode/GeoMech/GeoMechDataModel/CMakeLists.txt
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorShearSlipIndicator.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorShearSlipIndicator.h
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.h
- ApplicationCode/ProjectDataModel/RimGeoMechCase.cpp
- ApplicationCode/ProjectDataModel/RimGeoMechCase.h
> #6308 GeoMech: Add shear slip indicator calculation.

- ApplicationCode/GeoMech/GeoMechDataModel/CMakeLists.txt
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorInitialPorosity.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorInitialPorosity.h
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
> #6302 PORO-PERM: Calculate initial porosity.

- ApplicationCode/ProjectDataModel/RimWellLogTrack.cpp
- ApplicationCode/ReservoirDataModel/RigWellLogCurveData.cpp
* We no longer require the depth data to be well ordered.
> #6304 Improve stacked curve interpolation

- ApplicationCode/GrpcInterface/Python/rips/PythonExamples/surface_import.py
- ApplicationCode/ProjectDataModel/Surfaces/RimFileSurface.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimSurface.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimSurfaceCollection.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimSurfaceCollection.h
- ApplicationCode/ProjectDataModel/Surfaces/RimSurfaceInViewCollection.cpp
- ApplicationCode/ProjectDataModel/Surfaces/RimSurfaceInViewCollection.h
- ApplicationCode/ProjectDataModelCommands/CMakeLists_files.cmake
- ApplicationCode/ProjectDataModelCommands/RimcProject.cpp
- ApplicationCode/ProjectDataModelCommands/RimcProject.h
- ApplicationCode/ProjectDataModelCommands/RimcSurfaceCollection.cpp
- ApplicationCode/ProjectDataModelCommands/RimcSurfaceCollection.h
Implements a python interface for loading surfaces. Includes example of usage.
Closes #5382
> Surface python interface

- ApplicationCode/FileInterface/RifFractureModelPlotExporter.cpp
- ApplicationCode/FileInterface/RifFractureModelPlotExporter.h
> #6374 Update Geological.FRK file export to new xml format.

- ApplicationCode/Commands/FractureCommands/RicNewFractureModelFeature.cpp
- ApplicationCode/Commands/WellPathCommands/RicNewWellPathAttributeFeature.cpp
- ApplicationCode/ProjectDataModel/RimContextCommandBuilder.cpp
> #6296 Fix empty or duplicated fracture model menu items.

- ApplicationCode/Commands/RicImportFormationNamesFeature.cpp
- ApplicationCode/ProjectDataModel/RimEclipseCellColors.cpp
Closes #6373
Closes #6204
Closes #6380
> 3DView: Better handling of category color legends

- ApplicationCode/CommandFileInterface/RicfExportSnapshots.cpp
- ApplicationCode/Commands/ExportCommands/RicSnapshotAllPlotsToFileFeature.cpp
- ApplicationCode/Commands/ExportCommands/RicSnapshotAllPlotsToFileFeature.h
- ApplicationCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.cpp
- ApplicationCode/ProjectDataModel/CorrelationPlots/RimAbstractCorrelationPlot.cpp
> Make sure all snapshots use full MDI area

- ApplicationCode/FileInterface/RifEclipseInputFileTools.cpp
- ApplicationCode/ProjectDataModel/RimBoxIntersection.cpp
- ApplicationCode/ProjectDataModel/RimCellEdgeColors.cpp
- ApplicationCode/ProjectDataModel/RimRegularLegendConfig.cpp
- ApplicationCode/ReservoirDataModel/RigCaseCellResultsData.cpp
- ApplicationCode/ReservoirDataModel/RigCaseToCaseRangeFilterMapper.cpp
- ApplicationCode/ReservoirDataModel/RigReservoirBuilderMock.cpp
- ApplicationCode/UserInterface/RiuViewer.cpp
- ApplicationCode/UserInterface/RiuViewerCommands.cpp
> #2763 Use std::min and std::max instead of CVF_MAX and CVF_MIN

- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorMudWeightWindow.cpp
- ApplicationCode/ProjectDataModel/RimCase.cpp
- ApplicationCode/ProjectDataModel/RimCase.h
- ApplicationCode/ProjectDataModel/RimGeoMechCase.cpp
- ApplicationCode/ProjectDataModel/RimMudWeightWindowParameters.cpp
- ApplicationCode/ProjectDataModel/RimWellLogExtractionCurve.cpp
- ApplicationCode/ProjectDataModel/RimWellLogExtractionCurve.h
Closes #6303.
Closes #6387.
Closes #6369.
> Mud weight window fixes

- ApplicationCode/UserInterface/RiuCellAndNncPickEventHandler.cpp
> 2D Intersections View: Fix cell selection 

- ApplicationCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.cpp
- ApplicationCode/ProjectDataModel/CorrelationPlots/RimAbstractCorrelationPlot.cpp
* Change clears selected time step when filter is changed
* Changes string 'Time step filter' to 'Available Time steps'
* Now only shows clock time if we're showing all time steps or skip by days
and the time isn't 00:00.
> #6368 Minor time step improvements to Analysis and Correlation plots

- ApplicationCode/Application/Tools/RiaFilePathTools.cpp
- ApplicationCode/UnitTests/RiaFilePathTools-Test.cpp
> Import Ensemble : Windows-style network path not working as effective filter 

- ApplicationCode/Application/RiaApplication.cpp
- ApplicationCode/Commands/CompletionCommands/RicNewFractureModelPlotFeature.cpp
- ApplicationCode/Commands/RicImportElasticPropertiesFeature.cpp
- ApplicationCode/Commands/RicImportFaciesFeature.cpp
- ApplicationCode/Commands/RicImportFaciesFeature.h
- ApplicationCode/GrpcInterface/Python/rips/PythonExamples/create_and_export_fracture_model.py
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.h
Closes #6231. 
Closes #6150.
Closes #6040.
Closes #6363.
> Stimplan sprint8 fixes

- ApplicationCode/Commands/RicElasticPropertiesImportTools.cpp
- ApplicationCode/FileInterface/RifElasticPropertiesReader.cpp
- ApplicationCode/FileInterface/RifElasticPropertiesReader.h
- ApplicationCode/UnitTests/RifElasticPropertiesReader-Test.cpp
> Elastic properties reader fixes

- ApplicationCode/Commands/ColorLegendCommands/RicImportColorCategoriesFeature.cpp
- ApplicationCode/Commands/ExportCommands/RicExportSelectedWellPathsFeature.cpp
- ApplicationCode/Commands/ExportCommands/RicExportSelectedWellPathsFeature.h
- ApplicationCode/Commands/ExportCommands/RicExportVisibleWellPathsFeature.cpp
- ApplicationCode/Commands/ExportCommands/RicExportVisibleWellPathsFeature.h
- ApplicationCode/Commands/RicExportFractureModelPlotToFileFeature.cpp
- ApplicationCode/Commands/RicImportElasticPropertiesFeature.cpp
- ApplicationCode/Commands/RicImportFaciesFeature.cpp
- ApplicationCode/Commands/SurfaceCommands/RicCopySurfaceFeature.cpp
- ApplicationCode/Commands/SurfaceCommands/RicExportKLayerToPtlFeature.cpp
- ApplicationCode/Commands/SurfaceCommands/RicExportSurfaceToTsurfFeature.cpp
- ApplicationCode/Commands/SurfaceCommands/RicNewSurfaceCollectionFeature.cpp
- ApplicationCode/Commands/SurfaceCommands/RicReloadSurfaceFeature.cpp
- ApplicationCode/FileInterface/CMakeLists_files.cmake
- ApplicationCode/FileInterface/RifFractureModelDeviationFrkExporter.cpp
- ApplicationCode/FileInterface/RifFractureModelDeviationFrkExporter.h
- ApplicationCode/FileInterface/RifFractureModelGeologicalFrkExporter.cpp
- ApplicationCode/FileInterface/RifFractureModelGeologicalFrkExporter.h
- ApplicationCode/FileInterface/RifFractureModelPlotExporter.cpp
- ApplicationCode/FileInterface/RifFractureModelPlotExporter.h
- ApplicationCode/FileInterface/RifSurfaceExporter.cpp
- ApplicationCode/GrpcInterface/Python/rips/PythonExamples/create_and_export_fracture_model.py
- ApplicationCode/ProjectDataModelCommands/RimcFractureModelPlot.cpp
- ApplicationCode/ReservoirDataModel/CMakeLists_files.cmake
- ApplicationCode/ReservoirDataModel/RigWellPathGeometryExporter.cpp
- ApplicationCode/ReservoirDataModel/RigWellPathGeometryExporter.h
> Stimplan deviation export 6423

- ApplicationCode/ProjectDataModel/RimMultiPlotCollection.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCrossPlotCollection.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlotCollection.cpp
> Add reordering to some more collections

- ApplicationCode/FileInterface/CMakeLists_files.cmake
- ApplicationCode/FileInterface/RifFractureModelPerfsFrkExporter.cpp
- ApplicationCode/FileInterface/RifFractureModelPerfsFrkExporter.h
- ApplicationCode/FileInterface/RifFractureModelPlotExporter.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.h
- ApplicationCode/ReservoirDataModel/RigWellPathGeometryTools.cpp
- ApplicationCode/UnitTests/RigWellPathGeometryTools-Test.cpp
> Stimplan perfs export 6424

- ApplicationCode/ProjectDataModel/RimColorLegend.cpp
- ApplicationCode/ProjectDataModel/RimColorLegend.h
- ApplicationCode/ProjectDataModel/RimColorLegendCollection.cpp
- ApplicationCode/ProjectDataModel/RimColorLegendCollection.h
- ApplicationCode/ProjectDataModel/RimColorLegendItem.cpp
- ApplicationCode/ProjectDataModel/RimColorLegendItem.h
> Add reordering to color legend items

- ApplicationCode/FileInterface/CMakeLists_files.cmake
- ApplicationCode/FileInterface/RifFractureModelAsymmetricFrkExporter.cpp
- ApplicationCode/FileInterface/RifFractureModelAsymmetricFrkExporter.h
- ApplicationCode/FileInterface/RifFractureModelPlotExporter.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.h
> #6425 Fracture Model: Export Asymmetric.frk file.

- ApplicationCode/ProjectDataModel/Rim3dOverlayInfoConfig.cpp
- ApplicationCode/ProjectDataModel/Rim3dOverlayInfoConfig.h
> Only show statistics in info view if the histogram has valid data.

- ApplicationCode/Commands/RicElasticPropertiesImportTools.cpp
- ApplicationCode/ProjectDataModel/RimElasticPropertiesCurve.cpp
> #6175 Fracture Model: Remove hard-coded reference to Norne.

- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorInitialPorosity.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorPoreCompressibility.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorPorosityPermeability.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
- ApplicationCode/UserInterface/Riu3DMainWindowTools.cpp
- ApplicationCode/UserInterface/Riu3DMainWindowTools.h
> GeoMech : If running interactively, show error message in warning dialog box 

- ApplicationCode/Commands/RicImportSummaryCasesFeature.cpp
- ApplicationCode/Commands/RicImportSummaryCasesFeature.h
- ApplicationCode/ProjectDataModelCommands/RimcProject.cpp
> Summary Case import using python interface fix

- ApplicationCode/Application/RiaApplication.cpp
- ApplicationCode/Commands/CMakeLists_files.cmake
- ApplicationCode/Commands/RicCloseCaseFeature.cpp
- ApplicationCode/Commands/RicGeoMechCopyCaseFeature.cpp
- ApplicationCode/Commands/RicGeoMechCopyCaseFeature.h
- ApplicationCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationCode/ProjectDataModel/RimGeoMechCase.cpp
- ApplicationCode/ProjectDataModel/RimGeoMechCase.h
- ApplicationCode/ProjectDataModel/RimGeoMechModels.cpp
- ApplicationCode/ProjectDataModel/RimGeoMechModels.h
- ApplicationCode/ProjectDataModel/RimGridView.cpp
- ApplicationCode/ProjectDataModel/RimIntersectionResultDefinition.cpp
- ApplicationCode/ProjectDataModel/RimIntersectionResultDefinition.h
- ApplicationCode/ProjectDataModel/RimIntersectionResultsDefinitionCollection.cpp
- ApplicationCode/ProjectDataModel/RimProject.cpp
> Support for copying GeoMech case settings using new input

- ApplicationCode/Commands/CompletionCommands/RicNewFractureModelPlotFeature.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.h
> Stimplan ui fixes

- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.cpp
- ApplicationCode/ProjectDataModel/RimElasticPropertiesCurve.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelCurve.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelStressCurve.cpp
- ApplicationCode/ProjectDataModel/RimLayerCurve.cpp
> #6134 Fracture Model: Add menu item to delete a fracture model.

- ApplicationCode/Application/RiaApplication.cpp
- ApplicationCode/ProjectDataModel/RimGeoMechModels.cpp
The odb reader does not support opening the same file twice very well
> Do not allow opening the same odb file twice. 

- ApplicationCode/ProjectDataModel/RimWellLogRftCurve.cpp
> #6146 RFT plot: Use MD from Wells for Ensembles.

- Fwk/AppFwk/cafUserInterface/cafPdmUiColorEditor.cpp
> Color Dialog : Use Qt color dialog, not native color dialog

- Fwk/AppFwk/cafUserInterface/cafPdmUiColorEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiFilePathEditor.cpp
> Avoid using native file dialog on Linux

- ApplicationCode/FileInterface/RifSurfaceImporter.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiColorEditor.cpp
> Fix sign of z for openworksxyz surface import

- ApplicationCode/Application/RiaApplication.cpp
- ApplicationCode/ProjectDataModel/RimWellPathCollection.cpp
> Make sure we read the LAS file contents, too, when loading a project

- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.h
- ApplicationCode/ReservoirDataModel/RigCell.cpp
- ApplicationCode/ReservoirDataModel/RigCell.h
> Fracture model barrier detection 6500

- ApplicationCode/ProjectDataModel/RimEclipseView.cpp
- ApplicationCode/ProjectDataModel/RimVirtualPerforationResults.cpp
> Fixes #6554 by moving legend title definition.

- ApplicationCode/Application/Tools/RiaWellLogUnitTools.h
- ApplicationCode/Application/Tools/RiaWellLogUnitTools.inl
- ApplicationCode/ProjectDataModel/RimDepthTrackPlot.cpp
- ApplicationCode/ProjectDataModel/RimDepthTrackPlot.h
- ApplicationCode/ProjectDataModel/RimEclipseResultCase.cpp
- ApplicationCode/ProjectDataModel/RimEclipseResultCase.h
- ApplicationCode/ProjectDataModel/RimWellLogTrack.cpp
> RFT Plot - make sure we handle feet vs. meters in well log type plots

- ApplicationCode/GrpcInterface/Python/rips/PythonExamples/alter_wbs_plot.py
- ApplicationCode/GrpcInterface/Python/rips/PythonExamples/create_and_export_fracture_model.py
Changed hard coded temp directory pathes to built-in tempfile gettempdir(). Also searched all other Python files for other places hard coded temporary folder were used, but could not find any.
Closes #6571.
> Changed hard coded temp directory pathes

- ApplicationCode/ProjectDataModel/Flow/RimWellPltPlot.cpp
- ApplicationCode/ProjectDataModel/Flow/RimWellRftPlot.cpp
- ApplicationCode/ProjectDataModel/RimContourMapProjection.cpp
- ApplicationCode/ProjectDataModel/RimDepthTrackPlot.cpp
- ApplicationCode/ProjectDataModel/RimGeoMechContourMapProjection.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationCode/UserInterface/RiuTextEditWithCompletion.cpp
> Replaced QOverload with static_cast to assure downwards compatibility.

- ApplicationCode/Commands/RicGridStatisticsDialog.cpp
- ApplicationCode/ProjectDataModel/Rim3dOverlayInfoConfig.cpp
- ApplicationCode/ProjectDataModel/Rim3dOverlayInfoConfig.h
> Info view : Add check for histogram vector values

- ApplicationCode/Resources/ResInsight.qrc
- ApplicationCode/Resources/themes/dark.qss
- ApplicationCode/Resources/themes/dark/checkbox-checked-disabled.svg
- ApplicationCode/Resources/themes/dark/checkbox-checked.svg
- ApplicationCode/Resources/themes/dark/checkbox-indeterminate-disabled.svg
- ApplicationCode/Resources/themes/dark/checkbox-indeterminate.svg
- ApplicationCode/Resources/themes/dark/checkbox-tristate-disabled.svg
- ApplicationCode/Resources/themes/dark/checkbox-tristate.svg
- ApplicationCode/Resources/themes/dark/checkbox-unchecked-disabled.svg
- ApplicationCode/Resources/themes/dark/checkbox-unchecked.svg
- Fwk/AppFwk/cafUserInterface/cafPdmUiLineEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiPickableLineEditor.cpp
Replaced checkbox PNG icons with SVG icons and adjusted background colors.
Closes most of #6611.
> New checkbox icons as svgs and adjusted background colors

- ApplicationCode/FileInterface/RifFractureModelPerfsFrkExporter.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.h
> #6595 Fracture Model: Allow azimuth orientation for fracture.

- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.h
> #6594 Fracture Model: Add option to hide non-barrier faults.

- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorStressAnisotropy.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorStressAnisotropy.h
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorTimeLapse.cpp
- ApplicationCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorTimeLapse.h
> 6544 stress anisotropy timelapse

- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.h
> 6593 Fracture Model: Show barrier fault name and distance in 3d.

- ApplicationCode/Commands/CompletionExportCommands/RicFishbonesTransmissibilityCalculationFeatureImp.cpp
- ApplicationCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.cpp
- ApplicationCode/ReservoirDataModel/Completions/RigCompletionData.cpp
- ApplicationCode/ReservoirDataModel/Completions/RigCompletionData.h
> Export Completion: Report kh for Perforation Interval

- ApplicationCode/UserInterface/RiuMainWindowBase.cpp
> Fix crash when MDI window is closed 

- ApplicationCode/FileInterface/RifEclipseSummaryAddress.cpp
- ApplicationCode/FileInterface/RifEclipseSummaryAddress.h
- ApplicationCode/UnitTests/RifEclipseSummaryAddress-Test.cpp
> Summary Plot: Detect cumulative fluid components 

- ApplicationCode/Commands/RicNewContourMapViewFeature.cpp
- ApplicationCode/Resources/themes/default.qss
- ApplicationCode/UserInterface/RiuViewer.cpp
> Issues related to regression tests

- ApplicationCode/UnitTests/RiuSummaryVectorDescriptionMap-Test.cpp
- ApplicationCode/UserInterface/RiuSummaryQuantityNameInfoProvider.cpp
- ApplicationCode/UserInterface/RiuSummaryQuantityNameInfoProvider.h
> Summary data: Add description for 6X specific summary vectors 

- ApplicationCode/UserInterface/RiuMainWindowBase.cpp
> MDI Window : Set contained viewer widget after MDI window is resized

- ApplicationCode/Commands/ToggleCommands/CMakeLists_files.cmake
- ApplicationCode/Commands/ToggleCommands/RicMoveItemsToTopFeature.cpp
- ApplicationCode/Commands/ToggleCommands/RicMoveItemsToTopFeature.h
- ApplicationCode/ProjectDataModel/RimContextCommandBuilder.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmFieldReorderCapability.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmFieldReorderCapability.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewEditor.cpp
> AppFwk : Add support for moving selected items to top list 

- ApplicationCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCaseCollection.h
> Ensemble Parameters : Improve performance for list in Property Editor

- ApplicationCode/Commands/SummaryPlotCommands/RicViewZoomAllFeature.cpp
* Makes it consistent with the other view actions.
> Disable Zoom All if there's no active view.

- ApplicationCode/UserInterface/RiuAbstractLegendFrame.cpp
- ApplicationCode/UserInterface/RiuScalarMapperLegendFrame.cpp
Multiline legend title fix.
Fixes #6728.
> Legend title issues

- ApplicationCode/FileInterface/RifReaderEclipseSummary.cpp
- ApplicationCode/FileInterface/RifReaderEclipseSummary.h
> Fix difference summary vector names

- ApplicationCode/ModelVisualization/RivMeasurementPartMgr.cpp
> Themes : Apply style to measurement boxes

- ApplicationCode/ReservoirDataModel/cvfGeometryTools.cpp
> Tensor computations : Fix issues when creating the rotation matrix 

- ApplicationCode/Commands/ColorLegendCommands/RicCopyStandardLegendFeature.cpp
- ApplicationCode/Commands/ColorLegendCommands/RicInsertColorLegendFeature.cpp
- ApplicationCode/Commands/ColorLegendCommands/RicInsertColorLegendItemFeature.cpp
- ApplicationCode/ProjectDataModel/RimColorLegendCollection.cpp
> #6490: Improve color legends right-click menus

- ApplicationCode/Application/Tools/RiaProjectModifier.cpp
- ApplicationCode/Application/Tools/RiaProjectModifier.h
- ApplicationCode/Application/Tools/RiaRegressionTest.cpp
- ApplicationCode/Application/Tools/RiaRegressionTest.h
- ApplicationCode/Application/Tools/RiaRegressionTestRunner.cpp
- ApplicationCode/ProjectDataModel/RimProject.cpp
- ApplicationCode/ProjectDataModel/RimProject.h
> Test System : Add flag from regression dialog to invalidate external files

- ApplicationCode/Application/Tools/RiaProjectModifier.cpp
- ApplicationCode/Application/Tools/RiaProjectModifier.h
- ApplicationCode/Application/Tools/RiaRegressionTest.cpp
- ApplicationCode/Application/Tools/RiaRegressionTest.h
- ApplicationCode/Application/Tools/RiaRegressionTestRunner.cpp
- ApplicationCode/ModelVisualization/GridBox/RivGridBoxGenerator.cpp
- ApplicationCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.cpp
- ApplicationCode/ProjectDataModel/Flow/RimFlowCharacteristicsPlot.cpp
- ApplicationCode/ProjectDataModel/Flow/RimFlowDiagSolution.cpp
- ApplicationCode/ProjectDataModel/Flow/RimWellPlotTools.cpp
- ApplicationCode/ProjectDataModel/Flow/RimWellPltPlot.cpp
- ApplicationCode/ProjectDataModel/RimEclipseCase.cpp
- ApplicationCode/ProjectDataModel/RimEclipseResultDefinition.cpp
- ApplicationCode/ProjectDataModel/RimIntersection.cpp
- ApplicationCode/ProjectDataModel/RimSimWellInView.cpp
- ApplicationCode/ProjectDataModel/RimViewController.cpp
- ApplicationCode/SocketInterface/RiaPropertyDataCommands.cpp
> Regression Test : Add more input validation due to missing files

- ApplicationCode/ProjectDataModel/RimElementVectorResult.cpp
Fixes #6780.
Adjusted camel case style of settings fields.
> Fixes crash when there is no flr data

- ApplicationCode/ModelVisualization/RivElementVectorResultPartMgr.cpp
- ApplicationCode/ProjectDataModel/RimElementVectorResult.cpp
> Bugfix : Lower threshold not applied

- ApplicationCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
> Ensemble import: Show name of case with non-matching parameters

- ApplicationCode/ModelVisualization/RivElementVectorResultPartMgr.cpp
> 6781 - Fix of z scaling issue for flow vectors

- ApplicationCode/UserInterface/AnalysisPlots/RiuGroupedBarChartBuilder.cpp
> Changed legend text color in Correlation Plots.

- ApplicationCode/ModelVisualization/RivElementVectorResultPartMgr.cpp
> Adjusted arrow head size.

- ApplicationCode/UserInterface/RiuQwtCurvePointTracker.cpp
> Bug fix: curve point tracker not always on top of all curves

- ApplicationCode/Commands/RicElasticPropertiesImportTools.cpp
- ApplicationCode/Commands/RicElasticPropertiesImportTools.h
> 6651 elastic properties wildcard

- ApplicationCode/GrpcInterface/Python/rips/PythonExamples/create_and_export_fracture_model.py
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelCurve.cpp
- ApplicationCode/ProjectDataModel/RimLayerCurve.cpp
> 6233 fracture model md from python

- ApplicationCode/FileInterface/RifFractureModelDeviationFrkExporter.cpp
- ApplicationCode/FileInterface/RifFractureModelDeviationFrkExporter.h
- ApplicationCode/UnitTests/CMakeLists_files.cmake
- ApplicationCode/UnitTests/RifFractureModelDeviationFrkExporter-Test.cpp
> Deviation export md tvd 6526

- .github/workflows/ResInsightWithCache.yml
- ApplicationCode/CMakeLists.txt
> Deployment : Update names of deployment DLLs on Windows

- ApplicationCode/Application/Tools/RiaExtractionTools.cpp
- ApplicationCode/Application/Tools/RiaExtractionTools.h
- ApplicationCode/ProjectDataModel/RimWellLogPlotCollection.cpp
- ApplicationCode/ProjectDataModel/RimWellLogPlotCollection.h
> #6845 Fix not_null failure in WellMeasurement reg test

- ApplicationCode/Commands/CompletionCommands/RicNewFractureModelPlotFeature.cpp
- ApplicationCode/Commands/CompletionCommands/RicNewFractureModelPlotFeature.h
- ApplicationCode/Commands/FractureCommands/RicNewFractureModelFeature.cpp
- ApplicationCode/Commands/FractureCommands/RicNewFractureModelFeature.h
- ApplicationCode/Commands/FractureCommands/RicNewWellPathFractureModelAtPosFeature.cpp
- ApplicationCode/GrpcInterface/Python/rips/PythonExamples/create_and_export_fracture_model.py
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFractureModel.h
- ApplicationCode/ProjectDataModel/RimFractureModelCalculator.cpp
- ApplicationCode/ProjectDataModelCommands/CMakeLists_files.cmake
- ApplicationCode/ProjectDataModelCommands/RimcFractureModel.cpp
- ApplicationCode/ProjectDataModelCommands/RimcFractureModel.h
- ApplicationCode/ProjectDataModelCommands/RimcFractureModelCollection.cpp
- ApplicationCode/ProjectDataModelCommands/RimcFractureModelCollection.h
- ApplicationCode/ProjectDataModelCommands/RimcFractureModelPlotCollection.cpp
- ApplicationCode/ProjectDataModelCommands/RimcFractureModelPlotCollection.h
> 6833 fracture model set case

- ApplicationCode/ProjectDataModel/RimFractureModelElasticPropertyCalculator.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelLayerCalculator.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelWellLogCalculator.cpp
- ApplicationCode/ProjectDataModel/RimNonNetLayers.cpp
- ApplicationCode/ProjectDataModel/RimNonNetLayers.h
> 6835 improve non net layers

- ApplicationCode/ProjectDataModel/RimFractureModelElasticPropertyCalculator.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelLayerCalculator.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelStressCalculator.cpp
- ApplicationCode/ProjectDataModel/RimFractureModelWellLogCalculator.cpp
> #6854 Fix asserts/crashes when layer extraction fails.

- ApplicationCode/GrpcInterface/CMakeLists.txt
Once this pull request is in your builds should work as previousl, @akva2 . Tagging you so you get notification when it is merged.
> Support non-cmake builds of gRPC

- ApplicationCode/UnitTests/RiuSummaryVectorDescriptionMap-Test.cpp
- ApplicationCode/UserInterface/RiuSummaryQuantityNameInfoProvider.cpp
Include updates from Peter Forster
Closes #6867
> Summary Vector Names 6X : Include name updates from 6X

- ApplicationCode/FileInterface/RifReaderEclipseOutput.cpp
- ThirdParty/Ert/lib/ecl/ecl_grid.cpp
Closes #6869 
Based on fix by Jean-Paul Balabanian <jpb@equinor.com>
> Coarse Grid: Make sure empty coarsening cells are handled correctly

- OctavePlugin/riGetActiveCellCenters.cpp
- OctavePlugin/riGetActiveCellCorners.cpp
- OctavePlugin/riGetActiveCellInfo.cpp
- OctavePlugin/riGetActiveCellProperty.cpp
- OctavePlugin/riGetCaseGroups.cpp
- OctavePlugin/riGetCases.cpp
- OctavePlugin/riGetCellCenters.cpp
- OctavePlugin/riGetCellCorners.cpp
- OctavePlugin/riGetCoarseningInfo.cpp
- OctavePlugin/riGetCurrentCase.cpp
- OctavePlugin/riGetDynamicNNCValues.cpp
- OctavePlugin/riGetGridDimensions.cpp
- OctavePlugin/riGetGridProperty.cpp
- OctavePlugin/riGetGridPropertyForSelectedCells.cpp
- OctavePlugin/riGetMainGridDimensions.cpp
- OctavePlugin/riGetNNCConnections.cpp
- OctavePlugin/riGetNNCPropertyNames.cpp
- OctavePlugin/riGetPropertyNames.cpp
- OctavePlugin/riGetSelectedCases.cpp
- OctavePlugin/riGetSelectedCells.cpp
- OctavePlugin/riGetStaticNNCValues.cpp
- OctavePlugin/riGetTimeStepDates.cpp
- OctavePlugin/riGetTimeStepDays.cpp
- OctavePlugin/riGetWellCells.cpp
- OctavePlugin/riGetWellNames.cpp
- OctavePlugin/riGetWellStatus.cpp
- OctavePlugin/riSetActiveCellProperty.cpp
- OctavePlugin/riSetGridProperty.cpp
- OctavePlugin/riSetNNCProperty.cpp
> Octave Plugin: Use %s to concatenate text strings 

- ApplicationCode/Application/RiaApplication.cpp
- ApplicationCode/Application/RiaApplication.h
- ApplicationCode/Application/RiaGuiApplication.cpp
- ApplicationCode/Commands/OctaveScriptCommands/RicExecuteScriptForCasesFeature.cpp
- ApplicationCode/GrpcInterface/RiaGrpcProjectService.cpp
- ApplicationCode/SocketInterface/RiaProjectInfoCommands.cpp
- ApplicationCode/SocketInterface/RiaSocketServer.cpp
- ApplicationCode/SocketInterface/RiaSocketServer.h
> Allow Python scripts to use currently selected cases

- ApplicationCode/ProjectDataModel/RimModeledWellPath.cpp
- ApplicationCode/ProjectDataModel/RimModeledWellPath.h
> Allow user to edit well path name for user defined well paths.

- ApplicationCode/ModelVisualization/RivContourMapProjectionPartMgr.cpp
- ApplicationCode/ProjectDataModel/RimContourMapProjection.cpp
- ApplicationCode/ProjectDataModel/RimContourMapProjection.h
> Bugfix - make show contour label checkbox work for contour plots

- ApplicationCode/ProjectDataModel/StimPlanModel/RimStimPlanModelWellLogCalculator.cpp
> #6931 Fix missing scaling for porosity and permeability.

- ApplicationCode/ProjectDataModel/RimWellLogTrack.cpp
> #6946 StimPlan Model Plot: Fix incorrect colors in facies track.

- ApplicationCode/Application/Tools/RiaSummaryCurveAnalyzer.cpp
- ApplicationCode/Application/Tools/RiaSummaryCurveAnalyzer.h
- ApplicationCode/Commands/RicReloadSummaryCaseFeature.cpp
- ApplicationCode/Commands/RicReplaceSummaryCaseFeature.cpp
- ApplicationCode/Commands/RicReplaceSummaryCaseFeature.h
- ApplicationCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.h
- ApplicationCode/UserInterface/RiuSummaryQuantityNameInfoProvider.cpp
> Minor summary issues

- ApplicationCode/ProjectDataModel/StimPlanModel/RimElasticPropertyScalingCollection.cpp
- ApplicationCode/ProjectDataModel/StimPlanModel/RimElasticPropertyScalingCollection.h
- ApplicationCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
- ApplicationCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.h
- ApplicationCode/ProjectDataModel/StimPlanModel/RimStimPlanModelPlot.cpp
Closes #6948.
Closes #6934.
Closes #6937.
Closes #6936.
> Misc stimplan fixes

- ApplicationCode/GrpcInterface/Python/rips/PythonExamples/create_and_export_stim_plan_model.py
> #6935 Extend python example with more than one model.

- ApplicationCode/FileInterface/RifEclipseInputPropertyLoader.cpp
- ApplicationCode/FileInterface/RifEclipseInputPropertyLoader.h
- ApplicationCode/ProjectDataModel/RimEclipseCase.cpp
- ApplicationCode/ProjectDataModel/RimEclipseCase.h
- ApplicationCode/ProjectDataModel/RimEclipseInputCase.cpp
> Fault Import : Make sure faults in separate text file is imported

- ApplicationCode/ProjectDataModel/RimColorLegend.cpp
> Color Legend : Make sure there are at least two color items 

- ApplicationCode/ProjectDataModel/RimEclipseCellColors.cpp
- ApplicationCode/ProjectDataModel/RimRegularLegendConfig.cpp
- ApplicationCode/ProjectDataModel/RimRegularLegendConfig.h
- ApplicationCode/UnitTests/RifColorLegendData-Test.cpp
> Color Legend : Improve default settings for user defined values

- ApplicationCode/Application/RiaApplication.cpp
- ApplicationCode/ProjectDataModel/CMakeLists_files.cmake
- ApplicationCode/ProjectDataModel/RimCase.cpp
- ApplicationCode/ProjectDataModel/RimCase.h
- ApplicationCode/ProjectDataModel/RimCaseDisplayNameTools.cpp
- ApplicationCode/ProjectDataModel/RimCaseDisplayNameTools.h
- ApplicationCode/ProjectDataModel/RimEclipseCase.cpp
- ApplicationCode/ProjectDataModel/RimEclipseInputCase.cpp
- ApplicationCode/ProjectDataModel/RimEclipseResultCase.cpp
- ApplicationCode/ProjectDataModel/RimGeoMechCase.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCase.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCase.h
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
Added extra option to choose auto-name option (similar to RimSummaryCase).
Closes #6991.
> #6991 Update file name for replaced case.

- ApplicationCode/Commands/RicFaciesPropertiesImportTools.cpp
- ApplicationCode/ProjectDataModel/StimPlanModel/RimFaciesProperties.cpp
- ApplicationCode/ProjectDataModel/StimPlanModel/RimFaciesProperties.h
> #7012 Clear facies code names when importing roff files

- ApplicationCode/ProjectDataModel/StimPlanModel/RimNonNetLayers.cpp
- ApplicationCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
- ApplicationCode/ProjectDataModel/StimPlanModel/RimStimPlanModelWellLogCalculator.cpp
> 7022 stimplan model ux fixes

- ApplicationCode/Application/RiaSummaryCurveDefinition.cpp
- ApplicationCode/Commands/SummaryPlotCommands/RicNewDerivedSummaryFeature.cpp
- ApplicationCode/ModelVisualization/RivElementVectorResultPartMgr.cpp
- ApplicationCode/ProjectDataModel/Summary/RimDerivedEnsembleCaseCollection.cpp
- ApplicationCode/ProjectDataModel/Summary/RimDerivedSummaryCase.cpp
> Fix two crash situations

- ApplicationCode/GrpcInterface/Python/rips/tests/test_summary_cases.py
- ApplicationCode/ProjectDataModelCommands/RimcSummaryCase.cpp
> Python: Guard nullpointer access for summary methods

- ApplicationCode/GrpcInterface/RiaGrpcPropertiesService.cpp
> Python: Resize the result container before assigning data

- ApplicationCode/Commands/RicRecursiveFileSearchDialog.cpp
> File Import Dialog : Sort by numbers instead of text

- ApplicationCode/Application/RiaApplication.cpp
- ApplicationCode/UserInterface/RiuMainWindow.cpp
> Python: Avoid terminating process as part of open/closeProject

- ApplicationCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlot.cpp
> Grid Cross Plot: Fix inverted Y-axis for user-defined min/max range

- ApplicationCode/ModelVisualization/RivContourMapProjectionPartMgr.cpp
- ApplicationCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlot.cpp
- ApplicationCode/ProjectDataModel/RimRegularLegendConfig.cpp
- ApplicationCode/ProjectDataModel/RimRegularLegendConfig.h
- ApplicationCode/UserInterface/RiuScalarMapperLegendFrame.cpp
> Contour Map: Label format it should match the legend format 

- ApplicationCode/Commands/CompletionCommands/RicNewStimPlanModelPlotFeature.cpp
- ApplicationCode/Commands/CompletionCommands/RicNewStimPlanModelPlotFeature.h
> 6920 stimplan model plot default visible curves

- ApplicationCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.cpp
- ApplicationCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.h
Default is now to read the contour xml file and update the parameter,
but older projects are left unchanged.
Closes #7088.
> #7088 Add option to reread "Well/Fracture Intersection Depth" from XML.

- .github/workflows/ResInsightWithCache.yml
- ApplicationCode/GrpcInterface/Python/rips/grpc_retry_interceptor.py
- ApplicationCode/GrpcInterface/Python/rips/instance.py
- ApplicationCode/GrpcInterface/Python/rips/retry_policy.py
- ApplicationCode/GrpcInterface/Python/rips/tests/conftest.py
> 7136 python timeouts

- ApplicationLibCode/ProjectDataModel/Flow/RimWellRftEnsembleCurveSet.cpp
- ApplicationLibCode/ProjectDataModel/Flow/RimWellRftEnsembleCurveSet.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.h
> Ensemble RFT colors

- ApplicationLibCode/Commands/ApplicationCommands/RicShowPlotDataFeature.cpp
- ApplicationLibCode/ProjectDataModel/CMakeLists_files.cmake
- ApplicationLibCode/ProjectDataModel/RimVfpDefines.cpp
- ApplicationLibCode/ProjectDataModel/RimVfpDefines.h
- ApplicationLibCode/ProjectDataModel/RimVfpPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimVfpPlot.h
- ApplicationLibCode/UserInterface/CMakeLists_files.cmake
- ApplicationLibCode/UserInterface/RiuGridCrossQwtPlot.cpp
- ApplicationLibCode/UserInterface/RiuGridCrossQwtPlot.h
- ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp
- ApplicationLibCode/UserInterface/RiuQwtPlotWidget.h
- ApplicationLibCode/UserInterface/RiuVfpQwtPlot.cpp
- ApplicationLibCode/UserInterface/RiuVfpQwtPlot.h
- ApplicationLibCode/UserInterface/RiuWellAllocationPlot.cpp
- ApplicationLibCode/UserInterface/RiuWellAllocationPlot.h
> 7147 vfp show plot data

- ApplicationLibCode/ProjectDataModel/RimEclipseResultDefinition.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseResultDefinition.h
- ApplicationLibCode/ReservoirDataModel/CMakeLists_files.cmake
- ApplicationLibCode/ReservoirDataModel/RigVisibleTracerFilter.cpp
- ApplicationLibCode/ReservoirDataModel/RigVisibleTracerFilter.h
> #7151 Flow Diagnostics: Filter legend based on visible wells/regions.

- ApplicationLibCode/Application/RiaStimPlanModelDefines.cpp
- ApplicationLibCode/Application/RiaStimPlanModelDefines.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelTemplate.cpp
> #7148 StimPlanModel: provide better default for por/perm.

- ApplicationLibCode/Commands/FractureCommands/RicNewStimPlanFractureTemplateFeature.cpp
> #7111 Remember last file path for StimPlan XML.

- ApplicationLibCode/Application/RiaStimPlanModelDefines.cpp
- ApplicationLibCode/Application/RiaStimPlanModelDefines.h
- ApplicationLibCode/ProjectDataModel/RimWellLogTrack.cpp
- ApplicationLibCode/ProjectDataModel/RimWellLogTrack.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelCurve.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelCurve.h
> #6227 Filter out zero values in logarithmic plot.

- ApplicationLibCode/Commands/RicNewContourMapViewFeature.cpp
> Make sure surfaces are turned off in all contourmaps.

- ApplicationLibCode/ProjectDataModel/RimWellBoreStabilityPlot.cpp
Had to make a small adjustment to the update of plot title. A broken regression test was fixed with this PR.
> #7158 WBS plot : Update plot name when water depth changes

- ApplicationLibCode/Commands/OctaveScriptCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/OctaveScriptCommands/RicExecuteLastUsedScriptFeature.cpp
- ApplicationLibCode/Commands/OctaveScriptCommands/RicExecuteLastUsedScriptFeature.h
- ApplicationLibCode/Commands/OctaveScriptCommands/RicExecuteScriptFeature.cpp
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/UserInterface/RiuMainWindow.cpp
> Script : Add execute of last used script 

- ApplicationLibCode/Commands/CompletionExportCommands/RicExportFractureCompletionsImpl.cpp
- ApplicationLibCode/Commands/FractureCommands/RicNewStimPlanFractureTemplateFeature.cpp
- ApplicationLibCode/FileInterface/RifStimPlanXmlReader.cpp
- ApplicationLibCode/FileInterface/RifStimPlanXmlReader.h
- ApplicationLibCode/ModelVisualization/RivWellFracturePartMgr.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimEllipseFractureTemplate.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimEllipseFractureTemplate.h
- ApplicationLibCode/ProjectDataModel/Completions/RimFracture.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimFracture.h
- ApplicationLibCode/ProjectDataModel/Completions/RimFractureTemplate.h
- ApplicationLibCode/ProjectDataModel/Completions/RimFractureTemplateCollection.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.h
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathFracture.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathFracture.h
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathFractureCollection.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathFractureCollection.h
- ApplicationLibCode/ProjectDataModel/RimStimPlanColors.cpp
- ApplicationLibCode/ReservoirDataModel/Completions/RigWellPathStimplanIntersector.cpp
- ApplicationLibCode/ReservoirDataModel/RigStimPlanFractureDefinition.cpp
- ApplicationLibCode/ReservoirDataModel/RigStimPlanFractureDefinition.h
- ApplicationLibCode/UnitTests/RifStimPlanXmlReader-Test.cpp
Closes #6877.
Closes #7279,
Closes #7280.
> 6877 well fracture intersection per fracture

- ApplicationLibCode/ProjectDataModel/Completions/RimEllipseFractureTemplate.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimEllipseFractureTemplate.h
- ApplicationLibCode/ProjectDataModel/Completions/RimFracture.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimFractureTemplate.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimFractureTemplate.h
- ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.h
> 7026 well fracture intersection depth ellipse

- ApplicationLibCode/ProjectDataModel/Completions/RimFracture.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimFracture.h
- ApplicationLibCode/ProjectDataModel/Completions/RimFractureTemplate.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimFractureTemplate.h
- ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.h
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathFracture.cpp
> 7309 update intersection depth from template

- ApplicationLibCode/ProjectDataModel/Completions/RimFracture.cpp
> #7298 Fracture: generate fracture grid for 'create at depth'

- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorStressAnisotropy.cpp
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorStressAnisotropy.h
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.h
- ApplicationLibCode/ProjectDataModel/RimEclipseCellColors.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseCellColors.h
- ApplicationLibCode/ProjectDataModel/RimGeoMechResultDefinition.cpp
- ApplicationLibCode/ProjectDataModel/RimSummaryCalculation.cpp
- ApplicationLibCode/UnitTests/RicExpressionParser-Test.cpp
- ThirdParty/expressionparser/ExpressionParser.cpp
- ThirdParty/expressionparser/ExpressionParser.h
- ThirdParty/expressionparser/ExpressionParserImpl.cpp
- ThirdParty/expressionparser/ExpressionParserImpl.h
Closes #7074
Closes #7293
Closes #7304 
Implement support for if-statements #7316
> Fix some maintenance issues

- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
> #7140 StimPlanModel: Fix direction to barrier calculation.

- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
> #7143 StimPlanModel: Compute formation dip in fracture plane.

- ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.h
> #7329 Report MD and formation dip from StimPlan template XML.

- ApplicationLibCode/ProjectDataModel/RimEclipseResultDefinition.cpp
- ApplicationLibCode/ReservoirDataModel/RigFlowDiagSolverInterface.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/dune.module
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLGraph.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLPvtCommon.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLPvtGas.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLPvtOil.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLPvtWater.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLResultData.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLSaturationFunc.cpp
- ThirdParty/custom-opm-flowdiagnostics/opm-flowdiagnostics/dune.module
> Dual poro models : Support PVT and Rel Perm plots 

- ApplicationLibCode/ProjectDataModel/RimContourMapProjection.cpp
> Contour maps: Filter out both positive and negative inf values

- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLPvtCommon.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLPvtGas.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLPvtOil.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLPvtWater.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLSaturationFunc.cpp
> Dual poro models : Throw exception if invalid data is detected

- ApplicationLibCode/ReservoirDataModel/RigFlowDiagSolverInterface.cpp
- ApplicationLibCode/ReservoirDataModel/RigFlowDiagSolverInterface.h
- ApplicationLibCode/UserInterface/RiuPvtPlotUpdater.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLPvtCurveCollection.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLPvtCurveCollection.hpp
> PVT curves : Use PVTNUM value to get PVT curve data 

- ApplicationLibCode/Commands/ExportCommands/RicExportSelectedWellPathsFeature.cpp
- ApplicationLibCode/Commands/ExportCommands/RicExportSelectedWellPathsFeature.h
- ApplicationLibCode/Commands/ExportCommands/RicExportVisibleWellPathsFeature.cpp
> Export well path: Error for well name with slash

- ApplicationLibCode/Application/RiaSummaryCurveDefinition.cpp
- ApplicationLibCode/Application/RiaSummaryCurveDefinition.h
- ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.cpp
- ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.h
- ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlotCollection.cpp
- ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlotDataEntry.h
- ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimPlotDataFilterItem.h
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimAbstractCorrelationPlot.cpp
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimAbstractCorrelationPlot.h
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationMatrixPlot.cpp
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationPlot.cpp
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationPlot.h
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimParameterResultCrossPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimCustomObjectiveFunctionWeight.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveFilter.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotAxisFormatter.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotAxisFormatter.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotFilterTextCurveSetEditor.h
- ApplicationLibCode/UserInterface/RiuSummaryVectorSelectionDialog.h
> Improve UI text for correlation plots

- ApplicationLibCode/Commands/ExportCommands/RicAdvancedSnapshotExportFeature.cpp
> Fix advanced snapshot

- ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.h
> 7364 report tvd from stimplan xml

- ApplicationLibCode/Application/Tools/RiaQDateTimeTools.cpp
- ApplicationLibCode/Application/Tools/RiaTimeHistoryCurveResampler.cpp
- ApplicationLibCode/Commands/RicSummaryCaseRestartDialog.cpp
- ApplicationLibCode/FileInterface/RifColumnBasedUserData.cpp
- ApplicationLibCode/FileInterface/RifCsvUserDataParser.cpp
- ApplicationLibCode/FileInterface/RifKeywordVectorUserData.cpp
- ApplicationLibCode/FileInterface/RifReaderEclipseOutput.cpp
- ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.cpp
- ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimPlotDataFilterItem.cpp
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationMatrixPlot.cpp
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationPlot.cpp
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationReportPlot.cpp
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimParameterResultCrossPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimGridTimeHistoryCurve.cpp
- ApplicationLibCode/ProjectDataModel/RimSimWellInViewTools.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimAsciiDataCurve.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.cpp
- ApplicationLibCode/UnitTests/ObservedDataParser-Test.cpp
- ApplicationLibCode/UnitTests/RiaTimeHistoryCurveTools-Test.cpp
> Remove use of deprecated time_t functions in QDateTime 

- ApplicationLibCode/Application/RiaStimPlanModelDefines.cpp
- ApplicationLibCode/Application/RiaStimPlanModelDefines.h
- ApplicationLibCode/Commands/CompletionCommands/RicNewStimPlanModelPlotFeature.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelCalculator.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelCalculator.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelPressureCalculator.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelPressureCalculator.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelWellLogCalculator.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelWellLogCalculator.h
> 7400 improved pressure interpolation

- ApplicationLibCode/Commands/CompletionExportCommands/RicMswExportInfo.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelWellLogCalculator.cpp
- ApplicationLibCode/ReservoirDataModel/CMakeLists_files.cmake
- ApplicationLibCode/ReservoirDataModel/RigStimPlanModelTools.cpp
- ApplicationLibCode/ReservoirDataModel/RigStimPlanModelTools.h
> 7392 stimplanmodel extract geometry methods

- ApplicationLibCode/ModelVisualization/Streamlines/RivStreamlinesPartMgr.cpp
- ApplicationLibCode/ModelVisualization/Streamlines/RivStreamlinesPartMgr.h
- ApplicationLibCode/ProjectDataModel/Streamlines/CMakeLists_files.cmake
- ApplicationLibCode/ProjectDataModel/Streamlines/RimStreamline.cpp
- ApplicationLibCode/ProjectDataModel/Streamlines/RimStreamline.h
- ApplicationLibCode/ProjectDataModel/Streamlines/RimStreamlineDataAccess.cpp
- ApplicationLibCode/ProjectDataModel/Streamlines/RimStreamlineDataAccess.h
- ApplicationLibCode/ProjectDataModel/Streamlines/RimStreamlineGenerator.cpp
- ApplicationLibCode/ProjectDataModel/Streamlines/RimStreamlineGenerator.h
- ApplicationLibCode/ProjectDataModel/Streamlines/RimStreamlineGenerator2.cpp
- ApplicationLibCode/ProjectDataModel/Streamlines/RimStreamlineGenerator2.h
- ApplicationLibCode/ProjectDataModel/Streamlines/RimStreamlineGeneratorBase.cpp
- ApplicationLibCode/ProjectDataModel/Streamlines/RimStreamlineGeneratorBase.h
- ApplicationLibCode/ProjectDataModel/Streamlines/RimStreamlineInViewCollection.cpp
- ApplicationLibCode/ProjectDataModel/Streamlines/RimStreamlineInViewCollection.h
> Streamline improvement

- ApplicationLibCode/CommandFileInterface/CMakeLists_files.cmake
- ApplicationLibCode/CommandFileInterface/RicfCommandFileExecutor.cpp
- ApplicationLibCode/CommandFileInterface/RicfCommandFileExecutor.h
- ApplicationLibCode/CommandFileInterface/RicfEnableDataSourceAsComment.cpp
- ApplicationLibCode/CommandFileInterface/RicfEnableDataSourceAsComment.h
- ApplicationLibCode/CommandFileInterface/RicfExportSimWellFractureCompletions.cpp
- ApplicationLibCode/CommandFileInterface/RicfExportWellPathCompletions.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicExportCompletionDataSettingsUi.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicExportCompletionDataSettingsUi.h
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.h
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.h
- ApplicationLibCode/FileInterface/RifCsvDataTableFormatter.cpp
- ApplicationLibCode/FileInterface/RifTextDataTableFormatter.cpp
- ApplicationLibCode/FileInterface/RifTextDataTableFormatter.h
- ApplicationLibCode/UnitTests/RifTextDataTableFormatter-Test.cpp
NB Merge this PR after the MSW changes has been merged
Closes #7305 
Closes #7319 
Closes #7320
> Completion Export : Add option to control export of comments

- ApplicationLibCode/ProjectDataModel/RimEclipseCase.cpp
- ApplicationLibCode/ReservoirDataModel/Completions/RigVirtualPerforationTransmissibilities.cpp
> 7442 Create LGR : Segfault when no dynamic data is present

- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimPressureTable.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimPressureTable.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimPressureTableItem.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimPressureTableItem.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelCurve.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelTemplate.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelTemplate.h
> 7453 stimplan pressure table adjustments

- ApplicationLibCode/FileInterface/RifStimPlanModelGeologicalFrkExporter.cpp
- ApplicationLibCode/FileInterface/RifStimPlanModelGeologicalFrkExporter.h
> 7368 geological frk to csv

- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimFaciesInitialPressureConfig.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelPressureCalculator.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelTemplate.cpp
> 7454 facies pressure settings

- ApplicationLibCode/FileInterface/RifEclipseInputFileTools.cpp
> #6947 Silence warning about ECHO eclipse keyword size mismatch.

- ApplicationLibCode/Application/Tools/RiaInterpolationTools.cpp
- ApplicationLibCode/Application/Tools/RiaInterpolationTools.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelElasticPropertyCalculator.cpp
- ApplicationLibCode/ReservoirDataModel/RigElasticProperties.cpp
- ApplicationLibCode/ReservoirDataModel/RigElasticProperties.h
- ApplicationLibCode/UnitTests/RiaInterpolationTools-Test.cpp
> 7116 extrapolation elastic properties

- ApplicationLibCode/ReservoirDataModel/RigWellPathIntersectionTools.cpp
- ApplicationLibCode/ReservoirDataModel/RigWellPathIntersectionTools.h
> Well Path Tools : Use a positive value of each component to represent length

- ApplicationLibCode/Commands/CompletionExportCommands/RicExportCompletionsWellSegmentsFeature.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeature.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.cpp
> Compdat Export : Check if export folder exist 

- ApplicationLibCode/Application/Tools/RiaImportEclipseCaseTools.h
- ApplicationLibCode/Commands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/RicImportGridModelFromSummaryCaseFeature.cpp
- ApplicationLibCode/Commands/RicImportGridModelFromSummaryCaseFeature.h
- ApplicationLibCode/Commands/RicImportGridModelFromSummaryCurveFeature.cpp
- ApplicationLibCode/Commands/RicImportGridModelFromSummaryCurveFeature.h
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/UserInterface/RiuSummaryQwtPlot.cpp
- Fwk/AppFwk/cafCommand/cafCmdFeatureMenuBuilder.cpp
> Usability : Open grid model from summary case and summary curve

- ApplicationLibCode/Commands/CompletionExportCommands/RicFishbonesTransmissibilityCalculationFeatureImp.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.h
- ApplicationLibCode/ProjectDataModel/Completions/RimFishbonesCollection.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimFishbonesCollection.h
- ApplicationLibCode/ProjectDataModel/Completions/RimPerforationCollection.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimPerforationCollection.h
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathCompletionSettings.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathCompletionSettings.h
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathFractureCollection.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathFractureCollection.h
- ApplicationLibCode/ProjectDataModel/RimWellPath.cpp
- ApplicationLibCode/ProjectDataModel/RimWellPath.h
Restore MSW parameters on completion collections
> MSW : Remove MSW parameters at top level

- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelTemplate.cpp
> #7490 StimPlanModel: Group pressure data source fields.

- ApplicationLibCode/Application/RiaStimPlanModelDefines.cpp
- ApplicationLibCode/Application/RiaStimPlanModelDefines.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelCalculator.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelCalculator.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelPressureCalculator.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelPressureCalculator.h
> #7452 Use pressure gradient from equilibrium region for stress gradient

- ApplicationLibCode/UserInterface/RiuWellLogTrack.cpp
> #6222 Make cursor tracker readable in well log plot.

- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimFaciesInitialPressureConfig.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelTemplate.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelTemplate.h
> 7500 pressure config tweaks

- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelStressCalculator.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelStressCalculator.h
> StimPlanModelPlot: Remove gaps in stress gradient and temperature curves

- ApplicationLibCode/Commands/ExportCommands/RicSnapshotViewToFileFeature.cpp
- ApplicationLibCode/FileInterface/RifOpmCommonSummary.cpp
- ApplicationLibCode/FileInterface/RifReaderEclipseSummary.cpp
- ApplicationLibCode/UnitTests/RiaStdStringTools-Test.cpp
> Smaller maintenance issues

- ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp
- ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.h
- ApplicationLibCode/ProjectDataModel/RimWellLogRftCurve.cpp
- Fwk/AppFwk/cafCommand/cafCmdUiCommandSystemImpl.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafPdmUiCommandSystemProxy.cpp
> Fix RFT crash

- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimAbstractCorrelationPlot.cpp
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimAbstractCorrelationPlot.h
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationMatrixPlot.cpp
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationMatrixPlot.h
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationPlot.cpp
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationPlot.h
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationReportPlot.cpp
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationReportPlot.h
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimParameterResultCrossPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.h
> #7524 Correlation plot filter

- ApplicationLibCode/FileInterface/RifHdf5SummaryReader.cpp
> HDF Summary Reader : Support HH:MM:SS when parsing start date 

- ApplicationLibCode/Application/RiaPreferences.cpp
- ApplicationLibCode/Application/RiaPreferences.h
- ApplicationLibCode/CMakeLists.txt
- ApplicationLibCode/FileInterface/RifHdf5Exporter.cpp
- ApplicationLibCode/FileInterface/RifHdf5Exporter.h
- ApplicationLibCode/FileInterface/RifHdf5SummaryExporter.cpp
- ApplicationLibCode/FileInterface/RifHdf5SummaryExporter.h
- ApplicationLibCode/FileInterface/RifHdf5SummaryReader.cpp
- ApplicationLibCode/FileInterface/RifReaderEclipseSummary.cpp
- ApplicationLibCode/UnitTests/CMakeLists_files.cmake
- ApplicationLibCode/UnitTests/HDF5FileWriter-Test.cpp
- ThirdParty/custom-opm-common/opm-common/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
> HDF5 summary data export

- ApplicationLibCode/FileInterface/RifHdf5Exporter.cpp
- ApplicationLibCode/FileInterface/RifHdf5Exporter.h
- ApplicationLibCode/FileInterface/RifHdf5SummaryExporter.cpp
> Hdf adjustments

- ApplicationLibCode/Application/RiaEclipseFileNameTools.cpp
- ApplicationLibCode/Application/RiaEclipseFileNameTools.h
- ApplicationLibCode/Application/RiaPreferences.cpp
- ApplicationLibCode/Application/RiaPreferencesSummary.cpp
- ApplicationLibCode/Application/RiaPreferencesSummary.h
- ApplicationLibCode/FileInterface/RifHdf5SummaryExporter.cpp
- ApplicationLibCode/FileInterface/RifHdf5SummaryExporter.h
- ApplicationLibCode/FileInterface/RifHdf5SummaryReader.cpp
- ApplicationLibCode/FileInterface/RifHdf5SummaryReader.h
- ApplicationLibCode/FileInterface/RifReaderEclipseSummary.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.h
- ApplicationLibCode/ProjectDataModelCommands/RimcProject.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcProject.h
- GrpcInterface/Python/rips/tests/test_summary_cases.py
> Minor HDF adjustments

- ApplicationLibCode/Commands/WellPathCommands/RicNewWellPathLateralAtDepthFeature.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimFishbones.cpp
- ApplicationLibCode/ReservoirDataModel/RigWellLogExtractor.cpp
> Several multilateral well issues

- ThirdParty/custom-opm-common/opm-common/src/opm/common/utility/numeric/MonotCubicInterpolator.cpp
- ThirdParty/custom-opm-common/opm-common/src/opm/io/eclipse/EclUtil.cpp
Needed to build application in VS 2017.
> Add Missing Includes

- ApplicationLibCode/Commands/CompletionExportCommands/RicMswBranch.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicMswBranch.h
- ApplicationLibCode/Commands/CompletionExportCommands/RicMswTableFormatterTools.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.cpp
> MSW : Always connect to segment with lower measured depth 

- ApplicationLibCode/FileInterface/RifReaderEclipseSummary.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.cpp
- ThirdParty/custom-opm-common/opm-common/opm/io/eclipse/EclUtil.hpp
- ThirdParty/custom-opm-common/opm-common/src/opm/io/eclipse/ESmry.cpp
- ThirdParty/custom-opm-common/opm-common/src/opm/io/eclipse/EclUtil.cpp
> Make opm summary reader work with mixed casing

- ApplicationLibCode/Commands/CompletionExportCommands/RicFishbonesTransmissibilityCalculationFeatureImp.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicMswExportInfo.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicMswExportInfo.h
- ApplicationLibCode/Commands/CompletionExportCommands/RicMswTableFormatterTools.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimFishbonesCollection.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimFishbonesCollection.h
- ApplicationLibCode/ProjectDataModel/Completions/RimMswCompletionParameters.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimMswCompletionParameters.h
- ApplicationLibCode/ProjectDataModel/Completions/RimPerforationCollection.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimPerforationCollection.h
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathCompletionSettings.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathCompletionSettings.h
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathFractureCollection.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathFractureCollection.h
- ApplicationLibCode/ProjectDataModel/RimWellPath.cpp
- ApplicationLibCode/ProjectDataModel/RimWellPath.h
> Refactor MSW settings

- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.cpp
> Connect fracture to a segment with lower measured depth

- ApplicationExeCode/Resources/HelpCircle.svg
- ApplicationExeCode/Resources/ResInsight.qrc
- ApplicationExeCode/Resources/VfpPlot.svg
- ApplicationExeCode/Resources/VfpPlotCollection.svg
- ApplicationLibCode/Commands/ApplicationCommands/RicHelpFeatures.cpp
- ApplicationLibCode/Commands/RicNewVfpPlotFeature.cpp
- ApplicationLibCode/ProjectDataModel/RimVfpPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimVfpPlotCollection.cpp
> Added icons for VFP and help actions

- ApplicationLibCode/FileInterface/RifOpmCommonSummary.cpp
- ThirdParty/custom-opm-common/opm-common/opm/io/eclipse/ESmry.hpp
- ThirdParty/custom-opm-common/opm-common/opm/io/eclipse/SummaryNode.hpp
- ThirdParty/custom-opm-common/opm-common/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
- ThirdParty/custom-opm-common/opm-common/src/opm/io/eclipse/ESmry.cpp
- ThirdParty/custom-opm-common/opm-common/src/opm/io/eclipse/SummaryNode.cpp
> HDF Summary : Add missing categories

- ApplicationLibCode/Commands/CompletionCommands/RicNewFishbonesSubsAtMeasuredDepthFeature.cpp
- ApplicationLibCode/Commands/CompletionCommands/RicNewFishbonesSubsFeature.cpp
- ApplicationLibCode/Commands/CompletionCommands/RicNewFishbonesSubsFeature.h
If well radius scale is large, set a low default value and show info in message window.
Closes #7487
> Fishbones : Remove view scaling when adding a new fish bone

- ApplicationLibCode/CommandFileInterface/RicfExportVisibleCells.cpp
- ApplicationLibCode/CommandFileInterface/RicfExportVisibleCells.h
- ApplicationLibCode/Commands/ExportCommands/RicSaveEclipseInputVisibleCellsFeature.cpp
- ApplicationLibCode/Commands/ExportCommands/RicSaveEclipseInputVisibleCellsUi.cpp
- ApplicationLibCode/Commands/ExportCommands/RicSaveEclipseInputVisibleCellsUi.h
> Export Sector : Add support for export of ACTNUM 

- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.h
> 7558 mesh alignment by depth

- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.h
- GrpcInterface/Python/rips/pdmobject.py
> 7608 exclude cells in mean calculation

- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.h
> 7556 formation dip statistics

- ApplicationLibCode/Commands/FractureCommands/RicNewStimPlanFractureTemplateFeature.cpp
- ApplicationLibCode/Commands/FractureCommands/RicNewStimPlanFractureTemplateFeature.h
- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
> 7557 overwrite templates

- ApplicationLibCode/Application/RiaPreferences.cpp
- ApplicationLibCode/Application/RiaPreferencesSummary.cpp
- ApplicationLibCode/Application/RiaPreferencesSummary.h
- ApplicationLibCode/Commands/ExportCommands/RicExportToLasFileResampleUi.cpp
- ApplicationLibCode/FileInterface/RifReaderSettings.cpp
- ApplicationLibCode/FileInterface/RifReaderSettings.h
- ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.cpp
- ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiCheckBoxEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiCheckBoxEditor.h
> Make use of native checkbox easier and more robust

- ApplicationLibCode/ReservoirDataModel/RigWellLogExtractor.cpp
Monotonically is the mathematical term.
> Correct wording error in well log warning

- ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.cpp
> #7671 StimPlan XML import: fix unit system assert on missing file.

- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.h
- ApplicationLibCode/ReservoirDataModel/RigEnsembleFractureStatisticsCalculator.cpp
- ApplicationLibCode/ReservoirDataModel/RigEnsembleFractureStatisticsCalculator.h
> #7670 Show Ensemble Fracture Statistics as table

- ApplicationLibCode/CommandFileInterface/RicfCreateLgrForCompletions.cpp
- ApplicationLibCode/CommandFileInterface/RicfExportLgrForCompletions.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicExportCompletionDataSettingsUi.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicExportCompletionDataSettingsUi.h
- ApplicationLibCode/Commands/CompletionExportCommands/RicFishbonesTransmissibilityCalculationFeatureImp.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicMswCompletions.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicMswCompletions.h
- ApplicationLibCode/Commands/CompletionExportCommands/RicMswTableFormatterTools.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicMswTableFormatterTools.h
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.h
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.cpp
- ApplicationLibCode/Commands/ExportCommands/RicExportLgrFeature.cpp
- ApplicationLibCode/Commands/ExportCommands/RicExportLgrFeature.h
- ApplicationLibCode/Commands/ExportCommands/RicExportLgrUi.cpp
- ApplicationLibCode/ModelVisualization/RivWellConnectionFactorPartMgr.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimCompletionCellIntersectionCalc.cpp
- ApplicationLibCode/ReservoirDataModel/Completions/RigCompletionData.cpp
- ApplicationLibCode/ReservoirDataModel/Completions/RigCompletionData.h
- ApplicationLibCode/UserInterface/RiuMainWindow.cpp
> Improvements to multilateral completion data

- ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp
- ApplicationLibCode/ProjectDataModel/Streamlines/RimStreamlineInViewCollection.cpp
- ApplicationLibCode/ProjectDataModel/Streamlines/RimStreamlineInViewCollection.h
> Disable streamlines icon in explorer for eclipse input cases.

- ApplicationLibCode/FileInterface/RifSurfaceExporter.cpp
> Fix crash when exporting surface.

- ApplicationLibCode/ModelVisualization/Surfaces/RivSurfacePartMgr.cpp
- ApplicationLibCode/ModelVisualization/Surfaces/RivSurfacePartMgr.h
- ApplicationLibCode/UserInterface/RiuViewerCommands.cpp
> Surface: click on surface in 3d view to display value

- ApplicationLibCode/Commands/CompletionExportCommands/RicExportCompletionsForVisibleWellPathsFeature.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.h
- ApplicationLibCode/Commands/RicWellLogTools.cpp
- ApplicationLibCode/ProjectDataModel/cafTreeNode.cpp
- ApplicationLibCode/ProjectDataModel/cafTreeNode.h
- ApplicationLibCode/ReservoirDataModel/RigWellPathGeometryExporter.cpp
> Fix issues related to file well path and MSW export

- ApplicationLibCode/FileInterface/RifReaderEclipseOutput.cpp
- ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimWellLogTrack.cpp
- ApplicationLibCode/ReservoirDataModel/RigAccWellFlowCalculator.cpp
- ApplicationLibCode/ReservoirDataModel/RigAccWellFlowCalculator.h
> Fix import of MSW branch

- ApplicationLibCode/ProjectDataModel/Faults/RimFaultRAPreprocSettings.cpp
> FaultRA: Advanced processing crash fix

- ApplicationLibCode/Commands/CompletionCommands/RicEditPerforationCollectionFeature.cpp
- ApplicationLibCode/Commands/CompletionCommands/RicNewFishbonesSubsFeature.cpp
- ApplicationLibCode/Commands/CompletionCommands/RicNewPerforationIntervalFeature.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeature.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.cpp
- ApplicationLibCode/Commands/RicDeleteSubItemsFeature.cpp
- ApplicationLibCode/Commands/WellPathCommands/RicImportWellPaths.cpp
- ApplicationLibCode/Commands/WellPathCommands/RicWellPathFormationsImportFileFeature.cpp
- ApplicationLibCode/Commands/WellPathCommands/RicWellPathsUnitSystemSettingsImpl.cpp
- ApplicationLibCode/Commands/WellPathCommands/RicWellPathsUnitSystemSettingsImpl.h
- ApplicationLibCode/ProjectDataModel/Completions/RimCompletionCellIntersectionCalc.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.cpp
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimTools.h
- ApplicationLibCode/ProjectDataModel/RimWellLogCurveCommonDataSource.h
- ApplicationLibCode/ProjectDataModel/RimWellMeasurementInView.cpp
- ApplicationLibCode/ProjectDataModel/RimWellPath.cpp
- ApplicationLibCode/ProjectDataModel/RimWellPath.h
- ApplicationLibCode/ProjectDataModel/RimWellPathCollection.cpp
- ApplicationLibCode/ProjectDataModel/RimWellPathCollection.h
- ApplicationLibCode/ProjectDataModel/RimWellPathTieIn.cpp
- ApplicationLibCode/ProjectDataModel/cafTreeNode.cpp
> Improve UI for well path

- ApplicationLibCode/ProjectDataModel/Faults/RimFaultRAPostprocSettings.cpp
> Fault React. Assessment: updates

- ApplicationLibCode/Application/CMakeLists_files.cmake
- ApplicationLibCode/Application/RiaNumberFormat.cpp
- ApplicationLibCode/Application/RiaNumberFormat.h
- ApplicationLibCode/ProjectDataModel/RimEclipseCellColors.cpp
- ApplicationLibCode/ProjectDataModel/RimRegularLegendConfig.cpp
- ApplicationLibCode/ProjectDataModel/RimRegularLegendConfig.h
- ApplicationLibCode/ProjectDataModel/RimStatisticsPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimStatisticsPlot.h
- ApplicationLibCode/UserInterface/RiuScalarMapperLegendFrame.cpp
- ApplicationLibCode/UserInterface/RiuScalarMapperLegendFrame.h
Closes #7667.
Closes #7711.
Closes #7712.
> More histogram improvements

- ApplicationLibCode/ProjectDataModel/RimContourMapProjection.cpp
- ApplicationLibCode/ProjectDataModel/RimContourMapProjection.h
- ApplicationLibCode/ProjectDataModel/RimEclipseContourMapProjection.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseContourMapProjection.h
> Fix contour map index issues

- ApplicationLibCode/ReservoirDataModel/RigResultAccessorFactory.cpp
> Make input property data time step independent

- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.cpp
> Well Completion: Allocation of User defined D-factor to perforation connection factors 

- ApplicationLibCode/ProjectDataModel/Completions/RimCompletionTemplateCollection.cpp
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/ProjectDataModel/RimProject.cpp
> Stimplan menu fixes for release

- ApplicationLibCode/Commands/RicNewCustomObjectiveFunctionFeature.cpp
- ApplicationLibCode/Commands/RicNewCustomObjectiveFunctionWeightFeature.cpp
- ApplicationLibCode/Commands/SummaryPlotCommands/RicNewEnsembleCurveFilterFeature.cpp
- ApplicationLibCode/ProjectDataModel/RimCustomObjectiveFunction.cpp
- ApplicationLibCode/ProjectDataModel/RimCustomObjectiveFunction.h
- ApplicationLibCode/ProjectDataModel/RimCustomObjectiveFunctionWeight.cpp
- ApplicationLibCode/ProjectDataModel/Summary/CMakeLists_files.cmake
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveFilter.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveFilter.h
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.h
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSetColorManager.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSetColorManager.h
- ApplicationLibCode/ProjectDataModel/Summary/RimObjectiveFunction.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimObjectiveFunction.h
- ApplicationLibCode/ProjectDataModel/Summary/RimObjectiveFunctionTools.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimObjectiveFunctionTools.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.h
- ApplicationLibCode/UserInterface/RiuSummaryVectorSelectionDialog.cpp
- ApplicationLibCode/UserInterface/RiuSummaryVectorSelectionDialog.h
- ApplicationLibCode/UserInterface/RiuSummaryVectorSelectionUi.cpp
- ApplicationLibCode/UserInterface/RiuSummaryVectorSelectionUi.h
- use new formula for objective function
- improve names in UI
- add options for objective function
Closes #7761
> #7761 Objective Function : Change formula and add several options

- ApplicationLibCode/Application/Tools/RiaInterpolationTools.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelPressureCalculator.cpp
- ApplicationLibCode/UnitTests/RiaInterpolationTools-Test.cpp
> 7763 stimplan export bug

- ApplicationLibCode/Application/RiaApplication.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseCase.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseCase.h
- ApplicationLibCode/ProjectDataModel/RimEclipseResultDefinition.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.h
- ResInsightVersion.cmake
> Janitor : Fix missing formation category

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
> Release related fixes

- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatisticsCase.cpp
> Ensemble Statistics : Remove test for match on first reported simulation time step 

- ApplicationLibCode/FileInterface/RifFaultRAJsonWriter.cpp
- ApplicationLibCode/ProjectDataModel/Faults/RimFaultRASettings.cpp
- ApplicationLibCode/ProjectDataModel/Faults/RimFaultRASettings.h
Make sure to always overwrite parameter file.
Adjust digits in loadstep strings to max number of steps.
Always use 0 as first step for adv. processing.
> Fault RA: minor parameter changes

- ApplicationExeCode/RiaMain.cpp
- ApplicationLibCode/Application/RiaConsoleApplication.cpp
- ApplicationLibCode/Application/Tools/RiaArgumentParser.cpp
> Print version from command line 

- ApplicationLibCode/Commands/CellFilterCommands/RicNewRangeFilterSlice3dviewFeature.cpp
- ApplicationLibCode/Commands/CellFilterCommands/RicNewRangeFilterSliceFeature.cpp
- ApplicationLibCode/Commands/ExportCommands/RicAdvancedSnapshotExportFeature.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilter.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilter.h
- ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.h
- ApplicationLibCode/ProjectDataModel/CellFilters/RimCellRangeFilter.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimCellRangeFilter.h
- ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.h
- ApplicationLibCode/ProjectDataModel/CellFilters/RimPropertyFilter.h
- ApplicationLibCode/ProjectDataModel/CellFilters/RimUserDefinedFilter.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimUserDefinedFilter.h
- ApplicationLibCode/ReservoirDataModel/RigCell.cpp
> Improve handling of LGRs in cell filters

- ApplicationLibCode/Commands/GeoMechCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/GeoMechCommands/RicRunAdvFaultReactAssessment3dFeature.cpp
- ApplicationLibCode/Commands/GeoMechCommands/RicRunAdvFaultReactAssessment3dFeature.h
- ApplicationLibCode/Commands/GeoMechCommands/RicRunBasicFaultReactAssessment3dFeature.cpp
- ApplicationLibCode/Commands/GeoMechCommands/RicRunBasicFaultReactAssessment3dFeature.h
- ApplicationLibCode/Commands/GeoMechCommands/RicRunBasicFaultReactAssessmentFeature.cpp
- ApplicationLibCode/Commands/GeoMechCommands/RicRunFaultReactAssessmentFeature.cpp
- ApplicationLibCode/ProjectDataModel/Faults/RimFaultInViewCollection.cpp
- ApplicationLibCode/ProjectDataModel/Faults/RimFaultInViewCollection.h
- ApplicationLibCode/UserInterface/RiuViewerCommands.cpp
> Enable starting FaultRA processing from 3d view

- ApplicationLibCode/ProjectDataModel/RimWellLogFile.cpp
> #7718 Fix unnecessary error dialog for LAS import

- ApplicationLibCode/Commands/RicCreateGridStatisticsPlotFeature.cpp
- ApplicationLibCode/ProjectDataModel/RimGridStatisticsPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimGridStatisticsPlot.h
> 7782 statistics plot use active view result

- ApplicationLibCode/ProjectDataModel/RimWellLogExtractionCurve.cpp
- ApplicationLibCode/ProjectDataModel/RimWellLogExtractionCurve.h
- ApplicationLibCode/ProjectDataModel/RimWellLogPlotCollection.cpp
- ApplicationLibCode/ProjectDataModel/RimWellLogTrack.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelCurve.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelCurve.h
- ApplicationLibCode/ProjectDataModelCommands/CMakeLists_files.cmake
- ApplicationLibCode/ProjectDataModelCommands/RimcWellLogPlot.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcWellLogPlot.h
- ApplicationLibCode/ProjectDataModelCommands/RimcWellLogPlotCollection.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcWellLogPlotCollection.h
- ApplicationLibCode/ProjectDataModelCommands/RimcWellLogTrack.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcWellLogTrack.h
- GrpcInterface/Python/rips/PythonExamples/generate_ensemble_of_well_logs.py
> #7715 Add python interface for creating well log plots

- ApplicationLibCode/Commands/WellPathCommands/RicLinkWellPathFeature.cpp
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/UserInterface/RiuViewerCommands.cpp
> Janitor issues

- ApplicationLibCode/ProjectDataModel/RimEnsembleFractureStatisticsPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimEnsembleFractureStatisticsPlot.h
- ApplicationLibCode/ProjectDataModel/RimGridStatisticsPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimGridStatisticsPlot.h
- ApplicationLibCode/ProjectDataModel/RimStatisticsPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimStatisticsPlot.h
Fixes #7752.
Fixes #7751.
Fixes #7666.
Fixes #7781.
> Statistics plot improvements

- ApplicationLibCode/ProjectDataModel/StimPlanModel/CMakeLists_files.cmake
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimExtractionConfiguration.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimExtractionConfiguration.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelPressureCalculator.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelPressureCalculator.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelTemplate.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelTemplate.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelWellLogCalculator.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelWellLogCalculator.h
> 7871 data source options eqlnum

- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelWellLogCalculator.cpp
> 7872 data source options poro perm

- ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogCurveSet.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogCurveSet.h
- ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogStatistics.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogStatistics.h
- ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogStatisticsCurve.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogFileCurve.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogFileCurve.h
- ApplicationLibCode/ReservoirDataModel/CMakeLists_files.cmake
- ApplicationLibCode/ReservoirDataModel/RigWellLogIndexDepthOffset.cpp
- ApplicationLibCode/ReservoirDataModel/RigWellLogIndexDepthOffset.h
- GrpcInterface/Python/rips/PythonExamples/generate_ensemble_of_well_logs.py
> 7834 well logs depth equalization

- ApplicationLibCode/ProjectDataModel/Surfaces/RimGridCaseSurface.cpp
- ApplicationLibCode/ProjectDataModel/Surfaces/RimGridCaseSurface.h
- ApplicationLibCode/UnitTests/CMakeLists_files.cmake
- ApplicationLibCode/UnitTests/StructGridInterface-Test.cpp
- Fwk/AppFwk/CommonCode/cvfStructGrid.cpp
- Fwk/AppFwk/CommonCode/cvfStructGrid.h
> Add watertight surface

- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
- ApplicationLibCode/ReservoirDataModel/RigFractureGrid.cpp
- ApplicationLibCode/ReservoirDataModel/RigFractureGrid.h
- ApplicationLibCode/ReservoirDataModel/RigStimPlanFractureDefinition.cpp
> #7869 Ensemble Fracture Statistics: optimization by AABB tree.

- ApplicationLibCode/Application/Tools/RiaImportEclipseCaseTools.cpp
- ApplicationLibCode/Application/Tools/RiaImportEclipseCaseTools.h
- ApplicationLibCode/CommandFileInterface/RicfCreateView.cpp
- ApplicationLibCode/CommandFileInterface/RicfLoadCase.cpp
- ApplicationLibCode/Commands/RicImportGridModelFromSummaryCaseFeature.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseCase.cpp
- GrpcInterface/Python/rips/PythonExamples/load_case.py
- GrpcInterface/Python/rips/tests/test_properties.py
- GrpcInterface/Python/rips/tests/test_simulation_wells.py
> Python : Avoid creation of new view when opening case

- GrpcInterface/Python/rips/PythonExamples/export_snapshots.py
> Export Snapshot : Fix failing example

- ApplicationLibCode/Application/RiaSummaryCurveDefinition.cpp
- ApplicationLibCode/Application/RiaSummaryCurveDefinition.h
- ApplicationLibCode/ProjectDataModel/Summary/RimGridSummaryCase.cpp
- ApplicationLibCode/ReservoirDataModel/RigFlowDiagSolverInterface.cpp
- ThirdParty/Ert/lib/ecl/ecl_grid.cpp
> Fix two critical issues

- ApplicationLibCode/ModelVisualization/Riv3dWellLogPlanePartMgr.cpp
- ApplicationLibCode/ModelVisualization/RivContourMapProjectionPartMgr.cpp
- ApplicationLibCode/ModelVisualization/RivElementVectorResultPartMgr.cpp
- ApplicationLibCode/ModelVisualization/RivPipeGeometryGenerator.cpp
- ApplicationLibCode/ModelVisualization/RivReachCircleAnnotationPartMgr.cpp
- ApplicationLibCode/ModelVisualization/RivTensorResultPartMgr.cpp
- ApplicationLibCode/ModelVisualization/RivTextAnnotationPartMgr.cpp
- ApplicationLibCode/ModelVisualization/RivWellConnectionFactorGeometryGenerator.cpp
- ApplicationLibCode/ModelVisualization/RivWellConnectionsPartMgr.cpp
- ApplicationLibCode/ModelVisualization/RivWellPathPartMgr.cpp
- ApplicationLibCode/ModelVisualization/RivWellSpheresPartMgr.cpp
- ApplicationLibCode/ModelVisualization/Streamlines/RivStreamlinesPartMgr.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseResultCase.cpp
> Fix regression test issues

- ApplicationLibCode/Commands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/RicGenerateMultipleSurfacesFeature.cpp
- ApplicationLibCode/Commands/RicGenerateMultipleSurfacesFeature.h
- ApplicationLibCode/Commands/RicGenerateMultipleSurfacesUi.cpp
- ApplicationLibCode/Commands/RicGenerateMultipleSurfacesUi.h
- ApplicationLibCode/Commands/RicImportEnsembleSurfaceFeature.cpp
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/ProjectDataModel/RimDialogData.cpp
- ApplicationLibCode/ProjectDataModel/RimDialogData.h
- ApplicationLibCode/ProjectDataModelCommands/CommandRouter/RimcExtractSurfaces.cpp
- ApplicationLibCode/ProjectDataModelCommands/CommandRouter/RimcExtractSurfaces.h
> #7927 Add user interface for generating ensemble surfaces data.

- ApplicationLibCode/Commands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/RicCreateEnsembleWellLogFeature.cpp
- ApplicationLibCode/Commands/RicCreateEnsembleWellLogFeature.h
- ApplicationLibCode/Commands/RicCreateEnsembleWellLogUi.cpp
- ApplicationLibCode/Commands/RicCreateEnsembleWellLogUi.h
- ApplicationLibCode/Commands/RicImportEnsembleWellLogsFeature.cpp
- ApplicationLibCode/Commands/WellPathCommands/RicImportWellPaths.h
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/ProjectDataModel/RimDialogData.cpp
- ApplicationLibCode/ProjectDataModel/RimDialogData.h
- ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogCurveSet.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogCurveSet.h
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogPlotCollection.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogPlotCollection.h
- ApplicationLibCode/ProjectDataModelCommands/RimcWellLogPlot.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcWellLogPlot.h
- ApplicationLibCode/ProjectDataModelCommands/RimcWellLogPlotCollection.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcWellLogPlotCollection.h
- ApplicationLibCode/ProjectDataModelCommands/RimcWellLogTrack.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcWellLogTrack.h
> #7928 Add user interface for exporting multiple well logs.

- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.cpp
- GrpcInterface/Python/rips/PythonExamples/export_well_path_completions.py
Closes #7973 
Support absolute path of a export filename
Add basic example of well path completion export
> Export Completions : Custom export file name fails in some cases 

- ApplicationLibCode/Commands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/RicCreateEnsembleSurfaceFeature.cpp
- ApplicationLibCode/Commands/RicCreateEnsembleSurfaceFeature.h
- ApplicationLibCode/Commands/RicCreateEnsembleSurfaceUi.cpp
- ApplicationLibCode/Commands/RicCreateEnsembleSurfaceUi.h
- ApplicationLibCode/Commands/RicGenerateMultipleSurfacesUi.cpp
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/ProjectDataModel/RimDialogData.cpp
- ApplicationLibCode/ProjectDataModel/RimDialogData.h
> 7969 create ensemble surface UI tweaks

- ApplicationLibCode/Commands/RicRecursiveFileSearchDialog.cpp
- ApplicationLibCode/Commands/RicRecursiveFileSearchDialog.h
- auto search on launch
- add recently used history to file filter
> Janitor : Improve Ensemble File Search dialog

- ApplicationLibCode/GeoMech/GeoMechVisualization/RivFemPartGeometryGenerator.cpp
- ApplicationLibCode/GeoMech/GeoMechVisualization/RivFemPartGeometryGenerator.h
- ApplicationLibCode/ModelVisualization/RivBoxGeometryGenerator.cpp
- ApplicationLibCode/ModelVisualization/RivBoxGeometryGenerator.h
- ApplicationLibCode/ModelVisualization/RivFaultGeometryGenerator.cpp
- ApplicationLibCode/ModelVisualization/RivFaultGeometryGenerator.h
- ApplicationLibCode/ModelVisualization/RivWellFracturePartMgr.cpp
- Fwk/AppFwk/CommonCode/cvfStructGridGeometryGenerator.cpp
- Fwk/AppFwk/CommonCode/cvfStructGridGeometryGenerator.h
- Fwk/AppFwk/cafVizExtensions/cafBoxManipulatorGeometryGenerator.cpp
- Fwk/AppFwk/cafVizExtensions/cafBoxManipulatorGeometryGenerator.h
Remove duplicated code
Closes #7890
> Use only one implementation of lineIndicesFromQuadVertexArray

- ApplicationLibCode/Commands/CompletionCommands/RicImportEnsembleFractureStatisticsFeature.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
- ApplicationLibCode/ReservoirDataModel/RigEnsembleFractureStatisticsCalculator.cpp
- ApplicationLibCode/ReservoirDataModel/RigEnsembleFractureStatisticsCalculator.h
Also avoid recalculating the statistics for each added file.
Fixes #7963.
> #7963 Ensemble Fracture Statistics: add progress bar.

- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
> #7986 Ensemble Fracture Statistics: block negative number of cells.

- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.h
- ApplicationLibCode/ReservoirDataModel/RigEnsembleFractureStatisticsCalculator.cpp
- ApplicationLibCode/ReservoirDataModel/RigEnsembleFractureStatisticsCalculator.h
> 7962 ensemble fracture stats skip zero width

- ApplicationLibCode/Commands/RicCreateEnsembleWellLogFeature.cpp
> Ensemble Well Log : Close case after well log extraction 

- ApplicationLibCode/Application/Tools/RiaImportEclipseCaseTools.h
- ApplicationLibCode/Commands/EclipseCommands/RicImportEclipseCasesFeature.cpp
- ApplicationLibCode/Commands/RicImportGeneralDataFeature.cpp
> #8009 Missing return values due to default function parameters 

- ApplicationLibCode/Application/Tools/RiaStatisticsTools.cpp
- ApplicationLibCode/Application/Tools/RiaStatisticsTools.h
- ApplicationLibCode/FileInterface/RifReaderEnsembleStatisticsRft.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationPlot.cpp
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimParameterResultCrossPlot.cpp
- ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp
- ApplicationLibCode/ProjectDataModel/Rim3dOverlayInfoConfig.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCaseEvaluator.cpp
- ApplicationLibCode/ProjectDataModel/RimStatisticsPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatistics.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatisticsCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveAutoName.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogStatistics.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.cpp
- ApplicationLibCode/ReservoirDataModel/RigEnsembleFractureStatisticsCalculator.cpp
- ApplicationLibCode/ReservoirDataModel/RigSurfaceStatisticsCalculator.cpp
- ApplicationLibCode/ResultStatisticsCache/RigStatisticsDataCache.cpp
- ApplicationLibCode/ResultStatisticsCache/RigStatisticsMath.cpp
- ApplicationLibCode/ResultStatisticsCache/RigStatisticsMath.h
- ApplicationLibCode/UnitTests/RigStatisticsMath-Test.cpp
- ApplicationLibCode/UnitTests/RigSurfaceStatisticsCalculator-Test.cpp
> #7958 Make P10/P90 calculation style more explicit

- ApplicationLibCode/ProjectDataModelCommands/RimcWellLogPlot.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcWellLogPlotCollection.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcWellLogTrack.cpp
> #7952 Well Log Ensemble: Fix behavior when running in console mode

- ApplicationLibCode/Application/RiaStimPlanModelDefines.cpp
- ApplicationLibCode/FileInterface/RifStimPlanModelGeologicalFrkExporter.cpp
- ApplicationLibCode/FileInterface/RifStimPlanModelGeologicalFrkExporter.h
> #8019 StimPlan model: Apply default poro and perm as minimum values

- ApplicationLibCode/Commands/RicCreateEnsembleWellLogFeature.cpp
- ApplicationLibCode/Commands/RicCreateEnsembleWellLogUi.cpp
- ApplicationLibCode/Commands/RicCreateEnsembleWellLogUi.h
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
> #8006 Ensemble Well Log: Create ensemble from well path in project

- ApplicationLibCode/Application/Tools/RiaEnsembleNameTools.cpp
- ApplicationLibCode/Application/Tools/RiaEnsembleNameTools.h
- ApplicationLibCode/Commands/CompletionCommands/RicImportEnsembleFractureStatisticsFeature.cpp
- ApplicationLibCode/Commands/CompletionCommands/RicImportEnsembleFractureStatisticsFeature.h
- ApplicationLibCode/Commands/RicCreateEnsembleWellLogFeature.cpp
- ApplicationLibCode/Commands/RicImportEnsembleFeature.cpp
- ApplicationLibCode/Commands/RicImportEnsembleFeature.h
- ApplicationLibCode/Commands/RicImportEnsembleSurfaceFeature.cpp
- ApplicationLibCode/Commands/RicImportEnsembleSurfaceFeature.h
- ApplicationLibCode/Commands/RicImportEnsembleWellLogsFeature.cpp
- ApplicationLibCode/Commands/RicImportEnsembleWellLogsFeature.h
- ApplicationLibCode/Commands/RicImportSummaryCasesFeature.cpp
- ApplicationLibCode/Commands/RicImportSummaryCasesFeature.h
- ApplicationLibCode/Commands/RicRecursiveFileSearchDialog.cpp
- ApplicationLibCode/Commands/RicRecursiveFileSearchDialog.h
> #7965 Import ensemble: Add option to group import of multiple ensembles

- ApplicationLibCode/Commands/CompletionCommands/RicImportEnsembleFractureStatisticsFeature.cpp
- ApplicationLibCode/Commands/RicImportEnsembleFeature.cpp
- ApplicationLibCode/Commands/RicImportEnsembleSurfaceFeature.cpp
- ApplicationLibCode/Commands/RicImportEnsembleWellLogsFeature.cpp
- ApplicationLibCode/Commands/RicImportSummaryCasesFeature.cpp
- ApplicationLibCode/Commands/RicRecursiveFileSearchDialog.cpp
- ApplicationLibCode/Commands/RicRecursiveFileSearchDialog.h
> #8031 Ensemble import dialog: rename to 'Group by ensemble'

- ApplicationLibCode/Commands/RicCreateEnsembleWellLogUi.cpp
- GrpcInterface/Python/rips/PythonExamples/generate_ensemble_of_well_logs.py
> #8032 Ensemble Well Logs: change selected property from PERMZ to PERMX

- ApplicationLibCode/ProjectDataModel/Completions/RimEllipseFractureTemplate.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
- ApplicationLibCode/ReservoirDataModel/RigEnsembleFractureStatisticsCalculator.cpp
- ApplicationLibCode/ReservoirDataModel/RigEnsembleFractureStatisticsCalculator.h
- ApplicationLibCode/ReservoirDataModel/RigStimPlanFractureDefinition.cpp
> 8030 ensemble fracture stats report area

- ApplicationLibCode/Application/Tools/RiaColorTables.cpp
- ApplicationLibCode/Application/Tools/RiaColorTables.h
- ApplicationLibCode/Commands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/RicCreateSurfaceIntersectionBandFeature.cpp
- ApplicationLibCode/Commands/RicCreateSurfaceIntersectionBandFeature.h
- ApplicationLibCode/Commands/RicCreateSurfaceIntersectionCurveFeature.cpp
- ApplicationLibCode/Commands/RicCreateSurfaceIntersectionCurveFeature.h
- ApplicationLibCode/Commands/RicImportEnsembleSurfaceFeature.cpp
- ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionGeometryGenerator.cpp
- ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionPartMgr.cpp
- ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionPartMgr.h
- ApplicationLibCode/ProjectDataModel/Annotations/RimAnnotationLineAppearance.cpp
- ApplicationLibCode/ProjectDataModel/Annotations/RimAnnotationLineAppearance.h
- ApplicationLibCode/ProjectDataModel/CMakeLists_files.cmake
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/ProjectDataModel/RimExtrudedCurveIntersection.cpp
- ApplicationLibCode/ProjectDataModel/RimExtrudedCurveIntersection.h
- ApplicationLibCode/ProjectDataModel/RimSurfaceIntersectionBand.cpp
- ApplicationLibCode/ProjectDataModel/RimSurfaceIntersectionBand.h
- ApplicationLibCode/ProjectDataModel/RimSurfaceIntersectionCollection.cpp
- ApplicationLibCode/ProjectDataModel/RimSurfaceIntersectionCollection.h
- ApplicationLibCode/ProjectDataModel/RimSurfaceIntersectionCurve.cpp
- ApplicationLibCode/ProjectDataModel/RimSurfaceIntersectionCurve.h
- ApplicationLibCode/ProjectDataModel/Surfaces/RimEnsembleStatisticsSurface.cpp
- ApplicationLibCode/ProjectDataModel/Surfaces/RimEnsembleStatisticsSurface.h
- ApplicationLibCode/ProjectDataModel/Surfaces/RimEnsembleSurface.cpp
- ApplicationLibCode/ProjectDataModel/Surfaces/RimEnsembleSurface.h
- ApplicationLibCode/ProjectDataModel/Surfaces/RimFileSurface.cpp
- ApplicationLibCode/ProjectDataModel/Surfaces/RimSurfaceCollection.cpp
- ApplicationLibCode/ProjectDataModel/Surfaces/RimSurfaceCollection.h
> Improved UI for surface band and curves

- ApplicationLibCode/Application/RiaApplication.cpp
- ApplicationLibCode/Application/RiaConsoleApplication.cpp
- ApplicationLibCode/Application/RiaGuiApplication.cpp
- ApplicationLibCode/Application/Tools/RiaImportEclipseCaseTools.cpp
- ApplicationLibCode/Application/Tools/RiaImportEclipseCaseTools.h
- ApplicationLibCode/Commands/EclipseCommands/RicImportEclipseCaseFeature.cpp
- ApplicationLibCode/Commands/GeoMechCommands/RicNewFaultReactAssessmentFeature.cpp
- ApplicationLibCode/Commands/RicCreateEnsembleWellLogFeature.cpp
- ApplicationLibCode/Commands/RicImportGeneralDataFeature.cpp
- ApplicationLibCode/Commands/RicImportGeneralDataFeature.h
- ApplicationLibCode/Commands/RicRecursiveFileSearchDialog.cpp
- ApplicationLibCode/Commands/RicRecursiveFileSearchDialog.h
> Allow import of GRDECL cases when creating well log ensembles

- ApplicationLibCode/Commands/RicCreateEnsembleWellLogFeature.cpp
- ApplicationLibCode/Commands/RicCreateEnsembleWellLogUi.cpp
- ApplicationLibCode/Commands/RicCreateEnsembleWellLogUi.h
- ApplicationLibCode/Commands/RicImportGeneralDataFeature.cpp
- ApplicationLibCode/ProjectDataModel/Surfaces/RimSurfaceCollection.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/Rim3dWellLogExtractionCurve.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogStatistics.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.h
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogFileCurve.cpp
> Fix some minor issues

- ApplicationLibCode/Commands/CompletionCommands/RicNewStimPlanModelPlotFeature.cpp
> #8051 StimPlan Model Plot: Use geogrid for Formations.

- GrpcInterface/Python/rips/PythonExamples/save_project.py
> #8035 Python: Add save project example.

- ApplicationLibCode/Application/Tools/RiaImportEclipseCaseTools.cpp
- ApplicationLibCode/Application/Tools/RiaImportEclipseCaseTools.h
- ApplicationLibCode/CommandFileInterface/RicfLoadCase.cpp
- ApplicationLibCode/CommandFileInterface/RicfLoadCase.h
- ApplicationLibCode/Commands/EclipseCommands/RicImportEclipseCaseFeature.cpp
- ApplicationLibCode/Commands/RicCreateEnsembleWellLogFeature.cpp
- ApplicationLibCode/Commands/RicImportGeneralDataFeature.cpp
- ApplicationLibCode/Commands/RicImportGeneralDataFeature.h
- ApplicationLibCode/FileInterface/RifReaderEclipseOutput.cpp
- ApplicationLibCode/FileInterface/RifReaderInterface.cpp
- ApplicationLibCode/FileInterface/RifReaderInterface.h
- ApplicationLibCode/FileInterface/RifReaderSettings.cpp
- ApplicationLibCode/FileInterface/RifReaderSettings.h
- ApplicationLibCode/ProjectDataModel/RimEclipseCase.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseCase.h
- ApplicationLibCode/ProjectDataModel/RimEclipseResultCase.cpp
- ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.cpp
- GrpcInterface/GrpcProtos/Commands.proto
- GrpcInterface/Python/rips/PythonExamples/generate_ensemble_of_well_logs.py
- GrpcInterface/Python/rips/project.py
> 8034 well log extraction optimization

- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionsFileTools.cpp
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionsFileTools.h
- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.cpp
> Export Completion: Add ResInsight project file to file header

- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.h
- ApplicationLibCode/ProjectDataModelCommands/RimcStimPlanModelCollection.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcWellPath.cpp
> 8044 stimplan model extraction boundaries

- ApplicationLibCode/Commands/CompletionCommands/RicNewStimPlanModelPlotFeature.cpp
- ApplicationLibCode/Commands/CompletionCommands/RicNewStimPlanModelPlotFeature.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelCurve.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelPlot.cpp
Fixes #8054.
Fixes #8055.
Fixes #8052.
> Stimplan model plot improvements

- ApplicationLibCode/FileInterface/RifHdf5SummaryExporter.cpp
- ApplicationLibCode/FileInterface/RifOpmHdf5Summary.cpp
- ThirdParty/custom-opm-common/opm-common/src/opm/io/eclipse/ESmry.cpp
> Improve esmry robustness

- ApplicationLibCode/Application/Tools/RiaEnsembleNameTools.cpp
- ApplicationLibCode/Application/Tools/RiaEnsembleNameTools.h
- ApplicationLibCode/Commands/CompletionCommands/RicImportEnsembleFractureStatisticsFeature.cpp
- ApplicationLibCode/Commands/CompletionCommands/RicImportEnsembleFractureStatisticsFeature.h
- ApplicationLibCode/Commands/RicCreateEnsembleSurfaceFeature.cpp
- ApplicationLibCode/Commands/RicCreateEnsembleWellLogFeature.cpp
- ApplicationLibCode/Commands/RicImportEnsembleFeature.cpp
- ApplicationLibCode/Commands/RicImportEnsembleFeature.h
- ApplicationLibCode/Commands/RicImportEnsembleSurfaceFeature.cpp
- ApplicationLibCode/Commands/RicImportEnsembleSurfaceFeature.h
- ApplicationLibCode/Commands/RicImportEnsembleWellLogsFeature.cpp
- ApplicationLibCode/Commands/RicImportEnsembleWellLogsFeature.h
- ApplicationLibCode/Commands/RicImportSummaryCasesFeature.cpp
- ApplicationLibCode/Commands/RicImportSummaryCasesFeature.h
- ApplicationLibCode/Commands/RicRecursiveFileSearchDialog.cpp
- ApplicationLibCode/Commands/RicRecursiveFileSearchDialog.h
> Everest Import: Group into separate ensembles

- ApplicationLibCode/Commands/GeoMechCommands/RicRunWellIntegrityAnalysisFeature.cpp
- ApplicationLibCode/ProjectDataModel/WellPath/RimWellIASettings.cpp
- ApplicationLibCode/ProjectDataModel/WellPath/RimWellIASettings.h
> GeoMech WIA: Additional parameter validation

- ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogCurveSet.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogCurveSet.h
> #8028 Ensemble Well Logs: formation annotation from K-Layer offsets

- ApplicationLibCode/Application/RiaStimPlanModelDefines.cpp
- ApplicationLibCode/Application/RiaStimPlanModelDefines.h
- ApplicationLibCode/FileInterface/RifStimPlanModelGeologicalFrkExporter.cpp
- ApplicationLibCode/FileInterface/RifStimPlanModelGeologicalFrkExporter.h
- ApplicationLibCode/FileInterface/RifStimPlanModelPerfsFrkExporter.cpp
- ApplicationLibCode/FileInterface/RifStimPlanModelPerfsFrkExporter.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelCalculator.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelCalculator.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelElasticPropertyCalculator.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelLayerCalculator.cpp
> #8027 StimPlan Model Export: Add perforation, formation and facies info

- ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp
> Surface Result : Show separate results when Cell Result is None 

- ApplicationLibCode/Application/RiaPreferences.cpp
- ApplicationLibCode/Application/RiaPreferences.h
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogFileCurve.cpp
> LAS file import: Do not use message box for warning 

- ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogCurveSet.cpp
> #8217 Well Log Ensemble: Change curve defaults

- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.h
- ApplicationLibCode/ReservoirDataModel/RigEnsembleFractureStatisticsCalculator.cpp
- ApplicationLibCode/ReservoirDataModel/RigEnsembleFractureStatisticsCalculator.h
> #8182 Fracture Statistics: improve floating point format

- ApplicationLibCode/Application/Tools/CMakeLists_files.cmake
- ApplicationLibCode/Application/Tools/RiaVec3Tools.cpp
- ApplicationLibCode/Application/Tools/RiaVec3Tools.h
- ApplicationLibCode/Commands/WellPathCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/WellPathCommands/RicAppendPointsToPolygonFilterFeature.cpp
- ApplicationLibCode/Commands/WellPathCommands/RicAppendPointsToPolygonFilterFeature.h
- ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.cpp
- ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.cpp
- ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiTableViewEditor.cpp
> Paste and append coord to polygon filter

- ApplicationLibCode/Commands/CompletionCommands/RicNewStimPlanModelPlotFeature.cpp
- ApplicationLibCode/Commands/CompletionCommands/RicNewStimPlanModelPlotFeature.h
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.h
> Set default tick marks to min/max for StimPlan model plots

- ApplicationLibCode/Adm/LicenseInformation.txt
- ApplicationLibCode/Application/Tools/RiaEnsembleNameTools.cpp
- ApplicationLibCode/Commands/RicCreateEnsembleWellLogUi.cpp
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationMatrixPlot.cpp
- Fwk/AppFwk/cafUserInterface/cafProgressInfo.cpp
- Fwk/AppFwk/cafUserInterface/cafProgressInfo.h
- ResInsightVersion.cmake
Closes #7974
Closes #8095
Closes #8117
> Minor fixes

- ApplicationLibCode/ProjectDataModel/WellPath/RimFileWellPath.cpp
> Use correct measured depth for the generated path point at sea level 

- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
> #8244 Ensemble Fracture Statistics: log conductivity per fracture.

- ApplicationLibCode/Commands/GeoMechCommands/RicRunWellIntegrityAnalysisFeature.cpp
- ApplicationLibCode/ProjectDataModel/WellPath/RimWellIASettings.cpp
- ApplicationLibCode/ProjectDataModel/WellPath/RimWellIASettings.h
> GeoMech/WIA: update input parameters and model size settings

- ApplicationLibCode/Application/Tools/RiaEclipseUnitTools.h
- ApplicationLibCode/Commands/CompletionCommands/RicNewStimPlanModelPlotFeature.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.h
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelPressureCalculator.cpp
> 7027 stimplan model plot units

- ApplicationLibCode/Commands/PlotTemplateCommands/RicSummaryPlotTemplateTools.cpp
- ApplicationLibCode/ProjectDataModel/RimPlotCurve.cpp
- ApplicationLibCode/ProjectDataModel/RimPlotCurve.h
>  Update curve appearance for plot templates

- ApplicationLibCode/ProjectDataModel/Parameters/RimGenericParameter.cpp
- ApplicationLibCode/ProjectDataModel/Parameters/RimGenericParameter.h
> Show parameter descriptions as tooltips

- ApplicationLibCode/Commands/WellLogCommands/RicNewWellBoreStabilityPlotFeature.cpp
> Improve error message when well path is not crossing sea level

- ApplicationLibCode/FileInterface/RifParameterXmlReader.cpp
- ApplicationLibCode/ProjectDataModel/Parameters/CMakeLists_files.cmake
- ApplicationLibCode/ProjectDataModel/Parameters/RimParameterGroup.cpp
- ApplicationLibCode/ProjectDataModel/Parameters/RimParameterGroup.h
- ApplicationLibCode/ProjectDataModel/Parameters/RimParameterList.cpp
- ApplicationLibCode/ProjectDataModel/Parameters/RimParameterList.h
Allow editing each element in a list as a separate parameter in the UI
Closes #8263
> WIA: Add better support for list parameters

- ApplicationLibCode/ProjectDataModelCommands/RimcModeledWellPath.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcModeledWellPath.h
- ApplicationLibCode/ProjectDataModelCommands/RimcWellPath.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcWellPath.h
> Python : Move append perforation interval to RimWellPath

- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.h
> 8259 ensemble fracture statistics use mean value

- ApplicationLibCode/CommandFileInterface/RicfImportFormationNames.cpp
> Python : Fix import_formation_names for project

- .gitmodules
Use https://github.com/microsoft/vcpkg
> Update vcpkg to latest release (2021.05.12)

- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimElasticPropertyScalingCollection.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
> StimPlan : Use case insensitive string compare for facies and formations 

- ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.cpp
> Guard null pointer access

- ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotFeatureImpl.cpp
- ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotFeatureImpl.h
- ApplicationLibCode/ProjectDataModel/Parameters/RimParameterGroup.cpp
- ApplicationLibCode/ProjectDataModel/Parameters/RimParameterList.cpp
- ApplicationLibCode/ProjectDataModel/Summary/CMakeLists_files.cmake
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotFilterTextCurveSetEditor.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotFilterTextCurveSetEditor.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotManager.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotManager.h
- ApplicationLibCode/ProjectDataModel/WellPath/RimWellIASettings.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcSummaryPlotCollection.cpp
- ApplicationLibCode/UserInterface/RiuDockWidgetTools.cpp
- ApplicationLibCode/UserInterface/RiuDockWidgetTools.h
- ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp
- ApplicationLibCode/UserInterface/RiuPlotMainWindow.h
- Fwk/AppFwk/cafTests/cafTestApplication/CMakeLists.txt
- Fwk/AppFwk/cafTests/cafTestApplication/LineEditAndPushButtons.cpp
- Fwk/AppFwk/cafTests/cafTestApplication/LineEditAndPushButtons.h
- Fwk/AppFwk/cafTests/cafTestApplication/MainWindow.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiComboBoxEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiComboBoxEditor.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiLineEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiLineEditor.h
> Prototype of dock widget to manage summary plots

- ApplicationLibCode/Commands/ExportCommands/RicExportSelectedWellPathsFeature.cpp
- ApplicationLibCode/Commands/ExportCommands/RicExportSelectedWellPathsFeature.h
- ApplicationLibCode/Commands/RicRecursiveFileSearchDialog.cpp
- ApplicationLibCode/Commands/WellPathCommands/RicPasteModeledWellPathFeature.cpp
- ApplicationLibCode/Commands/WellPathCommands/RicPasteModeledWellPathFeature.h
- ApplicationLibCode/FileInterface/RifStimPlanModelDeviationFrkExporter.cpp
- ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionGeometryGenerator.cpp
- ApplicationLibCode/ReservoirDataModel/RigWellPathGeometryExporter.cpp
- ApplicationLibCode/ReservoirDataModel/RigWellPathGeometryExporter.h
- ApplicationLibCode/UnitTests/RigWellPathGeometryExporter-Test.cpp
Closes #8237 
Closes #8314 
Closes #8294 
Closes #8312
> Maintenance nov 2021

- ApplicationExeCode/RiaMain.cpp
- ApplicationLibCode/Application/RiaGuiApplication.cpp
> commandFile: Crash for scaleFractureTemplate

- ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp
> #8284 Well Log Plot: Avoid depth shift due to long title

- ApplicationLibCode/Application/RiaPreferencesGeoMech.cpp
- ApplicationLibCode/Application/RiaPreferencesGeoMech.h
- ApplicationLibCode/Commands/GeoMechCommands/RicRunWellIntegrityAnalysisFeature.cpp
Allows input file modifications.
Add option in preferences to enable/disable pause.
Closes #8352
> Support pausing before running abaqus script 

- ApplicationLibCode/Commands/RicWellLogTools.cpp
- ApplicationLibCode/Commands/RicWellLogTools.h
- ApplicationLibCode/Commands/WellLogCommands/RicAdd3dWellLogRftCurveFeature.cpp
- ApplicationLibCode/Commands/WellLogCommands/RicNewWellLogRftCurveFeature.cpp
- ApplicationLibCode/FileInterface/RifReaderEclipseRft.cpp
> Create Completion: Crash when creating completion from Project Tree

- ApplicationLibCode/Commands/PlotBuilderCommands/RicSummaryPlotBuilder.cpp
- ApplicationLibCode/Commands/SummaryPlotCommands/RicNewSummaryCurveFeature.cpp
- ApplicationLibCode/Commands/SummaryPlotCommands/RicNewSummaryEnsembleCurveSetFeature.cpp
- ApplicationLibCode/Commands/SummaryPlotCommands/RicPasteSummaryCurveFeature.cpp
- ApplicationLibCode/ProjectDataModel/RimProject.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSetCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
> Plot Project Tree : Avoid collapse of all items in some occasions

- ApplicationLibCode/Application/RiaDefines.cpp
- ApplicationLibCode/Application/RiaGuiApplication.cpp
- ApplicationLibCode/FileInterface/CMakeLists_files.cmake
- ApplicationLibCode/FileInterface/RifMultipleSummaryReaders.cpp
- ApplicationLibCode/FileInterface/RifMultipleSummaryReaders.h
- ApplicationLibCode/FileInterface/RifProjectSummaryDataWriter.cpp
- ApplicationLibCode/FileInterface/RifProjectSummaryDataWriter.h
- ApplicationLibCode/ProjectDataModel/Flow/RimWellPlotTools.cpp
- ApplicationLibCode/ProjectDataModel/RimProject.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimCalculatedSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimCalculatedSummaryCase.h
- ApplicationLibCode/ProjectDataModel/Summary/RimDerivedSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimDerivedSummaryCase.h
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatisticsCase.h
- ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.h
- ApplicationLibCode/ProjectDataModel/Summary/RimGridSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimGridSummaryCase.h
- ApplicationLibCode/ProjectDataModel/Summary/RimObservedSummaryData.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimObservedSummaryData.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCase.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.h
- ApplicationLibCode/ProjectDataModelCommands/RimcSummaryCase.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcSummaryCase.h
- GrpcInterface/Python/rips/PythonExamples/summary_vectors.py
- GrpcInterface/Python/rips/tests/test_summary_cases.py
- ThirdParty/custom-opm-common/opm-common/opm/io/eclipse/EclOutput.hpp
> Summary data from Python

- ApplicationLibCode/ProjectDataModel/RimPlotCurveAppearance.cpp
> #8365 Curve Appearance: correct visibility of options

- ApplicationLibCode/ReservoirDataModel/RigActiveCellInfo.cpp
- ApplicationLibCode/ReservoirDataModel/RigActiveCellInfo.h
- ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.cpp
- ApplicationLibCode/ReservoirDataModel/RigNumberOfFloodedPoreVolumesCalculator.cpp
- ApplicationLibCode/SocketInterface/RiaPropertyDataCommands.cpp
- GrpcInterface/RiaGrpcPropertiesService.cpp
> Stop ResInsight from crashing when calculating cell volume

- ApplicationLibCode/Application/Tools/RiaSummaryStringTools.cpp
- ApplicationLibCode/Application/Tools/RiaSummaryStringTools.h
- ApplicationLibCode/Commands/PlotBuilderCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/PlotBuilderCommands/RicNewSummaryMultiPlotFeature.cpp
- ApplicationLibCode/Commands/PlotBuilderCommands/RicNewSummaryMultiPlotFeature.h
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/ProjectDataModel/RimMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimMultiPlot.h
- ApplicationLibCode/ProjectDataModel/RimMultiPlotCollection.cpp
- ApplicationLibCode/ProjectDataModel/RimMultiPlotCollection.h
- ApplicationLibCode/ProjectDataModel/Summary/CMakeLists_files.cmake
- ApplicationLibCode/ProjectDataModel/Summary/RimMultiSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimMultiSummaryPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotManager.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotManager.h
- ApplicationLibCode/UnitTests/RiaSummaryStringTools-Test.cpp
- ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp
- ApplicationLibCode/UserInterface/RiuSummaryVectorSelectionUi.cpp
- ApplicationLibCode/UserInterface/RiuSummaryVectorSelectionUi.h
Improve robustness related to update of Summary Plot Manager
Add RimSummaryMultiPlot
Move shared code into RiaSummaryStringTools
Added "Create Summary Multi Plot" to menu of MultiPlot in project tree
> Summary Multi plot

- ApplicationLibCode/ModelVisualization/RivElementVectorResultPartMgr.cpp
- ApplicationLibCode/ProjectDataModel/RimElementVectorResult.cpp
- ApplicationLibCode/ProjectDataModel/RimElementVectorResult.h
- ApplicationLibCode/ReservoirDataModel/RigCaseCellResultCalculator.cpp
- ApplicationLibCode/ReservoirDataModel/RigResultModifierFactory.cpp
Closes #8401 
Will also improve performance of flow vector visualization, as results with no data is discarded before the cell result value aggregation.
> Flow Vector Result: Handle empty results for first time step

- ApplicationLibCode/ModelVisualization/RivElementVectorResultPartMgr.cpp
- ApplicationLibCode/ReservoirDataModel/RigNNCData.cpp
> Ensure the NNC connection polygon is created before computing area

- ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionGeometryGenerator.cpp
- ApplicationLibCode/ProjectDataModel/Intersections/CMakeLists_files.cmake
- ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.cpp
- ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.h
- ApplicationLibCode/ProjectDataModel/Intersections/RimIntersection.cpp
- ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionCollection.cpp
- ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionCollection.h
- ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionEnums.cpp
- ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionEnums.h
- Fwk/VizFwk/LibGeometry/cvfBoundingBox.cpp
- Fwk/VizFwk/LibGeometry/cvfBoundingBox.h
> Intersection depthfilter

- ApplicationLibCode/ProjectDataModel/RimVfpTableExtractor.cpp
> VFP Plot : Support import of all units (Field, PVT, ..)

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.h
Data source stepping for multi plot is work in progress, and have disabled stepping for single summary plots. This commit will make it possible to do source stepping on single summary plots.
> Summary Data Source Stepping : Reintroduce stepping for summary plot

- ApplicationLibCode/ProjectDataModel/Faults/RimFaultInViewCollection.cpp
> Update GUI text for faults

- ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionGeometryGenerator.cpp
- ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.cpp
- ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.h
- ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionCollection.cpp
- ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionCollection.h
- ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionEnums.cpp
- ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionEnums.h
> Intersection: depth filter updates

- ApplicationLibCode/ProjectDataModel/RimPlotCurve.cpp
- ApplicationLibCode/ProjectDataModel/RimPlotCurve.h
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
> #8453 Fix crash when changing plot type (QtCharts <-> Qwt).

- ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationPlot.cpp
> Bug fixes related to refactoring of plots

- ApplicationLibCode/Application/Tools/RiaRegressionTest.cpp
- ApplicationLibCode/Application/Tools/RiaRegressionTest.h
- ApplicationLibCode/Application/Tools/RiaRegressionTestRunner.cpp
- ApplicationLibCode/Application/Tools/RiaRegressionTestRunner.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
Add GUI to override plot engine to either Qwt or QtCharts in regression test dialog
> Regression Test : Make it possible to override plot engine

- ApplicationLibCode/Application/RiaGuiApplication.cpp
- ApplicationLibCode/Application/Tools/RiaArgumentParser.cpp
> Plotting : Add command line parameter to open 2D plot main window

- ApplicationLibCode/CMakeLists.txt
- ApplicationLibCode/Commands/CMakeLists.txt
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatisticsCase.cpp
- ApplicationLibCode/ProjectDataModel/WellPath/RimWellPathGroup.cpp
- ApplicationLibCode/UnitTests/RigSlice2D-Test.cpp
- ApplicationLibCode/UserInterface/RiuCadNavigation.cpp
- ApplicationLibCode/UserInterface/RiuGeoQuestNavigation.cpp
- ApplicationLibCode/UserInterface/RiuGridCrossQwtPlot.cpp
- ApplicationLibCode/UserInterface/RiuQwtPlotCurve.cpp
- ApplicationLibCode/UserInterface/RiuRmsNavigation.cpp
- ApplicationLibCode/UserInterface/RiuSummaryQwtPlot.cpp
- CMakeLists.txt
- Fwk/AppFwk/CommonCode/cafMouseState.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafPdmUiCommandSystemProxy.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiFieldEditorHelper.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewEditor.h
- Fwk/AppFwk/cafViewer/cafCadNavigation.cpp
- Fwk/AppFwk/cafViewer/cafCeetronNavigation.cpp
- Fwk/AppFwk/cafViewer/cafCeetronPlusNavigation.cpp
- Fwk/VizFwk/LibGuiQt/cvfqtMouseState.cpp
- GrpcInterface/CMakeLists.txt
- ThirdParty/clipper/CMakeLists.txt
- ThirdParty/custom-opm-common/CMakeLists.txt
- ThirdParty/custom-opm-flowdiag-app/CMakeLists.txt
> CMake : Improve handling of compiler flags

- ApplicationLibCode/Application/RiaEclipseFileNameTools.cpp
- ApplicationLibCode/Application/RiaEclipseFileNameTools.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
- GrpcInterface/Python/rips/tests/test_summary_cases.py
> Summary Import : Support cases with one file per time step

- ApplicationLibCode/Application/RiaDefines.cpp
- ApplicationLibCode/Application/RiaDefines.h
- ApplicationLibCode/Application/RiaGuiApplication.cpp
- ApplicationLibCode/Commands/ToggleCommands/RicMoveItemsToTopFeature.cpp
- ApplicationLibCode/Commands/ToggleCommands/RicToggleItemsFeatureImpl.cpp
- ApplicationLibCode/ProjectDataModel/RimProject.cpp
- ApplicationLibCode/ProjectDataModel/RimProject.h
- ApplicationLibCode/UserInterface/RiuDockWidgetTools.cpp
- ApplicationLibCode/UserInterface/RiuDockWidgetTools.h
- ApplicationLibCode/UserInterface/RiuDragDrop.cpp
- ApplicationLibCode/UserInterface/RiuDragDrop.h
- ApplicationLibCode/UserInterface/RiuMainWindow.cpp
- ApplicationLibCode/UserInterface/RiuMainWindow.h
- ApplicationLibCode/UserInterface/RiuMainWindowBase.cpp
- ApplicationLibCode/UserInterface/RiuMainWindowBase.h
- ApplicationLibCode/UserInterface/RiuMainWindowTools.cpp
- ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp
- ApplicationLibCode/UserInterface/RiuPlotMainWindow.h
- ApplicationLibCode/UserInterface/RiuProjectPropertyView.cpp
- ApplicationLibCode/UserInterface/RiuTreeViewEventFilter.cpp
- ApplicationLibCode/UserInterface/RiuTreeViewEventFilter.h
- ApplicationLibCode/UserInterface/RiuViewerCommands.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeView.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeView.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewEditor.cpp
- ResInsightVersion.cmake
> Project Tree updates

- ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.cpp
> Use cell face when leaving cell when well path starts inside cell

- ApplicationLibCode/Application/RiaGuiApplication.cpp
- ApplicationLibCode/Commands/SsiHubImportCommands/RimWellPathImport.cpp
- ApplicationLibCode/Commands/SsiHubImportCommands/RiuWellImportWizard.cpp
- ApplicationLibCode/Commands/ToggleCommands/RicToggleItemsFeatureImpl.cpp
- ApplicationLibCode/ProjectDataModel/RimViewWindow.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveCollection.cpp
- ApplicationLibCode/ProjectDataModel/WellPath/RimWellPath.cpp
- ApplicationLibCode/UserInterface/RiuMainWindow.cpp
- ApplicationLibCode/UserInterface/RiuMainWindowTools.cpp
- Fwk/AppFwk/cafCommandFeatures/ToggleCommands/cafToggleItemsFeatureImpl.cpp
- Fwk/AppFwk/cafUserInterface/CMakeLists.txt
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeAttributes.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeView.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeView.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewEditor.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewItemDelegate.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewItemDelegate.h
> Add Project Tree filter support

- ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionGeometryGenerator.cpp
- ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionGeometryGenerator.h
- ApplicationLibCode/ModelVisualization/Intersections/RivIntersectionGeometryGeneratorInterface.h
- ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.cpp
- ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionCollection.cpp
- ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionCollection.h
- ApplicationLibCode/ProjectDataModelCommands/CMakeLists_files.cmake
- ApplicationLibCode/ProjectDataModelCommands/RimcDataContainerDouble.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcDataContainerDouble.h
- ApplicationLibCode/ProjectDataModelCommands/RimcElasticProperties.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcIntersection.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcIntersection.h
- ApplicationLibCode/ProjectDataModelCommands/RimcStimPlanModelTemplateCollection.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcSummaryCase.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcSurfaceCollection.cpp
- ApplicationLibCode/UserInterface/RiuTimeStepChangedHandler.cpp
- Fwk/AppFwk/cafPdmScripting/cafPdmPythonGenerator.cpp
- GrpcInterface/Python/rips/PythonExamples/create_intersection.py
- GrpcInterface/Python/rips/pdmobject.py
- GrpcInterface/Python/rips/tests/test_wells.py
- ResInsightVersion.cmake
> Intersection : Add Python support for triangle and result values

- ApplicationLibCode/Application/Tools/RiaWellLogUnitTools.inl
- ApplicationLibCode/ProjectDataModel/RimGridTimeHistoryCurve.cpp
- ApplicationLibCode/UserInterface/RiuQwtPlotCurve.cpp
> Make curve drawing more robust

- ApplicationLibCode/UserInterface/RiuQtChartView.cpp
- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.cpp
> Qtcharts improvements

- ApplicationLibCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlotCurve.cpp
- ApplicationLibCode/ProjectDataModel/RimPlotCurve.cpp
- ApplicationLibCode/ProjectDataModel/RimPlotCurve.h
- ApplicationLibCode/ProjectDataModel/RimVfpPlot.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.cpp
- ApplicationLibCode/ProjectDataModel/WellMeasurement/RimWellMeasurementCurve.cpp
- ApplicationLibCode/UserInterface/RiuFlowCharacteristicsPlot.cpp
- ApplicationLibCode/UserInterface/RiuPlotCurve.cpp
- ApplicationLibCode/UserInterface/RiuPlotCurve.h
- ApplicationLibCode/UserInterface/RiuQwtPlotCurve.cpp
- ApplicationLibCode/UserInterface/RiuQwtPlotCurve.h
Fix invalid creation of isLogCurve in RimWellLogExtractionCurve::onLoadDataAndUpdate
> Improve handling of invalid values for logarithmic curves

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
The axis property position has to be reassigned for all axis types.
Fixes #8536.
> #8536 Summary Plot: Fix axis position for legacy projects.

- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.cpp
- GrpcInterface/Python/rips/tests/test_well_log_extraction.py
> Python fixes

- ApplicationLibCode/UserInterface/RiuQtChartsPlotTools.cpp
- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.cpp
> 8450 qtcharts nicer numbers

- ApplicationLibCode/FileInterface/RifEclipseOutputFileTools.cpp
The date import was wrong for some restart cases.
> #8558 Fix reading of simulation dates for restart case

- ApplicationLibCode/FileInterface/RifEclipseOutputFileTools.cpp
GeoMech cases require this test condition
> 8558 Grid model: Wrong date for RST-data

- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.cpp
> 8549 qtcharts fix time axis

- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurve.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurve.h
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp
- ApplicationLibCode/UserInterface/RiuWellLogPlot.cpp
- ApplicationLibCode/UserInterface/RiuWellLogPlot.h
> Support horizontally stacked curves

- ApplicationLibCode/Commands/RicWellLogTools.cpp
- ApplicationLibCode/Commands/WellLogCommands/RicChangeDataSourceFeature.cpp
- ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseResultCase.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseResultCase.h
- ApplicationLibCode/ProjectDataModel/WellLog/CMakeLists_files.cmake
- ApplicationLibCode/ProjectDataModel/WellLog/Rim3dWellLogRftCurve.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimRftTools.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimRftTools.h
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.h
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.h
> RFT data source adjustments

- ApplicationLibCode/ProjectDataModel/RimEclipseCellColors.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmCore_UnitTests/cafSignalTest.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafSignal.h
>  cafSignal : Improve robustness if a signal is connected twice to the same object

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotAxisFormatter.cpp
> 8523 axis name improvement

- Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafInternalPdmUiFieldCapability.inl
> Temporary workaround for crash seen on RHEL7

- ApplicationLibCode/Commands/RicCreateSummaryCaseCollectionFeature.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h
Allow drag'n'drop of realizations
Improve "Create Summary Case Group" feature to not delete selected realizations from the source collection.
Closes #8612
> SummaryPlots: Allow drag'n'drop of realizations 

- ApplicationExeCode/CMakeLists.txt
- ApplicationLibCode/CMakeLists.txt
- ApplicationLibCode/Commands/CMakeLists.txt
- ApplicationLibCode/Commands/CompletionCommands/RicNewStimPlanModelPlotFeature.cpp
- ApplicationLibCode/Commands/ExportCommands/RicExportToLasFileFeature.cpp
- ApplicationLibCode/Commands/WellLogCommands/RicNewWellBoreStabilityPlotFeature.cpp
- ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.h
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimAbstractCorrelationPlot.h
- ApplicationLibCode/ProjectDataModel/Flow/RimWellDistributionPlot.cpp
- ApplicationLibCode/ProjectDataModel/Flow/RimWellDistributionPlot.h
- ApplicationLibCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlot.cpp
- ApplicationLibCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlot.h
- ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.h
- ApplicationLibCode/ProjectDataModel/RimMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimPlot.h
- ApplicationLibCode/ProjectDataModel/RimVfpPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimVfpPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurve.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.h
- ApplicationLibCode/UserInterface/RiuWellLogPlot.cpp
Tag code with deprecated in RimWellLogTrack
Show deprecation warnings in Visual Studio
> Fix wrong renaming introduced when supporting horizontal tracks

- ApplicationLibCode/UserInterface/CMakeLists_files.cmake
- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.cpp
- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.h
- ApplicationLibCode/UserInterface/RiuQwtDateScaleWrapper.cpp
- ApplicationLibCode/UserInterface/RiuQwtDateScaleWrapper.h
- ApplicationLibCode/UserInterface/RiuSummaryQtChartsPlot.cpp
Use QCatetoryAxis to display date labels
Use Qwt label formatting and scale dividing tools to produce text labels
Closes #8611
> QtChart : Improve time axis grid intervals 

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.cpp
> QtCharts: Update labels when date format changes 

- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.cpp
- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.h
> Fix update issues when switching from axis side

- ApplicationLibCode/ProjectDataModel/RimPlotCurveAppearance.cpp
- ApplicationLibCode/UserInterface/RiuQtChartsPlotCurve.cpp
- ApplicationLibCode/UserInterface/RiuQtChartsPlotCurve.h
- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.cpp
- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.h
> 8452 qtcharts curve fill

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h
> Axis range: If water cut is assigned, use 0..1 as axis value range 

- .github/workflows/AppFwkUnitTest.yml
- .github/workflows/ResInsightWithCache.yml
- .github/workflows/ResInsightWithCacheManualPaths.yml
- .github/workflows/centos7.yml
- .github/workflows/clang-format.yml
- .github/workflows/clang-tidy.yml
- .github/workflows/cmake-format.yml
- .github/workflows/python-linting.yml
- .github/workflows/spell-check.yml
- .gitmodules
- GrpcInterface/Python/rips/retry_policy.py
> Update vcpkg and GitHub Actions

- ApplicationLibCode/ProjectDataModel/RimMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimMultiPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h
- ApplicationLibCode/UserInterface/RiuDragDrop.cpp
- ApplicationLibCode/UserInterface/RiuDragDrop.h
- ApplicationLibCode/UserInterface/RiuMultiPlotBook.cpp
- ApplicationLibCode/UserInterface/RiuMultiPlotBook.h
- ApplicationLibCode/UserInterface/RiuMultiPlotPage.cpp
- ApplicationLibCode/UserInterface/RiuPlotWidget.cpp
Create new plot if dropping address(collection) outside existing plots in plot grid.
Ref. #8620
> Summary Multiplot: drag/drop updates

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlotCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlotCollection.h
> Summary Multiplot: add button to create plot copy

- ApplicationLibCode/Application/RiaDefines.cpp
> #8637 3D-view legend: Make integer category for I-, J- and K-indexes

- ApplicationLibCode/Commands/PlotBuilderCommands/RicSummaryPlotBuilder.cpp
- ApplicationLibCode/Commands/PlotBuilderCommands/RicSummaryPlotBuilder.h
- ApplicationLibCode/ProjectDataModel/RimMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlotCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlotCollection.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryNameHelper.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h
- ApplicationLibCode/UserInterface/CMakeLists_files.cmake
- ApplicationLibCode/UserInterface/RiuMultiPlotBook.cpp
- ApplicationLibCode/UserInterface/RiuMultiPlotPage.cpp
- ApplicationLibCode/UserInterface/RiuMultiPlotPage.h
- ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp
- ApplicationLibCode/UserInterface/RiuPlotMainWindow.h
- ApplicationLibCode/UserInterface/RiuSummaryMultiPlotPage.cpp
- ApplicationLibCode/UserInterface/RiuSummaryMultiPlotPage.h
Ref. #8620 
- Always show selected grid size in multiplot, including empty cells
- Allow drop of summary addresses into empty MDI area to create new plot
> Further Summary Multiplot improvements

- ApplicationLibCode/Application/Tools/RiaImportEclipseCaseTools.cpp
- ApplicationLibCode/Commands/RicConvertGroupToEnsembleFeature.cpp
- ApplicationLibCode/Commands/RicImportEnsembleFeature.cpp
- ApplicationLibCode/Commands/RicImportSummaryCasesFeature.cpp
- ApplicationLibCode/Commands/RicImportSummaryGroupFeature.cpp
- ApplicationLibCode/Commands/SummaryPlotCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/SummaryPlotCommands/RicOpenSummaryPlotEditorFeature.cpp
- ApplicationLibCode/Commands/SummaryPlotCommands/RicOpenSummaryPlotEditorFeature.h
- ApplicationLibCode/Commands/SummaryPlotCommands/RicPasteAsciiDataToSummaryPlotFeature.cpp
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/ProjectDataModel/RimProject.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlotCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotCollection.cpp
- ApplicationLibCode/ProjectDataModelCommands/RimcSummaryPlotCollection.cpp
> SummaryPlot cleanup

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h
> Fix multi summary title and legend updates

- ApplicationLibCode/ProjectDataModel/RimEclipseContourMapView.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseContourMapView.h
- ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp
- ApplicationLibCode/ProjectDataModel/RimGridView.h
> #8623 Contour Map: exclude surfaces from appearing

- ApplicationLibCode/ProjectDataModel/RimPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h
- ApplicationLibCode/UserInterface/RiuMultiPlotPage.cpp
- ApplicationLibCode/UserInterface/RiuQtChartsPlotCurve.cpp
- ApplicationLibCode/UserInterface/RiuQtChartsPlotCurveSymbol.cpp
- ApplicationLibCode/UserInterface/RiuQtChartsPlotCurveSymbol.h
- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.cpp
- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.h
- ApplicationLibCode/UserInterface/RiuQwtPlotLegend.cpp
- ApplicationLibCode/UserInterface/RiuQwtPlotLegend.h
- ApplicationLibCode/UserInterface/RiuQwtPlotTools.cpp
- ApplicationLibCode/UserInterface/RiuQwtPlotTools.h
> Multiplot legend qtcharts

- ApplicationLibCode/Commands/ApplicationCommands/RicHelpFeatures.cpp
- ApplicationLibCode/Commands/ApplicationCommands/RicHelpFeatures.h
- ApplicationLibCode/UserInterface/RiuMainWindow.cpp
- ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp
Include on patch branch
See #8728
>  Help Menu : Add search issues and create new issue 

- ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionGeometryGenerator.cpp
> 8651 surface intersection crash

- ApplicationLibCode/ModelVisualization/RivWellSpheresPartMgr.cpp
> #8362 Simulations wells: Show Spheres gives crash

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
> Summary Multiplot: Show plot curves at the first level below a summary plot.

- ApplicationLibCode/Application/RiaGuiApplication.cpp
- ApplicationLibCode/ProjectDataModel/RimMultiPlot.cpp
- ApplicationLibCode/UserInterface/RiuMultiPlotBook.cpp
- ApplicationLibCode/UserInterface/RiuMultiPlotBook.h
> Summary Multiplot: fix wheel issues

- ApplicationLibCode/Application/RiaDefines.h
- ApplicationLibCode/Application/RiaPlotWindowRedrawScheduler.cpp
- ApplicationLibCode/Application/RiaPlotWindowRedrawScheduler.h
- ApplicationLibCode/Commands/PlotBuilderCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/PlotBuilderCommands/RicNewSummaryPlotFromCurveFeature.cpp
- ApplicationLibCode/Commands/PlotBuilderCommands/RicNewSummaryPlotFromCurveFeature.h
- ApplicationLibCode/Commands/PlotBuilderCommands/RicNewSummaryPlotFromDataVectorFeature.h
- ApplicationLibCode/Commands/PlotBuilderCommands/RicSummaryPlotBuilder.cpp
- ApplicationLibCode/Commands/PlotBuilderCommands/RicSummaryPlotBuilder.h
- ApplicationLibCode/UserInterface/RiuMultiPlotBook.cpp
- ApplicationLibCode/UserInterface/RiuMultiPlotPage.cpp
- ApplicationLibCode/UserInterface/RiuMultiPlotPage.h
- ApplicationLibCode/UserInterface/RiuSummaryPlot.cpp
- ApplicationLibCode/UserInterface/RiuWellLogPlot.cpp
- ApplicationLibCode/UserInterface/RiuWellLogPlot.h
Improves performance, too, by not rebuilding the plot every time a legend changes and fixes curve selection in summary plots inside summary multiplots
> Summary Multiplot: add new plot from a single curve in an ensemble plot

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlotCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlotCollection.h
> Summary Multiplot: Simplify tree in single-plot scenarios

- ApplicationLibCode/Application/RiaSummaryCurveDefinition.cpp
- ApplicationLibCode/Application/RiaSummaryCurveDefinition.h
- ApplicationLibCode/Commands/PlotBuilderCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForObjectsFeature.cpp
- ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForObjectsFeature.h
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
> MultiPlot : Duplicate and append plots for selected objects

- ApplicationLibCode/Commands/PlotTemplateCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/PlotTemplateCommands/RicCreateMultiPlotFromSelectionFeature.cpp
- ApplicationLibCode/Commands/PlotTemplateCommands/RicCreateMultiPlotFromSelectionFeature.h
- ApplicationLibCode/Commands/PlotTemplateCommands/RicSaveMultiPlotTemplateFeature.cpp
- ApplicationLibCode/Commands/PlotTemplateCommands/RicSaveMultiPlotTemplateFeature.h
- ApplicationLibCode/Commands/PlotTemplateCommands/RicSaveMultiPlotTemplateFeatureSettings.cpp
- ApplicationLibCode/Commands/PlotTemplateCommands/RicSaveMultiPlotTemplateFeatureSettings.h
- ApplicationLibCode/Commands/PlotTemplateCommands/RicSummaryPlotTemplateTools.cpp
- ApplicationLibCode/Commands/PlotTemplateCommands/RicSummaryPlotTemplateTools.h
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/ProjectDataModel/RimMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimMultiPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddress.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddress.h
> Multiplot template support

- ApplicationLibCode/Application/RiaPlotWindowRedrawScheduler.cpp
- ApplicationLibCode/Commands/PlotBuilderCommands/RicSummaryPlotBuilder.cpp
- ApplicationLibCode/Commands/WellLogCommands/RicDeleteSubPlotFeature.cpp
- ApplicationLibCode/ProjectDataModel/RimMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimMultiPlot.h
- ApplicationLibCode/ProjectDataModel/RimPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSetCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSetCollection.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveCollection.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlotCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/UserInterface/RiuMultiPlotBook.cpp
- ApplicationLibCode/UserInterface/RiuMultiPlotBook.h
- ApplicationLibCode/UserInterface/RiuMultiPlotPage.cpp
- ApplicationLibCode/UserInterface/RiuSummaryQtChartsPlot.cpp
- ApplicationLibCode/UserInterface/RiuSummaryQtChartsPlot.h
> Summary Multiplot performance improvements

- ApplicationLibCode/ProjectDataModel/RimPlotAxisProperties.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h
> 8768 multiplot axis control

- ApplicationLibCode/Application/Tools/RiaEnsembleNameTools.cpp
- ApplicationLibCode/Application/Tools/RiaEnsembleNameTools.h
- ApplicationLibCode/Commands/PlotTemplateCommands/RicCreateMultiPlotFromSelectionFeature.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCase.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiToolBarEditor.cpp
> Include ensemble cases in source stepping case list

- ApplicationLibCode/ProjectDataModel/RimPlotAxisProperties.cpp
- ApplicationLibCode/ProjectDataModel/RimPlotAxisProperties.h
- ApplicationLibCode/ProjectDataModel/RimPlotAxisPropertiesInterface.cpp
- ApplicationLibCode/ProjectDataModel/RimPlotAxisPropertiesInterface.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.cpp
- ApplicationLibCode/UserInterface/RiuPlotWidget.h
- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.cpp
- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.h
- ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp
- ApplicationLibCode/UserInterface/RiuQwtPlotWidget.h
> Summary Plot: Minor adjustments

- ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForObjectsFeature.cpp
- ApplicationLibCode/Commands/PlotTemplateCommands/RicCreateMultiPlotFromSelectionFeature.cpp
- ApplicationLibCode/Commands/PlotTemplateCommands/RicSummaryPlotTemplateTools.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
> Summary Plot: drag'n'drop data vector issue

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- ApplicationLibCode/UserInterface/RiuSummaryVectorSelectionUi.cpp
> Summary Curve Selection : Always show ensemble realizations cases

- ApplicationExeCode/Resources/themes/default.qss
- ApplicationLibCode/RiuThemesDirectory.h.cmake
> Use transparent instead of gray background

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp
> Regression Test : Fix crash in regression tests

- ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForObjectsFeature.cpp
- ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForObjectsFeature.h
> 8789 Summary Curve : Improve Append to Plot

- ApplicationLibCode/FileInterface/RifReaderFmuRft.cpp
> Import Of Observed FMU Data: Improve parsing of text files

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotControls.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotControls.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiToolBarEditor.cpp
Closes #8785 
Closes #8759  (using a workaround)
> Add simplified data source stepping control in toolbar

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h
- ApplicationLibCode/UserInterface/RiuQwtPlotCurve.cpp
- ApplicationLibCode/UserInterface/RiuSummaryMultiPlotPage.cpp
> Fix crash and minor UI adjustments

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCase.h
> More summary data types in data source tree

- ApplicationLibCode/Commands/PlotBuilderCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryCurvesForObjectsFeature.cpp
- ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryCurvesForObjectsFeature.h
- ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForObjectsFeature.cpp
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.h
> Data Sources : Add append curves to plot based on selection

- ApplicationLibCode/Application/RiaSummaryCurveDefinition.cpp
- ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorUi.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/UserInterface/RiuQwtPlotLegend.cpp
- ApplicationLibCode/UserInterface/RiuSummaryVectorSelectionUi.cpp
- ApplicationLibCode/UserInterface/RiuSummaryVectorSelectionUi.h
> Minor update issues

- ApplicationLibCode/FileInterface/RifSummaryReaderInterface.cpp
> Fix no data issue for Analysis Plot

- ApplicationLibCode/FileInterface/RifEclipseSummaryAddress.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.h
> Add support for all summary data types in data sources tree

- ApplicationLibCode/ProjectDataModel/RimMultiPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp
> Avoid regenerating viewer pages when just stepping curves in plots

- ApplicationLibCode/ProjectDataModel/RimSummaryCalculation.cpp
- ApplicationLibCode/ProjectDataModel/RimSummaryCalculationVariable.cpp
- ApplicationLibCode/ProjectDataModel/RimSummaryCalculationVariable.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddress.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddress.h
- ApplicationLibCode/UserInterface/RiuDragDrop.cpp
- ApplicationLibCode/UserInterface/RiuDragDrop.h
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmObjectHandle.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiTableViewEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTableViewEditor.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiTableViewQModel.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTableViewQModel.h
> Add drop target for calculation variables 

- ApplicationLibCode/Application/CMakeLists_files.cmake
- ApplicationLibCode/Application/RiaApplication.cpp
- ApplicationLibCode/Application/RiaCompletionTypeCalculationScheduler.cpp
- ApplicationLibCode/Application/RiaCompletionTypeCalculationScheduler.h
- ApplicationLibCode/Application/RiaPlotCollectionScheduler.cpp
- ApplicationLibCode/Application/RiaPlotCollectionScheduler.h
- ApplicationLibCode/Application/RiaScheduler.cpp
- ApplicationLibCode/Application/RiaScheduler.h
- ApplicationLibCode/Application/RiaViewRedrawScheduler.cpp
- ApplicationLibCode/Application/Tools/RiaWellNameComparer.cpp
- ApplicationLibCode/Application/Tools/RiaWellNameComparer.h
- ApplicationLibCode/Commands/ToggleCommands/RicToggleItemsFeatureImpl.cpp
- ApplicationLibCode/Commands/ToggleCommands/RicToggleItemsFeatureImpl.h
- ApplicationLibCode/Commands/ToggleCommands/RicToggleItemsOnOthersOffFeature.cpp
- ApplicationLibCode/ProjectDataModel/RimMainPlotCollection.cpp
- ApplicationLibCode/ProjectDataModel/RimMainPlotCollection.h
- ApplicationLibCode/ProjectDataModel/RimProject.cpp
> Performance improvements for toggle operations

- ApplicationLibCode/Commands/EclipseCommands/RicEclipsePropertyFilterInsertExec.cpp
- ApplicationLibCode/Commands/FractureCommands/RicCreateMultipleFracturesUi.cpp
- ApplicationLibCode/Commands/GeoMechCommands/RicGeoMechPropertyFilterInsertExec.cpp
- ApplicationLibCode/ProjectDataModel/Annotations/RimUserDefinedPolylinesAnnotation.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimFishbones.cpp
- ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimPressureTable.cpp
- ApplicationLibCode/ProjectDataModel/Surfaces/RimSurfaceCollection.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp
- ApplicationLibCode/ProjectDataModel/WellMeasurement/RimWellMeasurementCollection.cpp
- ApplicationLibCode/ProjectDataModel/WellPath/RimWellPathAttributeCollection.cpp
- ApplicationLibCode/ProjectDataModel/WellPath/RimWellPathGeometryDef.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmChildArrayField.h
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmChildArrayField.inl
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmFieldReorderCapability.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmFieldReorderCapability.h
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmPtrArrayField.h
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmPtrArrayField.inl
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmPtrArrayFieldHandle.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewItemDelegate.cpp
> Fix reorder capability

- ApplicationLibCode/Commands/PlotTemplateCommands/RicSummaryPlotTemplateTools.cpp
- ApplicationLibCode/ProjectDataModel/RimProject.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
> Improve summary case import performance

- ApplicationLibCode/Application/CMakeLists_files.cmake
- ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryCurvesForSummaryAddressesFeature.cpp
- ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForSummaryAddressesFeature.cpp
- ApplicationLibCode/Commands/PlotTemplateCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/PlotTemplateCommands/RicEditPlotTemplateFeature.cpp
- ApplicationLibCode/Commands/PlotTemplateCommands/RicEditPlotTemplateFeature.h
- ApplicationLibCode/Commands/PlotTemplateCommands/RicRenamePlotTemplateFeature.cpp
- ApplicationLibCode/Commands/PlotTemplateCommands/RicRenamePlotTemplateFeature.h
- ApplicationLibCode/Commands/RicShowGridCalculatorFeature.cpp
- ApplicationLibCode/Commands/RicUserDefinedCalculatorUi.cpp
- ApplicationLibCode/ProjectDataModel/CMakeLists_files.cmake
- ApplicationLibCode/ProjectDataModel/PlotTemplates/RimPlotTemplateFolderItem.cpp
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseCase.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseCase.h
- ApplicationLibCode/ProjectDataModel/RimEclipseResultAddress.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseResultAddress.h
- ApplicationLibCode/ProjectDataModel/RimEclipseResultAddressCollection.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseResultAddressCollection.h
- ApplicationLibCode/ProjectDataModel/RimGridCalculationVariable.cpp
- ApplicationLibCode/ProjectDataModel/RimGridCalculationVariable.h
- ApplicationLibCode/ProjectDataModel/RimProject.cpp
- ApplicationLibCode/ProjectDataModel/RimProject.h
- ApplicationLibCode/UserInterface/RiuDockWidgetTools.cpp
- ApplicationLibCode/UserInterface/RiuDockWidgetTools.h
- ApplicationLibCode/UserInterface/RiuDragDrop.cpp
- ApplicationLibCode/UserInterface/RiuMainWindow.cpp
- ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp
- ApplicationLibCode/UserInterface/RiuPlotMainWindow.h
Add support for renaming and editing templates
Closes #8879
> Show templates as separate project explorer tab.

- ApplicationLibCode/Commands/PlotTemplateCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/PlotTemplateCommands/RicDeletePlotTemplateFeature.cpp
- ApplicationLibCode/Commands/PlotTemplateCommands/RicDeletePlotTemplateFeature.h
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
> Add support for deleting plot templates

- ApplicationLibCode/Commands/RicCloseSummaryCaseFeature.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.h
> Speed up summary case close/delete for ensembles

- ApplicationLibCode/Commands/PlotBuilderCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/PlotBuilderCommands/RicSplitMultiPlotFeature.cpp
- ApplicationLibCode/Commands/PlotBuilderCommands/RicSplitMultiPlotFeature.h
- ApplicationLibCode/Commands/WellLogCommands/RicDeleteSubPlotFeature.cpp
- ApplicationLibCode/Commands/WellLogCommands/RicDeleteSubPlotFeature.h
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.h
- ApplicationLibCode/UserInterface/RiuSummaryPlot.cpp
> Split summary plot into multiple plots

- .github/workflows/ResInsightWithCache.yml
> GitHub Action : Fix macos build issues

- ApplicationLibCode/Commands/RicImportEnsembleFeature.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
> Fix memory leak for data source ensemble summary

- ApplicationLibCode/Application/RiaGuiApplication.cpp
- ApplicationLibCode/Application/RiaGuiApplication.h
- ApplicationLibCode/Commands/ApplicationCommands/RicShowMainWindowFeature.cpp
- ApplicationLibCode/UserInterface/RiuMainWindow.cpp
- ApplicationLibCode/UserInterface/RiuMdiSubWindow.cpp
> #7778 MainWindow: fix crash when reopening grid case

- ApplicationLibCode/Application/Tools/RiaSummaryStringTools.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.h
- ApplicationLibCode/ReservoirDataModel/RigStimPlanModelTools.cpp
> #8877 StimPlan model: Fix formation dip in export of Asymmetric.FRK

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.h
> 8817 summary multiplot visibility filter

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
> Support for appending curves by stepping summary case/ensemble

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
> Move duplicate button to the right of the multiplot toolbar

- ApplicationLibCode/Application/Tools/RiaSummaryAddressAnalyzer.cpp
- ApplicationLibCode/Application/Tools/RiaSummaryAddressAnalyzer.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlotCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotManager.cpp
Create plots for vectors with no grouping identifier
Do not invalidate GUI on selection changed
Use same name as in project tree
> Improve plot manager behavior

- ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp
- ApplicationLibCode/UserInterface/RiuQwtPlotWidget.h
> #8794 Multi Axes: Highlight relevant axes

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
> Fix crash in ensemble plot duplicate

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
> #8787 Summary Multiplot: Fix inversion of axis with axis aggregation.

- ApplicationLibCode/Application/RiaGuiApplication.cpp
- ApplicationLibCode/Commands/PlotTemplateCommands/RicSaveMultiPlotTemplateFeature.cpp
- ApplicationLibCode/Commands/PlotTemplateCommands/RicSaveMultiPlotTemplateFeatureSettings.cpp
- ApplicationLibCode/Commands/PlotTemplateCommands/RicSaveMultiPlotTemplateFeatureSettings.h
- ApplicationLibCode/Commands/SummaryPlotCommands/RicPasteSummaryCurveFeature.cpp
- ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.cpp
- ApplicationLibCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimPlotAxisProperties.cpp
- ApplicationLibCode/ProjectDataModel/RimPlotAxisProperties.h
- ApplicationLibCode/ProjectDataModel/RimPlotAxisPropertiesInterface.h
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotAxisFormatter.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotAxisFormatter.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.h
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp
- ApplicationLibCode/UserInterface/RiuPlotMainWindowTools.cpp
- ApplicationLibCode/UserInterface/RiuPlotMainWindowTools.h
- ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewEditor.cpp
- if auto name for plot title is empty, use title text "Plot N"
- double-click in plot activates Zoom All
- fix issue with missing key event
- select curve in project tree if curve is selected in plot
Closes #8946
Closes #8947
> Several minor issues
