OPM/ResInsight

ApplicationLibCode/Application/RiaPreferences.cpp, ApplicationLibCode/Application/RiaPreferences.h, ApplicationLibCode/Application/RiaPreferencesSummary.cpp, ApplicationLibCode/Application/RiaPreferencesSummary.h, ApplicationLibCode/Commands/PlotBuilderCommands/RicSummaryPlotBuilder.cpp, ApplicationLibCode/Commands/PlotTemplateCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/PlotTemplateCommands/RicReloadPlotTemplatesFeature.cpp, ApplicationLibCode/Commands/PlotTemplateCommands/RicSelectPlotTemplateUi.cpp, ApplicationLibCode/Commands/PlotTemplateCommands/RicSelectPlotTemplateUi.h, ApplicationLibCode/Commands/PlotTemplateCommands/RicSetAsDefaultTemplateFeature.cpp, ApplicationLibCode/Commands/PlotTemplateCommands/RicSetAsDefaultTemplateFeature.h, ApplicationLibCode/Commands/PlotTemplateCommands/RicSummaryPlotTemplateTools.cpp, ApplicationLibCode/Commands/PlotTemplateCommands/RicSummaryPlotTemplateTools.h, ApplicationLibCode/ProjectDataModel/PlotTemplates/RimPlotTemplateFolderItem.cpp, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp, ApplicationLibCode/ProjectDataModel/RimProject.cpp, ApplicationLibCode/ProjectDataModel/RimProject.h
=> Default summaryplot improvements

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
=> Add support for dropping folders in plots

ApplicationLibCode/Commands/PlotBuilderCommands/RicSplitMultiPlotFeature.cpp, ApplicationLibCode/Commands/ToggleCommands/RicToggleItemsFeatureImpl.cpp, ApplicationLibCode/ReservoirDataModel/RigFlowDiagSolverInterface.cpp
Closes #8964
Closes #8399
Closes #8952
=> Minor issues

ApplicationLibCode/ReservoirDataModel/RigResultAccessorFactory.cpp
=> 8892 Allan Diagram: Neighbor cells colored grey for dynamic report steps 

ApplicationLibCode/FileInterface/RifHdf5SummaryReader.cpp
The usual implementation of chrono::system_clock::to_time_t() uses nanoseconds
which will overflow on data with long time spans. Fixed by lowering resolution
to seconds, and adding custom conversion method.
Fixes #8900.
=> #8900 Summary Data: fix error in h5-data for time scale above 250 years

ApplicationLibCode/Commands/RicImportSummaryCasesFeature.cpp
=> Create multiple plots when importing multiple summary cases

ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForObjectsFeature.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForSummaryAddressesFeature.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicSummaryPlotBuilder.cpp, ApplicationLibCode/ProjectDataModel/RimMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/RimMultiPlot.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotManager.cpp
=> Show progress bar when appending plots to multiplot

ApplicationLibCode/UserInterface/RiuDragDrop.cpp
=> Make sure drag'n'drop works when explorer window is undocked, too.

ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.h
=> Well Log Plot: Appearance update not working

ApplicationLibCode/UserInterface/RiuMultiPlotPage.cpp, ApplicationLibCode/UserInterface/RiuMultiPlotPage.h, ApplicationLibCode/UserInterface/RiuQwtPlotLegend.cpp
=> Sub Plot : Legend visibility is unstable

GrpcInterface/RiaGrpcPropertiesService.cpp
=> #8540 Python: read only active cells for active_cell_property

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
=> Fix plot layout after plot visibility filter has been applied

ApplicationLibCode/Commands/CMakeLists_files.cmake, ApplicationLibCode/Commands/RicDeleteSubItemsFeature.cpp, ApplicationLibCode/Commands/RicDeleteSubItemsFeature.h, ApplicationLibCode/Commands/RicDeleteUncheckedSubItemsFeature.cpp, ApplicationLibCode/Commands/RicDeleteUncheckedSubItemsFeature.h, ApplicationLibCode/ProjectDataModel/Completions/RimWellPathFractureCollection.cpp, ApplicationLibCode/ProjectDataModel/Completions/RimWellPathFractureCollection.h, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlotCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlotCollection.h
=> New feature: delete unchecked subitems

ApplicationLibCode/Application/RiaApplication.cpp, ApplicationLibCode/Application/RiaPreferences.cpp, ApplicationLibCode/Application/RiaPreferences.h, ApplicationLibCode/Commands/OctaveScriptCommands/RicDeleteScriptPathFeature.cpp, ApplicationLibCode/Commands/OctaveScriptCommands/RicNewPythonScriptFeature.cpp, ApplicationLibCode/Commands/OctaveScriptCommands/RicRefreshScriptsFeature.cpp, ApplicationLibCode/Commands/PlotTemplateCommands/RicReloadPlotTemplatesFeature.cpp, ApplicationLibCode/ProjectDataModel/RimCalcScript.cpp, ApplicationLibCode/ProjectDataModel/RimProject.cpp, ApplicationLibCode/ProjectDataModel/RimProject.h, ApplicationLibCode/ProjectDataModel/RimScriptCollection.cpp, ApplicationLibCode/ProjectDataModel/RimScriptCollection.h
Clean up context menu a bit.
Closes #8958
=> Add preferences setting for maximum search depth in script folders.

ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionPartMgr.cpp, ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.cpp, ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.h
=> Fix intersection crash 

ApplicationLibCode/Application/Tools/RiaFieldHandleTools.cpp, ApplicationLibCode/Application/Tools/RiaFieldHandleTools.h, ApplicationLibCode/Application/Tools/RiaSummaryAddressAnalyzer.cpp, ApplicationLibCode/ProjectDataModel/Rim3dView.cpp, ApplicationLibCode/ProjectDataModel/RimPlotAxisProperties.cpp, ApplicationLibCode/ProjectDataModel/RimPlotAxisProperties.h, ApplicationLibCode/ProjectDataModel/RimPlotAxisPropertiesInterface.cpp, ApplicationLibCode/ProjectDataModel/RimPlotAxisPropertiesInterface.h, ApplicationLibCode/ProjectDataModel/RimProject.cpp, ApplicationLibCode/ProjectDataModel/RimViewWindow.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveAutoName.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotAxisFormatter.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogFile.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogFileChannel.cpp, Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafPdmUiItem.cpp, Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafPdmUiItem.h
Closes #9011 
Closes #8961 
Closes #9009
=> User experience improvements

ApplicationLibCode/FileInterface/RifEclipseSummaryAddress.cpp, ApplicationLibCode/FileInterface/RifEclipseSummaryAddress.h, ApplicationLibCode/FileInterface/RifEclipseUserDataKeywordTools.cpp, ApplicationLibCode/UnitTests/RiuSummaryVectorDescriptionMap-Test.cpp, ApplicationLibCode/UserInterface/RiuSummaryQuantityNameInfoProvider.cpp, ApplicationLibCode/UserInterface/RiuSummaryQuantityNameInfoProvider.h
=> Improve summary category detection for opm-common reader

ApplicationLibCode/Commands/PlotBuilderCommands/RicSummaryPlotBuilder.cpp, ApplicationLibCode/Commands/PlotTemplateCommands/RicSaveMultiPlotTemplateFeature.cpp, ApplicationLibCode/Commands/PlotTemplateCommands/RicSummaryPlotTemplateTools.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryDataSourceStepping.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryDataSourceStepping.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.h
=> Keep source step dimension when saving/loading multiplots

ApplicationLibCode/Commands/OctaveScriptCommands/RicNewOctaveScriptFeature.cpp, ApplicationLibCode/Commands/OctaveScriptCommands/RicNewPythonScriptFeature.cpp
=> Simplify "New ... script" enable logic.

ApplicationLibCode/FileInterface/RifReaderOpmRft.cpp
=> RFT import: Avoid crash when data is missing

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.h
=> Update multiplot source stepping - append plot

ApplicationLibCode/Commands/GridCrossPlotCommands/RicCreateGridCrossPlotFeature.cpp, ApplicationLibCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlotDataSet.cpp
=> #8991 3D grid cross plot: Select correct grid model.

ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatisticsCase.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatisticsCase.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeEditorHandle.h, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeItemEditor.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeView.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewEditor.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewEditor.h, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewItemDelegate.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewQModel.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewQModel.h
Depending on #9026, require more testing
=> More performance fixes

ApplicationLibCode/Application/RiaApplication.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculation.h, ApplicationLibCode/ProjectDataModel/RimGridCalculationVariable.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculationVariable.h
=> #8955 Grid Property Calculator : Add filtering support.

ApplicationLibCode/Application/Tools/RiaSimWellBranchTools.cpp, ApplicationLibCode/Commands/AnnotationCommands/RicImportPolylinesAnnotationFeature.cpp, ApplicationLibCode/Commands/CompletionCommands/RicNewStimPlanModelPlotFeature.cpp, ApplicationLibCode/Commands/FractureCommands/RicCreateMultipleFracturesFeature.cpp, ApplicationLibCode/Commands/FractureCommands/RicNewSimWellFractureAtPosFeature.cpp, ApplicationLibCode/Commands/FractureCommands/RicNewSimWellFractureFeature.cpp, ApplicationLibCode/Commands/FractureCommands/RicNewStimPlanModelFeature.cpp, ApplicationLibCode/Commands/FractureCommands/RicNewWellPathFractureFeature.cpp, ApplicationLibCode/Commands/RicWellLogTools.cpp, ApplicationLibCode/Commands/ViewLink/RicLinkVisibleViewsFeature.cpp, ApplicationLibCode/Commands/ViewLink/RicSetMasterViewFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicAdd3dWellLogCurveFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicAdd3dWellLogFileCurveFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicAdd3dWellLogRftCurveFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicAddWellLogToPlotFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewWellLogPlotFeatureImpl.cpp, ApplicationLibCode/ProjectDataModel/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/Flow/RimFlowCharacteristicsPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellDistributionPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellDistributionPlotCollection.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCaseTools.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCaseTools.h, ApplicationLibCode/ProjectDataModel/RimEclipseResultAddress.cpp, ApplicationLibCode/ProjectDataModel/RimProject.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogPlotCollection.cpp, ApplicationLibCode/ProjectDataModelCommands/RimcWellLogPlot.cpp, ApplicationLibCode/ProjectDataModelCommands/RimcWellLogTrack.cpp, Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafIconProvider.cpp
Closes #9047
The changes in this PR is based on measurements seen using CPU Diagnostics Tool in VS2022.
=> Performance : Avoid update of project when creating new objects

ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveAppearanceCalculator.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveAppearanceCalculator.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp, ApplicationLibCode/UserInterface/RiuQwtPlotWidget.h
=> Improve visual appearance for ensemble curves

ApplicationLibCode/ReservoirDataModel/RigEclipseNativeStatCalc.cpp, ApplicationLibCode/ReservoirDataModel/RigEclipseNativeStatCalc.h, ApplicationLibCode/ReservoirDataModel/RigEclipseNativeVisibleCellsStatCalc.cpp, ApplicationLibCode/ReservoirDataModel/RigEclipseNativeVisibleCellsStatCalc.h, ApplicationLibCode/ResultStatisticsCache/RigStatisticsCalculator.cpp, ApplicationLibCode/ResultStatisticsCache/RigStatisticsCalculator.h, ApplicationLibCode/ResultStatisticsCache/RigStatisticsDataCache.cpp, ApplicationLibCode/ResultStatisticsCache/RigStatisticsDataCache.h, ApplicationLibCode/ResultStatisticsCache/RigStatisticsMath.h
=> #8989 Grid statistics: Improve precision of p10/p90.

ApplicationLibCode/FileInterface/RifEclipseRftAddress.cpp, ApplicationLibCode/FileInterface/RifEclipseRftAddress.h, ApplicationLibCode/FileInterface/RifReaderEclipseRft.cpp, ApplicationLibCode/FileInterface/RifReaderEnsembleStatisticsRft.cpp, ApplicationLibCode/FileInterface/RifReaderFmuRft.cpp, ApplicationLibCode/FileInterface/RifReaderOpmRft.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellPltPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimRftTools.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurve.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.h
- Fix display of depth values for RFT segment updating Y-axis range
- Well Log Plot: Show RFT segments data source drop down list for time steps 
- Well Log Plot: Add RFT Segment data source as drop down list on menu 
- Add more space around curve data to make the curves fit into default zoom area
Closes #9043
Closes #9044
Closes #9045
=> Improve UI for RFT segment curves

ApplicationLibCode/Application/RiaPlotWindowRedrawScheduler.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForObjectsFeature.cpp, ApplicationLibCode/FileInterface/RifReaderOpmRft.cpp, ApplicationLibCode/ProjectDataModel/RimMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/RimPlot.cpp, ApplicationLibCode/ProjectDataModel/RimPlotCurve.cpp, ApplicationLibCode/ProjectDataModel/RimPlotCurve.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSetCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h, ApplicationLibCode/UserInterface/RiuMultiPlotBook.cpp, ApplicationLibCode/UserInterface/RiuSummaryQwtPlot.cpp
Several performance updates related to display of many plots in many pages in a multiplot
=> Performance updates

ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp, ApplicationLibCode/UserInterface/RiuMainWindow.cpp
=> Add grid calculator button to 3d view toolbar/ case context menu

ApplicationLibCode/Application/RiaGuiApplication.cpp, ApplicationLibCode/Application/RiaPreferencesSummary.cpp, ApplicationLibCode/Application/RiaPreferencesSummary.h, ApplicationLibCode/Application/Tools/RiaColorTables.cpp, ApplicationLibCode/Application/Tools/RiaColorTables.h, ApplicationLibCode/Application/Tools/RiaColorTools.cpp, ApplicationLibCode/Application/Tools/RiaColorTools.h, ApplicationLibCode/Commands/PlotBuilderCommands/RicNewSummaryMultiPlotFromDataVectorFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicNewSummaryEnsembleCurveSetFeature.cpp, ApplicationLibCode/ModelVisualization/RivWellPathPartMgr.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellPlotTools.cpp, ApplicationLibCode/ProjectDataModel/RimPlotCurve.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveAppearanceCalculator.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveAppearanceCalculator.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.cpp, ResInsightVersion.cmake
Closes #9079 
Make sure the well log plot toolbar is updated, related to #9076
=> Minor adjustments

ApplicationLibCode/Commands/PlotBuilderCommands/RicNewSummaryPlotFromCurveFeature.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/UserInterface/RiuPlotCurve.h, ApplicationLibCode/UserInterface/RiuQtChartsPlotCurve.cpp, ApplicationLibCode/UserInterface/RiuQtChartsPlotCurve.h, ApplicationLibCode/UserInterface/RiuQwtPlotCurve.cpp, ApplicationLibCode/UserInterface/RiuQwtPlotCurve.h
=> Missing legend

ApplicationLibCode/ReservoirDataModel/RigCaseCellResultCalculator.cpp
=> Fix crash if base time step has undefined data

ApplicationLibCode/Application/Tools/RiaColorTools.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryCurvesForSummaryCasesFeature.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForObjectsFeature.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForObjectsFeature.h, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForSummaryCasesFeature.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForSummaryCasesFeature.h, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveAppearanceCalculator.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp, Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmField.h
Closes #9125
Partial fix for #9126
=> Minor fixes for ensemble plotting

ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionGeometryGenerator.cpp, ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionPartMgr.cpp, ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.cpp, ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.h
=> Fix intersection depth filter limit calculations

ApplicationLibCode/Commands/SummaryPlotCommands/RicPasteEnsembleCurveSetFeature.cpp
=> Make sure project tree is updated on ensemble curve copy/paste

ApplicationLibCode/Application/RiaGuiApplication.cpp
=> Only create and show plot window if we import a summary file.

ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorUi.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorUi.h
=> Avoid dangling pointer in Plot Editor

ApplicationLibCode/Application/Tools/RiaEclipseUnitTools.cpp, ApplicationLibCode/Application/Tools/RiaEclipseUnitTools.h, ApplicationLibCode/FileInterface/RifThermalFractureReader.cpp, ApplicationLibCode/ProjectDataModel/Completions/RimThermalFractureTemplate.cpp, ApplicationLibCode/ReservoirDataModel/RigThermalFractureDefinition.cpp, ApplicationLibCode/ReservoirDataModel/RigThermalFractureDefinition.h, ApplicationLibCode/ReservoirDataModel/RigThermalFractureResultUtil.cpp
=> #9102 Thermal Fracture: handle field units.

ApplicationLibCode/Commands/ApplicationCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/ApplicationCommands/RicShowPlotDataCtxFeature.cpp, ApplicationLibCode/Commands/ApplicationCommands/RicShowPlotDataCtxFeature.h, ApplicationLibCode/Commands/ApplicationCommands/RicShowPlotDataFeature.cpp, ApplicationLibCode/Commands/ApplicationCommands/RicShowPlotDataFeature.h, ApplicationLibCode/Commands/PlotBuilderCommands/RicSplitMultiPlotFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/SummaryPlotCommands/RicDeleteSubPlotCtxFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicDeleteSubPlotCtxFeature.h, ApplicationLibCode/Commands/SummaryPlotCommands/RicEditSummaryPlotCtxFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicEditSummaryPlotCtxFeature.h, ApplicationLibCode/Commands/SummaryPlotCommands/RicEditSummaryPlotFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicDeleteSubPlotFeature.cpp, ApplicationLibCode/UserInterface/RiuSummaryPlot.cpp
=> Summary context menu cleanup and fixes

ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorUi.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotManager.cpp
=> Fix missing updates of curve names and plot titles

ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechResultDefinition.cpp, ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechResultDefinition.h
=> Do not use undo/redo for GeoMech result definition

ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp, ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp, ApplicationLibCode/UserInterface/RiuMultiPlotPage.cpp, ApplicationLibCode/UserInterface/RiuMultiPlotPage.h, ApplicationLibCode/UserInterface/RiuSummaryMultiPlotPage.cpp, ApplicationLibCode/UserInterface/RiuWellLogPlot.cpp, ApplicationLibCode/UserInterface/RiuWellLogTrack.cpp
Fixes #9117.
Fixes #9092.
Fixes #8539.
=> 9092 wlp tighter horizontal plot

ApplicationLibCode/Application/RiaPlotDefines.cpp, ApplicationLibCode/Application/RiaPlotDefines.h, ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp, ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp, ApplicationLibCode/UserInterface/RiuPlotCurveSymbol.h, ApplicationLibCode/UserInterface/RiuQwtSymbol.cpp, ApplicationLibCode/UserInterface/RiuWellPathComponentPlotItem.cpp, ApplicationLibCode/UserInterface/RiuWellPathComponentPlotItem.h
=> Show well completion annotations in horizontal plots

ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurve.cpp
=> Area Fill : Area filled curves should use zero as base line 

ApplicationLibCode/Commands/AnalysisPlotCommands/RicNewAnalysisPlotFeature.cpp, ApplicationLibCode/Commands/CompletionCommands/RicNewStimPlanModelPlotFeature.cpp, ApplicationLibCode/Commands/CorrelationPlotCommands/RicNewCorrelationMatrixPlotFeature.cpp, ApplicationLibCode/Commands/CorrelationPlotCommands/RicNewCorrelationPlotFeature.cpp, ApplicationLibCode/Commands/CorrelationPlotCommands/RicNewCorrelationReportPlotFeature.cpp, ApplicationLibCode/Commands/CorrelationPlotCommands/RicNewParameterResultCrossPlotFeature.cpp, ApplicationLibCode/Commands/FlowCommands/RicAddStoredFlowCharacteristicsPlotFeature.cpp, ApplicationLibCode/Commands/FlowCommands/RicAddStoredWellAllocationPlotFeature.cpp, ApplicationLibCode/Commands/FlowCommands/RicShowFlowCharacteristicsPlotFeature.cpp, ApplicationLibCode/Commands/FlowCommands/RicShowWellAllocationPlotFeature.cpp, ApplicationLibCode/Commands/GridCrossPlotCommands/RicCreateGridCrossPlotFeature.cpp, ApplicationLibCode/Commands/GridCrossPlotCommands/RicCreateSaturationPressurePlotsFeature.cpp, ApplicationLibCode/Commands/RicCreateEnsembleFractureStatisticsPlotFeature.cpp, ApplicationLibCode/Commands/RicCreateEnsembleWellLogFeature.cpp, ApplicationLibCode/Commands/RicCreateGridStatisticsPlotFeature.cpp, ApplicationLibCode/Commands/RicImportSummaryCasesFeature.cpp, ApplicationLibCode/Commands/RicNewVfpPlotFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicNewSummaryCrossPlotCurveFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicNewSummaryCrossPlotFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicAddWellLogToPlotFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewPltPlotFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewRftPlotFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewWellBoreStabilityPlotFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewWellLogPlotFeature.cpp
=> Make sure toolbar is refreshed when a new plot is added

ApplicationLibCode/Commands/WellPathCommands/RicWellPathPickEventHandler.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogPlot.cpp
=> Link well path selections in 3d view to well log plots

ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp, ApplicationLibCode/ProjectDataModel/RimPlotWindow.cpp, ApplicationLibCode/ProjectDataModel/RimPlotWindow.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/UserInterface/CMakeLists_files.cmake, ApplicationLibCode/UserInterface/RiuMultiPlotPage.cpp, ApplicationLibCode/UserInterface/RiuMultiPlotPage.h, ApplicationLibCode/UserInterface/RiuPlotWidget.cpp, ApplicationLibCode/UserInterface/RiuPlotWidget.h, ApplicationLibCode/UserInterface/RiuQwtLegendOverlayContentFrame.cpp, ApplicationLibCode/UserInterface/RiuQwtLegendOverlayContentFrame.h, ApplicationLibCode/UserInterface/RiuSummaryMultiPlotPage.cpp
=> 9202 wlp internal legends

ApplicationLibCode/ProjectDataModel/RimPlotCurve.cpp
=> Make sure errorbars are shown on project reload

ApplicationLibCode/UserInterface/RiuQwtPlotCurve.cpp
=> Make sure errorbars use the same axis as the data curve

ApplicationLibCode/ProjectDataModel/Streamlines/RimStreamlineInViewCollection.cpp
=> Avoid recalculating streamlines when a 3d calculation is done.

ApplicationLibCode/Application/RiaApplication.cpp
When Octave scripts fails, the application ends up in a deadlock. Add timing to be able to process next regression tests.
=> Regression Test: Add timeout to command object processing

ApplicationLibCode/Application/RiaGuiApplication.cpp, ApplicationLibCode/UserInterface/RiuMainWindow.cpp, ApplicationLibCode/UserInterface/RiuMainWindow.h, ApplicationLibCode/UserInterface/RiuMainWindowBase.cpp, ApplicationLibCode/UserInterface/RiuMainWindowBase.h, ApplicationLibCode/UserInterface/RiuMessagePanel.cpp, ApplicationLibCode/UserInterface/RiuMessagePanel.h, ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp, ApplicationLibCode/UserInterface/RiuPlotMainWindow.h
=> Main window updates

ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp, ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.h
=> Depth Axis : Improve visibility logic

ApplicationLibCode/Commands/RicImportFormationNamesFeature.cpp, ApplicationLibCode/ProjectDataModel/RimContourMapProjection.cpp
=> Contour Map: Fix crash when adding formations after a view is created

ApplicationLibCode/FileInterface/RifEclipseUserDataParserTools.cpp
=> Fix broken observed csv data import

ApplicationLibCode/UserInterface/RiuMultiPlotPage.cpp
=> Make sure font size is updated in legend refresh.

ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorUi.h, ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveCollection.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotCollection.h, ApplicationLibCode/ProjectDataModelCommands/RimcElasticProperties.h, ApplicationLibCode/ProjectDataModelCommands/RimcStimPlanModel.h, ApplicationLibCode/ProjectDataModelCommands/RimcStimPlanModelCollection.h, ApplicationLibCode/ProjectDataModelCommands/RimcStimPlanModelPlotCollection.h, ApplicationLibCode/ProjectDataModelCommands/RimcStimPlanModelTemplateCollection.h, ApplicationLibCode/ProjectDataModelCommands/RimcSurfaceCollection.h, ApplicationLibCode/ProjectDataModelCommands/RimcWellLogPlot.h, ApplicationLibCode/ProjectDataModelCommands/RimcWellLogPlotCollection.h, ApplicationLibCode/ProjectDataModelCommands/RimcWellLogTrack.h, Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmPtrArrayField.h
=> Remove unused members and remove includes

ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationReportPlot.cpp, ApplicationLibCode/UserInterface/RiuMultiPlotPage.cpp, ApplicationLibCode/UserInterface/RiuMultiPlotPage.h
=> 9233 correlation plot regression

ApplicationLibCode/ProjectDataModel/RimCellEdgeColors.cpp
=> #9251 Cell Edge : Add more tests on valid cell edge result

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveCollection.cpp
=> Sync curve ordering in explorer and legend

ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationPlot.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewItemDelegate.cpp
Closes #9250
Closes #9253
Closes #9254
=> Fix some smaller issues

ApplicationLibCode/Commands/WellLogCommands/RicNewWellBoreStabilityPlotFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewWellLogPlotFeatureImpl.cpp, ApplicationLibCode/ProjectDataModel/WellMeasurement/RimWellMeasurementCurve.cpp
=> Guard pointer access and update tree view when plot is created

ApplicationLibCode/ProjectDataModel/RimEclipseCase.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCase.h, ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp
=> Refresh data source tree when a grid calculation is updated

ApplicationLibCode/ReservoirDataModel/RigEclipseWellLogExtractor.cpp, ApplicationLibCode/ReservoirDataModel/RigEclipseWellLogExtractor.h, ApplicationLibCode/ReservoirDataModel/RigGeoMechWellLogExtractor.cpp, ApplicationLibCode/ReservoirDataModel/RigWellLogExtractionTools.h, ApplicationLibCode/ReservoirDataModel/RigWellLogExtractor.cpp, ApplicationLibCode/ReservoirDataModel/RigWellLogExtractor.h
=> Scale length threshold based on average DZ

ApplicationLibCode/Application/Tools/RiaWellNameComparer.cpp, ApplicationLibCode/Application/Tools/RiaWellNameComparer.h, ApplicationLibCode/Commands/WellPathCommands/RicPasteModeledWellPathFeature.cpp, ApplicationLibCode/ProjectDataModel/Completions/RimWellPathCompletionSettings.cpp, ApplicationLibCode/ProjectDataModel/WellPath/RimWellPathGroup.cpp
=> Names for completion export not updated

ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp, ApplicationLibCode/UserInterface/RiuQwtPlotCurve.cpp
The x axis was not assigned properly for the error bars in the plot curve.
Fixes #9280.
=> #9280 Fix missing horizontal error bars.

ApplicationLibCode/ProjectDataModel/RimObservedDataCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
=> Issues related to user course

ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.cpp
=> #9281 Analysis Plot: fix ensemble data source selection.

ApplicationLibCode/Commands/SummaryPlotCommands/RicEditSummaryPlotFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicOpenSummaryPlotEditorFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorDialog.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorDialog.h, ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorUi.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorUi.h, ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorWidgetCreator.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorWidgetCreator.h, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
=> Summary Plot Editor: Context menu update

ApplicationLibCode/Commands/SummaryPlotCommands/RicOpenSummaryPlotEditorFeature.cpp
=> Summary plot editor from context menu whith multiple cases

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.h, ApplicationLibCode/UserInterface/RiuMultiPlotBook.cpp, Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafPdmUiFieldHandle.cpp, Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafPdmUiFieldHandle.h
- Make sure auto plot settings are updated when required
- Use axis object name as key (axis text is not good for this)
=> Adjust auto plot settings

ApplicationExeCode/RiaMain.cpp, ApplicationLibCode/Application/Tools/RiaArgumentParser.cpp, GrpcInterface/Python/rips/instance.py, GrpcInterface/Python/rips/tests/test_launch.py, GrpcInterface/RiaGrpcApplicationInterface.cpp, GrpcInterface/RiaGrpcApplicationInterface.h, GrpcInterface/RiaGrpcServer.cpp
=> #9307 Python: avoid assigning same port number to multiple grpc sessions

.github/workflows/ResInsightWithCache.yml, ApplicationExeCode/RiaMain.cpp, ApplicationLibCode/Application/Tools/RiaArgumentParser.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiLineEditor.cpp, GrpcInterface/Python/rips/instance.py, GrpcInterface/Python/rips/tests/test_launch.py, GrpcInterface/RiaGrpcApplicationInterface.cpp, GrpcInterface/RiaGrpcApplicationInterface.h, GrpcInterface/RiaGrpcServer.cpp, ResInsightVersion.cmake, requirements.txt
- make sure python accesses unique instances
- fix crash for line edit controls
=> Fix two major issues on main branch

ApplicationLibCode/ProjectDataModel/Completions/RimStimPlanFractureTemplate.cpp
=> #9328 StimPlan Fracture: Fix nullptr crash on failed import.

ApplicationLibCode/Application/RiaRftDefines.cpp, ApplicationLibCode/Application/RiaRftDefines.h, ApplicationLibCode/FileInterface/RifReaderOpmRft.cpp, ApplicationLibCode/FileInterface/RifReaderOpmRft.h, ApplicationLibCode/FileInterface/RifRftSegment.cpp, ApplicationLibCode/FileInterface/RifRftSegment.h, ApplicationLibCode/ProjectDataModel/WellLog/RimRftTools.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiLineEditor.cpp
=> Preparations for RFT

ApplicationLibCode/Commands/RicWellLogTools.cpp, ApplicationLibCode/Commands/RicWellLogTools.h, ApplicationLibCode/Commands/WellLogCommands/RicNewRftSegmentWellLogPlotFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewRftSegmentWellLogPlotFeature.h, ApplicationLibCode/Commands/WellLogCommands/RicNewWellLogPlotFeatureImpl.cpp, ApplicationLibCode/FileInterface/RifReaderOpmRft.cpp, ApplicationLibCode/FileInterface/RifReaderOpmRft.h, ApplicationLibCode/FileInterface/RifRftSegment.cpp, ApplicationLibCode/FileInterface/RifRftSegment.h, ApplicationLibCode/ProjectDataModel/RiaOpmParserTools.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.cpp, ApplicationLibCode/ProjectDataModel/WellLog/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/WellLog/RimRftTools.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimRftTools.h, ApplicationLibCode/ProjectDataModel/WellLog/RimRftTopologyCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimRftTopologyCurve.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.h, ThirdParty/custom-opm-common/custom-opm-parser-tests/opm-parser-BasicTest.cpp
- add topology curves
- improve visual appearance of curves
- optionally color curves by phase
Depending on https://github.com/OPM/ResInsight/pull/9342
=> Add topology curves and show in additional track

ApplicationExeCode/CMakeLists.txt, ApplicationLibCode/CMakeLists.txt, ApplicationLibCode/FileInterface/RifJsonEncodeDecode.cpp, ApplicationLibCode/FileInterface/RifJsonEncodeDecode.h, ApplicationLibCode/FileInterface/RifWellPathImporter.cpp, CMakeLists.txt
=> 9172 update json parsing

ApplicationLibCode/ProjectDataModel/Flow/RimWellPltPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp, ApplicationLibCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlot.cpp, ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp, ApplicationLibCode/ProjectDataModel/RimEnsembleFractureStatisticsPlot.cpp, ApplicationLibCode/ProjectDataModel/RimGridStatisticsPlot.cpp, ApplicationLibCode/ProjectDataModel/RimMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/RimPlotCurve.cpp, ApplicationLibCode/ProjectDataModel/RimPlotWindow.cpp, ApplicationLibCode/ProjectDataModel/RimPlotWindow.h, ApplicationLibCode/ProjectDataModel/RimWellBoreStabilityPlot.cpp, ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.h
=> Rft segment plot adjustments

ApplicationLibCode/ProjectDataModelCommands/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModelCommands/RimcFractureTemplate.cpp, ApplicationLibCode/ProjectDataModelCommands/RimcFractureTemplate.h, GrpcInterface/Python/rips/PythonExamples/import_fractures_on_well.py
=> #9386 Fractures: add python api to scale fracture templates

ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp, ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelCurve.cpp, ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelElasticPropertyCalculator.cpp, ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelLayerCalculator.cpp, ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelStressCalculator.cpp, ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelWellLogCalculator.cpp, GrpcInterface/RiaGrpcServiceInterface.cpp
=> 9363 fix incorrect stimplan export

ApplicationLibCode/Application/RiaPlotDefines.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewMultiPhaseRftSegmentPlotFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewRftSegmentWellLogPlotFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewWellLogPlotFeatureImpl.cpp, ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp, ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.h, ApplicationLibCode/ProjectDataModel/RimPlotAxisAnnotation.cpp, ApplicationLibCode/ProjectDataModel/RimPlotAxisAnnotation.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.h, ApplicationLibCode/UserInterface/RiuGridCrossQwtPlot.cpp, ApplicationLibCode/UserInterface/RiuGuiTheme.cpp, ApplicationLibCode/UserInterface/RiuGuiTheme.h, ApplicationLibCode/UserInterface/RiuPlotAnnotationTool.cpp, ApplicationLibCode/UserInterface/RiuPlotAnnotationTool.h, ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp, ApplicationLibCode/UserInterface/RiuQwtPlotWidget.h, ApplicationLibCode/UserInterface/RiuSummaryQwtPlot.cpp, ApplicationLibCode/UserInterface/RiuWellLogPlot.cpp, ApplicationLibCode/UserInterface/RiuWellLogTrack.cpp, ApplicationLibCode/UserInterface/RiuWellLogTrack.h, ApplicationLibCode/UserInterface/RiuWellPathComponentPlotItem.cpp, ApplicationLibCode/UserInterface/RiuWellPathComponentPlotItem.h
=> Depth Track Plots: Optionally show a line in all tracks

ApplicationLibCode/Commands/ViewLink/RicDeleteAllLinkedViewsFeature.cpp, ApplicationLibCode/ProjectDataModel/Rim3dView.cpp, ApplicationLibCode/ProjectDataModel/Rim3dView.h, ApplicationLibCode/ProjectDataModel/RimEclipseContourMapViewCollection.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseContourMapViewCollection.h, ApplicationLibCode/ProjectDataModel/RimViewController.cpp, ApplicationLibCode/ProjectDataModel/RimViewLinker.cpp, ApplicationLibCode/ProjectDataModel/RimViewLinker.h, ApplicationLibCode/ProjectDataModel/RimViewLinkerCollection.cpp, ApplicationLibCode/ProjectDataModel/RimViewWindow.h, ApplicationLibCode/UserInterface/RiuMainWindow.cpp
=> Maintenance october

ApplicationLibCode/Application/Tools/WellPathTools/RiaPolyArcLineSampler.cpp, ApplicationLibCode/ProjectDataModel/WellPath/RimWellPathGeometryDef.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTableViewEditor.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTableViewEditor.h
=> Wells: Assertion failed for editing Well Targes manually

ApplicationLibCode/Commands/SummaryPlotCommands/RicDeleteSubPlotCtxFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicDeleteSubPlotCtxFeature.h, ApplicationLibCode/FileInterface/RifWellPathImporter.h, ApplicationLibCode/ProjectDataModel/WellPath/RimWellPathCollection.cpp
=> Well path import improvements

ApplicationLibCode/ProjectDataModel/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/RimEclipseCellColors.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCellColors.h, ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseView.h, ApplicationLibCode/ProjectDataModel/RimMultipleEclipseResults.cpp, ApplicationLibCode/ProjectDataModel/RimMultipleEclipseResults.h, ApplicationLibCode/UserInterface/RiuResultInfoPanel.cpp, ApplicationLibCode/UserInterface/RiuResultTextBuilder.cpp, ApplicationLibCode/UserInterface/RiuResultTextBuilder.h
=> Result Info: Add support for multiple properties when clicking on a cell 

ThirdParty/Ert/lib/ecl/ecl_smspec.cpp
=> libecl: Fix summary restart absolute path issues

ApplicationLibCode/Commands/RicWellLogTools.cpp, ApplicationLibCode/Commands/RicWellLogTools.h, ApplicationLibCode/Commands/WellLogCommands/RicNewRftSegmentWellLogPlotFeature.cpp, ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.h, ApplicationLibCode/UserInterface/RiuWellLogTrack.cpp
- disable auto color for RFT curves by default
- fix wiggling legends due to multiple plot updates
- fix display of CONFAC by searching more layers, starting at annulus
- move track orientation to depth axis group
Closes #9457
=> Fix RFT segment plot issues

ApplicationLibCode/GeoMech/OdbReader/RifOdbReader.cpp
Support was already there, just a typo away....
Closes #9476
=> Add support for another element type

ApplicationLibCode/ProjectDataModel/Completions/RimEllipseFractureTemplate.cpp
=> #9473 Elliptic Fracture: wrong area for scale fractures

ApplicationLibCode/Application/RiaApplication.cpp, ApplicationLibCode/FileInterface/RifReaderOpmRft.cpp, ApplicationLibCode/FileInterface/RifRftSegment.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculation.h, ApplicationLibCode/ProjectDataModel/RimGridCalculationCollection.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculationCollection.h, ApplicationLibCode/ProjectDataModel/RimReloadCaseTools.cpp, ApplicationLibCode/ProjectDataModel/RimViewController.cpp, ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.cpp
=> Improve property linking

.github/workflows/ResInsightWithCache.yml, .github/workflows/cmake-format.yml, .github/workflows/python-linting.yml, .github/workflows/spell-check.yml
=> #8981 GitHub Actions: Pin VM version used for daily builds

ApplicationLibCode/ModelVisualization/Surfaces/RivSurfacePartMgr.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseContourMapView.cpp, ApplicationLibCode/ProjectDataModel/RimViewController.cpp
=> 9464 contour plot crash on legend levels change

ApplicationLibCode/Commands/CompletionExportCommands/RicExportFractureCompletionsImpl.cpp, ApplicationLibCode/Commands/CompletionExportCommands/RicExportFractureCompletionsImpl.h, ApplicationLibCode/ModelVisualization/RivWellConnectionFactorGeometryGenerator.cpp, ApplicationLibCode/ModelVisualization/RivWellConnectionFactorGeometryGenerator.h, ApplicationLibCode/ProjectDataModel/Completions/RimEllipseFractureTemplate.cpp, ApplicationLibCode/ProjectDataModel/Completions/RimFractureTemplate.cpp, ApplicationLibCode/ProjectDataModel/Completions/RimFractureTemplate.h, ApplicationLibCode/ProjectDataModel/Completions/RimMeshFractureTemplate.cpp, ApplicationLibCode/ReservoirDataModel/Completions/RigWellPathStimplanIntersector.cpp, ApplicationLibCode/ReservoirDataModel/Completions/RigWellPathStimplanIntersector.h, ApplicationLibCode/ReservoirDataModel/RigThermalFractureResultUtil.cpp, ApplicationLibCode/ReservoirDataModel/RigThermalFractureResultUtil.h, ApplicationLibCode/ReservoirDataModel/cvfGeometryTools.cpp, ApplicationLibCode/ReservoirDataModel/cvfGeometryTools.h
=> 9470 user defined perf length for azimuth fractures

ApplicationLibCode/FileInterface/RifReaderEclipseOutput.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculation.h, ApplicationLibCode/ReservoirDataModel/RigActiveCellInfo.cpp, ApplicationLibCode/ReservoirDataModel/RigActiveCellInfo.h
=> 9493 grid calculator on active cells only

ApplicationLibCode/Commands/ExportCommands/RicExportToLasFileResampleUi.cpp, ApplicationLibCode/Commands/RicWellMeasurementImportTools.cpp
Closes #9489 
Fixes parts of #9383
=> Geo Mech related fixes

ApplicationLibCode/ProjectDataModel/Completions/RimFractureTemplate.cpp, GrpcInterface/Python/rips/PythonExamples/import_fractures_on_well.py
Also use it in example script.
=> #9470 Fracture Template: make perforation length scriptable.

ApplicationLibCode/Commands/ExportCommands/RicExportEclipseSectorModelFeature.cpp, ApplicationLibCode/Commands/ExportCommands/RicExportEclipseSectorModelUi.cpp, ApplicationLibCode/Commands/ExportCommands/RicExportEclipseSectorModelUi.h, ApplicationLibCode/FileInterface/RifEclipseInputFileTools.cpp, ThirdParty/Ert/lib/util/util.c
=> Export Sector Model: Add file path

ApplicationLibCode/Application/RiaApplication.cpp
=> #7839 Python: fix crash when stopping process

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h, ApplicationLibCode/UserInterface/RiuPlotWidget.h, ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.h, ApplicationLibCode/UserInterface/RiuQwtPlotWidget.h
=> 9437 fix missing summary sub plot update

ApplicationLibCode/UserInterface/RiuMultiPlotPage.cpp
=> #9438 Multiplot: Avoid overwriting font sizes.

ApplicationLibCode/UserInterface/RiuMainWindowBase.cpp
=> Update to latest docking release

ApplicationLibCode/Commands/ApplicationCommands/RicTileWindowsFeature.cpp, ApplicationLibCode/FileInterface/RifReaderOpmRft.cpp, ApplicationLibCode/FileInterface/RifReaderOpmRft.h, ApplicationLibCode/ProjectDataModel/Rim3dView.cpp, ApplicationLibCode/UserInterface/RiuMdiArea.cpp
Fix crash related to opening of RFT files
Fix crash for tiling related functions
=> Fix two crashes

ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.cpp, ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.cpp
=> Make sure indexIJK values are computed only once

ApplicationLibCode/FileInterface/RifReaderOpmRft.cpp, ApplicationLibCode/FileInterface/RifReaderOpmRft.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.cpp, ResInsightVersion.cmake
=> RFT plot: Fix stepping on well

ApplicationLibCode/UserInterface/RiuMultiPlotPage.cpp
=> Add "Add plot" to empty multiplot area context menu

ApplicationLibCode/GeoMech/GeoMechDataModel/CMakeLists.txt, ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorKIndices.cpp, ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorKIndices.h, ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.cpp
Add well depth adjustments by use of reference well for WellLogExtractionCurve for geomech case.
---
Closes: #9517
=> Add reference well depth adjustment to geomech case

ApplicationLibCode/Commands/GeoMechCommands/RicNewWellIntegrityAnalysisFeature.cpp
=> Update Well int. analysis menu text

ApplicationLibCode/Commands/RicWellLogTools.cpp, GrpcInterface/RiaGrpcServer.cpp
=> Reorganize how and when objects are deleted when shutting down GRPC

ApplicationLibCode/Commands/CompletionExportCommands/RicExportCompletionsForVisibleWellPathsFeature.cpp, ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.cpp
Closes https://github.com/OPM/ResInsight/issues/9461
=> 9461 MSW: Wrong length and depth for lateral with ICV

ApplicationLibCode/Commands/WellLogCommands/RicNewRftSegmentWellLogPlotFeature.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseContourMapProjection.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseContourMapProjection.h, ApplicationLibCode/ProjectDataModel/RimEclipseResultDefinition.cpp, ApplicationLibCode/ProjectDataModel/RimReloadCaseTools.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimRftTopologyCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp
=> Release related issues

ThirdParty/Ert/lib/ecl/ecl_util.cpp
Closes https://github.com/OPM/ResInsight/issues/9529
=> Import of grid models: Support mix of lower and upper case letters in file name

ApplicationLibCode/Application/RiaConsoleApplication.cpp, ApplicationLibCode/Application/RiaGuiApplication.cpp, ApplicationLibCode/Application/Tools/RiaLogging.cpp, ApplicationLibCode/Application/Tools/RiaLogging.h, ApplicationLibCode/ProjectDataModel/RimEclipseCase.cpp, ApplicationLibCode/ReservoirDataModel/RigMainGrid.cpp, ApplicationLibCode/ReservoirDataModel/RigMainGrid.h, ApplicationLibCode/ReservoirDataModel/RigSimulationWellCenterLineCalculator.cpp, Fwk/VizFwk/LibGeometry/cvfBoundingBoxTree.cpp, Fwk/VizFwk/LibGeometry/cvfBoundingBoxTree.h, GrpcInterface/RiaGrpcCallbacks.h
Closes #9588
Add support for aggregation of bounding boxes along K-direction. Compute how many cells to aggregate based on a maximum value of leaf nodes, by default set to 4 000 000.
Change logging: Display debug logging text only if `RiaApplication::enableDevelopmentFeatures()` is set.
=> Accumulate N cells for AABB tree

ApplicationLibCode/ReservoirDataModel/RigMainGrid.cpp
The use of OpenMP is not stable, and produce wrong geometry in some cases.
=> Revert OpenMP for detection of faults

ApplicationLibCode/Application/Tools/CMakeLists_files.cmake, ApplicationLibCode/Application/Tools/RiaNumericalTools.cpp, ApplicationLibCode/Application/Tools/RiaNumericalTools.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationPlot.cpp, ApplicationLibCode/ProjectDataModel/RimPlotAxisLogRangeCalculator.cpp, ApplicationLibCode/ProjectDataModel/RimRegularLegendConfig.cpp, ApplicationLibCode/ProjectDataModel/RimRegularLegendConfig.h, ApplicationLibCode/ProjectDataModel/RimTernaryLegendConfig.cpp, ApplicationLibCode/ProjectDataModel/RimTernaryLegendConfig.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.h, ApplicationLibCode/UnitTests/RifColorLegendData-Test.cpp, ResInsightVersion.cmake
Closes #9606
Closes #9602
Closes #9604
=> Fix summary issues

ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechView.cpp
=> Fix crash when reloading geomech case after altering time step filter

ApplicationLibCode/FileInterface/RifCsvUserDataParser.cpp, ApplicationLibCode/UnitTests/ObservedDataParser-Test.cpp
=> Support up to three header lines for CSV import 

ApplicationLibCode/Application/Tools/RiaFilePathTools.cpp, ApplicationLibCode/Application/Tools/RiaFilePathTools.h, ApplicationLibCode/FileInterface/RifHdf5SummaryExporter.cpp, ApplicationLibCode/FileInterface/RifHdf5SummaryExporter.h, ApplicationLibCode/FileInterface/RifOpmCommonSummary.cpp, ApplicationLibCode/FileInterface/RifOpmCommonSummary.h
=> Check last write time for ESMRY files and SMSPEC files 

ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveFilter.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.h
=> Ensemble Parameter: Add alphabetical and by correlation value sorting

ApplicationLibCode/Commands/SsiHubImportCommands/RimWellPathImport.cpp, ApplicationLibCode/Commands/SsiHubImportCommands/RimWellPathImport.h, ApplicationLibCode/Commands/SsiHubImportCommands/RiuWellImportWizard.cpp, ApplicationLibCode/FileInterface/RifJsonEncodeDecode.cpp, ApplicationLibCode/FileInterface/RifJsonEncodeDecode.h
Closes https://github.com/OPM/ResInsight/issues/9630
=> Fix import of data from SSIHUB

ApplicationLibCode/FileInterface/RifRoffFileTools.cpp
=> #9616 Roff: fix incorrect cell mapping leading to incorrect faults.

ApplicationLibCode/ReservoirDataModel/RigMainGrid.cpp, Fwk/AppFwk/CommonCode/cvfStructGrid.cpp
Closes https://github.com/OPM/ResInsight/issues/9622
=> Improve detection of cell face direction

.github/workflows/AppFwkUnitTest.yml, .github/workflows/ResInsightWithCache.yml, .github/workflows/clang-tidy.yml
Make sure to call `apt-get update` before `apt-get install`
https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners
=> Fix build issues with Github Action

CMakeLists.txt
Avoid calling submodule update on specific subfolders.
=> Maintenance: Issue submodule update once

ApplicationLibCode/FileInterface/RifOpmCommonSummary.cpp
=> Fix invalid dates for data imported from ESMRY

ApplicationLibCode/Commands/ApplicationCommands/RicShowPlotDataFeature.cpp, ApplicationLibCode/Commands/FlowCommands/RicShowWellAllocationPlotFeature.cpp, ApplicationLibCode/ProjectDataModel/Flow/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/Flow/RimFlowPlotCollection.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimFlowPlotCollection.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationOverTimeCollection.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationOverTimeCollection.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationOverTimePlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationOverTimePlot.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationPlot.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationTools.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationTools.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellPlotTools.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellPlotTools.h, ApplicationLibCode/ReservoirDataModel/RigAccWellFlowCalculator.cpp, Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmObjectHandle.h
Closes: #9491 
---
Note: Not implemented multithreading to speed up computations yet
=> Well allocation over time plot

ApplicationLibCode/UserInterface/RiuMainWindow.cpp, ApplicationLibCode/UserInterface/RiuMainWindow.h, ApplicationLibCode/UserInterface/RiuMainWindowBase.cpp, Fwk/AppFwk/cafAnimControl/cafAnimationToolBar.cpp, Fwk/AppFwk/cafAnimControl/cafAnimationToolBar.h
=> Add time step slider to 3d views

ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorNormalST.cpp
=> Fix missing integration point and element nodal result

ApplicationLibCode/ProjectDataModel/CellFilters/RimCellRangeFilter.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellRangeFilter.h, Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafQShortenedLabel.cpp
=> Improve range filter slider gui

ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp, ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechCase.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.cpp
Fix crash when loading an existing WBS plot
Move plot update out of `RigFemPartResultsCollection`
=> Fix issues related to well bore stability plot

.misspell-fixer.ignore, ApplicationLibCode/Application/CMakeLists_files.cmake, ApplicationLibCode/Application/RiaLasDefines.cpp, ApplicationLibCode/Application/RiaLasDefines.h, ApplicationLibCode/Commands/ExportCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/ExportCommands/RicCreateDepthAdjustedLasFilesFeature.cpp, ApplicationLibCode/Commands/ExportCommands/RicCreateDepthAdjustedLasFilesFeature.h, ApplicationLibCode/Commands/ExportCommands/RicCreateDepthAdjustedLasFilesImpl.cpp, ApplicationLibCode/Commands/ExportCommands/RicCreateDepthAdjustedLasFilesImpl.h, ApplicationLibCode/Commands/ExportCommands/RicCreateDepthAdjustedLasFilesUi.cpp, ApplicationLibCode/Commands/ExportCommands/RicCreateDepthAdjustedLasFilesUi.h, ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorKIndices.cpp, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp, ApplicationLibCode/ReservoirDataModel/RigWellLogFile.cpp, ApplicationLibCode/ReservoirDataModel/RigWellLogFile.h
Create depth adjusted LAS files for a set of wells, using LAS file for a "Source well"
Closes: #9619
=> Create depth adjusted LAS files

ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp, ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.h, ApplicationLibCode/ProjectDataModel/RimWellBoreStabilityPlot.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurve.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.h
=> Move Reference Well funcitonality to WellLogExtractionCurve

ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotFeatureImpl.cpp, ApplicationLibCode/FileInterface/RifEclipseSummaryAddress.cpp, ApplicationLibCode/UnitTests/ObservedDataParser-Test.cpp, ApplicationLibCode/UnitTests/RiaSummaryAddressAnalyzer-Test.cpp, GrpcInterface/Python/rips/tests/test_summary_cases.py
=> Trim spaces and avoid spaces in generated address text

ApplicationExeCode/CMakeLists.txt
=> Windows Installer: Make sure qoffscreen.dll is included

ApplicationLibCode/GeoMech/GeoMechVisualization/RivGeoMechVizLogic.cpp, ApplicationLibCode/GeoMech/GeoMechVisualization/RivGeoMechVizLogic.h, ApplicationLibCode/ModelVisualization/RivTensorResultPartMgr.cpp, ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechCase.cpp, ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechPartCollection.cpp, ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechPartCollection.h, ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechView.cpp, ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechView.h
=> Fix geomech reload issues

ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorSurfaceAngles.cpp
=> Fix missing Pazi/Pinc

ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationOverTimeCollection.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationOverTimeCollection.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationOverTimePlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationOverTimePlot.h, ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp
Adjustments on well allocation over time based feedback
Closes: #9712
=> Well Allocation over time adjustements

ApplicationLibCode/ModelVisualization/RivTensorResultPartMgr.cpp
=> Fix broken test

ApplicationLibCode/Application/Tools/RiaSummaryTools.cpp, ApplicationLibCode/Application/Tools/RiaSummaryTools.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellPlotTools.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp, ApplicationLibCode/ProjectDataModel/RimPressureDepthData.cpp, ApplicationLibCode/ProjectDataModel/RimPressureDepthData.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogFileCurve.cpp
=> RFT improvements

ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
=> Remove FAULTMOB result fra ST

ApplicationLibCode/FileInterface/RifDataSourceForRftPlt.cpp, ApplicationLibCode/FileInterface/RifDataSourceForRftPlt.h, ApplicationLibCode/ProjectDataModel/Flow/RimDataSourceForRftPlt.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimDataSourceForRftPlt.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellPlotTools.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellPltPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellPltPlot.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.h
Move AppEnum init to RifDataSourceForRftPlt
Simplify constructors for RifDataSourceForRftPlt
Rename enum names in RifDataSourceForRftPlt::SourceType
Add missing pressureDepthData in RimDataSourceForRftPlt
=> Improve RftPlt data source objects

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp, Fwk/AppFwk/cafUserInterface/cafProgressInfo.cpp
=> Avoid progress window staying behind on Linux when loading summary data

ApplicationLibCode/ProjectDataModel/Flow/RimWellPlotTools.cpp, ApplicationLibCode/ReservoirDataModel/RigSimulationWellCenterLineCalculator.cpp
=> #9771: Guard nullpointer access 

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
=> Compare axis unit text case insensitive

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotNameHelper.cpp
Closes https://github.com/OPM/ResInsight/issues/9147
=> Group identifier is missing from curve name

GrpcInterface/Python/rips/PythonExamples/case_grid_group.py, GrpcInterface/Python/rips/gridcasegroup.py
=> Add missing import of EclipseView

ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationOverTimePlot.cpp
=> Use point to point on Accumulated Flow Volume Percentage

ApplicationLibCode/UserInterface/RiuPlotWidget.cpp, ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp, ApplicationLibCode/UserInterface/RiuQwtPlotWidget.h
=> Fix active cell not resetting when clicking on cells

.github/workflows/AppFwkUnitTest.yml, .github/workflows/ResInsightWithCache.yml, .github/workflows/clang-format.yml, .github/workflows/clang-tidy.yml
=> GHA: Add retry for apt commands

.github/workflows/AppFwkUnitTest.yml, .github/workflows/ResInsightWithCache.yml, .github/workflows/clang-format.yml, ApplicationLibCode/Application/RiaThermalFractureDefines.h, ApplicationLibCode/Commands/CompletionExportCommands/RicMswSegmentCellIntersection.h, ApplicationLibCode/Commands/ExportCommands/RicExportLgrFeature.h, ApplicationLibCode/FileInterface/RifSurfaceImporter.h, ApplicationLibCode/ProjectDataModel/Annotations/RimReachCircleAnnotation.h, ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionResultsDefinitionCollection.h, ApplicationLibCode/ReservoirDataModel/RigFlowDiagInterfaceTools.h, ApplicationLibCode/UserInterface/AnalysisPlots/RiuGroupedBarChartBuilder.h
- Add mirrors for `apt-get` package servers
- Improve `clang-format-10` usage
- Include source code fixes for updated clang-format usage
=> Add apt mirror

ApplicationLibCode/Commands/WellLogCommands/RicNewWellMeasurementCurveFeature.cpp, ApplicationLibCode/Commands/WellPathCommands/RicImportWellMeasurementsFeature.cpp, ApplicationLibCode/ModelVisualization/RivWellPathPartMgr.cpp, ApplicationLibCode/ProjectDataModel/WellMeasurement/RimWellMeasurementInViewCollection.cpp, ApplicationLibCode/ProjectDataModel/WellMeasurement/RimWellMeasurementInViewCollection.h
Update well measurement folder in 3D view when well measurements are loaded.
Load data for well measurement curve when new curve is created.
Closes #8625
=> Well measurement improvements

ApplicationLibCode/FileInterface/RifReaderEclipseOutput.cpp
=> Fix freeze when loading eclipse grid

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryDataSourceStepping.cpp
=> Rearrange order of source stepping options

ApplicationLibCode/Commands/PlotBuilderCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/PlotBuilderCommands/RicNewEmptySummaryMultiPlotFeature.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicNewEmptySummaryMultiPlotFeature.h, ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp
=> Create a new, empty summaryplot from empty MDI area

ApplicationLibCode/Commands/ExportCommands/RicCreateDepthAdjustedLasFilesFeature.cpp, ApplicationLibCode/Commands/ExportCommands/RicCreateDepthAdjustedLasFilesImpl.cpp, ApplicationLibCode/Commands/ExportCommands/RicCreateDepthAdjustedLasFilesUi.cpp, ApplicationLibCode/Commands/ExportCommands/RicCreateDepthAdjustedLasFilesUi.h
=> Adjustment of creating depth adjusted LAS files

ApplicationLibCode/Commands/SummaryPlotCommands/RicNewSummaryCurveFeature.cpp, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
=> New summary plot curve improvements

ApplicationLibCode/FileInterface/CMakeLists_files.cmake, ApplicationLibCode/FileInterface/RifOpmGridTools.cpp, ApplicationLibCode/FileInterface/RifOpmGridTools.h, ApplicationLibCode/FileInterface/RifReaderEclipseOutput.cpp, ApplicationLibCode/FileInterface/RifReaderEclipseOutput.h, ApplicationLibCode/ProjectDataModel/RimMultipleEclipseResults.cpp, ApplicationLibCode/ProjectDataModel/RimMultipleEclipseResults.h, ApplicationLibCode/UnitTests/opm-summary-Test.cpp, ApplicationLibCode/UserInterface/RiuResultTextBuilder.cpp, ApplicationLibCode/UserInterface/RiuResultTextBuilder.h
Closes #9688
Closes #9610 
Closes #7007
=> Add support for radial grids

ApplicationLibCode/CommandFileInterface/RicfExportWellPathCompletions.cpp, ApplicationLibCode/CommandFileInterface/RicfExportWellPathCompletions.h, ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.cpp, ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionsFileTools.cpp, ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionsFileTools.h, ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.cpp
=> Export Completion: Make sure export folder is used correctly

ThirdParty/Ert/lib/ecl/ecl_nnc_data.cpp
=> Case crashes on grid load

ApplicationLibCode/ProjectDataModel/RimEclipseCase.cpp, ApplicationLibCode/ReservoirDataModel/RigMainGrid.cpp, ApplicationLibCode/ReservoirDataModel/RigMainGrid.h, Fwk/AppFwk/CommonCode/cvfStructGrid.cpp, Fwk/AppFwk/CommonCode/cvfStructGrid.h
=> Export Completion: Fix missing segments and connections for LGR grids

ApplicationLibCode/FileInterface/RifEclipseInputFileTools.cpp, ApplicationLibCode/FileInterface/RifEclipseInputPropertyLoader.cpp, ApplicationLibCode/FileInterface/RifEclipseInputPropertyLoader.h, ApplicationLibCode/FileInterface/RifEclipseTextFileReader.cpp, ApplicationLibCode/UnitTests/RifEclipseTextFileReader-Test.cpp
=> Fix invalid parsing of line with keyword end tag and comment

ApplicationLibCode/ProjectDataModel/Flow/RimWellPltPlot.cpp, Fwk/AppFwk/cafCommand/cafCmdUiCommandSystemImpl.cpp, Fwk/AppFwk/cafCommand/cafCmdUiCommandSystemImpl.h, Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafInternalPdmUiCommandSystemInterface.h, Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafPdmUiCommandSystemProxy.cpp
=> Fix missing LAS curves

ApplicationLibCode/Application/RiaPreferences.cpp, ApplicationLibCode/Application/RiaPreferences.h, ApplicationLibCode/Application/Tools/RiaNetworkTools.cpp, ApplicationLibCode/Application/Tools/RiaNetworkTools.h, ApplicationLibCode/CommandFileInterface/RicfExportProperty.cpp, ApplicationLibCode/CommandFileInterface/RicfExportPropertyInViews.cpp, ApplicationLibCode/Commands/ApplicationCommands/RicEditPreferencesFeature.cpp, ApplicationLibCode/Commands/ApplicationCommands/RicEditPreferencesFeature.h, ApplicationLibCode/Commands/ApplicationCommands/RicHelpFeatures.cpp, ApplicationLibCode/Commands/ExportCommands/RicEclipseCellResultToFileImpl.cpp, ApplicationLibCode/Commands/ExportCommands/RicEclipseCellResultToFileImpl.h, ApplicationLibCode/Commands/ExportCommands/RicExportEclipseSectorModelFeature.cpp, ApplicationLibCode/Commands/ExportCommands/RicExportEclipseSectorModelUi.cpp, ApplicationLibCode/Commands/ExportCommands/RicExportEclipseSectorModelUi.h, ApplicationLibCode/Commands/ExportCommands/RicSaveEclipseInputPropertyFeature.cpp, ApplicationLibCode/Commands/ExportCommands/RicSaveEclipseInputVisibleCellsFeature.cpp, ApplicationLibCode/Commands/ExportCommands/RicSaveEclipseInputVisibleCellsUi.cpp, ApplicationLibCode/Commands/ExportCommands/RicSaveEclipseInputVisibleCellsUi.h, ApplicationLibCode/Commands/ExportCommands/RicSaveEclipseResultAsInputPropertyExec.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicOpenSummaryPlotEditorFeature.cpp, ApplicationLibCode/FileInterface/RifEclipseInputFileTools.cpp, ApplicationLibCode/FileInterface/RifEclipseInputFileTools.h, ApplicationLibCode/ProjectDataModel/RimBinaryExportSettings.cpp, ApplicationLibCode/ProjectDataModel/RimBinaryExportSettings.h, ApplicationLibCode/ProjectDataModel/RimExportInputPropertySettings.cpp, ApplicationLibCode/ProjectDataModel/RimExportInputPropertySettings.h, ApplicationLibCode/UserInterface/RiuTreeViewEventFilter.cpp, ApplicationLibCode/UserInterface/RiuTreeViewEventFilter.h
Closes #9818
Closes #9814 
Add `Ctrl-E` as shortcut for Plot Editor
=> Minor issues related to release

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.cpp
=> Improve date tickmarks user interface in Summary Plot

ApplicationLibCode/Commands/SummaryPlotCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/SummaryPlotCommands/RicOpenSummaryPlotEditorFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicOpenSummaryPlotEditorFromMdiAreaFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicOpenSummaryPlotEditorFromMdiAreaFeature.h, ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp
- Add to summary plot node in project tree
- Add to empty space in plot window (mdi area)
Closes: #9870
=> Add open plot editor to menus

ApplicationLibCode/Commands/PlotBuilderCommands/RicSummaryPlotBuilder.cpp, ApplicationLibCode/Commands/PlotTemplateCommands/RicSummaryPlotTemplateTools.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicNewSummaryEnsembleCurveSetFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorUi.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotFeatureImpl.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressModifier.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotFilterTextCurveSetEditor.cpp
=> Prevent update of Show Statistics Curves flag during source stepping in Summary Plot

ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp, ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.h, ApplicationLibCode/ProjectDataModel/WellLog/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveInfoTextProvider.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveInfoTextProvider.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.cpp, ApplicationLibCode/UserInterface/RiuWellLogTrack.cpp, ApplicationLibCode/UserInterface/RiuWellLogTrack.h
- Add realization number to hover info on mouse over for Ensemble RFT-plot
- Refactor curve info text provider functionality and point tracker for separation of point tracker and RiuWellLogTrack object. Now allows override of info text provider to customize mouseover text.
Closes: #9861
=> Realization in Ensemble RFT-plot hover info + refactoring of point tracker functionality

ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.cpp
=> Enable filter when picking is done.

ApplicationLibCode/FileInterface/RifRoffFileTools.cpp
=> #9887 Roff: fix freeze due combining omp and progress info.

ApplicationLibCode/ModelVisualization/RivFishbonesSubsPartMgr.cpp, ApplicationLibCode/ModelVisualization/RivPipeGeometryGenerator.cpp, ApplicationLibCode/ModelVisualization/RivPipeGeometryGenerator.h, ApplicationLibCode/ModelVisualization/RivSimWellPipesPartMgr.cpp, ApplicationLibCode/ModelVisualization/RivSimWellPipesPartMgr.h, ApplicationLibCode/ModelVisualization/RivWellFracturePartMgr.cpp, ApplicationLibCode/ModelVisualization/RivWellPathPartMgr.cpp, ApplicationLibCode/ModelVisualization/RivWellPathPartMgr.h, ApplicationLibCode/ProjectDataModel/RimSimWellInView.cpp, ApplicationLibCode/ProjectDataModel/RimSimWellInView.h, ApplicationLibCode/ProjectDataModel/RimSimWellInViewCollection.cpp, ApplicationLibCode/ProjectDataModel/RimSimWellInViewCollection.h, ApplicationLibCode/ReservoirDataModel/RigMswCenterLineCalculator.cpp, ApplicationLibCode/ReservoirDataModel/RigMswCenterLineCalculator.h, ApplicationLibCode/ReservoirDataModel/RigWellResultPoint.cpp, ApplicationLibCode/ReservoirDataModel/RigWellResultPoint.h
=> Add valve visualization to MSW wells

ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.cpp
=> Default Connection Factors and WPIMULT gives an incorrect Well Connection Factor

ApplicationExeCode/Resources/DataVector.svg, ApplicationExeCode/Resources/DataVectorCalculated.svg, ApplicationExeCode/Resources/ResInsight.qrc, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddress.cpp
=> Add icon for calculated summary vectors

ApplicationLibCode/Application/RiaApplication.cpp, ApplicationLibCode/Application/RiaApplication.h, ApplicationLibCode/Commands/FractureCommands/RicNewStimPlanModelFeature.cpp, ApplicationLibCode/Commands/RicCreateEnsembleWellLogFeature.cpp, ApplicationLibCode/Commands/SsiHubImportCommands/RicWellPathsImportSsihubFeature.cpp, ApplicationLibCode/Commands/WellPathCommands/RicCreateMultipleWellPathLaterals.cpp, ApplicationLibCode/Commands/WellPathCommands/RicImportWellPaths.cpp, ApplicationLibCode/Commands/WellPathCommands/RicImportWellPaths.h, ApplicationLibCode/Commands/WellPathCommands/RicNewEditableWellPathFeature.cpp, ApplicationLibCode/Commands/WellPathCommands/RicNewWellPathLateralAtDepthFeature.cpp, ApplicationLibCode/Commands/WellPathCommands/RicPasteModeledWellPathFeature.cpp, ApplicationLibCode/ProjectDataModel/WellPath/RimWellPathCollection.cpp, ApplicationLibCode/ProjectDataModel/WellPath/RimWellPathCollection.h
=> Improve well path import how wells are connected

ApplicationLibCode/Commands/ApplicationCommands/RicShowMainWindowFeature.cpp, ApplicationLibCode/Commands/RicImportGridModelFromSummaryCaseFeature.cpp, ApplicationLibCode/Commands/ToggleCommands/RicToggleItemsFeatureImpl.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewMultiPhaseRftSegmentPlotFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewRftSegmentWellLogPlotFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewRftSegmentWellLogPlotFeature.h, ApplicationLibCode/Commands/WellLogCommands/RicNewWellLogPlotFeatureImpl.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewWellLogPlotFeatureImpl.h, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp, ApplicationLibCode/ProjectDataModel/RimRftPlotCollection.cpp, ApplicationLibCode/ProjectDataModel/RimRftPlotCollection.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.cpp
=> Several RFT plot adjustments

ApplicationLibCode/ReservoirDataModel/ResultAccessors/RigDepthResultAccessor.cpp, ApplicationLibCode/UserInterface/RiuDepthQwtPlot.cpp, ApplicationLibCode/UserInterface/RiuSelectionChangedHandler.cpp
=> Improve depth plot performance

ApplicationLibCode/Application/RiaGuiApplication.cpp, ApplicationLibCode/Application/RiaRftPltCurveDefinition.cpp, ApplicationLibCode/FileInterface/RifTextDataTableFormatter.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp, ApplicationLibCode/ProjectDataModel/RimAdvancedSnapshotExportDefinition.cpp, ApplicationLibCode/ProjectDataModel/RimAdvancedSnapshotExportDefinition.h, ApplicationLibCode/ProjectDataModel/RimProject.cpp, ApplicationLibCode/ProjectDataModel/RimProject.h, ApplicationLibCode/UnitTests/RifTextDataTableFormatter-Test.cpp, ApplicationLibCode/UserInterface/RiuAdvancedSnapshotExportWidget.cpp, ApplicationLibCode/UserInterface/RiuResultTextBuilder.cpp, ResInsightVersion.cmake
=> Adjustments for release

ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.cpp
=> Fix RFT plot crash

ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatistics.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatistics.h, ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogCurveSet.cpp, ApplicationLibCode/UserInterface/RiuMultiPlotPage.cpp
=> Reduce space around legend texts for better visuals.

ApplicationLibCode/Application/RiaRftPltCurveDefinition.cpp, ApplicationLibCode/Application/RiaRftPltCurveDefinition.h, ApplicationLibCode/FileInterface/RifDataSourceForRftPlt.cpp, ApplicationLibCode/FileInterface/RifDataSourceForRftPlt.h
=> Fix selection of multiple pressure/depth sources in plot

ApplicationLibCode/Commands/WellLogCommands/RicNewMultiPhaseRftSegmentPlotFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewRftSegmentWellLogPlotFeature.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.cpp, ResInsightVersion.cmake
=> Improve RFT reader performance

ApplicationLibCode/Application/RiaApplication.cpp, ApplicationLibCode/ProjectDataModel/Summary/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/Summary/RimGridSummaryCase.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimGridSummaryCase.h
=> Reintroduce RimGridSummaryCase to be able to read existing project files

ApplicationLibCode/Application/Tools/RiaSummaryTools.cpp, ApplicationLibCode/Application/Tools/RiaSummaryTools.h, ApplicationLibCode/FileInterface/RifEclipseSummaryAddress.cpp, ApplicationLibCode/FileInterface/RifEclipseSummaryAddress.h, ApplicationLibCode/ProjectDataModel/RimSummaryCalculation.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimCsvUserData.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimCsvUserData.h, ApplicationLibCode/ProjectDataModel/Summary/RimObservedEclipseUserData.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimObservedEclipseUserData.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.cpp, ApplicationLibCode/UserInterface/RiuSummaryVectorSelectionUi.cpp
=> 9966 summary observed data

.github/workflows/ResInsightWithCache.yml
remove qtscript
remove use of obsolete action
improve cache key for vcpkg
=> Improve main github action 

ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationOverTimePlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellConnectivityTable.cpp, ApplicationLibCode/ReservoirDataModel/RigAccWellFlowCalculator.cpp
Fix crash situations where no well cells are found for tracers
=> Improve robustness of well flow calculator

ApplicationLibCode/ProjectDataModel/Flow/RimWellConnectivityTable.cpp
=> Add icons and hide child items in Producer/Injector Connectivity Table

ApplicationLibCode/ProjectDataModel/RimPlotAxisProperties.cpp, ApplicationLibCode/ProjectDataModel/RimPlotAxisProperties.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
=> Use auto-value features only for RimSummaryPlot

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTable.h, ApplicationLibCode/UserInterface/RiuMatrixPlotWidget.cpp
Weird conversion error seen for Unity build on MSVC. Single file compile works fine.
=> Fix type conversion error

ApplicationLibCode/ModelVisualization/Seismic/CMakeLists_files.cmake, ApplicationLibCode/ModelVisualization/Seismic/RivSeismicSectionPartMgr.cpp, ApplicationLibCode/ModelVisualization/Seismic/RivSeismicSectionSourceInfo.cpp, ApplicationLibCode/ModelVisualization/Seismic/RivSeismicSectionSourceInfo.h, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicData.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicData.h, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicSection.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicSection.h, ApplicationLibCode/UserInterface/RiuViewerCommands.cpp
=> Add seismic result info in 3D view

CMakeLists.txt
=> Remove test code for ccache

ApplicationLibCode/ProjectDataModel/RimProject.cpp, ApplicationLibCode/ProjectDataModel/RimProject.h, Fwk/AppFwk/cafProjectDataModel/cafPdmDocument.cpp, Fwk/AppFwk/cafProjectDataModel/cafPdmDocument.h
=> Make sure file paths are resolved before initAfterRead() is called

ApplicationLibCode/Application/RiaSeismicDefines.cpp, ApplicationLibCode/Application/RiaSeismicDefines.h, ApplicationLibCode/Commands/SeismicCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/SeismicCommands/RicNewInlineSeismicSectionFeature.cpp, ApplicationLibCode/Commands/SeismicCommands/RicNewPolylineSeismicSectionFeature.cpp, ApplicationLibCode/Commands/SeismicCommands/RicNewWellpathSeismicSectionFeature.cpp, ApplicationLibCode/Commands/SeismicCommands/RicNewWellpathSeismicSectionFeature.h, ApplicationLibCode/Commands/SeismicCommands/RicNewXlineSeismicSectionFeature.cpp, ApplicationLibCode/Commands/SeismicCommands/RicNewZSliceSeismicSectionFeature.cpp, ApplicationLibCode/Commands/SeismicCommands/RicSeismicSectionFeatureImpl.cpp, ApplicationLibCode/Commands/SeismicCommands/RicSeismicSectionFeatureImpl.h, ApplicationLibCode/Commands/SeismicCommands/RicSeismicSectionFromIntersectionFeature.cpp, ApplicationLibCode/Commands/SeismicCommands/RicSeismicSectionFromIntersectionFeature.h, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp, ApplicationLibCode/ProjectDataModel/RimTools.cpp, ApplicationLibCode/ProjectDataModel/RimTools.h, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicAlphaMapper.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicData.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicSection.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicSection.h
Closes #10044 
Closes #10046 
Adds more validation and stability fixes
=> Seismic support improvments

ApplicationLibCode/ProjectDataModel/Flow/RimWellConnectivityTable.cpp
=> Fix producer/injector selection issues

ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicSection.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicSection.h, ApplicationLibCode/ProjectDataModel/WellPath/RimModeledWellPath.cpp, ApplicationLibCode/ProjectDataModel/WellPath/RimModeledWellPath.h
=> Sync seismic section with well path changes.

ApplicationLibCode/Commands/RicFaciesPropertiesImportTools.cpp, ApplicationLibCode/FileInterface/RifRoffReader.cpp, ApplicationLibCode/FileInterface/RifRoffReader.h, ApplicationLibCode/UnitTests/RifRoffReader-Test.cpp
=> Make RifRoffReader to utilize roffcpp reader/parser

ApplicationLibCode/ProjectDataModel/Flow/RimFlowDiagnosticsTools.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellConnectivityTable.cpp
=> Improve robustness of RimWellConnectivityTable

ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorNormalST.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogWbsCurve.h
=> WBS-plot: Add optional support for maximum curve interval for UCS parameter curve 

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTable.cpp
Closes: #10138
----
Note: Compared vector data values to threshold value and not 0.0 to detect first/last time step with summary values
=> Fix incorrect sorting of rows in summary table 

ApplicationExeCode/CMakeLists.txt, ApplicationLibCode/CMakeLists.txt, ApplicationLibCode/Commands/CMakeLists.txt, ApplicationLibCode/Commands/SeismicCommands/RicImportSeismicFeature.cpp, ApplicationLibCode/FileInterface/CMakeLists_files.cmake, ApplicationLibCode/FileInterface/RifOpenVDSReader.cpp, ApplicationLibCode/FileInterface/RifOpenVDSReader.h, ApplicationLibCode/FileInterface/RifSeismicReader.cpp, ApplicationLibCode/FileInterface/RifSeismicReader.h, ApplicationLibCode/FileInterface/RifSeismicZGYReader.cpp, ApplicationLibCode/FileInterface/RifSeismicZGYReader.h, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicAlphaMapper.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicData.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicData.h, ApplicationLibCode/UserInterface/RiuViewerCommands.cpp, CMakeLists.txt
=> OpenVDS seismic access

ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechView.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicDataCollection.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicDataCollection.h, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicSectionCollection.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicSectionCollection.h
=> Hide seismic section folder in views if no seismic data is loaded

ApplicationLibCode/FileInterface/RifHdf5Exporter.h, ApplicationLibCode/FileInterface/RifHdf5Reader.cpp, ApplicationLibCode/FileInterface/RifHdf5Reader.h, ApplicationLibCode/FileInterface/RifHdf5SummaryReader.cpp, ApplicationLibCode/ReservoirDataModel/ResultCalculators/RigFaultDistanceResultCalculator.cpp, ApplicationLibCode/UnitTests/HDF5FileReader-Test.cpp, ApplicationLibCode/UnitTests/HDF5FileWriter-Test.cpp
=> Improve fault distance computations

ApplicationLibCode/FileInterface/RifCsvUserDataParser.cpp, ApplicationLibCode/FileInterface/RifCsvUserDataParser.h, ApplicationLibCode/FileInterface/RifRevealCsvSectionSummaryReader.cpp
=> #10130 Reveal summary import: convert to Eclipse units.

ApplicationLibCode/Application/Tools/RiaEnsembleNameTools.cpp
=> #10129 StimPlan Summary Ensemble: Simplify paths

ApplicationExeCode/CMakeLists.txt, ApplicationLibCode/CMakeLists.txt, ApplicationLibCode/Commands/SeismicCommands/RicImportSeismicFeature.cpp, ApplicationLibCode/FileInterface/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicData.cpp, CMakeLists.txt
=> OpenVDS should always be used

ApplicationLibCode/Application/Tools/RiaEnsembleNameTools.cpp, ApplicationLibCode/Application/Tools/RiaEnsembleNameTools.h, ApplicationLibCode/Commands/RicImportEnsembleFeature.cpp, ApplicationLibCode/Commands/RicRecursiveFileSearchDialog.cpp
=> #10128 Reveal Summary: add ensemble import.

ApplicationLibCode/Commands/SeismicCommands/RicImportSeismicFeature.cpp, ApplicationLibCode/Commands/SeismicCommands/RicImportSeismicFeature.h, ApplicationLibCode/FileInterface/RifOpenVDSReader.h, ApplicationLibCode/ProjectDataModel/ProcessControl/RimProcess.cpp, ApplicationLibCode/ProjectDataModel/ProcessControl/RimProcess.h, ApplicationLibCode/ProjectDataModel/ProcessControl/RimProcessMonitor.cpp, ApplicationLibCode/ProjectDataModel/Seismic/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/Seismic/RimSEGYConvertOptions.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSEGYConvertOptions.h
=> Import SEG-Y files by converting to VDS

ThirdParty/Ert/lib/ecl/ecl_grid.cpp
=> Read NNC data from INIT file for Intersect files

CMakeLists.txt
=> Add optional support for download of geomech dependencies

.github/workflows/ResInsightWithCache.yml, ApplicationLibCode/CMakeLists.txt, CMakeLists.txt
=> Download and use binaries as part of a build 

ApplicationLibCode/ProjectDataModel/Flow/RimWellConnectivityTable.cpp, ApplicationLibCode/ProjectDataModel/Summary/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTable.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTable.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTableTools.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTableTools.h, ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeSelectionEditor.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeSelectionEditor.h, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeSelectionQModel.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeSelectionQModel.h
=> Add filtering/exclude of rows in SummaryTable

ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionEnums.cpp
=> Set default depth filter type to "between"

ApplicationLibCode/ModelVisualization/RivPolylinePartMgr.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicSection.cpp, ApplicationLibCode/ReservoirDataModel/RigPolyLinesData.cpp, ApplicationLibCode/ReservoirDataModel/RigPolyLinesData.h
=> Skip bounding box check when drawing seismic outline

ApplicationLibCode/ProjectDataModel/RimColorLegendCollection.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseResultDefinition.cpp
=> Show category text in 3D view legend

ApplicationLibCode/Application/Tools/RiaExtractionTools.cpp, ApplicationLibCode/Application/Tools/RiaExtractionTools.h, ApplicationLibCode/ProjectDataModel/RimPltPlotCollection.cpp, ApplicationLibCode/ProjectDataModel/RimPltPlotCollection.h, ApplicationLibCode/ProjectDataModel/RimRftPlotCollection.cpp, ApplicationLibCode/ProjectDataModel/RimRftPlotCollection.h, ApplicationLibCode/ProjectDataModel/WellLog/Rim3dWellLogExtractionCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/Rim3dWellLogExtractionCurve.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogPlotCollection.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogPlotCollection.h, ApplicationLibCode/ReservoirDataModel/RigGeoMechWellLogExtractor.cpp, ApplicationLibCode/ReservoirDataModel/RigGeoMechWellLogExtractor.h
=> Specify part id for well extraction from geomech data

ApplicationLibCode/Application/Tools/RiaTextStringTools.cpp, ApplicationLibCode/Application/Tools/RiaTextStringTools.h, ApplicationLibCode/Commands/CompletionExportCommands/RicExportFractureCompletionsImpl.cpp, ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.h, ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathFractureReportItem.cpp, ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathFractureReportItem.h
- add the operator<=> for QString
- add operator<=> to fracture report item
Closes #10249
=> Display all data if multiple fractures crosses a cell

ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.cpp
=> Disable depth filter for GeoMech cases.

ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.cpp
=> Enable intersection depth filter for geomech cases, too

ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.h
=> Fix polygon cell filter crash for geomech case with mulitple parts

.gitmodules, ApplicationLibCode/Commands/SummaryPlotCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/SummaryPlotCommands/RicCreateRegressionAnalysisCurveFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicCreateRegressionAnalysisCurveFeature.h, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp, ApplicationLibCode/ProjectDataModel/Summary/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryRegressionAnalysisCurve.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryRegressionAnalysisCurve.h, CMakeLists.txt
=> #7206 Add regression analysis.

CMakeLists.txt
Make redocking floating windows on WSL work
=> Update docking framework to latest version 

ApplicationLibCode/ProjectDataModel/CellFilters/RimEclipsePropertyFilter.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimEclipsePropertyFilter.h, ApplicationLibCode/ProjectDataModel/RimEclipseResultDefinitionTools.cpp
=> Category legend improvements

ApplicationLibCode/ProjectDataModel/RimPlotCurve.cpp, ApplicationLibCode/ProjectDataModel/RimPlotCurve.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSetCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSetCollection.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSetColorManager.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryRegressionAnalysisCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogCurveSet.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeAttributes.h, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewItemDelegate.cpp
=> 10214 ensemble appearance

ApplicationLibCode/UserInterface/RiuSummaryVectorSelectionUi.cpp
=> Fix inverted flag when filtering summary vectors to show in UI

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurvesData.cpp
=> Summary plot: Show plot data applies values to realizations with undefined vectors

ApplicationLibCode/ReservoirDataModel/RigWellLogCurveData.cpp, ApplicationLibCode/ReservoirDataModel/RigWellLogCurveData.h, ApplicationLibCode/UnitTests/CMakeLists_files.cmake, ApplicationLibCode/UnitTests/RigWellLogCurveData-Test.cpp
- Fixes resampling bug
- Refactored code for testability
- Added unit tests
---
Closes #10241
=> Fix bug and refactor createResampledValuesAndDepts in RigWellLogCurveData

ApplicationLibCode/ModelVisualization/Intersections/RivEclipseIntersectionGrid.cpp, ApplicationLibCode/ModelVisualization/Intersections/RivEclipseIntersectionGrid.h, ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionGeometryGenerator.cpp, ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionGeometryGenerator.h, ApplicationLibCode/ModelVisualization/Intersections/RivFemIntersectionGrid.cpp, ApplicationLibCode/ModelVisualization/Intersections/RivFemIntersectionGrid.h, ApplicationLibCode/ModelVisualization/Intersections/RivIntersectionHexGridInterface.h, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterIntervalTool.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterIntervalTool.h, ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.h, ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.cpp, ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.h, ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionCollection.cpp, ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionCollection.h
=> Add support for K filter to polyline intersections

ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterIntervalTool.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterIntervalTool.h, ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.cpp, ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.cpp, ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionCollection.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeSelectionEditor.cpp
=> Add step support to range text format

ApplicationLibCode/Application/RiaDefines.cpp, ApplicationLibCode/Application/RiaDefines.h, ApplicationLibCode/Commands/RicImportRevealSummaryCaseFeature.cpp, ApplicationLibCode/Commands/RicImportStimPlanSummaryCaseFeature.cpp, ApplicationLibCode/ProjectDataModel/RimObservedDataCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimDerivedEnsembleCaseCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCase.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCase.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryDataSourceStepping.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryDataSourceStepping.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.h, ApplicationLibCode/UserInterface/RiuDragDrop.cpp
Closes #10317 
Closes #10253
Closes #10252
- remove light mode from theme selection, as this is causing confusion for users
- support drag/drop of ensembles
=> Maintenance fixes

ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.cpp, ApplicationLibCode/ReservoirDataModel/Completions/RigTransmissibilityCondenser.cpp
=> Fix build issues MSVC 17.6.2

ApplicationLibCode/FileInterface/RifRoffFileTools.cpp
=> #10331 Roff property import: Add support for BYTE data type

ApplicationLibCode/Commands/IntersectionBoxCommands/RicAppendIntersectionBoxFeature.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimEclipsePropertyFilter.cpp
=> Property filter: range sliders not initialized when reloading project

ApplicationLibCode/Commands/EclipseCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/EclipseCommands/RicAddGridCalculationFeature.cpp, ApplicationLibCode/Commands/EclipseCommands/RicAddGridCalculationFeature.h, ApplicationLibCode/Commands/RicShowGridCalculatorFeature.cpp, ApplicationLibCode/ProjectDataModel/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculationVariable.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculationVariable.h, ApplicationLibCode/ProjectDataModel/RimResultSelectionUi.cpp, ApplicationLibCode/ProjectDataModel/RimResultSelectionUi.h
Closes  #10137
Create new calculation from right-click menu of a grid cell result
=> Add edit button to grid calculation expressions

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryDeclineCurve.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryRegressionAnalysisCurve.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryRegressionAnalysisCurve.h, ApplicationLibCode/UnitTests/CMakeLists_files.cmake, ApplicationLibCode/UnitTests/RimSummaryRegressionAnalysisCurve-Test.cpp
=> #10292 Regression Analysis: add forecasting

ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.cpp
- Part Id in curve name and plot title
- Part Id selection using dropdown menu
Closes: #10247
=> Improvements of part id visualization for well log extraction curves

ApplicationLibCode/FileInterface/RifCsvUserDataParser.cpp, ApplicationLibCode/FileInterface/RifCsvUserDataParser.h, ApplicationLibCode/FileInterface/RifRevealCsvSectionSummaryReader.cpp
This gives better behavior in summary plot (correct phase colors and better default axis grouping).
Fixes #10210.
=> #10210 Reveal Summary Import: map reveal names to eclipse names.

ApplicationExeCode/Resources/ResInsight.qrc, ApplicationExeCode/Resources/themes/dark.qss, ApplicationExeCode/Resources/themes/default.qss, ApplicationExeCode/Resources/themes/shared/radio-button-active.svg, ApplicationExeCode/Resources/themes/shared/radio-circle-active.svg, ApplicationLibCode/ProjectDataModel/Flow/RimWellConnectivityTable.cpp, ApplicationLibCode/ProjectDataModel/Surfaces/RimGridCaseSurface.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeSelectionEditor.cpp
Closes #10411
Closes #10415 
Closes #10417
=> Adjustments after release

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
=> Fix stacking of curves

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurvesData.cpp
=> Summary Data: Show confirm dialog before creating a large number of text lines 

ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCaseEvaluator.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCaseEvaluator.h, ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.cpp
=> Do not clear generated results during statistics computation

ApplicationLibCode/Application/Tools/RiaStdStringTools.cpp, ApplicationLibCode/Application/Tools/RiaStdStringTools.h, ApplicationLibCode/ProjectDataModel/Flow/RimFlowCharacteristicsPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationOverTimePlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellConnectivityTable.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellDistributionPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellDistributionPlotCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTable.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTable.h, ApplicationLibCode/UserInterface/RiuFlowCharacteristicsPlot.cpp, ApplicationLibCode/UserInterface/RiuFlowCharacteristicsPlot.h, ApplicationLibCode/UserInterface/RiuMatrixPlotWidget.cpp, ApplicationLibCode/UserInterface/RiuMatrixPlotWidget.h, ApplicationLibCode/UserInterface/RiuPlotWidget.cpp, ApplicationLibCode/UserInterface/RiuPlotWidget.h, ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.cpp, ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp, ApplicationLibCode/UserInterface/RiuQwtPlotWidget.h, ApplicationLibCode/UserInterface/RiuWellAllocationPlot.cpp
Closes https://github.com/OPM/ResInsight/issues/10446
=> Layout adjustments

ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp, ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.h, ApplicationLibCode/ProjectDataModel/RimPlotCurve.cpp, ApplicationLibCode/ProjectDataModel/RimWellBoreStabilityPlot.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp
Fix memory leak of associated viewer
Closes #10384
=> Fix missing curve tracker

ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCase.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCase.h, ApplicationLibCode/ProjectDataModel/RimIdenticalGridCaseGroup.cpp, ApplicationLibCode/ProjectDataModel/RimIdenticalGridCaseGroup.h, ApplicationLibCode/ProjectDataModelCommands/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModelCommands/RimcEclipseStatisticsCase.cpp, ApplicationLibCode/ProjectDataModelCommands/RimcEclipseStatisticsCase.h, ApplicationLibCode/ProjectDataModelCommands/RimcIdenticalGridCaseGroup.cpp, ApplicationLibCode/ProjectDataModelCommands/RimcIdenticalGridCaseGroup.h, GrpcInterface/Python/rips/PythonExamples/case_grid_group_generated_results.py, GrpcInterface/Python/rips/gridcasegroup.py
=> Fix and improve create_statistics_case

ApplicationLibCode/ProjectDataModel/RimEclipseResultDefinition.cpp
=> Support delta computations for generated results

ApplicationLibCode/Application/Tools/RiaNumericalTools.cpp, ApplicationLibCode/Application/Tools/RiaNumericalTools.h, ApplicationLibCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlotDataSet.cpp, ApplicationLibCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlotRegressionCurve.cpp, ApplicationLibCode/ProjectDataModel/RimRegularLegendConfig.cpp, ApplicationLibCode/ProjectDataModel/RimTernaryLegendConfig.cpp, ApplicationLibCode/UnitTests/CMakeLists_files.cmake, ApplicationLibCode/UnitTests/RiaNumericalTools-Test.cpp, ApplicationLibCode/UnitTests/RifColorLegendData-Test.cpp
Closes #10481
Use regression curve icon for grid cross plot regression curves.
=> Adjust ranges using floor and ceil

ApplicationLibCode/Commands/RicImportGridModelFromSummaryCaseFeature.cpp, ApplicationLibCode/Commands/RicImportGridModelFromSummaryCaseFeature.h, ApplicationLibCode/FileInterface/RifDataSourceForRftPlt.cpp, ApplicationLibCode/FileInterface/RifDataSourceForRftPlt.h, ApplicationLibCode/ProjectDataModel/Flow/RimDataSourceForRftPlt.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellPlotTools.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp, ApplicationLibCode/ProjectDataModel/RimProject.cpp
=> Support well path geometry for summary RFT data

ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp, ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemScalarResultFrames.cpp
Make sure element results are created only once
Make sure single element results access data for time step 0 and frame 0
Closes #10488
=> Element property values not shown in geomech view 

ApplicationLibCode/FileInterface/RifEclipseInputFileTools.cpp
=> Refined grid export appears to give wrong number of cells

ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorBarConverted.cpp, ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorNormalized.cpp, ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
=> Normalize by Hydrostatic Pressure don't work for pore pressure  

ApplicationLibCode/Commands/ExportCommands/RicExportEclipseSectorModelUi.cpp, ApplicationLibCode/FileInterface/RifEclipseInputFileTools.cpp
=> Export sector model: Support more result categories

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotManager.cpp
=> Use "Sub Plots" when computing y-range for plots

ApplicationLibCode/Application/RiaApplication.cpp, ApplicationLibCode/ProjectDataModel/RimPlotAxisProperties.cpp, ApplicationLibCode/ProjectDataModel/RimPlotAxisProperties.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.h, Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafPdmUiFieldHandle.cpp
=> Performance: Slow performance for some plot and curve operations 

ApplicationLibCode/Commands/RicCreateSurfaceIntersectionBandFeature.cpp, ApplicationLibCode/Commands/RicCreateSurfaceIntersectionBandFeature.h, ApplicationLibCode/Commands/RicImportEnsembleSurfaceFeature.cpp, ApplicationLibCode/Commands/SurfaceCommands/RicImportSurfacesFeature.cpp, ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionGeometryGenerator.cpp, ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionGeometryGenerator.h, ApplicationLibCode/ModelVisualization/Seismic/RivSeismicSectionPartMgr.cpp, ApplicationLibCode/ModelVisualization/Seismic/RivSeismicSectionPartMgr.h, ApplicationLibCode/ProjectDataModel/RimGridView.cpp, ApplicationLibCode/ProjectDataModel/RimSurfaceIntersectionBand.cpp, ApplicationLibCode/ProjectDataModel/RimSurfaceIntersectionCurve.cpp, ApplicationLibCode/ProjectDataModel/RimTools.cpp, ApplicationLibCode/ProjectDataModel/RimTools.h, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicSectionCollection.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicSectionCollection.h, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicView.cpp, ApplicationLibCode/ReservoirDataModel/RigSurfaceResampler.cpp, ApplicationLibCode/ReservoirDataModel/RigSurfaceResampler.h
=> Show surface intersection lines on seismic geometry

ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp
=> Fix visibility of single RFT curves

ApplicationLibCode/Application/Tools/RiaExtractionTools.cpp, ApplicationLibCode/Application/Tools/RiaExtractionTools.h, ApplicationLibCode/Commands/RicWellLogTools.cpp, ApplicationLibCode/FileInterface/RifDataSourceForRftPlt.cpp, ApplicationLibCode/FileInterface/RifDataSourceForRftPlt.h, ApplicationLibCode/FileInterface/RifReaderEclipseRft.cpp, ApplicationLibCode/FileInterface/RifReaderEclipseRft.h, ApplicationLibCode/FileInterface/RifReaderEnsembleStatisticsRft.cpp, ApplicationLibCode/FileInterface/RifReaderEnsembleStatisticsRft.h, ApplicationLibCode/FileInterface/RifReaderOpmRft.cpp, ApplicationLibCode/FileInterface/RifReaderOpmRft.h, ApplicationLibCode/FileInterface/RifReaderRftInterface.cpp, ApplicationLibCode/FileInterface/RifReaderRftInterface.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellPlotTools.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellPlotTools.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellPltPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftEnsembleCurveSet.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.h, ApplicationLibCode/ReservoirDataModel/RigWellLogExtractor.cpp, ApplicationLibCode/ReservoirDataModel/RigWellLogExtractor.h
=> RFT refactoring 2

ApplicationLibCode/FileInterface/RifOpmGridTools.cpp, ResInsightVersion.cmake
=> opm-common: Add support for map axes import

ApplicationLibCode/Commands/CellFilterCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/CellFilterCommands/RicNewCellIndexFilterFeature.cpp, ApplicationLibCode/Commands/CellFilterCommands/RicNewCellIndexFilterFeature.h, ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPart.cpp, ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPart.h, ApplicationLibCode/GeoMech/OdbReader/RifGeoMechReaderInterface.h, ApplicationLibCode/GeoMech/OdbReader/RifOdbReader.cpp, ApplicationLibCode/GeoMech/OdbReader/RifOdbReader.h, ApplicationLibCode/ProjectDataModel/CellFilters/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilter.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilter.h, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.h, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellIndexFilter.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellIndexFilter.h, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellRangeFilter.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellRangeFilter.h, ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.h, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp, ApplicationLibCode/ProjectDataModel/RimTools.cpp, ApplicationLibCode/ProjectDataModel/RimTools.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogExtractionCurve.cpp
=> Support filtering on element sets

ApplicationLibCode/FileInterface/RifReaderEnsembleStatisticsRft.cpp, ApplicationLibCode/FileInterface/RifReaderEnsembleStatisticsRft.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp
=> Fix missing statistics curves in some cases

ApplicationLibCode/ModelVisualization/CMakeLists_files.cmake, ApplicationLibCode/ModelVisualization/Riv3dWellLogDrawSurfaceGenerator.cpp, ApplicationLibCode/ModelVisualization/RivAnnotationSourceInfo.cpp, ApplicationLibCode/ModelVisualization/RivAnnotationSourceInfo.h, ApplicationLibCode/ModelVisualization/RivAnnotationTools.cpp, ApplicationLibCode/ModelVisualization/RivAnnotationTools.h, ApplicationLibCode/ModelVisualization/RivPolylineGenerator.h, ApplicationLibCode/ModelVisualization/RivWellPathPartMgr.cpp, ApplicationLibCode/ModelVisualization/Seismic/RivSeismicSectionPartMgr.cpp, ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.cpp, ApplicationLibCode/ProjectDataModel/Rim3dView.cpp, ApplicationLibCode/ProjectDataModel/Rim3dView.h, ApplicationLibCode/ProjectDataModel/WellPath/RimWellPath.cpp, ApplicationLibCode/ProjectDataModel/WellPath/RimWellPath.h, ApplicationLibCode/ReservoirDataModel/RigWellPath.cpp, ApplicationLibCode/ReservoirDataModel/RigWellPath.h
=> Add annotations based on a set of annotation anchor candidates

ApplicationLibCode/Commands/GeoMechCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/GeoMechCommands/RicNewFaultReactModelingFeature.cpp, ApplicationLibCode/Commands/GeoMechCommands/RicRunFaultReactModelingFeature.cpp, ApplicationLibCode/Commands/GeoMechCommands/RicRunFaultReactModelingFeature.h, ApplicationLibCode/Commands/GeoMechCommands/RicShowFaultReactModelFeature.cpp, ApplicationLibCode/Commands/GeoMechCommands/RicShowFaultReactModelFeature.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModelCollection.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModelCollection.h, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp, ApplicationLibCode/ProjectDataModel/RimTimeStepFilter.cpp, ApplicationLibCode/ProjectDataModel/RimTimeStepFilter.h, ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.cpp
Add commands to run the modeling as well as quickly view the model defined in 3D. 
Changes node element order according to feedback.
Add support for selecting timesteps to include.
=> Fault Reactivation Modeling updates

ApplicationLibCode/Commands/RicImportSummaryCasesFeature.cpp
Make sure that the loaded summary cases are added to the project.
=> Fix Import Summary Cases Recursively

ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.cpp
=> Fix crash when creating a contour map from a 3d view

Fwk/AppFwk/cafTests/cafTestApplication/MainWindow.cpp, Fwk/AppFwk/cafUserInterface/CMakeLists.txt, Fwk/AppFwk/cafUserInterface/cafPdmUiCheckBoxAndTextEditor.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiDefaultObjectEditor.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiDoubleSliderEditor.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiLineEditor.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiLineEditor.h, Fwk/AppFwk/cafUserInterface/cafPdmUiSliderTools.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiSliderTools.h, Fwk/AppFwk/cafUserInterface/cafPdmUiValueRangeEditor.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiValueRangeEditor.h
Add editor backed by std::pair<double, double> to be used to define a range
=> Add Value Range editor

ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicSection.cpp
=> Fix corrupted section when switching seismic data input

ApplicationLibCode/Commands/GeoMechCommands/RicRunFaultReactModelingFeature.cpp, ApplicationLibCode/ProjectDataModel/Faults/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationDataAccess.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationDataAccess.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.h, ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechFaultReactivationResult.cpp, ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechFaultReactivationResult.h, ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechView.cpp, ApplicationLibCode/ProjectDataModel/WellPath/RimWellIADataAccess.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModel.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModel.h, ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.cpp, ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.h
Add interface for accessing pressure data for nodes
Misc fixes and improvements
=> Fault Reactivation updates

ApplicationLibCode/Commands/CellFilterCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/CellFilterCommands/RicNewUserDefinedIndexFilterFeature.cpp, ApplicationLibCode/Commands/CellFilterCommands/RicNewUserDefinedIndexFilterFeature.h, ApplicationLibCode/ProjectDataModel/CellFilters/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.h, ApplicationLibCode/ProjectDataModel/CellFilters/RimUserDefinedIndexFilter.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimUserDefinedIndexFilter.h, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
makes some debugging tasks easier
=> Add support for user defined index filters

ApplicationLibCode/Commands/RicCreateSurfaceIntersectionBandFeature.cpp, ApplicationLibCode/Commands/RicCreateSurfaceIntersectionBandFeature.h, ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionPartMgr.cpp, ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionPartMgr.h, ApplicationLibCode/ModelVisualization/RivAnnotationTools.cpp, ApplicationLibCode/ModelVisualization/RivAnnotationTools.h, ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionCollection.cpp, ApplicationLibCode/ProjectDataModel/Rim2dIntersectionView.cpp, ApplicationLibCode/ProjectDataModel/Rim3dView.cpp, ApplicationLibCode/ProjectDataModel/RimGridView.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicSectionCollection.cpp, ApplicationLibCode/ProjectDataModel/Seismic/RimSeismicSectionCollection.h, ApplicationLibCode/ProjectDataModel/Surfaces/RimGridCaseSurface.cpp, ApplicationLibCode/ProjectDataModel/Surfaces/RimSurface.cpp, ApplicationLibCode/ProjectDataModel/Surfaces/RimSurfaceCollection.cpp, ApplicationLibCode/ReservoirDataModel/RigSurfaceResampler.cpp
=> Fix display of intersection lines in 3D view

ApplicationLibCode/ProjectDataModel/RiaOpmParserTools.cpp, ResInsightVersion.cmake
=> Valve Import: Make sure default values are handled correctly

ApplicationLibCode/Commands/CompletionCommands/RicNewFishbonesSubsAtMeasuredDepthFeature.cpp, ApplicationLibCode/Commands/CompletionCommands/RicNewFishbonesSubsAtMeasuredDepthFeature.h, ApplicationLibCode/Commands/CompletionCommands/RicNewFishbonesSubsFeature.cpp, ApplicationLibCode/Commands/CompletionCommands/RicNewFishbonesSubsFeature.h, ApplicationLibCode/Commands/SummaryPlotCommands/RicCreateCrossPlotFeature.cpp, ApplicationLibCode/ProjectDataModel/Completions/RimFishbones.cpp, ApplicationLibCode/ProjectDataModel/Completions/RimFishbones.h, ApplicationLibCode/ProjectDataModel/Completions/RimFishbonesPipeProperties.cpp, ApplicationLibCode/ProjectDataModel/Completions/RimFishbonesPipeProperties.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCrossPlotStatisticsCase.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryRegressionAnalysisCurve.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryRegressionAnalysisCurve.h, ResInsightVersion.cmake
=> Release adjustments

ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForObjectsFeature.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForObjectsFeature.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressModifier.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressModifier.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp
=> Fix stepping issues and refactor RimSummaryAddressModifier

ApplicationLibCode/Commands/WellLogCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/WellLogCommands/RicCreateRftPlotsFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicCreateRftPlotsFeature.h, ApplicationLibCode/Commands/WellLogCommands/RicCreateRftPlotsFeatureUi.cpp, ApplicationLibCode/Commands/WellLogCommands/RicCreateRftPlotsFeatureUi.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.h, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
Show a dialog with all available RFT wells, and let the user select from this list. Create a copy of the RFT plot, and replace well name in the copy.
Closes #10787
=> Create multiple RFT plots based on the selected RFT plot

ApplicationLibCode/Commands/RicUserDefinedCalculatorUi.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCaseTools.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCaseTools.h, ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseView.h, ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculation.h, ApplicationLibCode/ProjectDataModel/RimGridCalculationCollection.cpp, ApplicationLibCode/ProjectDataModel/RimReservoirCellResultsStorage.cpp, ApplicationLibCode/ProjectDataModel/RimResultSelectionUi.cpp, ApplicationLibCode/ProjectDataModel/RimUserDefinedCalculation.cpp, ApplicationLibCode/ProjectDataModel/RimUserDefinedCalculation.h, ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.cpp
=> Optionally execute grid calculation on all grids

ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCase.cpp
=> Grid Statistics: If only one view, select the first available result 

ApplicationLibCode/Commands/RicCreateTemporaryLgrFeature.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCase.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCase.h, ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCaseEvaluator.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCaseEvaluator.h, ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculation.h, ApplicationLibCode/ProjectDataModel/RimGridCalculationCollection.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculationCollection.h, ApplicationLibCode/ProjectDataModel/RimIdenticalGridCaseGroup.cpp, ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.cpp, ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.h, ResInsightVersion.cmake
- add data source selection, either Case Property or Grid Calculation
- add Time Step Selection, can be used for both dynamic case properties and Grid Calculations
- optionally release grid calculation data when statistics is computed
- recursive grid calculations is supported
Closes #10798
=> Add support for grid calculations as data source for statistics

Fwk/AppFwk/CMakeLists.txt, Fwk/AppFwk/cafPdmScripting/CMakeLists.txt, Fwk/AppFwk/cafPdmScripting/cafPdmPythonGenerator.cpp, Fwk/CMakeLists.txt
Add ifdef for code related to CeeViz, so it is possible to compile AppFwk without CeeViz
=> Adjust build settings to c++20

ApplicationLibCode/ProjectDataModel/RimSummaryCalculation.cpp, ApplicationLibCode/ProjectDataModel/RimSummaryCalculation.h, ApplicationLibCode/ProjectDataModel/Summary/RimMultipleSummaryPlotNameHelper.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimMultipleSummaryPlotNameHelper.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveAutoName.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryNameHelper.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotNameHelper.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotNameHelper.h
=> Minor usability improvements

ApplicationLibCode/Commands/CellFilterCommands/RicNewPolygonFilter3dviewFeature.cpp, ApplicationLibCode/Commands/CellFilterCommands/RicNewRangeFilterSlice3dviewFeature.cpp, ApplicationLibCode/Commands/RicNewContourMapViewFeature.cpp, ApplicationLibCode/Commands/RicNewViewFeature.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCase.cpp
=> Fix several issues when opening a project without views

ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCase.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCase.h, ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCaseEvaluator.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCaseEvaluator.h, ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculation.h
=> Grid Calculations: Add optional support for using visible cells as filter

ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.cpp, ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.h
=> Completion Export for ML-wells: Remove COMPDAT cells for de-activated laterals

ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationOverTimePlot.cpp
=> Guard use of null pointer

ApplicationLibCode/CommandFileInterface/RicfExportVisibleCells.cpp, ApplicationLibCode/Commands/ExportCommands/RicSaveEclipseInputVisibleCellsUi.h, GrpcInterface/GrpcProtos/Commands.proto
=> Fix crash for export_visible_cells

ApplicationLibCode/ProjectDataModel/Rim2dIntersectionView.cpp, ApplicationLibCode/ProjectDataModel/Rim3dView.cpp, ApplicationLibCode/ProjectDataModel/Rim3dView.h, ApplicationLibCode/UserInterface/RiuViewerCommands.cpp
=> 10587 compare to same view type

ApplicationLibCode/ModelVisualization/RivWellFracturePartMgr.cpp
=> #10690 Fractures: Show Perforation Interval for azimuth fractures.

ApplicationLibCode/Commands/CMakeLists.txt, ApplicationLibCode/Commands/SeismicCommands/RicImportSeismicFeature.cpp, ApplicationLibCode/UserInterface/RiuMainWindow.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiToolBarEditor.cpp
=> Maintenance adjustments

ApplicationLibCode/Application/RiaApplication.cpp, ApplicationLibCode/Commands/GeoMechCommands/RicNewFaultReactModelingFeature.cpp, ApplicationLibCode/FileInterface/RifFaultReactivationModelExporter.cpp, ApplicationLibCode/FileInterface/RifFaultReactivationModelExporter.h, ApplicationLibCode/ModelVisualization/Faults/RivFaultReactivationModelPartMgr.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.h, ApplicationLibCode/ProjectDataModel/CellFilters/RimUserDefinedIndexFilter.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimUserDefinedIndexFilter.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationEnums.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModelCollection.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModelCollection.h, ApplicationLibCode/ReservoirDataModel/CMakeLists_files.cmake, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModel.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModel.h, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.h, ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.cpp, ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.h
=> Fault reactivation gridding update

ApplicationLibCode/ProjectDataModel/CellFilters/RimCellIndexFilter.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModel.h, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.h, ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.h
=> Fault Reactivation Grid Update

ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.h, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.h, ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.cpp, ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.h, ResInsightVersion.cmake
Closes #10873 
Updates version to dev.09
=> Fault Reactivation: grow horizontal cell size away from fault

ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCase.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCaseEvaluator.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp, ApplicationLibCode/ProjectDataModel/RimGridCalculation.h, ApplicationLibCode/ProjectDataModel/RimGridCalculationVariable.cpp
=> Improve handling of aggregated grid calculations

ApplicationLibCode/FileInterface/RifFaultReactivationModelExporter.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationEnums.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModel.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModel.h, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.cpp, ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.cpp, ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.h
=> Update grid part naming

ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.h, ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.cpp, ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.h, ApplicationLibCode/UserInterface/RiuFemResultTextBuilder.cpp
Add depth range info for the various zones
Fix some gridding issues, handling pinched cells
Fix K layer info for elements
=> Fault reactivation: grid info improvements

ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationEnums.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp, ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.cpp
Fix issue with 0 fault extension
=> Add seabed border surface

ApplicationLibCode/Commands/ExportCommands/RicExportInpFileFeature.cpp, ApplicationLibCode/Commands/GeoMechCommands/RicRunFaultReactModelingFeature.cpp, ApplicationLibCode/FileInterface/RifFaultReactivationModelExporter.cpp, ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp, ApplicationLibCode/GeoMech/OdbReader/RifInpReader.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.h, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.cpp, ResInsightVersion.cmake
Enable porosity calculator for imported inp data
Add model validation check for export/show model
Fix last res. layer not being splitted into subelements
=> Use correct result name for Void ratio

ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.cpp, ResInsightVersion.cmake
=> Bump version to dev.05

ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp
=> Fix grid calculation issue

ApplicationLibCode/Application/Tools/RiaFilePathTools.cpp, ApplicationLibCode/Application/Tools/RiaFilePathTools.h, ApplicationLibCode/Commands/ExportCommands/RicExportInpFileFeature.cpp, ApplicationLibCode/Commands/GeoMechCommands/RicRunFaultReactModelingFeature.cpp, ApplicationLibCode/Commands/GeoMechCommands/RicShowFaultReactModelFeature.cpp, ApplicationLibCode/FileInterface/RifFaultReactivationModelExporter.cpp, ApplicationLibCode/FileInterface/RifFaultReactivationModelExporter.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.h
=> Improve fault reactivation file names

.github/workflows/ResInsightWithCache.yml, ApplicationLibCode/Application/Tools/WellPathTools/RiaSCurveCalculator.cpp, ApplicationLibCode/FileInterface/RifSurfaceImporter.cpp, ApplicationLibCode/ProjectDataModel/Annotations/RimAnnotationCollection.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp, ApplicationLibCode/UserInterface/RiuMainWindow.cpp
There is a known bug in `Ubuntu 22.04` causing grpc applications to hang https://bugs.launchpad.net/ubuntu/+source/grpc/+bug/1971114
ResInsight compiles on `Ubuntu 22.04`, but running `pytest` is not working and is disabled for this runner.
Closes #10972
=> GHA: Update to clang-16

ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.h, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.h
=> Fault Reactivation: Add minimum cell height limit

ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.h, ApplicationLibCode/ReservoirDataModel/RigCellGeometryTools.cpp, ApplicationLibCode/ReservoirDataModel/RigCellGeometryTools.h, ApplicationLibCode/UnitTests/RigCellGeometryTools-Test.cpp
=> Add polyline filter support

ApplicationLibCode/ProjectDataModel/Faults/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationDataAccess.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationDataAccessorStress.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationDataAccessorStress.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationDataAccessorStressEclipse.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationDataAccessorStressEclipse.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationDataAccessorStressGeoMech.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationDataAccessorStressGeoMech.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationDataAccessorWellLogExtraction.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationDataAccessorWellLogExtraction.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.h, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModel.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModel.h, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.h
=> 11034 stress from eclipse

ApplicationLibCode/Application/RiaMemoryCleanup.cpp, ApplicationLibCode/Application/RiaMemoryCleanup.h, ApplicationLibCode/Application/Tools/RiaStdStringTools.cpp, ApplicationLibCode/Application/Tools/RiaStdStringTools.h, ApplicationLibCode/Commands/ApplicationCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/ApplicationCommands/RicShowMemoryReportFeature.cpp, ApplicationLibCode/Commands/ApplicationCommands/RicShowMemoryReportFeature.h, ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp, ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.cpp, ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.h, ApplicationLibCode/UserInterface/RiuMainWindow.cpp
=> Memory Report

ApplicationLibCode/FileInterface/RifReaderOpmCommon.cpp, ApplicationLibCode/FileInterface/RifReaderOpmCommon.h
=> Fix import of time since simulation start

ApplicationLibCode/GeoMech/GeoMechFileInterface/RifInpReader.cpp
- Do not require steps defined in file
- Allow multiple element types (all types must be 8 nodes)
=> Make INP reader a bit more generic

ApplicationLibCode/FileInterface/RifFaultReactivationModelExporter.cpp, ApplicationLibCode/FileInterface/RifFaultReactivationModelExporter.h, ApplicationLibCode/ProjectDataModel/Faults/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationDataAccess.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationDataAccess.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationDataAccessorStressEclipse.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationDataAccessorStressEclipse.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationEnums.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationEnums.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.h, ResInsightVersion.cmake
=> Fault Reactivation: Update stress source selection

.github/workflows/ResInsightWithCache.yml, .github/workflows/clang-format.yml, .github/workflows/clang-tidy.yml, .github/workflows/cmake-format.yml, .github/workflows/delete_artifacts.yml, .github/workflows/python-linting.yml, .github/workflows/spell-check.yml
=> Use latest version of actions

ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationEnums.h, ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModel.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModel.h, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.cpp, ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.cpp, ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.h
=> Fault Reactivation - set updates

ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellConnectivityTable.cpp, ApplicationLibCode/UserInterface/RiuMdiArea.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeSelectionEditor.cpp
Closes #11132 
Closes #11134 
Closes #11140 
Closes #11094
=> Maintenance issues

ApplicationLibCode/Commands/WellPathCommands/RicCreateWellTargetsPickEventHandler.cpp
=> Guard assert when picking in a zoomed scene

ApplicationLibCode/FileInterface/RifReaderEclipseOutput.cpp, ApplicationLibCode/FileInterface/RifReaderEclipseOutput.h, ApplicationLibCode/FileInterface/RifReaderInterface.cpp, ApplicationLibCode/FileInterface/RifReaderInterface.h, ApplicationLibCode/FileInterface/RifReaderOpmCommon.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCase.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCase.h
=> Import faults when using omp common file reader, too

ApplicationLibCode/UserInterface/RiuFemResultTextBuilder.cpp
=> #11198 Fix result info for POR-Bar normalized by hydrostatic pressure.

ApplicationLibCode/ProjectDataModel/Rim3dView.cpp
=> Show measurement in static geomech view, too

ApplicationLibCode/Commands/PolygonCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/PolygonCommands/RicDuplicatePolygonFeature.cpp, ApplicationLibCode/Commands/PolygonCommands/RicDuplicatePolygonFeature.h, ApplicationLibCode/Commands/PolygonCommands/RicExportPolygonCsvFeature.cpp, ApplicationLibCode/Commands/PolygonCommands/RicExportPolygonCsvFeature.h, ApplicationLibCode/Commands/PolygonCommands/RicExportPolygonPolFeature.cpp, ApplicationLibCode/Commands/PolygonCommands/RicExportPolygonPolFeature.h, ApplicationLibCode/Commands/PolygonCommands/RicImportPolygonFileFeature.cpp, ApplicationLibCode/Commands/PolygonCommands/RicSimplifyPolygonFeature.cpp, ApplicationLibCode/Commands/PolygonCommands/RicSimplifyPolygonFeature.h, ApplicationLibCode/FileInterface/RifCsvDataTableFormatter.cpp, ApplicationLibCode/FileInterface/RifCsvDataTableFormatter.h, ApplicationLibCode/FileInterface/RifTextDataTableFormatter.cpp, ApplicationLibCode/FileInterface/RifTextDataTableFormatter.h, ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.cpp, ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygon.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygon.h, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonCollection.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonCollection.h, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonInView.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonInView.h, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonInViewCollection.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonTools.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonTools.h
=> Export and duplication of polygons

ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.cpp, ApplicationLibCode/ProjectDataModel/Intersections/RimExtrudedCurveIntersection.h, ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionCollection.cpp, ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionCollection.h, ApplicationLibCode/ProjectDataModel/RimEclipseResultCase.cpp, ApplicationLibCode/ProjectDataModel/RimSimWellInViewCollection.cpp
=> Remove caching of simulation well coordinates to avoid state handling bugs

ApplicationLibCode/FileInterface/RifInpExportTools.cpp, ResInsightVersion.cmake
=> Fault Reactivation: improve node coordinate accuracy

ApplicationLibCode/FileInterface/RifFaultReactivationModelExporter.cpp, ApplicationLibCode/FileInterface/RifJsonEncodeDecode.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModel.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModel.h, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.cpp, ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.h
=> Exported coordinate fix

ApplicationLibCode/ReservoirDataModel/Completions/RigEclipseToStimPlanCellTransmissibilityCalculator.cpp, ApplicationLibCode/ReservoirDataModel/Completions/RigFractureTransmissibilityEquations.cpp
=> Handle nan transmissibility

ApplicationExeCode/RiaGrpcConsoleApplication.cpp, ApplicationLibCode/Commands/CellFilterCommands/RicNewPolygonFilterFeature.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygon.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygon.h, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonCollection.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonCollection.h, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonFile.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonInView.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonInViewCollection.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonInViewCollection.h
Closes #11273 
Closes #11274 
Fixes issues with reload of polygon files
Fixes some crashes
=> Polygon updates

ApplicationLibCode/ProjectDataModel/RimDataSourceSteppingTools.cpp, ApplicationLibCode/ProjectDataModel/RimSummaryCalculationCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp, ResInsightVersion.cmake
- Make sure to rebuild meta data when a calculation expression has been updated.
- Fix source stepping for calculated vectors.
=> Fix summary plotting issues

ApplicationLibCode/Application/RiaSummaryDefines.cpp, ApplicationLibCode/Application/RiaSummaryDefines.h, ApplicationLibCode/Application/Tools/RiaStdStringTools.cpp, ApplicationLibCode/Application/Tools/RiaStdStringTools.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveFilter.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveFilter.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveFilterCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp, ApplicationLibCode/UnitTests/RiaStdStringTools-Test.cpp, ApplicationLibCode/UserInterface/RiuTextContentFrame.cpp, ApplicationLibCode/UserInterface/RiuTextContentFrame.h
=> Improve realization number filtering for ensembles

.github/workflows/ResInsightWithCache.yml
https://gitlab.kitware.com/cmake/cmake/-/issues/25873
=> Pin CMake to 3.28.x due to build issues with 3.29

ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.cpp, ApplicationLibCode/ReservoirDataModel/RigCellGeometryTools.cpp, ApplicationLibCode/ReservoirDataModel/RigCellGeometryTools.h
=> Allow polygon line filter with only one point

ApplicationLibCode/Application/Tools/RiaProjectBackupTools.cpp, ApplicationLibCode/Application/Tools/RiaProjectBackupTools.h, ApplicationLibCode/ProjectDataModel/RimProject.cpp, CMakeLists.txt, ThirdParty/extract-projectfile-versions/.clang-format, ThirdParty/extract-projectfile-versions/CMakeLists.txt, ThirdParty/extract-projectfile-versions/main.cpp
=> Tool used to extract project file revisions from project file database

ApplicationLibCode/ProjectDataModel/RimSummaryCalculation.cpp, ApplicationLibCode/ProjectDataModel/RimSummaryCalculation.h
=> Fix calculation between multiple cases

ApplicationLibCode/ResultStatisticsCache/RigStatisticsDataCache.cpp
=> Guard overwrite of already calculated statistics values

ApplicationLibCode/Commands/RicImportObservedDataFeature.cpp, ApplicationLibCode/FileInterface/RifCsvUserDataParser.cpp, ApplicationLibCode/FileInterface/RifCsvUserDataParser.h
=> Propagate detected date format to line based parsing

GrpcInterface/Python/rips/instance.py
Search for resinsight_executable in JSON-file located at ./share/rips/rips_config.json
=> #11463 Look for resinsight_executable in JSON

ApplicationLibCode/Application/RiaApplication.cpp, ApplicationLibCode/Application/Tools/CMakeLists_files.cmake, ApplicationLibCode/Application/Tools/RiaProjectFileTools.cpp, ApplicationLibCode/Application/Tools/RiaProjectFileTools.h, ApplicationLibCode/Commands/ExportCommands/RicExportSelectedWellPathsFeature.cpp, ApplicationLibCode/ProjectDataModel/Annotations/RimAnnotationCollection.cpp, ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionCollection.cpp, ApplicationLibCode/ProjectDataModel/RimProject.cpp, ApplicationLibCode/ProjectDataModel/RimProject.h, ApplicationLibCode/ProjectDataModel/VerticalFlowPerformance/RimVfpPlot.cpp, ApplicationLibCode/UnitTests/CMakeLists.txt, ApplicationLibCode/UnitTests/RiaProjectFileTools-Test.cpp, ApplicationLibCode/UnitTests/RimRelocatePath-Test.cpp, Fwk/AppFwk/cafProjectDataModel/cafPdmDocument.cpp, Fwk/AppFwk/cafProjectDataModel/cafPdmDocument.h, Fwk/AppFwk/cafProjectDataModel/cafProjectDataModel_UnitTests/cafPdmBasicTest.cpp, Fwk/AppFwk/cafTests/cafTestApplication/MainWindow.cpp
=> Make sure file paths are valid before calling initAfterRead

ApplicationLibCode/Commands/RicCreateTemporaryLgrFeature.cpp, ApplicationLibCode/ProjectDataModel/RimGridView.h
A missing update caused the regression test TestCase_Create_Lgr_For_Completions  to fail due to missing visibility of temporary LGRs.
=> Temporary LGR: Make sure the view is updated based on new LGRs

ApplicationLibCode/Commands/RicNewContourMapViewFeature.cpp, ApplicationLibCode/ModelVisualization/Faults/RivFaultPartMgr.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultInViewCollection.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultInViewCollection.h, ApplicationLibCode/ProjectDataModel/RimEclipseContourMapView.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseContourMapView.h
=> Fix issue with missing fault visualization

ApplicationLibCode/Commands/ApplicationCommands/RicShowPlotDataFeature.cpp, ApplicationLibCode/ProjectDataModel/RimPlotAxisProperties.cpp, ApplicationLibCode/ProjectDataModel/RimPlotAxisProperties.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotAxisFormatter.cpp, ApplicationLibCode/ProjectDataModel/Tools/RimPlotAxisTools.cpp, ApplicationLibCode/ProjectDataModel/Tools/RimPlotAxisTools.h, ApplicationLibCode/ProjectDataModel/VerticalFlowPerformance/RimCustomVfpPlot.cpp, ApplicationLibCode/ProjectDataModel/VerticalFlowPerformance/RimCustomVfpPlot.h, ApplicationLibCode/ProjectDataModel/VerticalFlowPerformance/RimVfpDefines.cpp, ApplicationLibCode/ProjectDataModel/VerticalFlowPerformance/RimVfpPlotCollection.cpp, ApplicationLibCode/ReservoirDataModel/RigVfpTables.cpp, ApplicationLibCode/ReservoirDataModel/RigVfpTables.h, ApplicationLibCode/UserInterface/RiuMainWindow.cpp, ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp, Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafInternalPdmValueFieldSpecializations.h, Fwk/AppFwk/cafProjectDataModel/cafPdmXml/cafPdmXml_UnitTests/cafPdmXmlNumberTest.cpp
=> VFP: Allow multiselection of all available variables

ApplicationLibCode/Commands/OsduImportCommands/RiaOsduConnector.cpp, ApplicationLibCode/Commands/OsduImportCommands/RiaOsduConnector.h, ApplicationLibCode/Commands/OsduImportCommands/RicWellPathsImportOsduFeature.cpp, ApplicationLibCode/Commands/OsduImportCommands/RiuWellImportWizard.cpp, ApplicationLibCode/Commands/OsduImportCommands/RiuWellImportWizard.h
=> 11498 osdu well multiselect

ApplicationLibCode/ProjectDataModel/WellLog/Rim3dWellLogFileCurve.cpp, ApplicationLibCode/ProjectDataModel/WellLog/Rim3dWellLogFileCurve.h, ApplicationLibCode/ProjectDataModel/WellLog/RimOsduWellLog.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLog.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLog.h, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogChannel.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCsvFile.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogLasFile.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogLasFileCurve.cpp, ApplicationLibCode/ProjectDataModel/WellPath/RimWellPath.cpp
=> 11497 osdu 3d well logs

ApplicationLibCode/Commands/OsduImportCommands/RiuWellImportWizard.cpp, ApplicationLibCode/Commands/OsduImportCommands/RiuWellImportWizard.h
=> #11496 OSDU well path import: add sorting and filter of wells.

ApplicationLibCode/Commands/OsduImportCommands/RiaOsduConnector.cpp, ApplicationLibCode/Commands/OsduImportCommands/RiaOsduConnector.h, ApplicationLibCode/Commands/OsduImportCommands/RicWellPathsImportOsduFeature.cpp, ApplicationLibCode/Commands/OsduImportCommands/RiuWellImportWizard.cpp, ApplicationLibCode/Commands/OsduImportCommands/RiuWellImportWizard.h, ApplicationLibCode/FileInterface/RifOsduWellPathReader.cpp, ApplicationLibCode/FileInterface/RifOsduWellPathReader.h, ApplicationLibCode/ProjectDataModel/WellPath/RimOsduWellPath.cpp, ApplicationLibCode/ProjectDataModel/WellPath/RimOsduWellPath.h, ApplicationLibCode/ProjectDataModel/WellPath/RimWellPathCollection.cpp, ApplicationLibCode/ProjectDataModel/WellPath/RimWellPathCollection.h
=> #11514 OSDU: parse and add datum elevation to well paths.

ApplicationLibCode/ProjectDataModel/Rim2dIntersectionView.cpp, ApplicationLibCode/ProjectDataModel/Rim2dIntersectionView.h, ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp, ApplicationLibCode/UserInterface/RiuViewerCommands.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTextEditor.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTextEditor.h, ResInsightVersion.cmake
Closes #11515
Closes #11516
Closes #11522
=> Minor UI improvements

ApplicationLibCode/FileInterface/RifReaderOpmCommon.cpp, ApplicationLibCode/FileInterface/RifReaderOpmCommon.h
Fixes failing regression tests
Preparing for reading only active cell grid information
Closes #11520 
Closes #11074
=> opm_common reader updates

ApplicationLibCode/FileInterface/RifStimPlanModelDeviationFrkExporter.cpp, ApplicationLibCode/FileInterface/RifStimPlanModelDeviationFrkExporter.h
=> #11556 StimPlan Model: export deviation with less precision.

ApplicationLibCode/Commands/SurfaceCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/SurfaceCommands/RicNewDepthSurfaceFeature.cpp, ApplicationLibCode/Commands/SurfaceCommands/RicNewDepthSurfaceFeature.h, ApplicationLibCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlotRegressionCurve.cpp, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp, ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp, ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp, ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelTemplate.cpp, ApplicationLibCode/ProjectDataModel/Surfaces/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/Surfaces/RimDepthSurface.cpp, ApplicationLibCode/ProjectDataModel/Surfaces/RimDepthSurface.h, ApplicationLibCode/ProjectDataModel/Surfaces/RimSurface.h, ApplicationLibCode/ProjectDataModel/Surfaces/RimSurfaceCollection.cpp, ApplicationLibCode/ProjectDataModel/Surfaces/RimSurfaceCollection.h, Fwk/AppFwk/cafUserInterface/cafPdmUiDoubleValueEditor.h
=> Add depth plane to surfaces

ApplicationLibCode/Application/Tools/RiaStdStringTools.cpp, ApplicationLibCode/Application/Tools/RiaStdStringTools.h, ApplicationLibCode/FileInterface/RifEclipseUserDataParserTools.cpp, ApplicationLibCode/FileInterface/RifKeywordVectorParser.cpp, ApplicationLibCode/FileInterface/RifOpmCommonSummary.cpp, ApplicationLibCode/FileInterface/RifOpmHdf5Summary.cpp, ApplicationLibCode/GeoMech/GeoMechFileInterface/RifInpReader.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonAppearance.cpp, ApplicationLibCode/UnitTests/RiaStdStringTools-Test.cpp
=> Janitor tasks

ThirdParty/Ert/lib/ecl/well_state.cpp
=> Support skipping invalid IWEL records without shutting down ResInsight

GrpcInterface/Python/dev-requirements.txt
Fixed vulnerability in the pip dependencies: `GrpcInterface/Python/dev-requirements.txt`
=> Vulnerability Fix

.github/dependabot.yml
Add configuration file for `Dependabot` used to create PR when selected submodules are updated.
=> Add configuration for Dependabot

ApplicationLibCode/Commands/CellFilterCommands/RicNewPolygonFilterFeature.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.h, ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygon.cpp, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
=> Improve user experience for polygon filters

GrpcInterface/Python/rips/instance.py
=> Python: By default, use port number assigned by GRPC

ApplicationLibCode/ModelVisualization/RivContourMapProjectionPartMgr.cpp
=> Fix regression test crash

ApplicationLibCode/Application/RiaApplication.cpp, ApplicationLibCode/Application/RiaPreferencesOsdu.cpp, ApplicationLibCode/Application/RiaPreferencesOsdu.h, ApplicationLibCode/Application/RiaPreferencesSumo.cpp, ApplicationLibCode/Application/RiaPreferencesSumo.h, ApplicationLibCode/Application/Tools/Cloud/RiaCloudConnector.cpp, ApplicationLibCode/Application/Tools/Cloud/RiaConnectorTools.cpp, ApplicationLibCode/Application/Tools/Cloud/RiaConnectorTools.h
Check for `sumo_config.json` and `osdu_config.json.` If present, import settings to preferences and set fields read only.
=> Add optional import of SUMO/OSDU settings from JSON

ApplicationLibCode/Application/RiaApplication.cpp, ApplicationLibCode/ModelVisualization/RivWellSpheresPartMgr.cpp, ApplicationLibCode/ProjectDataModel/Faults/RimFaultInViewCollection.cpp, ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogLasFile.cpp, ApplicationLibCode/ProjectDataModel/WellPath/RimFileWellPathDataLoader.cpp, ApplicationLibCode/ProjectDataModel/WellPath/RimFileWellPathDataLoader.h, ResInsightVersion.cmake
Closes https://github.com/OPM/ResInsight/issues/11636
=> Regression test issues

ApplicationLibCode/Commands/OperationsUsingObjReferences/RicPasteEclipseViewsFeature.cpp
=> #11422  Grid Ensemble: Fix copy and paste of a view.

ApplicationLibCode/Application/RiaApplication.cpp, ApplicationLibCode/Application/RiaPreferences.cpp
=> Cloud data configuration file search order

ApplicationLibCode/Application/Tools/RiaRegressionTextTools.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicShowSummaryCurveCalculatorFeature.cpp, ApplicationLibCode/UserInterface/RiuResultQwtPlot.cpp
=> 11649 UI adjustments

ApplicationLibCode/Commands/CompletionExportCommands/RicExportFractureCompletionsImpl.cpp, ApplicationLibCode/Commands/CompletionExportCommands/RicWellPathExportMswCompletionsImpl.cpp, ApplicationLibCode/ProjectDataModel/Completions/RimFracture.cpp
=> Make sure non-Darcy data is computed before export of transmissibilities

GrpcInterface/Python/rips/instance.py
Related to https://github.com/equinor/everest-models/issues/46
=> Python: increase launch timeout.

ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.cpp
=> Don't skip loading data if one or more timesteps are missing.

ApplicationLibCode/FileInterface/RifEclipseInputFileTools.cpp, ApplicationLibCode/FileInterface/RifReaderInterface.cpp
Remove logging text causing noise, write out message only when PFLOTRAN file is found.
=> PFLOTRAN: Make parsing of faults more robust

ApplicationLibCode/UserInterface/RiuMainWindowBase.cpp, ApplicationLibCode/UserInterface/RiuMainWindowBase.h
=> Avoid storing dock layout if window never has been visible

ApplicationLibCode/Application/RiaPreferencesGrid.cpp, ApplicationLibCode/Application/RiaPreferencesGrid.h, ApplicationLibCode/FileInterface/RifEclipseInputFileTools.cpp, ApplicationLibCode/FileInterface/RifReaderEclipseOutput.cpp, ApplicationLibCode/FileInterface/RifReaderEclipseOutput.h, ApplicationLibCode/FileInterface/RifReaderInterface.cpp, ApplicationLibCode/FileInterface/RifReaderInterface.h, ApplicationLibCode/FileInterface/RifReaderOpmCommon.cpp, ApplicationLibCode/FileInterface/RifReaderOpmCommonActive.cpp, ApplicationLibCode/FileInterface/RifReaderSettings.h
=> Add option to skip/invalidate long, thin cells.

ApplicationLibCode/ProjectDataModel/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/Rim3dView.h, ApplicationLibCode/ProjectDataModel/RimCameraPosition.cpp, ApplicationLibCode/ProjectDataModel/RimCameraPosition.h, ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseView.h
=> Store camera position for each associated case

ApplicationLibCode/Commands/Sumo/RicCreateSumoEnsembleFeature.cpp, ApplicationLibCode/ProjectDataModel/Cloud/RimCloudDataSourceCollection.cpp, ApplicationLibCode/ProjectDataModel/Cloud/RimCloudDataSourceCollection.h, ApplicationLibCode/ProjectDataModel/Summary/Sumo/RimSummarySumoDataSource.cpp, ApplicationLibCode/ProjectDataModel/Summary/Sumo/RimSummarySumoDataSource.h, ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiLineEditor.cpp
=> UI adjustments for SUMO import

ApplicationLibCode/UserInterface/RiuRelativePermeabilityPlotPanel.cpp, ApplicationLibCode/UserInterface/RiuRelativePermeabilityPlotPanel.h
=> Make sure PC axis is visible when required

ApplicationLibCode/ProjectDataModel/RimEclipseContourMapView.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseContourMapView.h, ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseView.h
=> Update window title when required

ApplicationLibCode/Commands/CellFilterCommands/RicNewCellRangeFilterFeature.cpp, ApplicationLibCode/Commands/CellFilterCommands/RicNewPolygonFilterFeature.cpp, ApplicationLibCode/Commands/CellFilterCommands/RicNewRangeFilterSliceFeature.cpp, ApplicationLibCode/Commands/CellFilterCommands/RicNewRangeFilterSliceIFeature.cpp, ApplicationLibCode/Commands/CellFilterCommands/RicNewRangeFilterSliceJFeature.cpp, ApplicationLibCode/Commands/CellFilterCommands/RicNewRangeFilterSliceKFeature.cpp, ApplicationLibCode/Commands/CellFilterCommands/RicNewUserDefinedFilterFeature.cpp, ApplicationLibCode/Commands/CellFilterCommands/RicNewUserDefinedIndexFilterFeature.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygon.cpp, ApplicationLibCode/UserInterface/RiuViewerCommands.cpp
=> Reordering and improvements for grid right-click menu

ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionPartMgr.cpp, ApplicationLibCode/ModelVisualization/Intersections/RivExtrudedCurveIntersectionPartMgr.h, ApplicationLibCode/ProjectDataModel/Rim2dIntersectionView.cpp, ApplicationLibCode/ProjectDataModel/Rim2dIntersectionView.h, ApplicationLibCode/ProjectDataModel/Rim2dIntersectionViewCollection.cpp
=> 2d intersection view filter support

ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCrossPlotStatisticsCase.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatisticsCase.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatisticsCase.h
=> Summary: Improve robustness for statistics calculations

ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.cpp
Make sure that a polygon defined below the grid can be used to filter grid cells
Closes #11713
=> Polygon filter: Use a ray from point in polygon both up and down

ApplicationLibCode/UserInterface/RiuMohrsCirclePlot.cpp
=> Replace assert with a warning message

ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseView.h
=> Add enum to control zoom operation when case is changed

ApplicationLibCode/ProjectDataModel/Cloud/RimCloudDataSourceCollection.cpp
=> #11746 Simplify layout to silence warning from Qt5.

ApplicationLibCode/ProjectDataModel/RiaOpmParserTools.cpp
=> Add special parsing of SLAVES keyword as the default parsing fails

ApplicationLibCode/UserInterface/RiuFlowCharacteristicsPlot.cpp, ApplicationLibCode/UserInterface/RiuFlowCharacteristicsPlot.h, ApplicationLibCode/UserInterface/RiuResultQwtPlot.cpp, ApplicationLibCode/UserInterface/RiuResultQwtPlot.h, ApplicationLibCode/UserInterface/RiuSelectionChangedHandler.cpp
=> Show current time step in result plot

ApplicationLibCode/Commands/GeoMechCommands/RicRunFaultReactModelingFeature.cpp, ApplicationLibCode/Commands/GeoMechCommands/RicRunWellIntegrityAnalysisFeature.cpp, ApplicationLibCode/Commands/SeismicCommands/RicImportSeismicFeature.cpp, ApplicationLibCode/ProjectDataModel/ProcessControl/RimProcess.cpp, ApplicationLibCode/ProjectDataModel/ProcessControl/RimProcess.h
=> Make sure launching external processes works after switch to qt6

.github/workflows/ResInsightWithCache.yml, GrpcInterface/Python/build-requirements.txt, GrpcInterface/Python/setup.py.cmake
Merge main into dev after release of 2024.9.1
Includes changes to build related to conflicting Python requirements
=> Merge in latest changes from main

ApplicationLibCode/Application/RiaPlotWindowRedrawScheduler.cpp, ApplicationLibCode/Application/RiaPlotWindowRedrawScheduler.h, ApplicationLibCode/Application/RiaSummaryCurveDefinition.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForObjectsFeature.cpp, ApplicationLibCode/FileInterface/RifEclipseSummaryAddress.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressModifier.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressModifier.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
=> Handling of two levels in summary network address

ApplicationLibCode/Application/Tools/CMakeLists_files.cmake, ApplicationLibCode/Application/Tools/RiaCurveMerger.inl, ApplicationLibCode/Application/Tools/RiaHashTools.h, ApplicationLibCode/FileInterface/RifSummaryReaderInterface.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatisticsCase.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatisticsCase.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCase.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCase.h, ResInsightVersion.cmake
=> Improve performance for plotting of large summary ensembles

ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.cpp
=> Multi-segment RFT plot: Make sure reservoir pressure is plotted

CMakeLists.txt
=> Use FetchContent_MakeAvailable

ApplicationLibCode/ProjectDataModelCommands/RimcSummaryPlotCollection.cpp
=> Make sure plot create from Python is visible

ApplicationLibCode/Commands/ToolCommands/RicAddFieldToQuickAccessFeature.cpp, ApplicationLibCode/Commands/ToolCommands/RicAddFieldToQuickAccessFeature.h, ApplicationLibCode/ProjectDataModel/QuickAccess/RimFieldQuickAccessGroup.cpp, ApplicationLibCode/ProjectDataModel/QuickAccess/RimFieldReference.cpp, ApplicationLibCode/ProjectDataModel/QuickAccess/RimFieldReference.h
=> Quick Access adjustments

ApplicationLibCode/Application/RiaGuiApplication.cpp, ApplicationLibCode/Application/RiaPlotWindowRedrawScheduler.cpp, ApplicationLibCode/Application/RiaPlotWindowRedrawScheduler.h, ApplicationLibCode/Application/RiaScheduler.cpp, ApplicationLibCode/Application/RiaScheduler.h, ApplicationLibCode/Application/Tools/RiaImportEclipseCaseTools.cpp, ApplicationLibCode/Commands/ExportCommands/RicSnapshotViewToFileFeature.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForObjectsFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewMultiPhaseRftSegmentPlotFeature.cpp, ApplicationLibCode/Commands/WellLogCommands/RicNewRftSegmentWellLogPlotFeature.cpp, ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp
=> Fix initialization of OpenGL and redraw 3D views correctly

ApplicationLibCode/UserInterface/RiuDockWidgetTools.cpp
=> Use window icons to show toggle state in windows menu

ApplicationLibCode/Application/RiaPlotWindowRedrawScheduler.cpp, ApplicationLibCode/Application/RiaScheduler.cpp, ApplicationLibCode/Application/RiaScheduler.h, ApplicationLibCode/Application/RiaViewRedrawScheduler.cpp, ApplicationLibCode/Application/Tools/Summary/RiaSummaryTools.cpp, ApplicationLibCode/Commands/FlowCommands/RicPlotProductionRateFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorUi.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotFeatureImpl.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
=> Make sure the summary curve type (Rate/Accumulated) always is updated 

ApplicationLibCode/FileInterface/RifEclipseOutputFileTools.cpp
=> Do not assume that the first reported time step is initial time step

ApplicationLibCode/Commands/RicSummaryCaseRestartDialog.cpp, ApplicationLibCode/FileInterface/RifEclipseSummaryTools.cpp, ApplicationLibCode/FileInterface/RifEclipseSummaryTools.h, ApplicationLibCode/FileInterface/RifSummaryCaseRestartSelector.cpp, ApplicationLibCode/FileInterface/RifSummaryReaderMultipleFiles.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.cpp, ApplicationLibCode/UnitTests/RifReaderEclipseSummary-Test.cpp, ApplicationLibCode/UnitTests/opm-summary-Test.cpp
=> Performance when reading summary restart file name

ApplicationExeCode/RiaMain.cpp, ApplicationLibCode/UserInterface/RiuComparisonViewMover.cpp, ApplicationLibCode/UserInterface/RiuViewer.cpp, ApplicationLibCode/UserInterface/RiuViewer.h, Fwk/AppFwk/cafViewer/cafViewer.cpp, Fwk/AppFwk/cafViewer/cafViewer.h
Make sure opengl canvas is scaled correctly with DPI scaling different from 100%
Closes #11745
=> OpenGL DPI scaling support

ApplicationLibCode/Application/Tools/RiaCurveMerger.h, ApplicationLibCode/Application/Tools/Summary/RiaSummaryTools.cpp, ApplicationLibCode/Application/Tools/Summary/RiaSummaryTools.h, ApplicationLibCode/FileInterface/RifReaderEnsembleStatisticsRft.cpp, ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.cpp, ApplicationLibCode/ProjectDataModel/RimSummaryCalculation.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimDeltaSummaryCase.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimDeltaSummaryCase.h, ApplicationLibCode/ProjectDataModel/Summary/RimDeltaSummaryEnsemble.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimDeltaSummaryEnsemble.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatistics.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatistics.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatisticsCase.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryEnsemble.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryEnsemble.h, ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogStatistics.cpp, ApplicationLibCode/UnitTests/RigTimeCurveHistoryMerger-Test.cpp
This pull request includes several changes to the `ApplicationLibCode` project, focusing on improving the handling of incomplete or missing realizations in summary calculations and enhancing the `RimDeltaSummaryCase` class functionality. 
The most important changes include the introduction of a new method to calculate time thresholds, updates to the handling of incomplete curves, and modifications to the `RimDeltaSummaryCase` and `RimDeltaSummaryEnsemble` classes.
=> Improve delta curves

ApplicationLibCode/FileInterface/RifReaderOpmRft.cpp, ApplicationLibCode/FileInterface/RifReaderOpmRft.h, ApplicationLibCode/ReservoirDataModel/ResultCalculators/RigSoilResultCalculator.cpp
If no SOIL is found on file, compute based on available SWAT and SGAS.
Closes #11895
=> #11895 Always show Oil Saturation as available

ApplicationLibCode/Application/RiaPreferencesGrid.cpp, ApplicationLibCode/FileInterface/RifEclipseOutputFileTools.cpp, ApplicationLibCode/FileInterface/RifReaderOpmCommon.cpp, ApplicationLibCode/FileInterface/RifReaderOpmCommon.h, ApplicationLibCode/ProjectDataModel/RimEclipseResultCase.cpp
=> Support multiple timesteps per day using opm_common reader

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTable.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTable.h, ApplicationLibCode/UserInterface/RiuMatrixPlotWidget.cpp
=> Summary Table: Add user option to set time range on x-axis

ApplicationLibCode/Commands/FractureCommands/RicCreateMultipleFracturesFeature.cpp, ApplicationLibCode/Commands/FractureCommands/RicNewWellPathFractureFeature.cpp, ApplicationLibCode/ProjectDataModel/Completions/RimWellPathFractureCollection.cpp, ApplicationLibCode/ProjectDataModel/Completions/RimWellPathFractureCollection.h
=> Make sure the Fractures folder in view is visible when required

ApplicationLibCode/ModelVisualization/RivReservoirViewPartMgr.cpp, ApplicationLibCode/ReservoirDataModel/RigActiveCellGrid.cpp, ApplicationLibCode/ReservoirDataModel/RigActiveCellGrid.h
=> Make sure we only loop over active grids local cells when calculating visibility

ApplicationLibCode/Commands/SummaryPlotCommands/RicPasteAsciiDataToSummaryPlotFeature.cpp, ApplicationLibCode/ProjectDataModel/RimPlotCurve.cpp, ApplicationLibCode/ProjectDataModel/RimPlotCurve.h, ApplicationLibCode/ProjectDataModel/Summary/RimAsciiDataCurve.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimAsciiDataCurve.h
=> Summary Plot: Missing legend curve name for Excel data

ApplicationLibCode/ProjectDataModel/Completions/RimMswCompletionParameters.cpp, ApplicationLibCode/ProjectDataModel/Completions/RimWellPathCompletionSettings.cpp, ApplicationLibCode/ProjectDataModelCommands/RimcWellPath.cpp, ApplicationLibCode/ProjectDataModelCommands/RimcWellPath.h, GrpcInterface/Python/rips/tests/test_create_well_path.py
=> Python: Make more well completion parameters available

ApplicationLibCode/UserInterface/RiuRelativePermeabilityPlotPanel.cpp, ApplicationLibCode/UserInterface/RiuRelativePermeabilityPlotPanel.h
=> Support showing both scaled and unscaled curves in relperm plot

ApplicationLibCode/Application/RiaApplication.cpp, ApplicationLibCode/Application/RiaConsoleApplication.cpp, ApplicationLibCode/Application/RiaGuiApplication.cpp, ApplicationLibCode/Application/RiaPreferences.cpp, ApplicationLibCode/Application/RiaPreferences.h, ApplicationLibCode/Application/Tools/Cloud/RiaConnectorTools.cpp, ApplicationLibCode/Application/Tools/Cloud/RiaConnectorTools.h
=> Cloud Config: Show the full path to config file for cloud services

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
=> Fix visibility control of curve legends

ApplicationLibCode/Application/Tools/RiaStdStringTools.cpp, ApplicationLibCode/Commands/RicRecursiveFileSearchDialog.cpp, ApplicationLibCode/Commands/RicRecursiveFileSearchDialog.h, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterIntervalTool.cpp, ApplicationLibCode/UnitTests/RiaStdStringTools-Test.cpp
=> Improve ensemble file import dialog

ApplicationLibCode/Commands/EclipseCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/EclipseCommands/RicAddLinkedEclipsePropertyFilterFeature.cpp, ApplicationLibCode/Commands/EclipseCommands/RicAddLinkedEclipsePropertyFilterFeature.h, ApplicationLibCode/Commands/GeoMechCommands/RicGeoMechPropertyFilterFeatureImpl.cpp, ApplicationLibCode/GeoMech/GeoMechVisualization/RivFemElmVisibilityCalculator.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimEclipsePropertyFilter.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimEclipsePropertyFilter.h, ApplicationLibCode/ProjectDataModel/CellFilters/RimEclipsePropertyFilterCollection.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimEclipsePropertyFilterCollection.h, ApplicationLibCode/ProjectDataModel/CellFilters/RimGeoMechPropertyFilter.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimGeoMechPropertyFilter.h, ApplicationLibCode/ProjectDataModel/CellFilters/RimGeoMechPropertyFilterCollection.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimGeoMechPropertyFilterCollection.h, ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechCase.cpp, ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechView.cpp, ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechView.h, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp
=> Allow property filter to be linked to cell result

ApplicationLibCode/Commands/RicNewWellTargetCandidatesGeneratorFeature.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCaseEnsemble.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCaseEnsemble.h, ApplicationLibCode/ProjectDataModel/RimProject.cpp, ApplicationLibCode/ProjectDataModel/RimRegularGridCase.cpp, ApplicationLibCode/ProjectDataModel/RimWellTargetCandidatesGenerator.cpp, ApplicationLibCode/ProjectDataModel/RimWellTargetCandidatesGenerator.h, ApplicationLibCode/ReservoirDataModel/Well/RigWellTargetCandidatesGenerator.cpp
=> 12005 move ensemble grid in project tree

ApplicationLibCode/FileInterface/RifReaderRegularGridModel.cpp, ApplicationLibCode/FileInterface/RifReaderRegularGridModel.h, ApplicationLibCode/ProjectDataModel/RimRegularGridCase.cpp, ApplicationLibCode/ProjectDataModel/RimRegularGridCase.h, ApplicationLibCode/ProjectDataModel/RimWellTargetCandidatesGenerator.cpp, ApplicationLibCode/ReservoirDataModel/Well/RigWellTargetCandidatesGenerator.cpp
=> Add caching of well target data

ApplicationLibCode/ReservoirDataModel/ResultCalculators/RigFaultDistanceResultCalculator.cpp, ApplicationLibCode/ReservoirDataModel/ResultCalculators/RigIndexIjkResultCalculator.cpp
=> Wrong calculation of INDEX_IJK

ApplicationLibCode/ProjectDataModel/RimContourMapProjection.cpp
=> Fix broken filters in contour maps

ApplicationLibCode/ProjectDataModel/CellFilters/RimEclipsePropertyFilter.cpp
=> Quick Access: Fix display of integer category values for filter

Fwk/AppFwk/CommonCode/cafEffectGenerator.cpp
=> Fix isEqual for TextureImage

ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechContourMapProjection.cpp, ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechContourMapProjection.h, ApplicationLibCode/ProjectDataModel/Intersections/RimIntersectionEnums.cpp, ApplicationLibCode/ProjectDataModel/RimContourMapProjection.cpp, ApplicationLibCode/ProjectDataModel/RimContourMapProjection.h, ApplicationLibCode/ProjectDataModel/RimEclipseContourMapProjection.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseContourMapProjection.h, ApplicationLibCode/ProjectDataModel/RimStatisticsContourMapProjection.cpp, ApplicationLibCode/ProjectDataModel/RimStatisticsContourMapProjection.h, ApplicationLibCode/ReservoirDataModel/RigContourMapProjection.cpp, ApplicationLibCode/ReservoirDataModel/RigContourMapProjection.h, ApplicationLibCode/ReservoirDataModel/RigContourMapTrianglesGenerator.cpp
=> Contour Map: Add optional value filtering

ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonInView.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCaseEnsemble.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCaseEnsemble.h, ApplicationLibCode/ProjectDataModel/RimProject.cpp, ApplicationLibCode/ProjectDataModel/RimStatisticsContourMap.cpp, ApplicationLibCode/ProjectDataModel/RimStatisticsContourMap.h, ApplicationLibCode/ProjectDataModel/RimStatisticsContourMapView.cpp, ApplicationLibCode/UserInterface/RiuViewerCommands.cpp
=> Enable polygons in contourmaps

ApplicationLibCode/UserInterface/RiuSummaryVectorSelectionUi.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeSelectionEditor.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiTreeSelectionEditor.h
=> When activating an item, also select the item

ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.cpp
=> Make sure filters are connected to geomech view on project reload

ApplicationLibCode/ProjectDataModel/RimStatisticsContourMap.cpp, ApplicationLibCode/ProjectDataModel/RimStatisticsContourMap.h
=> Ui adjustments based on feedback

ApplicationLibCode/Commands/RicNewContourMapViewFeature.cpp, ApplicationLibCode/ProjectDataModel/ContourMap/RimContourMapResolutionTools.cpp, ApplicationLibCode/ProjectDataModel/ContourMap/RimContourMapResolutionTools.h, ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechContourMapProjection.cpp, ApplicationLibCode/ProjectDataModel/RimContourMapProjection.cpp, ApplicationLibCode/ProjectDataModel/RimContourMapProjection.h, ApplicationLibCode/ProjectDataModel/RimEclipseContourMapProjection.cpp
=> Use resolution enum in contourmaps

ApplicationLibCode/Application/Tools/Cloud/RiaCloudConnector.cpp, ApplicationLibCode/Application/Tools/Cloud/RiaCloudConnector.h, ApplicationLibCode/Commands/OsduCommands/RiuWellImportWizard.cpp, ApplicationLibCode/ProjectDataModel/Cloud/RimCloudDataSourceCollection.cpp, ApplicationLibCode/ProjectDataModel/Cloud/RimCloudDataSourceCollection.h, ApplicationLibCode/ProjectDataModel/WellPath/RimWellPathCollection.cpp
=> Show dialog with cancel button when requesting authorization tokens

ApplicationLibCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlotDataSet.cpp, ApplicationLibCode/ReservoirDataModel/RigEclipseCrossPlotDataExtractor.cpp, ApplicationLibCode/ReservoirDataModel/RigEclipseCrossPlotDataExtractor.h
=> Fix wrong display of fracture values in grid cross plot

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.h
=> Add option to hide time labels on x axis

Fwk/AppFwk/cafPdmCvf/cafPdmMat3d/cafPdmUiCoreMat3d.h, Fwk/AppFwk/cafPdmCvf/cafPdmUiCoreColor3f.h, Fwk/AppFwk/cafPdmCvf/cafPdmUiCoreMat4d.h, Fwk/AppFwk/cafPdmCvf/cafPdmUiCoreVec3d.h, Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafAppEnum.h, Fwk/AppFwk/cafProjectDataModel/cafPdmObject.h, Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafInternalPdmFieldTypeSpecializations.h, Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafInternalPdmUiFieldCapability.inl, Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafPdmUiFieldSpecialization.h, Fwk/AppFwk/cafTests/cafTestApplication/ApplicationEnum.cpp, Fwk/AppFwk/cafTests/cafTestApplication/ApplicationEnum.h, Fwk/AppFwk/cafTests/cafTestApplication/CMakeLists.txt, Fwk/AppFwk/cafTests/cafTestApplication/MainWindow.cpp
=> Add static function to define a subset of enums to be used for AppEnum

ApplicationLibCode/ProjectDataModel/ContourMap/RimContourMapProjection.cpp, ApplicationLibCode/ProjectDataModel/ContourMap/RimContourMapResolutionTools.cpp, ApplicationLibCode/ProjectDataModel/ContourMap/RimStatisticsContourMap.cpp, ApplicationLibCode/ProjectDataModel/ContourMap/RimStatisticsContourMap.h, ApplicationLibCode/ProjectDataModel/ContourMap/RimStatisticsContourMapView.cpp
Adjust contour map resolution choices, too
=> Support missing timesteps in statistics ensemble cases

ApplicationLibCode/ProjectDataModel/ContourMap/RimStatisticsContourMap.cpp
=> Statistics Contour Map: Static results do not work

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveAppearanceCalculator.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveAppearanceCalculator.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryEnsembleTools.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryEnsembleTools.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h, ApplicationLibCode/UserInterface/RiuPlotAnnotationTool.cpp, ApplicationLibCode/UserInterface/RiuPlotCurve.h, ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp, ApplicationLibCode/UserInterface/RiuQwtCurvePointTracker.cpp, ApplicationLibCode/UserInterface/RiuQwtPlotCurveDefines.cpp, ApplicationLibCode/UserInterface/RiuQwtPlotCurveDefines.h, ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp, ApplicationLibCode/UserInterface/RiuQwtPlotWidget.h
=> Allow highlight of curves based on selection of realization object

ApplicationLibCode/Commands/PolygonCommands/CMakeLists_files.cmake, ApplicationLibCode/Commands/PolygonCommands/RicCreatePolygonFeature.cpp, ApplicationLibCode/Commands/PolygonCommands/RicDeleteAllPolygonsFeature.cpp, ApplicationLibCode/Commands/PolygonCommands/RicDeleteAllPolygonsFeature.h, ApplicationLibCode/Commands/PolygonCommands/RicDuplicatePolygonFeature.cpp, ApplicationLibCode/Commands/PolygonCommands/RicImportPolygonFileFeature.cpp, ApplicationLibCode/Commands/RicCreateContourMapPolygonAdvancedFeature.cpp, ApplicationLibCode/Commands/RicCreateContourMapPolygonFeature.cpp, ApplicationLibCode/Commands/RicCreateContourMapPolygonFeature.h, ApplicationLibCode/Commands/RicCreateContourMapPolygonTools.cpp, ApplicationLibCode/Commands/RicCreateContourMapPolygonTools.h, ApplicationLibCode/Commands/RicPolygonFromImageDialog.cpp, ApplicationLibCode/Commands/RicPolygonFromImageDialog.h, ApplicationLibCode/ProjectDataModel/Annotations/RimAnnotationCollection.cpp, ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.cpp, ApplicationLibCode/ProjectDataModel/ContourMap/RimContourMapProjection.cpp, ApplicationLibCode/ProjectDataModel/ContourMap/RimStatisticsContourMap.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonCollection.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonCollection.h, ApplicationLibCode/ProjectDataModel/RimTools.cpp, ApplicationLibCode/ReservoirDataModel/ContourMap/RigContourMapProjection.cpp, ApplicationLibCode/ReservoirDataModel/ContourMap/RigContourMapProjection.h, ApplicationLibCode/ReservoirDataModel/RigPolygonTools.cpp, ApplicationLibCode/ReservoirDataModel/RigPolygonTools.h
=> Create multiple polygons from a contour map

ApplicationLibCode/ModelVisualization/RivPipeGeometryGenerator.cpp
=> Remove assert when creating pipe geometry

ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechView.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp, ApplicationLibCode/ProjectDataModel/RimGridView.cpp, ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp
=> Fix interaction with 3D scene and mouse handling

ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp
=> Ongoing 3D interaction for picking points is not working

ApplicationLibCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlotDataSet.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCellColors.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCellColors.h, ApplicationLibCode/ProjectDataModel/RimEclipseResultDefinition.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseResultDefinition.h, ApplicationLibCode/ProjectDataModel/RimEclipseResultDefinitionTools.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseResultDefinitionTools.h, ApplicationLibCode/ReservoirDataModel/RigVisibleCategoriesCalculator.cpp, ApplicationLibCode/ReservoirDataModel/RigVisibleCategoriesCalculator.h
=> Grid Cross Plot: Avoid display of unused values in category legend

ApplicationExeCode/RiaMain.cpp, ApplicationExeCode/RiaMainTools.cpp, ApplicationExeCode/RiaMainTools.h, ApplicationLibCode/Application/RiaPreferences.cpp
=> Make IO of data for preferences more robust

Fwk/AppFwk/cafUserInterface/QMinimizePanel.cpp, Fwk/AppFwk/cafUserInterface/cafPdmUiFormLayoutObjectEditor.cpp
=> Update the UI layout when expanded state of group is changed

ApplicationLibCode/ModelVisualization/Surfaces/RivSurfacePartMgr.cpp, ApplicationLibCode/ModelVisualization/Surfaces/RivSurfacePartMgr.h, ApplicationLibCode/ProjectDataModel/Surfaces/RimFractureSurface.cpp, ApplicationLibCode/ProjectDataModel/Surfaces/RimFractureSurface.h, ApplicationLibCode/ProjectDataModel/Surfaces/RimSurface.cpp, ApplicationLibCode/ProjectDataModel/Surfaces/RimSurface.h, ApplicationLibCode/ProjectDataModel/Surfaces/RimSurfaceInView.cpp, ApplicationLibCode/ProjectDataModel/Surfaces/RimSurfaceInView.h, ApplicationLibCode/ProjectDataModel/Surfaces/RimSurfaceInViewCollection.cpp, ApplicationLibCode/ReservoirDataModel/RigTriangleMeshData.cpp, ApplicationLibCode/ReservoirDataModel/RigTriangleMeshData.h
=> 12211 fracture surface mesh lines

ApplicationLibCode/Application/Tools/Summary/RiaSummaryAddressAnalyzer.cpp, ApplicationLibCode/Application/Tools/Summary/RiaSummaryAddressAnalyzer.h, ApplicationLibCode/FileInterface/RifEclipseSummaryTools.cpp, ApplicationLibCode/FileInterface/RifEclipseSummaryTools.h, ApplicationLibCode/ProjectDataModel/RimDataSourceSteppingTools.cpp
=> Improve stepping on history vectors

ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.h, ApplicationLibCode/UserInterface/RiuDragDrop.cpp, ApplicationLibCode/UserInterface/RiuDragDrop.h
=> Summary Cases: Allow reordering of summary cases

ApplicationLibCode/Application/RiaApplication.cpp, ApplicationLibCode/Application/RiaApplication.h, ApplicationLibCode/Application/RiaConsoleApplication.cpp, ApplicationLibCode/Application/RiaGuiApplication.cpp, ApplicationLibCode/Application/RiaPreferences.cpp, ApplicationLibCode/Application/RiaPreferences.h, ApplicationLibCode/Application/Tools/RiaArgumentParser.cpp, ApplicationLibCode/Commands/ExportCommands/RicSnapshotAllViewsToFileFeature.cpp, ApplicationLibCode/Commands/ExportCommands/RicSnapshotFilenameGenerator.cpp
=> Add import/export of preference values to text file

ApplicationLibCode/ModelVisualization/RivReservoirViewPartMgr.cpp
=> Make sure cell visibilities are initialized properly for all cells

ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp, ApplicationLibCode/UserInterface/RiuQwtPlotWidget.h
Reintroduce the distance criteria for selection of curves.
=> #12203 Improve selection of curves

Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmChildArrayField.inl, Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmCore_UnitTests/cafPdmChildArrayFieldHandleTest.cpp
=> Make sure signals are disconnected before objects are deleted

ApplicationLibCode/ModelVisualization/Surfaces/RivSurfacePartMgr.cpp, ApplicationLibCode/ProjectDataModel/Surfaces/RimFileSurface.cpp, ApplicationLibCode/ProjectDataModel/Surfaces/RimFractureSurface.cpp, ApplicationLibCode/ProjectDataModel/Surfaces/RimFractureSurface.h, ApplicationLibCode/ProjectDataModel/Surfaces/RimSurface.cpp, ApplicationLibCode/ProjectDataModel/Surfaces/RimSurface.h, ApplicationLibCode/ProjectDataModel/Surfaces/RimSurfaceInView.cpp, ApplicationLibCode/ReservoirDataModel/RigSurface.cpp, ApplicationLibCode/ReservoirDataModel/RigSurface.h, ApplicationLibCode/ReservoirDataModel/RigSurfaceStatisticsCalculator.cpp
=> Fracture surface fixes

ApplicationLibCode/Commands/EclipseCommands/RicCreateGridCaseEnsemblesFromFilesFeature.cpp, ApplicationLibCode/Commands/RicNewStatisticsContourMapFeature.cpp, ApplicationLibCode/ProjectDataModel/ContourMap/RimStatisticsContourMap.cpp, ApplicationLibCode/ProjectDataModel/Formations/RimFormationTools.cpp, ApplicationLibCode/ProjectDataModel/Formations/RimFormationTools.h, ApplicationLibCode/ProjectDataModel/RimEclipseCaseEnsemble.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseResultCase.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp
=> Ensemble contourmap updates

ApplicationLibCode/Application/RiaPreferencesSystem.cpp, ApplicationLibCode/Application/RiaPreferencesSystem.h, ApplicationLibCode/ReservoirDataModel/RigCellFaceGeometryTools.cpp, ApplicationLibCode/ReservoirDataModel/RigNNCData.cpp
=> Guard display of debug messages using keywords in Preferences

ApplicationLibCode/Application/Tools/RiaEnsembleNameTools.cpp, ApplicationLibCode/ProjectDataModel/RimPlotCurve.cpp, ApplicationLibCode/ProjectDataModel/RimPlotCurve.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryEnsembleTools.cpp
Closes #12299
Closes #12298
Improves performance related to ensemble summary curves.
=> Ensemble curve issues

ApplicationLibCode/Commands/EclipseCommands/RicCreateGridCaseEnsemblesFromFilesFeature.cpp, ApplicationLibCode/Commands/RicCreateContourMapPolygonTools.cpp, ApplicationLibCode/Commands/RicExportContourMapToTextFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicReplaceSummaryEnsembleFeature.cpp, ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimCorrelationMatrixPlot.cpp, ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimParameterResultCrossPlot.cpp, ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonInViewCollection.cpp, ApplicationLibCode/ProjectDataModel/RimCase.cpp, ApplicationLibCode/ProjectDataModel/RimCaseCollection.cpp, ApplicationLibCode/ProjectDataModel/RimCaseCollection.h, ApplicationLibCode/ProjectDataModel/RimEclipseCaseEnsemble.cpp, ApplicationLibCode/ProjectDataModel/RimProject.cpp, ApplicationLibCode/UserInterface/RiuMainWindow.cpp, ApplicationLibCode/UserInterface/RiuMessagePanel.cpp, ApplicationLibCode/UserInterface/RiuMessagePanel.h, ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp
=> Several minor adjustments

ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
=> #12297 Improve right-click menu on grid case model.

ApplicationLibCode/Commands/RicImportEnsembleFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicReplaceSummaryEnsembleFeature.cpp, ApplicationLibCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlot.cpp, ApplicationLibCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlotDataSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp, ApplicationLibCode/UserInterface/RiuCategoryLegendFrame.cpp
=> Show full name for single summary case

ApplicationLibCode/Application/Tools/Summary/RiaSummaryTools.cpp, ApplicationLibCode/Application/Tools/Summary/RiaSummaryTools.h, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryCurvesForObjectsFeature.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryCurvesForSummaryAddressesFeature.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryCurvesForSummaryCasesFeature.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryCurvesForSummaryCasesFeature.h, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForObjectsFeature.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForSummaryAddressesFeature.cpp, ApplicationLibCode/Commands/PlotBuilderCommands/RicAppendSummaryPlotsForSummaryCasesFeature.cpp, ApplicationLibCode/Commands/RicCloseSummaryCaseFeature.cpp, ApplicationLibCode/Commands/RicDeleteSummaryCaseCollectionFeature.cpp, ApplicationLibCode/Commands/RicReloadSummaryCaseFeature.cpp, ApplicationLibCode/Commands/RicReplaceCaseFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicPasteSummaryMultiPlotFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicReplaceSummaryCaseFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicReplaceSummaryEnsembleFeature.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellPlotTools.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellPlotTools.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.h, ApplicationLibCode/ProjectDataModel/RimReloadCaseTools.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatistics.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimRftCase.cpp, ApplicationLibCode/ProjectDataModel/Summary/Sumo/RimSummaryEnsembleSumo.cpp, ApplicationLibCode/ProjectDataModel/Tools/RimPlotAxisTools.cpp, ApplicationLibCode/UserInterface/RiuDockWidgetTools.cpp, ApplicationLibCode/UserInterface/RiuDockWidgetTools.h, ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp, Fwk/AppFwk/cafProjectDataModel/cafPdmCore/CMakeLists.txt, Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmObjectHandleTools.h
=> Summary plot and RFT plot adjustments

ApplicationLibCode/Application/RiaPreferencesSystem.cpp, ApplicationLibCode/FileInterface/RifReaderOpmCommon.cpp, ApplicationLibCode/FileInterface/RifReaderOpmCommonActive.cpp, ApplicationLibCode/ProjectDataModel/ContourMap/RimContourMapProjection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/ReservoirDataModel/ContourMap/RigContourMapCalculator.cpp, ApplicationLibCode/ReservoirDataModel/ContourMap/RigContourMapCalculator.h
=> Small adjustments

ApplicationLibCode/Application/Tools/Summary/RiaSummaryAddressAnalyzer.cpp, ApplicationLibCode/FileInterface/RifEclipseSummaryTools.cpp, ApplicationLibCode/FileInterface/RifEclipseSummaryTools.h, ApplicationLibCode/ProjectDataModel/RimDataSourceSteppingTools.cpp, ApplicationLibCode/ProjectDataModel/RimDataSourceSteppingTools.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp
=> Improve summary stepping

ApplicationLibCode/Commands/CorrelationPlotCommands/RicCreateEnsembleFromFilteredCasesFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicNewEnsembleCurveFilterFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicNewSummaryEnsembleCurveSetFeature.cpp, ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveFilter.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveFilter.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveFilterCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressSelector.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressSelector.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/UserInterface/RiuPlotAnnotationTool.cpp, ApplicationLibCode/UserInterface/RiuSummaryPlot.cpp, ApplicationLibCode/UserInterface/RiuSummaryQwtPlot.cpp
=> Add filter based on summary value at timestep

ApplicationLibCode/ProjectDataModel/ContourMap/RimStatisticsContourMap.cpp, ApplicationLibCode/ProjectDataModel/ContourMap/RimStatisticsContourMap.h
=> Ensemble contourmap fix

ApplicationLibCode/Application/RiaPreferencesSystem.cpp, ApplicationLibCode/Application/Tools/RiaLogging.cpp, ApplicationLibCode/Application/Tools/RiaLogging.h, ApplicationLibCode/FileInterface/RifReaderOpmCommonActive.cpp, ApplicationLibCode/ReservoirDataModel/RigCellFaceGeometryTools.cpp, ApplicationLibCode/ReservoirDataModel/RigNNCData.cpp, ApplicationLibCode/ReservoirDataModel/Well/RigWellTargetMapping.cpp
=> Simplify interface for log messages

ApplicationLibCode/UserInterface/RiuMessagePanel.h
=> Make sure the clear all messages slot is defined as a slot.

ApplicationLibCode/Commands/CorrelationPlotCommands/RicCreateEnsembleFromFilteredCasesFeature.cpp, ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimParameterResultCrossPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryEnsembleTools.cpp
=> Correlation Parameter Filter: Make sure realizations are detected correctly

ApplicationLibCode/Commands/RicRecursiveFileSearchDialog.cpp
=> Fix ensemble import dialog

ApplicationLibCode/FileInterface/RifVtkSurfaceImporter.cpp, ApplicationLibCode/UnitTests/RifVtkSurfaceImporter-Test.cpp, ApplicationLibCode/UnitTests/TestData/RifVtkSurfaceImporter/fracture-00000.vtu
=> #12367 VTK surface import: handle NaN in vtu file.

.github/workflows/ResInsightWithCache.yml, CMakeUserPresets-example.json
=> Use default vcpkg triplet

ApplicationLibCode/FileInterface/RifEclipseSummaryTools.cpp, ApplicationLibCode/FileInterface/RifEclipseSummaryTools.h
=> Use Qt file operations to establish path to restart case

ApplicationLibCode/ProjectDataModel/RimWellTargetMapping.cpp
=> Use subscript for permability unit

ApplicationLibCode/Commands/RicSummaryCaseRestartDialog.cpp, ApplicationLibCode/FileInterface/RifEclipseSummaryTools.cpp
=> Read and display date for summary restart files

ApplicationLibCode/FileInterface/RifEclEclipseSummary.cpp, ApplicationLibCode/FileInterface/RifEclEclipseSummary.h, ApplicationLibCode/UnitTests/RifReaderEclipseSummary-Test.cpp
=> Support both single and double underscore as keyword divider

ApplicationLibCode/FileInterface/RifInputPropertyLoader.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseCase.cpp, ApplicationLibCode/ProjectDataModel/RimEclipseResultCase.cpp
=> #12419 Avoid assert during load of simulation case

ApplicationLibCode/ProjectDataModel/CellFilters/RimEclipsePropertyFilter.cpp
=> #12438 Fix crash on incomplete category result.

ApplicationLibCode/ProjectDataModel/Flow/RimWellRftEnsembleCurveSet.h, ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp
=> Recompute statistical curves in RFT plots on replace

ApplicationLibCode/Commands/CorrelationPlotCommands/RicCreateEnsembleFromFilteredCasesFeature.cpp, ApplicationLibCode/ProjectDataModel/Annotations/CMakeLists_files.cmake, ApplicationLibCode/ProjectDataModel/Annotations/RimTimeAxisAnnotation.cpp, ApplicationLibCode/ProjectDataModel/Annotations/RimTimeAxisAnnotation.h, ApplicationLibCode/ProjectDataModel/Annotations/RimTimeAxisAnnotationUpdater.cpp, ApplicationLibCode/ProjectDataModel/Annotations/RimTimeAxisAnnotationUpdater.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveFilter.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.h, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSetCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryDeclineCurve.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryDeclineCurve.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryRegressionAnalysisCurve.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryRegressionAnalysisCurve.h, ApplicationLibCode/UserInterface/RiuSummaryPlot.cpp
=> Improve management of time axis annotations and curve filters

ApplicationLibCode/Application/Tools/RiaOptionItemFactory.cpp, ApplicationLibCode/FileInterface/RifEclEclipseSummary.cpp, ApplicationLibCode/FileInterface/RifEclipseSummaryAddress.cpp, ApplicationLibCode/FileInterface/RifEclipseSummaryAddress.h, ApplicationLibCode/FileInterface/RifEclipseSummaryAddressDefines.cpp, ApplicationLibCode/FileInterface/RifEclipseSummaryAddressDefines.h, ApplicationLibCode/FileInterface/RifEclipseUserDataKeywordTools.cpp, ApplicationLibCode/FileInterface/RifReaderObservedData.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCrossPlotStatisticsCase.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatisticsCase.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddress.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddress.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveAutoName.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryRegressionAnalysisCurve.cpp, ApplicationLibCode/ProjectDataModel/Summary/Sumo/RimSummaryEnsembleSumo.cpp, ApplicationLibCode/UnitTests/RifEclipseSummaryAddress-Test.cpp, ApplicationLibCode/UserInterface/RiuSummaryVectorSelectionUi.cpp
=> Refactors ensemble statistics handling

ApplicationLibCode/Commands/RicReloadSummaryCaseFeature.cpp, ApplicationLibCode/Commands/SummaryPlotCommands/RicReplaceSummaryEnsembleFeature.cpp, ApplicationLibCode/ProjectDataModel/EnsembleFileSet/RimEnsembleFileSet.cpp, ApplicationLibCode/ProjectDataModel/EnsembleFileSet/RimEnsembleFileSet.h, ApplicationLibCode/ProjectDataModel/EnsembleFileSet/RimEnsembleFileSetCollection.cpp, ApplicationLibCode/ProjectDataModel/Summary/Ensemble/RimSummaryFileSetEnsemble.cpp, ApplicationLibCode/ProjectDataModel/Summary/Ensemble/RimSummaryFileSetEnsemble.h, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryEnsemble.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimSummaryEnsemble.h, ApplicationLibCode/UserInterface/RiuDockWidgetTools.cpp
Add support for use of '*'
Make sure Reload and Replace works as expected
Update RFT plot when summary data source changes
=> Adjustments for ensemble file sets

ApplicationLibCode/Commands/FlowCommands/RicSelectViewUI.cpp, ApplicationLibCode/Commands/RicSelectOrCreateViewFeatureImpl.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationOverTimePlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationPlot.cpp, ApplicationLibCode/ProjectDataModel/Flow/RimWellConnectivityTable.cpp, ApplicationLibCode/ReservoirDataModel/RigTofAccumulatedPhaseFractionsCalculator.cpp
Avoid crash when trying to use well allocation plot with an ensemble
=> Well allocation plot: Add nullptr guards 

ApplicationLibCode/ProjectDataModel/Summary/RimCalculatedSummaryCurveReader.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimCalculatedSummaryCurveReader.h, ApplicationLibCode/ProjectDataModel/Summary/RimCsvUserData.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.cpp, ApplicationLibCode/ProjectDataModel/Summary/RimObservedEclipseUserData.cpp
=> Avoid use of caf::PdmPointer in async delete of objects

GrpcInterface/Python/rips/PythonExamples/compute_avg_poro_for_region.py, GrpcInterface/RiaGrpcPropertiesService.cpp
=> #12542 Make sure case is open before accessing cell data
