OPM/ResInsight

- CMakeLists.txt
due to c++11 name mangling issues in boost::filesystem,
you cannot build a program with c++11 if boost was built for c++03.
workaround this by using boost's internal hack to do so,
disabling the exposure of c++11 scoped enums which is the cause
of the problems.
Motivation: Building on debian jessie.
refs: http://stackoverflow.com/questions/15634114/cant-link-program-using-boost-filesystem/17988317 and https://svn.boost.org/trac/boost/ticket/6779
> fixed: compilation issues with boost < 1.57

- ApplicationCode/Commands/CompletionCommands/RicNewFishbonesSubsFeature.cpp
- ApplicationCode/Commands/RicFlyToObjectFeature.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFishbonesCollection.cpp
- ApplicationCode/ProjectDataModel/Completions/RimFishbonesMultipleSubs.cpp
- Fwk/AppFwk/cafViewer/cafViewer.cpp
highlighted by building with gcc6.
opm ci-systems were recently bumped to debian 9.1, which included an update to gcc6. these trivial fixes are necessary to build.
> fixed: add missing cmath include statements

- ApplicationCode/FileInterface/RifEclipseRestartDataAccess.h
- ApplicationCode/FileInterface/RifEclipseUnifiedRestartFileAccess.h
The libecl library has been converted to *compile* with a C++ compiler; the process of making it into an actual C++ library is of course a long road. The well functionality is quite limited and seems like a reasonable and simple first step. 
This PR is a very very first step to enable that conversion. The `well_info.hpp` and `well_info.h` headers have been present side-by-side for some time, and this PR should be trivial.
> Use hpp header files when accessing well_info from libecl

- ApplicationCode/ReservoirDataModel/RigFlowDiagInterfaceTools.h
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLFluxCalc.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLFluxCalc.hpp
Recent developments have rendered this parameter unused.  Remove it to make API simpler.  The library now always loads arrays as if the caller requests end-point scaling behaviour and we defer effects of actual end-point scaling until client code queries the flux calculator at run time.
> ECLFluxCalc: Remove Unused 'useEPS' Constructor Parameter

- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLSaturationFunc.cpp
A simulation run might not activate all three phases.  We therefore must guard against querying the connate saturations of the missing phase.
This tentatively fixes #4075.
Pointy hat: Bard.Skaflestad@sintef.no
Thanks to: Magne Sjåstad
> Max 2P Sat-Sum: Don't Dereference Null Pointer

- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLSaturationFunc.cpp
This pull request captures the result set's availability of saturation function end-point scaling (EPS) data in a new data member
```C++
bool ECLSaturationFunc::Impl::haveEPSData_
```
We need this piece of information to identify whether a null `eps_` data member corresponds to missing EPS data or failure to form the backing EPS data object&mdash;for instance due to an allocation failure.  In the first case it is fine to output/display the unscaled curves while throwing an exception in the latter case is more appropriate.
This restores ResInsight's ability to show unscaled saturation function curves if the backing EPS data is not available in the result set's INIT file and (hopefully) reduces the frequency of the scary message
```
"Cannot Activate EPS without Backing Object"
``` …
> Don't Calculate Scaled Curves if EPS Data Unavailable

- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLPvtGas.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLPvtOil.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLPvtWater.cpp
This commit refines the error message emitted if a particular phase does not have a PVT interpolant&mdash;e.g., if the INIT file does not provide PVT data.  Previously we would generate a message akin to
```
Region Index 0 Outside Valid Range (0 .. (size_t)-1)
```
which is not very helpful to users in diagnosing the issue.  The new message does at least indicate that there is no interpolant for the accompanying phase and also emits the (1-based) region index for context.
> PVT Interpolants: Give More Meaningful Diagnostic if PVT Interpolant Missing

- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLGraph.cpp
- ThirdParty/custom-opm-flowdiag-app/opm-flowdiagnostics-applications/opm/utility/ECLGraph.hpp
This commit introduces a new static function
```C++
ECLGraph ECLGraph::load(const ecl_grid_type*, const ECLInitFileData&)
```
This is in order to simplify constructing the backing graph from ResInsight's .EGRID input--especially to have consistent view of a model's active cells irrespective of which simulator created the result set.
> Support Creating ECLGraph from "ecl_grid_type*"

- ApplicationCode/ProjectDataModel/Rim3dWellLogCurve.cpp
- ApplicationCode/ProjectDataModel/Rim3dWellLogCurve.h
- ApplicationCode/ProjectDataModel/Rim3dWellLogExtractionCurve.cpp
- ApplicationCode/ProjectDataModel/Rim3dWellLogFileCurve.cpp
- ApplicationCode/ProjectDataModel/Rim3dWellLogRftCurve.cpp
- ApplicationCode/ProjectDataModel/RimEclipseResultDefinition.cpp
- ApplicationCode/ProjectDataModel/RimGeoMechResultDefinition.cpp
I did not have time to test this extensively before holidays, so if we need it in a patch, it needs to be tested.
The idea is that we no longer need to call updateConnectedEditors on the parent object when changing a result definition, and for GeoMech it is actually harmful, because it will cause defineUiOrdering to be called twice and the second time will mess things up.
This causes issues for plots, property filters and 3d well log plots that uses GeoMech results, but not for the regular 3d-view because we don't explicitly update the connected editors there.
The change removes all explicit updateConnectedEditors on field change in GeoMech result definition.
> #4703 Fix changing result position in GeoMech result definition

- ApplicationCode/UserInterface/RiuPlotMainWindow.cpp
by blocking the selection of the plot when window is activated
> #4753 Fix selection of plot subitems jumps to parent plot

- ApplicationCode/Application/RiaGuiApplication.cpp
Use current working directory as base, and create a sub folder named "snapshots". Export snapshots from the application into this folder.
>  #4765 Summary : Support command line snapshots without a project file

- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlotAxisFormatter.cpp
* The issue is that the bottom axis is really a QwtDateScaleEngine as opposed to a QwtLinearScaleEngine.
* This may have worked before by "accident" before the changes to the date format on the date/time axis.
* The fix is that if we want a QwtLinearScaleEngine and have a QwtDateScaleEngine we replace the scale engine.
> #5234 Fix auto scale of cross plot x-axis

- ApplicationCode/ReservoirDataModel/RigGeoMechWellLogExtractor.cpp
* The field name was hardcoded as "SH" and compared to the name of the SH result-string, which isn't the same as the input parameter anymore
> #5524 Stop asking for an address with the field name "SH".

- .github/workflows/main.yml
- .gitmodules
- vcpkg_x64-linux.txt
- vcpkg_x64-windows.txt
Hi!
I would like to contribute to your CI system, in particular to the GitHub one. Here my proposed changes, I am open to feedback and any modification required:
-vcpkg is a submodule: useful to have full control over versioning of the dependencies;
-removed the commit id of vcpkg from the yaml file, as that is implicitly defined by the submodule;
-use run-cmake action for building both Linux and Windows;
-use vcpkg's response file installing dependencies; same is to be used on CI and locally by developers;
-changed Cache's key, based on packages installed and version of vpckg used, so that it is properly invalidated;
> CI proposed changes

- ApplicationCode/FileInterface/RifEclipseOutputFileTools.cpp
- ApplicationCode/FileInterface/RifEclipseOutputFileTools.h
- ApplicationCode/FileInterface/RifEclipseRestartDataAccess.h
- ApplicationCode/FileInterface/RifEclipseRestartFilesetAccess.cpp
- ApplicationCode/FileInterface/RifEclipseUnifiedRestartFileAccess.cpp
- ApplicationCode/FileInterface/RifEclipseUnifiedRestartFileAccess.h
- ApplicationCode/FileInterface/RifReaderEclipseOutput.cpp
- ApplicationCode/FileInterface/RifReaderEclipseOutput.h
- ApplicationCode/FileInterface/RifReaderInterface.h
- ApplicationCode/ReservoirDataModel/RigCaseCellResultsData.cpp
6X simulator can report multiple keywords per time step. These additional keywords do not contain any data possible to import into ResInsight, but must be used when accessing the correct result keyword based on index in file.
Closes #5763
> Incomplete import of Restart data from 6X

- ApplicationCode/ProjectDataModel/RimEclipseStatisticsCaseEvaluator.cpp
- ApplicationCode/ResultStatisticsCache/RigStatisticsMath.cpp
* We sent in percent values (0-100) instead of the fractional values (0 - 1) that RigHistogramCalculator::calculatePercentile required.
* It has been like this for years AFAICT.
>  #5905 Fix wrong percentile calculation

- ApplicationCode/ProjectDataModel/RimRegularLegendConfig.cpp
Projects containing Rim2dIntersectionViews copy legend config from the view using
PdmXmlObjectHandle::writeObjectToXmlString/readObjectFromXmlString. The
resulting xml contains references to RimColorLegendCollection which are unresolved,
and this would lead to a crash (m_colorLegend == nullptr). Fixed by resolving
the references explicitly after copy the config.
Closes #5979.
> #5979 Fix color legend crash when opening regression test project

- ApplicationCode/ProjectDataModel/RimWellLogTrack.cpp
The parent of RimWellLogTrack can also be a RimDepthTrackPlot.
> Fix crash in fracture model plot.

- .github/workflows/ResInsightWithCache.yml
The text arguments to the linker are now too largre causing MSVC to fail and exit. Use  Unity build to reduce the number of files.
> gha : Enable RESINSIGHT_ENABLE_UNITY_BUILD

- ApplicationCode/CMakeLists.txt
- ApplicationCode/GrpcInterface/Python/rips/__init__.py
- ApplicationCode/GrpcInterface/Python/rips/case.py
- ApplicationCode/GrpcInterface/Python/rips/contour_map.py
- ApplicationCode/GrpcInterface/Python/rips/grid.py
- ApplicationCode/GrpcInterface/Python/rips/gridcasegroup.py
- ApplicationCode/GrpcInterface/Python/rips/instance.py
- ApplicationCode/GrpcInterface/Python/rips/pdmobject.py
- ApplicationCode/GrpcInterface/Python/rips/plot.py
- ApplicationCode/GrpcInterface/Python/rips/project.py
- ApplicationCode/GrpcInterface/Python/rips/simulation_well.py
- ApplicationCode/GrpcInterface/Python/rips/view.py
- ApplicationCode/GrpcInterface/Python/rips/well_log_plot.py
- Fwk/AppFwk/cafPdmScripting/cafPdmPythonGenerator.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmObject.cpp
- docs/rips/project.py
* Change base PdmObject class name to PdmObjectBase to avoid name conflicts
* Make all import paths relative
* On my kit there's still some test failures and crashes with test_summary_case which appears unrelated and more to do with the automatic selection of options and import dialog.
> #6322 Fix Python 3.8 problems

- ApplicationCode/ProjectDataModel/RimRegularLegendConfig.cpp
- ApplicationCode/ProjectDataModel/RimRegularLegendConfig.h
- Fwk/AppFwk/cafVizExtensions/cafCategoryMapper.cpp
- Fwk/AppFwk/cafVizExtensions/cafCategoryMapper.h
Closes #5315 
If category values are specified for a subset of category values, show only specified categories and display other values as undefined gray.
> Category Cell Results: Use color legend values

- ApplicationCode/Application/RiaSummaryCurveDefinition.cpp
- ApplicationCode/Application/RiaSummaryCurveDefinition.h
- ApplicationCode/Commands/SummaryPlotCommands/RicNewDerivedEnsembleFeature.cpp
- ApplicationCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorUi.cpp
- ApplicationCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.cpp
- ApplicationCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.h
- ApplicationCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlotCollection.cpp
- ApplicationCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlotDataEntry.cpp
- ApplicationCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlotDataEntry.h
- ApplicationCode/ProjectDataModel/CorrelationPlots/RimAbstractCorrelationPlot.cpp
- ApplicationCode/ProjectDataModel/CorrelationPlots/RimAbstractCorrelationPlot.h
- ApplicationCode/ProjectDataModel/CorrelationPlots/RimCorrelationPlotCollection.cpp
- ApplicationCode/ProjectDataModel/RimSummaryCalculation.cpp
- ApplicationCode/ProjectDataModel/Summary/RimDerivedEnsembleCaseCollection.cpp
- ApplicationCode/ProjectDataModel/Summary/RimDerivedEnsembleCaseCollection.h
- ApplicationCode/ProjectDataModel/Summary/RimDerivedSummaryCase.cpp
- ApplicationCode/ProjectDataModel/Summary/RimDerivedSummaryCase.h
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCase.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCase.h
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCaseCollection.h
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCurve.h
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryPlotFilterTextCurveSetEditor.cpp
- ApplicationCode/UserInterface/RiuSummaryVectorSelectionDialog.cpp
- ApplicationCode/UserInterface/RiuSummaryVectorSelectionUi.cpp
* Split the RimSummaryCurveCollection::updateDerivedEnsembleCases into to methods, one that creates new derived ensemble cases and one that updates existing ones. The latter one is called when closing a case.
* Store the m_inUse-flag of the derived cases as an actual field so it gets stored and loaded in projects otherwise closed cases gets reset after save/load.
* Also always store the ensemble in the RiaSummaryCurveDefinition, but use a boolean to say if it should be treated as an individual case. Otherwise we lose information that requires much more connections in the code to restore.
* Add a signal when closing a case which we can monitor in Analysis and Correlation plots.
> #6479 Update analysis and correlation plots are updated when closing derived cases

- ApplicationCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.cpp
- ApplicationCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.h
- ApplicationCode/ProjectDataModel/AnalysisPlots/RimPlotDataFilterCollection.cpp
- ApplicationCode/ProjectDataModel/CorrelationPlots/RimAbstractCorrelationPlot.cpp
- ApplicationCode/ProjectDataModel/CorrelationPlots/RimAbstractCorrelationPlot.h
- ApplicationCode/ProjectDataModel/RimViewWindow.cpp
- ApplicationCode/ProjectDataModel/RimWellLogExtractionCurve.cpp
- ApplicationCode/ProjectDataModel/RimWellLogExtractionCurve.h
- ApplicationCode/ProjectDataModel/RimWellLogTrack.cpp
- ApplicationCode/ProjectDataModel/RimWellLogTrack.h
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
- ApplicationCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmObjectHandle.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmObjectHandle.h
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafSignal.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafSignal.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewEditor.h
* Remove the DeleteSignal and instead use a list of emitted and observed signals in the Emitter and Observer respectively.
* This enables us to perform disconnections automatically when an object is removed from a field and avoid disconnections in application code.
> Refactor signals

- ApplicationCode/ReservoirDataModel/RigWellPathGeometryExporter.cpp
- ApplicationCode/UnitTests/CMakeLists_files.cmake
- ApplicationCode/UnitTests/RigWellPathGeometryExporter-Test.cpp
The change in measured depth (MD) must be greater or equal to change in
true vertical depth (TVD), and this was not always the case due to
interpolation imprecision. Fixed by adjusting TVD.
Closes #6526.
> #6526 Fracture Model: Make TVD/MD values consistent in Deviation.FRK

- ApplicationCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.cpp
- ApplicationCode/ProjectDataModel/AnalysisPlots/RimPlotDataFilterItem.cpp
- ApplicationCode/ProjectDataModel/AnalysisPlots/RimPlotDataFilterItem.h
* The concept doesn't make sense.
* A range of -1 to +1 becomes +1 to +1 (empty range)
* A range of -0.5 to +1.0 becomes +0.5 to +1.0 excluding all values from +0.0 to +0.5.
> #6543 Remove option for absolute value filters.

- CMakeLists.txt
* This should not hurt anywhere but may fix MacOS build issues
> #6472 Use CMake's CMAKE_CXX_STANDARD flag to require C++11

- ApplicationCode/Resources/themes/default.qss
- ApplicationCode/UserInterface/RiuGuiTheme.cpp
Stylesheet parser in RiuGuiTheme can now parse QPalette::$QColorRole[::$QColorGroup] and uses the application's default QPalette for color replacements.
Adjusted default style sheet accordingly to use QPalette::Base color as QwtPlots' background color.
This closes #6601.
> Stylesheet parser in RiuGuiTheme can now parse QPalette

- ApplicationCode/Resources/themes/dark.qss
It's hard to see where menus are ending due to the shadow colour being hard to see on the black background. Added a border around the menu to improve the visibility.
> Added border around QMenu.

- ApplicationCode/ProjectDataModel/RimFaciesProperties.cpp
- ApplicationCode/ProjectDataModel/RimRegularLegendConfig.cpp
- ApplicationCode/ProjectDataModel/RimTools.cpp
- ApplicationCode/ProjectDataModel/RimTools.h
- ApplicationCode/ProjectDataModel/RimWellLogTrack.cpp
Move the generation of the options list to RimTools to avoid duplication.
This introduces color legend icons in RimWellLogTrack.
Closes #6649
> #6649 Use color legend icon in drop down list.

- ApplicationCode/Resources/themes/dark.qss
QMdiSubWindows could not be rescaled anymore and the frame looked weird. These commits fix that behaviour.
> Dark theme subwindow issues

- ApplicationCode/Commands/CompletionExportCommands/RicWellPathExportCompletionDataFeatureImpl.cpp
When loading result data required for completion calculations, the results usually are located in STATIC_NATIVE. If data is imported from GRDECL file, the PERM, PORO, etc will be located in "Input Property". This commit will search for data of all types, in priority given by RigCaseCellResultsData::findOrLoadKnownScalarResult()
Closes #6727
> Completion Export : Search all result types

- ApplicationCode/UserInterface/RiuDockWidgetTools.cpp
- ApplicationCode/UserInterface/RiuDockWidgetTools.h
- ApplicationCode/UserInterface/RiuMainWindow.cpp
- ApplicationCode/UserInterface/RiuMainWindow.h
Closes #6743 
High CPU usage is triggered when some dock widgets containing a Qwt widget are hidden below other widgets in a tabbed state. This PR will force the rendering of relperm/pvt plots at least once, and then restore the window configuration specified by the user. The drawback is a slight flicking of windows when ResInsight starts.
> Dock Widgets : Workaround for high CPU usage 

- ApplicationCode/UserInterface/CMakeLists_files.cmake
Currently we get a MOC-warning because there is nothing to MOC in the header. Plus it doesn't show up in Visual Studio.
> Move RiuQssSyntaxHighlighter.h from MOC-headers to regular headers

- .github/workflows/ResInsightWithCache.yml
- .github/workflows/centos7.yml
- .gitmodules
This change will most probably work once the GitHub actions have also been altered to use ThirdParty/vcpkg
Merge after release
This also upgrades to VCPKG 2020.07
> Moved VCPKG into ThirdParty

- ApplicationCode/Application/RiaStimPlanModelDefines.cpp
- ApplicationCode/Application/RiaStimPlanModelDefines.h
- ApplicationCode/Commands/CompletionCommands/RicNewStimPlanModelPlotFeature.cpp
- ApplicationCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
- ApplicationCode/ProjectDataModel/StimPlanModel/RimStimPlanModelElasticPropertyCalculator.cpp
- ApplicationCode/ProjectDataModel/StimPlanModel/RimStimPlanModelWellLogCalculator.cpp
The elastic properties are already scaled by net-to-gross. Scaling the porosity
by net-to-gross before looking up the properties was applying the scaling twice.
Closes #6938.
> #6938 Use unscaled porosity for elastic property lookup.

- .github/workflows/ResInsightWithCache.yml
Replace use of add-path 
Output from gha
The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> dev : Update ResInsightWithCache.yml

- ThirdParty/custom-opm-common/opm-common/src/opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
- ThirdParty/custom-opm-common/opm-common/src/opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.cpp
- ThirdParty/custom-opm-common/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp
- ThirdParty/custom-opm-common/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParams.cpp
Include `<cctype>` to bring declarations of `std::toupper()` &c into scope.  With this patch the application builds and runs on VS 15 (2017) using MSVC 19.16.27044 on Windows 10 1909.
> Patch OPM-Common To Support VS 15 (2017)

- ApplicationCode/UserInterface/RiuViewer.cpp
The state of caf::Viewer::isComparisonViewActive() and Rim3dView::activeComparisonView()
can be out-of-sync until all events have been processed by the Qt event loop.
The caf::Viewer state is updated as part of an scheduled display update, but the
update to Rim3dView is a direct call.
Fix crash by checking for nullptr from Rim3dView::activeComparisonView().
Closes #7024.
> #7024 Fix crash when closing comparison view on linux.

- ApplicationCode/FileInterface/RifStimPlanModelGeologicalFrkExporter.cpp
- ApplicationCode/FileInterface/RifStimPlanModelGeologicalFrkExporter.h
- ApplicationCode/ProjectDataModel/StimPlanModel/RimStimPlanModelElasticPropertyCalculator.cpp
- ApplicationCode/ReservoirDataModel/RigElasticProperties.cpp
- ApplicationCode/ReservoirDataModel/RigElasticProperties.h
This can happen when the elastic properties are not defined for the
entire range of porosity in the grid.
Closes #7072.
> #7072 Warn when geological frk export produces NaN or inf.

- ApplicationCode/ReservoirDataModel/RigHistogramData.cpp
Introduced in 7120b9ad7e727c0d9c38f8aa3b6cf6bd940fadd9.
Closes #7144.
> #7144 Fix "QwtLinearScaleEngine::divideScale: overflow" warning.

- ApplicationLibCode/ProjectDataModel/RimDepthTrackPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimWellBoreStabilityPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimWellBoreStabilityPlot.h
- ApplicationLibCode/ProjectDataModel/RimWellLogTrack.cpp
- ApplicationLibCode/ProjectDataModel/RimWellLogTrack.h
- ApplicationLibCode/ReservoirDataModel/RigGeoMechWellLogExtractor.cpp
- ApplicationLibCode/ReservoirDataModel/RigGeoMechWellLogExtractor.h
The first intersection between the well path and the GeoMech model
is the correct water depth only when well path starts outside the model.
Top of the bounding box is used as an estimated water depth when
there is no intersection. WBS curves are now disabled for this case.
Closes #7158.
> #7158 Fix water depth calculation for WBS plot.

- ApplicationCode/GrpcInterface/Python/rips/PythonExamples/launch_load_case_snapshot_exit.py
- ApplicationCode/GrpcInterface/Python/rips/PythonExamples/load_case.py
- ApplicationCode/GrpcInterface/Python/rips/PythonExamples/open_project.py
- CMakeLists.txt
Add another example and optionally copy test models in the install stage. This ensures that the test models are present and the example can be run without changing paths
> Minor improvements patch

- ApplicationLibCode/ProjectDataModel/RimEclipseContourMapView.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseView.h
Split RimEclipseView::updateVisibleGeometriesAndCellColors() into two methods,
and make sure the visible geometries are recreated before updating the legends.
Closes #7207.
> #7207 Fix flow diagnostics cell color when property filtering.

- ApplicationLibCode/Application/RiaGuiApplication.cpp
Occasionally QGuiApplication::lastWindowClosed() signal could be sent
more than once.
Closes #7283.
> #7283 Fix crash on exit on centos 7.

- Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafPdmUiCommandSystemProxy.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafPdmUiCommandSystemProxy.h
Improvement of #7347 
When using toggle buttons in tree view, the current field changed might be outside of the current selection. Only apply multiple field changed if current field is part of the current selection.
> Property Editor : Check if current field is part of selection

- ThirdParty/Ert/lib/ecl/ecl_smspec.cpp
Use NaN instead of -99 to indicate no data present
Closes #7065
> WBHP for historic period reported as -99 in some cases 

- ApplicationLibCode/ProjectDataModel/RimEclipseContourMapProjection.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseStatisticsCaseEvaluator.cpp
- ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.cpp
- ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.h
ResInsight assumes that loading of data is done for all time steps at a time. Special handling of data loading is required for statistics calculations. Make statistical class a friend to be able to do this operation.
> Janitor : Hide loading of date for one time step from public API

- Fwk/AppFwk/CommonCode/cafVecIjk.h
> Fixes issue #7623: ‘size_t’ does not name a type

- ApplicationLibCode/Commands/CMakeLists.txt
- ApplicationLibCode/Commands/FlowCommands/RicPlotProductionRateFeature.cpp
- ApplicationLibCode/Commands/RicSummaryCaseRestartDialog.cpp
- ApplicationLibCode/Commands/RicSummaryCaseRestartDialog.h
- ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorDialog.cpp
- ApplicationLibCode/Commands/SummaryPlotCommands/RicSummaryPlotEditorUi.cpp
- ApplicationLibCode/FileInterface/CMakeLists_files.cmake
- ApplicationLibCode/FileInterface/RifEclEclipseSummary.cpp
- ApplicationLibCode/FileInterface/RifEclEclipseSummary.h
- ApplicationLibCode/FileInterface/RifEclipseSummaryTools.cpp
- ApplicationLibCode/FileInterface/RifEclipseSummaryTools.h
- ApplicationLibCode/FileInterface/RifReaderEclipseSummary.cpp
- ApplicationLibCode/FileInterface/RifSummaryCaseRestartSelector.cpp
- ApplicationLibCode/FileInterface/RifSummaryReaderMultipleFiles.cpp
- ApplicationLibCode/FileInterface/RifSummaryReaderMultipleFiles.h
- ApplicationLibCode/ProjectDataModel/Summary/RimAsciiDataCurve.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSetCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.h
- ApplicationLibCode/ProjectDataModel/Summary/RimGridSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimGridSummaryCase.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveCollection.cpp
- ApplicationLibCode/UnitTests/HDF5FileWriter-Test.cpp
- ApplicationLibCode/UnitTests/RifReaderEclipseSummary-Test.cpp
- ApplicationLibCode/UnitTests/RifSummaryDataReader-Test.cpp
- add a summary reader able to work with multiple summary files
- remove support for reading of complete history in low level summary importers
- make sure HDF5 creation/import works as expected in this setting
Closes #7622
> Add a summary file reader able to manage multiple restart history files

- ApplicationLibCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlotDataSet.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseCellColors.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseCellColors.h
Restore default color legend to "Continuous Logarithmic" instead of "Discrete Logarithmic" 
Closes #7647
> PERM and other arrays default colour legend type change

- .github/workflows/ResInsightWithCache.yml
Ubuntu using clang is created to make sure the clang compiler works. The artifact name is identical and break the build if two processes upload at the same time.
This commit will disable upload of artifact for Ubuntu clang build
> GHA : Skip upload of duplicate artifacts

- ApplicationLibCode/Application/RiaDefines.cpp
- ApplicationLibCode/Application/RiaDefines.h
- ApplicationLibCode/Application/Tools/RiaEclipseUnitTools.cpp
- ApplicationLibCode/Application/Tools/RiaEclipseUnitTools.h
- ApplicationLibCode/Commands/RicWellLogTools.cpp
- ApplicationLibCode/ModelVisualization/RivReservoirViewPartMgr.cpp
- ApplicationLibCode/ProjectDataModel/Flow/RimWellPltPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimExtrudedCurveIntersection.cpp
- ApplicationLibCode/ProjectDataModel/RimExtrudedCurveIntersection.h
- ApplicationLibCode/ProjectDataModel/RimWellLogCurve.cpp
- ApplicationLibCode/ProjectDataModel/RimWellLogCurve.h
- ApplicationLibCode/ProjectDataModel/RimWellLogRftCurve.cpp
- ApplicationLibCode/ReservoirDataModel/RigWellLogCurveData.cpp
- ApplicationLibCode/ReservoirDataModel/RigWellLogCurveData.h
Eclipse reports parent cell to LGR cells as active, and this property has been tested for in code.
Intersect reports inactive cell in the parent grid cell. Then we have to only check the active state of the LGR cell, not the parent cell.
Closes #3693
Closes #7765
> #3693 Intersect : Use active state of LGR to define visibility

- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafAppEnum.h
If the AppEnum text used to serialize the AppEnum contains whitespace at start or end, the serialization will fail and the AppEnum value will end up with a default value. 
This commit will make sure that this field is always trimmed ( text coming from the application, from xml parsing, text from scripting).
Closes #7829 
Closes #7825
> AppEnum : Make sure text used in XML serialization is trimmed 

- GrpcInterface/Python/rips/instance.py
The location variable was not defined when creating the error message
for version mismatch between rips and application.
Fixes #7842.
> #7842 Python: fix undefined variable on version mismatch.

- ApplicationLibCode/Commands/WellPathCommands/RicLinkWellPathFeature.cpp
Need to handle that wellpaths imported from file could exist.
If there is a mix of imported and modeled well paths, the code might have to do more than the existing fix does?
> Protect against crash in 3d view due to nullptr in linkwellpathfeature command check

- ApplicationLibCode/GeoMech/OdbReader/CMakeLists.txt
This enables ResInsight to read abaqus 2020 odb files (and only version 2020, as there only can be one version at a time)
You need the abaqus odb 2020 libraries to build ResInsight with odb/geomech support.
Closes #7798
Closes #6886
> ODB 2020: Update libraries list for linking

- CMakeLists.txt
- cmake/AutoVcpkg.cmake
This fixes #7915.
Copy Vcpkg bootstrap file from the cmake subfolder and include the Vcpkg toolchain file at a point where it exists.
> Autovcpkg repair

- ApplicationLibCode/Application/RiaPreferences.cpp
The freeze bug in Qt is triggered when the progress bar is displayed for long-running processes. A temporary workaround for freeze issues is to disable the progress bar. Move the setting into General tab to make it easily available for all users.
> #7957 Move progressdialog control to General tab

- ThirdParty/custom-opm-common/opm-common/src/opm/io/eclipse/EclUtil.cpp
> Include <cctype> for std::isdigit

- .github/workflows/centos7.yml
For some unknown reason, gcc9 does not work on this configuration. Reverting back to gcc7
This reverts commit 72dcc46e2795cf0e172e1954f178e40464e1e8ae.
> Revert "Use devtoolset-9 on CentOS 7"

- ApplicationLibCode/FileInterface/RifHdf5Reader.cpp
- ApplicationLibCode/FileInterface/RifHdf5SummaryReader.cpp
Some regression tests cause exceptions to trigger based on the HDF5 data present in test dataset. This causes the regression test to hang.
> Janitor : Move disable exception print before any HDF5 operations

- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimEnsembleFractureStatistics.h
For property Beta, low values are high (max, P10) case and high values are
low (min, P90) case. Calculation of statistical Beta values now uses
inverted logic.
Fixes #8232.
> #8232 Ensemble Fracture Statistics: Swap min/max and P90/P10 for Beta

- GrpcInterface/Python/rips/PythonExamples/set_grid_properties.py
- GrpcInterface/Python/rips/case.py
- GrpcInterface/Python/rips/grid.py
- GrpcInterface/Python/rips/tests/test_grids.py
- GrpcInterface/RiaGrpcPropertiesService.cpp
Avoid resize if data is already present
Improve functions for getting grid data and accessing single cell values
Add example for read and write of grid data
Closes #8297
> Python : Do not modify result container when reading grid result data

- ApplicationLibCode/UserInterface/AnalysisPlots/RiuGroupedBarChartBuilder.h
- ThirdParty/custom-opm-common/opm-common/opm/io/eclipse/SummaryNode.hpp
Note: this PR depends on #8329 which should be merged first.
Fixes issue #8330.
> Add missing limits header in RiuGroupedBarChartBuilder.h

- ApplicationLibCode/ReservoirDataModel/RigCellFaceGeometryTools.cpp
- ApplicationLibCode/ReservoirDataModel/RigFault.cpp
- ApplicationLibCode/ReservoirDataModel/RigFault.h
- ApplicationLibCode/ReservoirDataModel/RigNncConnection.cpp
- GrpcInterface/Python/rips/tests/test_nnc_properties.py
Closes #8371
Make sure that the first cell in RigConnection is assigned the lowest cell index. Assign the opposite face if the cell indexes are swapped.
In RigCellFaceGeometryTools, test both combinations of (cellA, cellB) and (cellB, cellA)
> Make sure all NNC faces are created and assigned

- Fwk/VizFwk/LibCore/cvfArray.inl
The c++ standard guarantees that "this" is nonnull in valid programs.
So this check is unneccessary, and gcc warns in debug mode.
> Janitor: remove assert(this) warnings.

- CMakeLists.txt
CMake is set to import submodules by default but fast_float was missing
from the list.
This fixes #8525
> CMake: Add fast_float to list of submodules to init

- ApplicationLibCode/Commands/SummaryPlotCommands/RicNewPlotAxisPropertiesFeature.cpp
- ApplicationLibCode/ProjectDataModel/RimPlotAxisProperties.cpp
- ApplicationLibCode/ProjectDataModel/RimPlotAxisProperties.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiFormLayoutObjectEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiFormLayoutObjectEditor.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeViewEditor.h
- Allow axis property signals to be connected multiple times, as the previous commit did not work when creating summary plot interactively
- More memory cleanup
- Make sure the two default axes are not able to delete or move to opposite side.
> Fix axis property signals and memory cleanup

- ApplicationLibCode/Commands/ExportCommands/RicSnapshotViewToFileFeature.cpp
Crash seen on Windows related to theme change as part of export to PDF. This is related to export of plots to PDF in dark mode. Investigate other solution.
> Pdf export : Remove theme change before export to PDF

- ApplicationLibCode/Application/Tools/RiaStdStringTools.cpp
- ApplicationLibCode/Application/Tools/RiaStdStringTools.h
- ApplicationLibCode/FileInterface/RifSurfaceImporter.cpp
- ApplicationLibCode/UnitTests/RiaStdStringTools-Test.cpp
The file had DOS line endings (\t\n) which where not properly trimmed on linux.
Fixes #8652.
> #8652 Import Surface: Fix ts-file import with properties on Linux

- ApplicationLibCode/FileInterface/RifEclipseTextFileReader.cpp
- ApplicationLibCode/UnitTests/RifEclipseTextFileReader-Test.cpp
Keywords without data does not have a trailing '/'.
Fixes #2434 (again).
> #2434 Eclipse input property: fix import for keywords without data

- ApplicationLibCode/Application/RiaRftDefines.h
- ApplicationLibCode/Application/Tools/RiaSummaryTools.cpp
- ApplicationLibCode/Application/Tools/RiaSummaryTools.h
- ApplicationLibCode/Commands/PlotTemplateCommands/RicSelectCaseOrEnsembleUi.cpp
- ApplicationLibCode/Commands/RicWellLogTools.cpp
- ApplicationLibCode/FileInterface/RifReaderOpmRft.cpp
- ApplicationLibCode/FileInterface/RifReaderOpmRft.h
- ApplicationLibCode/FileInterface/RifRftSegment.cpp
- ApplicationLibCode/FileInterface/RifRftSegment.h
- ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCurveCommonDataSource.h
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogTrack.h
- Make sure start MD is at correct position
- Use summary case as data source for RFT data
- Well Log Plot: Invert data range 
- Add some more space to default depth zoom range
- When plotting RFT segment data, use time steps where segment data is available
- RFT-data: Show Plot data multiplies pressure data in table #8898
- Create categories for branches(tubing, annular, device) Set tubing if length is longer than 1.0
- Show tubing branches in drop down list
Closes #9046 
Closes #9051
Closes #8898
> More RFT fixes

- CMakeLists.txt
Set CMake version on top level to avoid warnings on MSVC when warning level is set to something else than the default.
https://stackoverflow.com/questions/58708772/cmake-project-in-visual-studio-gives-flag-override-warnings-command-line-warnin
> Set minimum CMake version to 3.15 to avoid warnings on MSVC

- ApplicationLibCode/UserInterface/RiuQwtPlotCurve.cpp
Fixes #9131.
Fixed by drawing the line with Qt::NoPen (invisible).
> #9131 Summary Plot: Show area fill also when line style is 'None'.

- ApplicationLibCode/Commands/CompletionCommands/RicNewStimPlanModelPlotFeature.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelPlot.cpp
- ApplicationLibCode/UserInterface/RiuWellLogTrack.cpp
- update project tree after plot is generated
- set default text tracker orientation to vertical
- call base class fieldChangedByUi to handle hiding of Stimplan plot
Closes #9357
> StimPlanModelPlot: Plot visibility and logic updates

- Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafPdmUiFieldHandle.cpp
This avoids reassigning "valueString" and also, incidentally, fixes the build using Visual Studio 2017.
> Ignore Non-True Value Strings

- ApplicationLibCode/ProjectDataModel/RiaOpmParserTools.cpp
- CMakeLists.txt
- ThirdParty/custom-opm-common/custom-opm-parser-tests/TestData/mysubfolder/test_wseglink_subfolder.DATA
- ThirdParty/custom-opm-common/custom-opm-parser-tests/opm-parser-BasicTest.cpp
Add PATHS to supported keywords to be able to use include files with alias in file path.
> Opm Parser: Include PATHS when importing WSEGLINK

- ApplicationLibCode/Commands/OperationsUsingObjReferences/RicPasteEclipseViewsFeature.cpp
- ApplicationLibCode/Commands/RicNewContourMapViewFeature.cpp
- ApplicationLibCode/Commands/ViewLink/RicDeleteAllLinkedViewsFeature.cpp
- ApplicationLibCode/Commands/ViewLink/RicLinkViewFeature.cpp
- ApplicationLibCode/Commands/ViewLink/RicLinkVisibleViewsFeature.cpp
- ApplicationLibCode/Commands/ViewLink/RicLinkVisibleViewsFeature.h
- ApplicationLibCode/Commands/ViewLink/RicLinkVisibleViewsFeatureUi.cpp
- ApplicationLibCode/Commands/ViewLink/RicShowAllLinkedViewsFeature.cpp
- ApplicationLibCode/Commands/ViewLink/RicUnLinkViewFeature.cpp
- ApplicationLibCode/ModelVisualization/RivContourMapProjectionPartMgr.cpp
- ApplicationLibCode/ProjectDataModel/Rim3dView.cpp
- ApplicationLibCode/ProjectDataModel/Rim3dView.h
- ApplicationLibCode/ProjectDataModel/RimEclipseContourMapView.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseContourMapView.h
- ApplicationLibCode/ProjectDataModel/RimProject.cpp
- ApplicationLibCode/ProjectDataModel/RimViewController.cpp
- ApplicationLibCode/ProjectDataModel/RimViewController.h
- ApplicationLibCode/ProjectDataModel/RimViewLinker.cpp
- ApplicationLibCode/ProjectDataModel/RimViewLinker.h
- ApplicationLibCode/UserInterface/RiuViewerCommands.cpp
Closes #8632
Allow linking of a contour map and a 3D view. If the 3D view is primary view, the contour map can be rotated in 3D. When the contour map is unlinked, use `Zoom All` to reset the contour map to the default settings.
> Allow linking of contour map views

- ApplicationLibCode/Commands/EclipseCommands/RicEclipsePropertyFilterFeatureImpl.cpp
- ApplicationLibCode/Commands/EclipseCommands/RicEclipsePropertyFilterInsertExec.cpp
- ApplicationLibCode/Commands/EclipseCommands/RicEclipsePropertyFilterNewExec.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimEclipsePropertyFilter.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimEclipsePropertyFilter.h
- ApplicationLibCode/ProjectDataModel/CellFilters/RimEclipsePropertyFilterCollection.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimEclipsePropertyFilterCollection.h
- ApplicationLibCode/ProjectDataModel/CellFilters/RimPropertyFilterCollection.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimPropertyFilterCollection.h
- ApplicationLibCode/ProjectDataModel/RimEclipseCase.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseView.cpp
- ApplicationLibCode/ProjectDataModel/RimViewController.cpp
- ApplicationLibCode/ProjectDataModel/RimViewController.h
- ApplicationLibCode/ProjectDataModel/RimViewLinker.cpp
- ApplicationLibCode/ProjectDataModel/RimViewLinker.h
When a property filter is linked across grid model cases, the property filters must be duplicated and applied to each case individually.
Related to #9487
> Support copy of property filters to linked views

- ApplicationLibCode/Commands/EclipseCommands/RicImportEclipseCaseFeature.cpp
- ApplicationLibCode/Commands/RicImportGeneralDataFeature.cpp
- ApplicationLibCode/Commands/RicWellLogTools.cpp
- ApplicationLibCode/Commands/WellLogCommands/RicNewMultiPhaseRftSegmentPlotFeature.cpp
- ApplicationLibCode/Commands/WellLogCommands/RicNewRftSegmentWellLogPlotFeature.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.cpp
- ApplicationLibCode/UserInterface/RiuMainWindow.cpp
- ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp
Show RFT tree node only when RFT file is present
Guard null pointer use for RFT data
Avoid opening of 3D view when importing summary data
Use specific grid import feature instead of general import feature
Closes #9551
> Adjustments to UI

- ApplicationLibCode/ReservoirDataModel/RigMainGrid.cpp
Do not use buildCellSearchTreeOptimized() when when cellCountPerBB is 1, as the performance in this case is best using buildCellSearchTree()
> OpenMP: Use default AABB tree construction for one cell per BB

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
Set auto name to false to be able to use the stored name in project files.
> Ensemble: Disable auto name for old projects

- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
This will make sure existing regression tests produce the same file name
> Regression Test: If only one frame is present, skip adding postfix

- ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp
QwtPlotShapeItem objects were not reset, giving highlight bug in RimCorrelationMatrixPlot
> Fix bug in QwtPlotWidget highlight reset

- ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationOverTimeCollection.cpp
Using `.contains()` followed by `.at()` with the same argument will perform the same map lookup twice.
The `.contains()` member function is most appropriate when we make decisions based on the presence/absence of an element.  If we additionally need the actual element, then `.find()` is typically the better tool.
> Look Up Time Step Object Exactly Once

- ApplicationLibCode/FileInterface/RifActiveCellsReader.cpp
- ApplicationLibCode/FileInterface/RifActiveCellsReader.h
- ApplicationLibCode/FileInterface/RifReaderEclipseOutput.cpp
- ApplicationLibCode/UnitTests/RifActiveCellsReader-Test.cpp
Some models do not have the dual porosity flag set correctly. Add additional check to set the dual porosity flag if the number of active cells is the double of main grid cell count.
> #9833: Add extra check based on value/cell count

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.h
- ApplicationLibCode/UserInterface/RiuPlotWidget.h
- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.cpp
- ApplicationLibCode/UserInterface/RiuQtChartsPlotWidget.h
- ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp
- ApplicationLibCode/UserInterface/RiuQwtPlotWidget.h
- Add custom tickmark configuration in time axis properties
- Refactor code to separate handling of time axis properties and regular axis properties in RimSummaryPlot
- Add method for setting major ticks by use of list for RiuPlotWidget interface.
---
Closes: #9790
> Add custom tickmark configuration for Summary Plot

- ApplicationLibCode/ProjectDataModel/RimProject.cpp
When starting resinsight from a working folder, the project file paths can be relative to this folder (current working folder). If files are referenced relative to current working folder, the file references can start with either '..' or '.'  Make sure that these paths are left unchanged.
Closes #10002
> Do not replace '.' with the current project path

- Fwk/AppFwk/cafPdmScripting/cafPdmScripting_UnitTests/cafPdmScriptingBasicTest.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmObject.h
- Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafInternalPdmUiFieldCapability.h
- Fwk/AppFwk/cafProjectDataModel/cafPdmXml/cafInternalPdmXmlFieldCapability.h
- Fwk/AppFwk/cafProjectDataModel/cafPdmXml/cafPdmXmlObjectHandleMacros.h
- Fwk/AppFwk/cafProjectDataModel/cafProjectDataModel_UnitTests/cafPdmBasicTest.cpp
Use lowercase for function names
Use const
Remove double '; '
> Cleanup macros used to initialize objects and fields

- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafInternalPdmValueFieldSpecializations.h
- Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafInternalPdmFieldTypeSpecializations.h
- Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafPdmUiFieldSpecialization.h
- Fwk/AppFwk/cafProjectDataModel/cafPdmXml/cafInternalPdmStreamOperators.h
- Fwk/AppFwk/cafProjectDataModel/cafProjectDataModel_UnitTests/AggregatedTypesInField.cpp
- Fwk/AppFwk/cafProjectDataModel/cafProjectDataModel_UnitTests/CMakeLists.txt
- Fwk/AppFwk/cafTests/cafTestApplication/MainWindow.cpp
- Fwk/AppFwk/cafUserInterface/CMakeLists.txt
- Fwk/AppFwk/cafUserInterface/cafPdmUiCheckBoxAndTextEditor.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiCheckBoxAndTextEditor.h
- Fwk/AppFwk/cafUserInterface/cafPdmUiDefaultObjectEditor.cpp
Add support for field of `std::pair<T, U>`. Add UI editor with a check box and a line edit based on conversion to `std::pair<bool, QString>`. 
Add tests for `caf::PdmField<std::pair<bool, double>>` and `caf::PdmField<std::pair<bool, QString>>`
Closes #10030
> Add support for field of std::pair<bool, double> 

- ApplicationLibCode/ProjectDataModel/RimRegularLegendConfig.cpp
This code caused legend config to be reset to 1 number of levels.
> Remove test code related to producer/injector table plots

- ApplicationLibCode/Application/Tools/RiaImportEclipseCaseTools.cpp
- ApplicationLibCode/Application/Tools/RiaImportEclipseCaseTools.h
- ApplicationLibCode/Commands/CMakeLists.txt
- ApplicationLibCode/Commands/RicImportGeneralDataFeature.cpp
- ApplicationLibCode/Commands/RicImportGeneralDataFeature.h
- ApplicationLibCode/FileInterface/RifRoffFileTools.cpp
- ApplicationLibCode/FileInterface/RifRoffFileTools.h
Adding support for loading of multiple roff grid files, or 1 single grid file with N corresponding property files.
----
Closes: #9713 and #9690
> Roff: support import of N grid files and 1 grid file with N property files

- ApplicationLibCode/UserInterface/CMakeLists_files.cmake
- ApplicationLibCode/UserInterface/RiuMainWindow.cpp
- ApplicationLibCode/UserInterface/RiuMenuBarBuildTools.cpp
- ApplicationLibCode/UserInterface/RiuMenuBarBuildTools.h
- ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp
- Create RiuMenuBarBuildTools with utilities for building default/common menus for menubar.
- Synch menu options/actions to have as common as possible setup between MainWindow and PlotMainWindow
Note: Added Roff case import for plot main window
----
Closes: #10040
> Refactor menu building for main windows

- ApplicationLibCode/Application/RiaApplication.cpp
- ApplicationLibCode/Application/Tools/RiaImportEclipseCaseTools.cpp
- ApplicationLibCode/Application/Tools/RiaImportEclipseCaseTools.h
- ApplicationLibCode/Commands/RicImportGeneralDataFeature.cpp
- ApplicationLibCode/Commands/RicImportGeneralDataFeature.h
- ApplicationLibCode/FileInterface/RifEclipseInputFileTools.cpp
- ApplicationLibCode/FileInterface/RifEclipseInputFileTools.h
- ApplicationLibCode/ProjectDataModel/RimEclipseInputCase.cpp
Add import of multiple grid files
Note: Initial implementation utilizes existing code for opening and reading grdecl files. If performance becomes slow, consider creating new method looking for keyword in `RifEclipseTextFileReader`, utilized in `RifEclipseInputFileTools::hasGridData`. The new function can read grdecl file line for line and return true on first hit on keyword. This can prevent reading large amount of file data for a simple check.
---
Closes: #10125
> GRDECL: Import multiple grid files from dialog

- ApplicationLibCode/ProjectDataModelCommands/RimcEclipseCase.cpp
Minor build warning in conversion from std::vector<QString> to QStringList in windows
> Fix warning for conversion from std::vector to QStringList

- Fwk/AppFwk/cafPdmScripting/cafPdmFieldScriptingCapability.h
- Fwk/AppFwk/cafPdmScripting/cafPdmScripting_UnitTests/CMakeLists.txt
- Fwk/AppFwk/cafPdmScripting/cafPdmScripting_UnitTests/cafPdmFieldSerializationTest.cpp
The strings in a string list in a command file are quoted
> Regression Test: Fix parsing of string lists from command file

- Fwk/VizFwk/LibCore/cvfVector4.inl
Found while analyzing static analyzer warnings in the copy that was imported into opm-common.
> fixed: do not compare index 2 twice

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotAxisFormatter.cpp
Qwt uses Qt::mightBeRichText to determine if the axis title is rich text or not. Qt::mightBeRichText is a simple heuristic which checks whether there is something that looks like a tag before the first line break. See: https://doc.qt.io/qt-6/qt-sub-qtgui.html#mightBeRichText
Fixed bug by using html br tag to have at least some html before breaking the line.
Fixes #10209.
> #10209 Plot: fix html axis title

- ApplicationLibCode/Commands/RicWellLogTools.cpp
- ApplicationLibCode/Commands/RicWellLogTools.h
- ApplicationLibCode/Commands/WellLogCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/WellLogCommands/RicNewWellLogCalculatedCurveFeature.cpp
- ApplicationLibCode/Commands/WellLogCommands/RicNewWellLogCalculatedCurveFeature.h
- ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechFaultReactivationResult.cpp
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/CMakeLists_files.cmake
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCalculatedCurve.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogCalculatedCurve.h
- ApplicationLibCode/UnitTests/CMakeLists_files.cmake
- ApplicationLibCode/UnitTests/RimWellLogCalculatedCurve-Test.cpp
- Renaming
- Add math operators
- Add option to select which curve to use as "base" for resampling, or to use union of depth values from both curves
Closes: #10296
> Rename RimWellLogDiffCurve to RimWellLogCalculatedCurve and additional improvements

- ApplicationLibCode/ProjectDataModel/RimMultiPlot.cpp
- ApplicationLibCode/UserInterface/RiuMultiPlotBook.cpp
- ApplicationLibCode/UserInterface/RiuMultiPlotBook.h
When a dock widget in a dock widget tab group is activated, a show event is triggered in `RimMultiPlotBook::showEvent`. This causes a crash if performUpdate is called in showEvent. Make sure the performUpdate is called from `RimMultiPlot::onLoadDataAndUpdate()`
Closes #10349
> Avoid calling performUpdate() in showEvent()

- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPart.cpp
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPart.h
- ApplicationLibCode/ProjectDataModel/Flow/RimWellAllocationPlot.cpp
- ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechFaultReactivationResult.cpp
- ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechFaultReactivationResult.h
- ApplicationLibCode/ReservoirDataModel/RigWellLogCurveData.cpp
- ApplicationLibCode/ReservoirDataModel/RigWellLogCurveData.h
- ApplicationLibCode/UnitTests/CMakeLists_files.cmake
- ApplicationLibCode/UnitTests/RigWellLogCurveData-Test.cpp
- `RimGeoMechFaultReactivationResult`:
- Fix automatic detection of part id
- `RigWellLogCurveData`:
- Fixes resampling bug
- Refactored code for testability
- Added unit tests
---
Closes: #10391
Closes: #10241
> Fix automatic part id detection for Fault Reactivation Result, and resampling bug in RigWellLogCurveData

- .github/workflows/clang-tidy.yml
Make it possible to have temporary code violating clang-tidy fixes in work-in-progress branches
Closes #10428
> clang-tidy: Run on dev and main

- ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp
Grid calculator results was tagged to be stored in cache. No data was stored, but meta data for the result was added. These results are always recalculated when the project is loaded, and `needsToBeStored `is set to false
Related to #10489
> Do not tag calculator results to be stored in cache

- ApplicationLibCode/ProjectDataModel/RimRegularLegendConfig.cpp
- ApplicationLibCode/ProjectDataModel/Surfaces/RimGridCaseSurface.cpp
- Fwk/VizFwk/LibRender/cvfScalarMapperRangeBased.cpp
> Regression test fixes

- ApplicationLibCode/UserInterface/RiuPlotMainWindow.cpp
The call to updateConnectedEditors is very time consuming for summary models with many vectors. Testing indicates that this update is not required.
Closes #10508
> Avoid update connected editors

- ApplicationLibCode/GeoMech/GeoMechDataModel/CMakeLists.txt
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemAddressDefines.cpp
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemAddressDefines.h
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorBarConverted.cpp
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorEnIpPorBar.cpp
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorGamma.cpp
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorMudWeightWindow.cpp
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorNodalGradients.cpp
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorNormalST.cpp
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorNormalized.cpp
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorPoreCompressibility.cpp
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorPorosityPermeability.cpp
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorShearSlipIndicator.cpp
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultCalculatorTimeLapse.cpp
- ApplicationLibCode/GeoMech/GeoMechDataModel/RigFemPartResultsCollection.cpp
- ApplicationLibCode/GeoMech/GeoMechVisualization/RivFemElmVisibilityCalculator.cpp
- ApplicationLibCode/GeoMech/GeoMechVisualization/RivFemPartPartMgr.cpp
- ApplicationLibCode/ModelVisualization/Intersections/RivIntersectionResultsColoringTools.cpp
- ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechCase.cpp
- ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechContourMapProjection.cpp
- ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechResultDefinition.cpp
- ApplicationLibCode/ProjectDataModel/WellPath/RimWellIASettings.cpp
- ApplicationLibCode/ReservoirDataModel/RigGeoMechWellLogExtractor.cpp
- ApplicationLibCode/ReservoirDataModel/RigWbsParameter.cpp
- ApplicationLibCode/UserInterface/RiuFemResultTextBuilder.cpp
> Additional refactoring for POR-Bar result handling

- ApplicationLibCode/GeoMech/GeoMechVisualization/RivFemElmVisibilityCalculator.cpp
- ApplicationLibCode/GeoMech/GeoMechVisualization/RivFemElmVisibilityCalculator.h
- ApplicationLibCode/GeoMech/GeoMechVisualization/RivGeoMechVizLogic.cpp
- ApplicationLibCode/ModelVisualization/RivReservoirViewPartMgr.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilter.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilter.h
- ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.h
- ApplicationLibCode/ProjectDataModel/CellFilters/RimCellRangeFilter.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimPolygonFilter.h
- ApplicationLibCode/ProjectDataModel/CellFilters/RimPropertyFilter.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimUserDefinedFilter.cpp
- ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechContourMapProjection.cpp
> Cell filter performance improvement

- ApplicationLibCode/Commands/CompletionCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/CompletionCommands/RicImportValveTemplatesFeature.cpp
- ApplicationLibCode/Commands/CompletionCommands/RicImportValveTemplatesFeature.h
- ApplicationLibCode/FileInterface/RifEclipseInputFileTools.cpp
- ApplicationLibCode/FileInterface/RifEclipseInputFileTools.h
- ApplicationLibCode/FileInterface/RifReaderEclipseOutput.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimValveTemplate.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimValveTemplate.h
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathAicdParameters.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathAicdParameters.h
- ApplicationLibCode/ProjectDataModel/RiaOpmParserTools.cpp
- ApplicationLibCode/ProjectDataModel/RiaOpmParserTools.h
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/UnitTests/RifEclipseInputFileTools-Test.cpp
> Import of AICD valve definition from text file

- ApplicationLibCode/ModelVisualization/Faults/RivFaultPartMgr.cpp
- ApplicationLibCode/ModelVisualization/RivAnnotationTools.cpp
- ApplicationLibCode/ModelVisualization/RivAnnotationTools.h
- ApplicationLibCode/ModelVisualization/RivTextAnnotationPartMgr.cpp
- ApplicationLibCode/ModelVisualization/RivWellHeadPartMgr.cpp
- ApplicationLibCode/ModelVisualization/RivWellPathPartMgr.cpp
- ResInsightVersion.cmake
NB Merge depending PR before merging this PR
Depending on https://github.com/OPM/ResInsight/pull/10591
> Remove duplicated code

- ApplicationLibCode/UserInterface/CMakeLists_files.cmake
- ApplicationLibCode/UserInterface/RiuGridCrossQwtPlot.cpp
- ApplicationLibCode/UserInterface/RiuGridCrossQwtPlot.h
- ApplicationLibCode/UserInterface/RiuQwtPlotZoomer.h
- ApplicationLibCode/UserInterface/RiuQwtPlotZoomerMultiAxes.cpp
- ApplicationLibCode/UserInterface/RiuQwtPlotZoomerMultiAxes.h
- ApplicationLibCode/UserInterface/RiuSummaryQwtPlot.cpp
- ApplicationLibCode/UserInterface/RiuSummaryQwtPlot.h
> Make sure interactive zoom on a plot with multiple axis works as expected

- ApplicationLibCode/Commands/SummaryPlotCommands/RicCreateDeclineCurvesFeature.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryDeclineCurve.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryDeclineCurve.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryRegressionAnalysisCurve.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryRegressionAnalysisCurve.h
Use `int` as internal representation in sliders , as `time_t` can cause overflow. Never use `time_t`.
Closes #10706
> Avoid use of time_t when using sliders in GUI

- ApplicationLibCode/FileInterface/RifFaultReactivationModelExporter.cpp
- ApplicationLibCode/FileInterface/RifFaultReactivationModelExporter.h
- ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp
- ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.h
- ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechView.cpp
- ResInsightVersion.cmake
> 10678 fault reactivation more materials

- ApplicationLibCode/Commands/PlotTemplateCommands/RicSaveMultiPlotTemplateFeature.cpp
- ApplicationLibCode/Commands/PlotTemplateCommands/RicSummaryPlotTemplateTools.cpp
- ApplicationLibCode/ProjectDataModel/RimMainPlotCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSetCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressModifier.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurveCollection.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryDataSourceStepping.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryMultiPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.h
After merging the cross plot with the summary plot, the sources stepping can be simplified. Remove obsolete sources stepping code, as preparation before fixing other source stepping issues.
> Remove obsolete code

- ApplicationLibCode/FileInterface/RifReaderFmuRft.cpp
- ApplicationLibCode/UnitTests/RifReaderFmuRft-Test.cpp
Find candidate for the observation file name including measurement ID. Make sure that observations are filtered by date.
Closes #10775
> RFT: Improve text import and make sure visibility based on date is working

- ApplicationLibCode/ProjectDataModel/Completions/RimMswCompletionParameters.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimMswCompletionParameters.h
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathCompletionSettings.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathCompletionSettings.h
- ApplicationLibCode/ProjectDataModel/WellPath/RimWellPath.cpp
- ResInsightVersion.cmake
> Make completion settings scriptable

- ApplicationLibCode/Application/RiaPreferences.cpp
- ApplicationLibCode/Commands/ExportCommands/RicExportEclipseSectorModelUi.cpp
- ApplicationLibCode/Commands/ExportCommands/RicExportLgrUi.cpp
- ApplicationLibCode/Commands/RicGridCalculatorUi.cpp
- ApplicationLibCode/Commands/RicUserDefinedCalculatorUi.cpp
- ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlot.cpp
- ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimPlotDataFilterItem.cpp
- ApplicationLibCode/ProjectDataModel/Annotations/RimReachCircleAnnotation.cpp
- ApplicationLibCode/ProjectDataModel/Annotations/RimTextAnnotation.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathFracture.cpp
- ApplicationLibCode/ProjectDataModel/Completions/RimWellPathValve.cpp
- ApplicationLibCode/ProjectDataModel/CorrelationPlots/RimAbstractCorrelationPlot.cpp
- ApplicationLibCode/ProjectDataModel/Flow/RimWellConnectivityTable.cpp
- ApplicationLibCode/ProjectDataModel/GridCrossPlots/RimGridCrossPlotDataSet.cpp
- ApplicationLibCode/ProjectDataModel/RimCustomObjectiveFunctionWeight.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseResultDefinition.cpp
- ApplicationLibCode/ProjectDataModel/RimRegularLegendConfig.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModel.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelPlot.cpp
- ApplicationLibCode/ProjectDataModel/StimPlanModel/RimStimPlanModelTemplate.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveFilter.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleCurveSet.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressSelector.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotManager.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryTimeAxisProperties.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafPdmUiOrdering.cpp
- Fwk/AppFwk/cafProjectDataModel/cafPdmUiCore/cafPdmUiOrdering.h
- Fwk/AppFwk/cafTests/cafTestApplication/MainWindow.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiFormLayoutObjectEditor.cpp
> Refactor LayoutOptions to improve readability

- ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp
- ApplicationLibCode/ProjectDataModel/RimGridCalculation.h
- ApplicationLibCode/ReservoirDataModel/RigActiveCellInfo.cpp
- ApplicationLibCode/ReservoirDataModel/RigActiveCellInfo.h
Make sure the correct Eclipse case is used when extracting values for a variable. Simplify the data extraction using activeReservoirCellIndices
See also #10884
> Make sure data for a variable is using correct case

- ApplicationLibCode/Commands/RicExportGridCalculationExpressionsFeature.cpp
On Linux, the file suffix is not added automatically.
> If empty, add .toml as file suffix

- ApplicationExeCode/CMakeLists.txt
- ApplicationExeCode/empty.cpp
- CMakeLists.txt
> Fix build issues

- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmFieldCapability.h
It is not sufficient with a forward declaration of QString here. Since the vector is created in PdmFieldCapability::attributes() the size of QString must be known at that point.
closes #10950
> Fix insufficient forward declaration

- ApplicationLibCode/GeoMech/OdbReader/CMakeLists.txt
Unity build was recently broken, hard to find source to the broken build. Few files in this library, no unity build is required.
> Disable unity build for OdbReader

- Fwk/AppFwk/CMakeLists.txt
- Fwk/AppFwk/cafHexInterpolator/cafHexInterpolator_UnitTest/CMakeLists.txt
- Fwk/AppFwk/cafPdmCvf/cafPdmCvf_UnitTests/CMakeLists.txt
- Fwk/AppFwk/cafVizExtensions/cafHexGridIntersectionTools/cafHexGridIntersectionTools_UnitTest/CMakeLists.txt
- Fwk/VizFwk/CMakeLists.txt
- Fwk/VizFwk/LibFreeType/CMakeLists.txt
- Fwk/VizFwk/LibIo/CMakeLists.txt
- Fwk/VizFwk/LibRegGrid2D/CMakeLists.txt
- Fwk/VizFwk/LibStructGrid/CMakeLists.txt
- Fwk/VizFwk/LibUtilities/CMakeLists.txt
- Fwk/VizFwk/TestApps/Qt/QtMinimal/CMakeLists.txt
- Fwk/VizFwk/TestApps/Qt/QtMultiView/CMakeLists.txt
- Fwk/VizFwk/TestApps/Qt/QtSnippetRunner/CMakeLists.txt
- Fwk/VizFwk/Tests/CMakeLists.txt
- Fwk/VizFwk/Tests/LibCore_UnitTests/CMakeLists.txt
- Fwk/VizFwk/Tests/LibGeometry_UnitTests/CMakeLists.txt
- Fwk/VizFwk/Tests/LibGuiQt_UnitTests/CMakeLists.txt
- Fwk/VizFwk/Tests/LibIo_UnitTests/CMakeLists.txt
- Fwk/VizFwk/Tests/LibRegGrid2D_UnitTests/CMakeLists.txt
- Fwk/VizFwk/Tests/LibRender_UnitTests/CMakeLists.txt
- Fwk/VizFwk/Tests/LibStructGrid_UnitTests/CMakeLists.txt
- Fwk/VizFwk/Tests/LibUtilities_UnitTests/CMakeLists.txt
- Fwk/VizFwk/Tests/LibViewing_UnitTests/CMakeLists.txt
- Fwk/VizFwk/Tests/SnippetsBasis/CMakeLists.txt
- Fwk/VizFwk/ThirdParty/FreeType/CMakeLists.txt
- Update the minimum required CMake version to 3.15 for Fwk folders that might be used as top level projects.
- Remove the minimum required CMake version from projects that is just included from other top level projects.
Since version 3.19 CMake has been warning that CMake versions below 3.5 is deprecated and support will be removed in the future. This will silence those warning.
By removing the minimum required version check from projects that is not intended as top level projects we avoid redundant checks and simplifies future maintenance.
Closes #10957
> CMake: Update/Remove old minimum version check

- Fwk/AppFwk/cafTests/cafTestApplication/CMakeLists.txt
- Fwk/AppFwk/cafTests/cafTestCvfApplication/CMakeLists.txt
- Fwk/AppFwk/cafUserInterface/CMakeLists.txt
- Fwk/AppFwk/cafUserInterface/cafUserInterface_UnitTests/CMakeLists.txt
The project cafUserInterface requires the library QtSvg because of the use of QSvgRenderer in cafUiIconFactory.cpp. The library has to be linked into the final executable. The target introdicing the dependency should also be the one specifying it.
This allows us to remove the dependency from targets that doesn't directly use QtSvg at all.
Closes #10955
> Add dependency on QtSvg for project cafUserInterface

- ApplicationLibCode/ReservoirDataModel/RigFaultReactivationModelGenerator.cpp
- ApplicationLibCode/ReservoirDataModel/RigGriddedPart3d.cpp
- ResInsightVersion.cmake
Abaqus likes it better that way.
Bump version to dev.03
> Flip Y to get local coordinate element nodes in correct order 

- ApplicationLibCode/Commands/RicImportElementPropertyFeature.cpp
- ApplicationLibCode/Commands/RicImportElementPropertyFeature.h
- ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechCase.cpp
Additional bonus: Improve reload/close element property UI
Closes #10983
> Make sure imported element properties goes to the selected case.

- ApplicationLibCode/FileInterface/RifFaultReactivationModelExporter.cpp
- ApplicationLibCode/FileInterface/RifFaultReactivationModelExporter.h
- ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp
- ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.h
> Minor changes to exported INP file based on feedback and testing

- ApplicationLibCode/FileInterface/RifReaderOpmCommon.cpp
> Fix import of restart data using opm-common

- ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp
- ApplicationLibCode/ProjectDataModel/RimGridCalculation.h
> Grid Calculation: Improve property value address selection

- ApplicationLibCode/FileInterface/RifReaderOpmCommon.cpp
- ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp
- ApplicationLibCode/ProjectDataModel/RimGridCalculation.h
- ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.cpp
- ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.h
- read data for a single time step
- calculate expression
- if input data source is not a `Generated` result, release memory
Avoid caching data in opm-common file reader.
Allow selection of a grid case group to perform a calculation on all cases in a grid group.
Closes #11089
> Reduce memory use during grid calculation

- ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp
- ApplicationLibCode/ProjectDataModel/RimGridCalculation.h
- ResInsightVersion.cmake
Wrong version of `opm-common` was used in a previous commit. Set to correct version.
Use correct type when selecting a grid case group.
> Set correct version of opm-common and fix use of grid case group

- ApplicationLibCode/Application/Tools/RiaSummaryTools.cpp
- ApplicationLibCode/Application/Tools/RiaSummaryTools.h
- ApplicationLibCode/Commands/CompletionExportCommands/RicExportFractureCompletionsImpl.cpp
- ApplicationLibCode/Commands/RicDeleteTemporaryLgrsFeature.cpp
- ApplicationLibCode/Commands/RicImportGridModelFromSummaryCaseFeature.cpp
- ApplicationLibCode/Commands/RicImportGridModelFromSummaryCaseFeature.h
- ApplicationLibCode/Commands/RicImportGridModelFromSummaryCurveFeature.cpp
- ApplicationLibCode/Commands/RicReloadCaseFeature.cpp
- ApplicationLibCode/Commands/RicReloadSummaryCaseFeature.cpp
- ApplicationLibCode/Commands/RicReloadSummaryCaseFeature.h
- ApplicationLibCode/Commands/RicReplaceCaseFeature.cpp
- ApplicationLibCode/Commands/RicReplaceSummaryCaseFeature.cpp
- ApplicationLibCode/Commands/RicReplaceSummaryCaseFeature.h
- ApplicationLibCode/ProjectDataModel/Flow/RimWellRftPlot.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseCase.cpp
- ApplicationLibCode/ProjectDataModel/RimReloadCaseTools.cpp
- ApplicationLibCode/ProjectDataModel/RimReloadCaseTools.h
- ApplicationLibCode/ProjectDataModel/RimSimWellInViewTools.cpp
- ApplicationLibCode/ProjectDataModel/RimTimeStepFilter.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimRftCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.h
> Improve reload and replace of cases

- GrpcInterface/GrpcProtos/PdmObject.proto
- GrpcInterface/Python/rips/pdmobject.py
- GrpcInterface/Python/rips/tests/test_object_lifetime.py
- GrpcInterface/RiaGrpcCallbacks.h
- GrpcInterface/RiaGrpcCaseService.cpp
- GrpcInterface/RiaGrpcGridService.cpp
- GrpcInterface/RiaGrpcHelper.cpp
- GrpcInterface/RiaGrpcHelper.h
- GrpcInterface/RiaGrpcNNCPropertiesService.cpp
- GrpcInterface/RiaGrpcPdmObjectService.cpp
- GrpcInterface/RiaGrpcPdmObjectService.h
- GrpcInterface/RiaGrpcPropertiesService.cpp
- GrpcInterface/RiaGrpcServiceInterface.cpp
- GrpcInterface/RiaGrpcServiceInterface.h
- GrpcInterface/RiaGrpcSimulationWellService.cpp
> Prototype delete of object from Python

- ApplicationLibCode/UserInterface/RiuSummaryQuantityNameInfoProvider.cpp
- ResInsightVersion.cmake
> Fix *GGLIT summary vector

- ApplicationLibCode/ProjectDataModel/RimEclipseCase.cpp
Calculation of the bounding box for main grid used to be on demand. This was changed in a previous commit. The computation of bounding box is now done first.
The regression was introduced in 51517177435fd0d7cf2d9fd60bb7b1c3e7517cee
> Fix computation of bounding box main grid

- Fwk/AppFwk/cafProjectDataModel/cafProjectDataModel_UnitTests/CMakeLists.txt
The project cafProjectDataModel_UnitTests was triggering multiple CMake warnings saying that the Widget component was missing when trying to collect dependencies.
The warnings can be seen here for example: 
https://github.com/OPM/ResInsight/actions/runs/7753949547/job/21146279132#step:8:94
> Add missing Qt component to silence CMake warnings

- ApplicationLibCode/ProjectDataModel/WellLog/RimRftTools.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimRftTools.h
- ApplicationLibCode/ProjectDataModel/WellLog/RimRftTopologyCurve.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimRftTopologyCurve.h
- ApplicationLibCode/ProjectDataModel/WellLog/RimWellLogRftCurve.cpp
The segment symbol is displayed once per segment. Previous code used segment start as symbol location. Add support for selecting the location for the segment indicator, either start, mid or end.
When reading segment property values, always use segment end as the curve is plotted using step left.
Closes #11069
> RFT segment topology

- Fwk/AppFwk/cafProjectDataModel/cafPdmCore/cafPdmReferenceHelper.cpp
- Fwk/AppFwk/cafUserInterface/cafMemoryInspector.cpp
- Fwk/AppFwk/cafUserInterface/cafPdmUiTreeSelectionEditor.cpp
Qt::SkipEmptyParts was introduced in Qt 5.14 and QString::SkipEmptyParts was deprecated in Qt 5.15. This will avoid warnings when compiling with Qt 5.15.
Just a very tiny change that will benefit those few building with Qt 5.15 only.
> Use correct qt version check for SkipEmptyParts

- ApplicationLibCode/FileInterface/RifFaultReactivationModelExporter.cpp
- ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.cpp
- ApplicationLibCode/ProjectDataModel/Faults/RimFaultReactivationModel.h
Add expansion material parameter (requires updated XML)
> Fault reactivation: Use S5 for top, fault and base surfaces.

- ApplicationLibCode/Commands/RicUserDefinedCalculatorUi.cpp
- ApplicationLibCode/FileInterface/RifEclEclipseSummary.h
- ApplicationLibCode/FileInterface/RifMultipleSummaryReaders.cpp
- ApplicationLibCode/FileInterface/RifMultipleSummaryReaders.h
- ApplicationLibCode/FileInterface/RifOpmCommonSummary.h
- ApplicationLibCode/FileInterface/RifOpmHdf5Summary.h
- ApplicationLibCode/FileInterface/RifReaderEclipseSummary.h
- ApplicationLibCode/FileInterface/RifSummaryReaderInterface.cpp
- ApplicationLibCode/FileInterface/RifSummaryReaderInterface.h
- ApplicationLibCode/ProjectDataModel/RimSummaryCalculation.cpp
- ApplicationLibCode/ProjectDataModel/RimSummaryCalculationCollection.cpp
- ApplicationLibCode/ProjectDataModel/RimSummaryCalculationCollection.h
- ApplicationLibCode/ProjectDataModel/RimUserDefinedCalculationCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimCalculatedSummaryCurveReader.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimCalculatedSummaryCurveReader.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryAddressCollection.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCase.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.h
- ResInsightVersion.cmake
> Improve summary calculation performance

- ApplicationLibCode/Application/Tools/RiaEclipseUnitTools.cpp
Closes #11231
Previous unit conversion factor (scaling factor is 1.0e6 / 5800)
Corrected conversion factor (scaling factor is 1.0e3 / 5614.63)
> Use consistent scaling factor for gas rates in field units

- ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp
- ApplicationLibCode/ProjectDataModel/RimGridCalculation.h
Avoid release of memory when working on a single case
Closes #11258
> Grid Calculation: Unintended release of result data memory

- Fwk/AppFwk/CommonCode/CMakeLists.txt
- Fwk/AppFwk/CommonCode/cafEffectGenerator.cpp
- Fwk/AppFwk/CommonCode/cafUtils.cpp
- Fwk/AppFwk/CommonCode/cafUtils.h
- Fwk/AppFwk/cafViewer/CMakeLists.txt
- Fwk/AppFwk/cafViewer/cafCadNavigation.cpp
- Fwk/AppFwk/cafViewer/cafCeetronNavigation.cpp
- Fwk/AppFwk/cafViewer/cafCeetronPlusNavigation.cpp
- Fwk/AppFwk/cafVizExtensions/CMakeLists.txt
- Fwk/CMakeLists.txt
I just wanted to make a tiny contribution to issue #10567.
- Add possibility to use Qt6 to more Fwk libraries.
- Update includes to work with Qt6 as well
- Use updated qt-functions for cursor position and scrolling. 
The following still remains for Fwk to be ready for Qt6:
- There are a few libraries that I have not migrated (including some unit test libraries)
- caf::OpenGLWidget in cafViewer does not work with Qt6. It is not used anymore after commit 8e13d6c5283b4a7a5363da2215f7a475aa3d4f1b so it might as well be removed completely?
> Prepare building with Qt6

- ApplicationLibCode/GeoMech/GeoMechVisualization/RivFemElmVisibilityCalculator.cpp
- ApplicationLibCode/GeoMech/GeoMechVisualization/RivFemElmVisibilityCalculator.h
- ApplicationLibCode/GeoMech/GeoMechVisualization/RivGeoMechVizLogic.cpp
- ApplicationLibCode/ModelVisualization/RivReservoirViewPartMgr.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.cpp
- ApplicationLibCode/ProjectDataModel/CellFilters/RimCellFilterCollection.h
- ApplicationLibCode/ProjectDataModel/GeoMech/RimGeoMechContourMapProjection.cpp
> Support both AND and OR operations when combining range and index filters

- ApplicationLibCode/FileInterface/RifSurfaceImporter.cpp
> Do not crash if no valid points are found when importing a surface .dat file

- ApplicationExeCode/RiaGrpcConsoleApplication.cpp
Increase polling interval to avoid using one core constantly.
Fixes #11285.
> #11285 GRPC: fix high CPU usage in console application

- ApplicationLibCode/Application/Tools/RiaFilePathTools.cpp
- ApplicationLibCode/FileInterface/RifOpmCommonSummary.cpp
- ApplicationLibCode/ProjectDataModel/RimSummaryCalculationCollection.cpp
- ApplicationLibCode/ProjectDataModel/RimSummaryCalculationCollection.h
- ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
- ApplicationLibCode/UnitTests/RiaFilePathTools-Test.cpp
Closes #11297
Tested on Windows and Linux with significantly improved performance.
> Summary performance improvements

- ApplicationLibCode/FileInterface/RifPressureDepthTextFileReader.cpp
- ApplicationLibCode/FileInterface/RifPressureDepthTextFileReader.h
- ApplicationLibCode/UnitTests/RifPressureDepthTextFileReader-Test.cpp
> Allow field units when importing RFT pressures

- ApplicationLibCode/Commands/WellPathCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/WellPathCommands/RicSetParentWellPathFeature.cpp
- ApplicationLibCode/Commands/WellPathCommands/RicSetParentWellPathFeature.h
- ApplicationLibCode/ProjectDataModel/RimContextCommandBuilder.cpp
- ApplicationLibCode/ProjectDataModel/RimTools.h
- ApplicationLibCode/ProjectDataModel/WellPath/RimWellPath.h
- ApplicationLibCode/ProjectDataModel/WellPath/RimWellPathTieIn.cpp
- ApplicationLibCode/ProjectDataModel/WellPath/RimWellPathTieIn.h
Setting parent well directly from Property Editor caused crash. Use a feature to connect a well to a parent well.
Closes #11313
Closes #11312
> Add feature to set parent well

- Fwk/AppFwk/CommonCode/cvfStructGrid.cpp
Well pipe radius would become HUGE_VAL due to off-by-one error. The assert could only happen on model with a single cell.
Fixes #11310.
> #11310 Fix assert on single cell model.

- ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.cpp
This PR reverts wrong behaviour introduced in a880a42 causing missing restart history when using `ESMRY` files. The original performance improvement was tested with wrong/incomplete test data.
Closes #11337
Related to #11342
> Summary import: Make sure ESMRY includes restart history

- ApplicationLibCode/Application/RiaResultNames.cpp
- ApplicationLibCode/Application/RiaResultNames.h
- ApplicationLibCode/FileInterface/RifEclipseInputFileTools.cpp
- ApplicationLibCode/FileInterface/RifEclipseInputPropertyLoader.cpp
- ApplicationLibCode/FileInterface/RifHdf5SummaryExporter.cpp
- ApplicationLibCode/FileInterface/RifHdf5SummaryExporter.h
- ApplicationLibCode/FileInterface/RifOpmCommonSummary.cpp
- ApplicationLibCode/FileInterface/RifReaderEclipseSummary.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseResultCase.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseResultDefinition.cpp
- ApplicationLibCode/ProjectDataModel/RimGridCalculation.cpp
- ApplicationLibCode/ProjectDataModel/RimGridCalculation.h
- ApplicationLibCode/ProjectDataModel/Summary/RimFileSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
- ApplicationLibCode/ReservoirDataModel/RigCaseCellResultsData.cpp
- ApplicationLibCode/UnitTests/HDF5FileWriter-Test.cpp
- ApplicationLibCode/UserInterface/RiuViewer.cpp
- Fwk/AppFwk/CommonCode/cvfStructGrid.cpp
- ResInsightVersion.cmake
Closes #11352
Closes #11353
Closes #11355
Closes #11337 
Closes #11359
> Fixes for patch 2024.03.1

- ApplicationLibCode/Commands/RicContourMapPickEventHandler.cpp
- ApplicationLibCode/ProjectDataModel/RimContourMapProjection.cpp
- ApplicationLibCode/ProjectDataModel/RimContourMapProjection.h
> Fix eclipse case contour map left click

- .github/workflows/ResInsightWithCache.yml
- ApplicationExeCode/CMakeLists.txt
The OpenSSL library from vcpkg is unlikely to be the one needed by Qt.
> OpenSSL: remove OpenSSL bundling.

- ApplicationLibCode/FileInterface/RifArrowTools.cpp
- ApplicationLibCode/FileInterface/RifArrowTools.h
- ApplicationLibCode/FileInterface/RifByteArrayArrowRandomAccessFile.h
- ApplicationLibCode/FileInterface/RifOsduWellLogReader.cpp
- ApplicationLibCode/FileInterface/RifOsduWellPathReader.cpp
- ApplicationLibCode/UnitTests/RifParquetReader-Test.cpp
- ApplicationLibCode/pch.h
The arrow library has a function parameter called `signals` that causes trouble when compiled using Qt. Add undef signals to avoid this issue.
> Fix compiler issue when importing arrow

- CMakeLists.txt
For internal builds, support picking up libraries  from internal build server.
Set RESINSIGHT_DOWNLOAD_ODB_FROM_SERVER to On and set RESINSIGHT_ODB_VERSION to "2020" or "2024" depending on the version you want. 2020 is default (for now)
When switching versions, it is recommended to delete the CMake cache and reconfigure.
> ODB 2020 and 2024 support

- ApplicationLibCode/Application/RiaApplication.cpp
- ApplicationLibCode/Commands/OsduImportCommands/RicWellPathsImportOsduFeature.cpp
- ApplicationLibCode/Commands/RicImportWellLogOsduFeature.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimOsduWellLogDataLoader.cpp
- ApplicationLibCode/ProjectDataModel/WellPath/RimOsduWellPathDataLoader.cpp
- ApplicationLibCode/ProjectDataModel/WellPath/RimWellPathCollection.cpp
Show more details when support for SSL is missing.
Move connection of signal/slot away from constructor. This makes it possible to use ResInsight even if SSL is not available.
> Improve error handling when trying to access OSDU data

- ApplicationLibCode/Application/RiaSummaryDefines.cpp
- ApplicationLibCode/Application/RiaSummaryDefines.h
- ApplicationLibCode/Application/Tools/RiaSummaryTools.cpp
- ApplicationLibCode/Application/Tools/RiaSummaryTools.h
- ApplicationLibCode/FileInterface/RifEclipseSummaryAddressDefines.cpp
- ApplicationLibCode/FileInterface/RifEclipseSummaryAddressDefines.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurvesData.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurvesData.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryDeclineCurve.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryDeclineCurve.h
When resampling a rate curve, the last time period with no data is not affecting the computed range.
Allow user to set Accumulated or Rate for a summary curve. Default value is Auto, and Accumulated/Rate is derived from the summary address.
> Improve user control on resampling operations

- ApplicationLibCode/Application/RiaPreferencesGrid.cpp
- ApplicationLibCode/FileInterface/CMakeLists_files.cmake
- ApplicationLibCode/FileInterface/RifReaderEclipseWell.cpp
- ApplicationLibCode/FileInterface/RifReaderInterface.cpp
- ApplicationLibCode/FileInterface/RifReaderInterface.h
- ApplicationLibCode/FileInterface/RifReaderOpmCommon.cpp
- ApplicationLibCode/FileInterface/RifReaderOpmCommon.h
- ApplicationLibCode/FileInterface/RifReaderOpmCommonActive.cpp
- ApplicationLibCode/FileInterface/RifReaderOpmCommonActive.h
- ApplicationLibCode/ProjectDataModel/RimEclipseCase.cpp
- ApplicationLibCode/ProjectDataModel/RimEclipseResultCase.cpp
- ApplicationLibCode/ReservoirDataModel/CMakeLists_files.cmake
- ApplicationLibCode/ReservoirDataModel/RigActiveCellGrid.cpp
- ApplicationLibCode/ReservoirDataModel/RigActiveCellGrid.h
- ApplicationLibCode/ReservoirDataModel/RigEclipseCaseData.cpp
- ApplicationLibCode/ReservoirDataModel/RigEclipseCaseData.h
- ApplicationLibCode/ReservoirDataModel/RigGridBase.cpp
- ApplicationLibCode/ReservoirDataModel/RigGridBase.h
- ApplicationLibCode/ReservoirDataModel/RigMainGrid.h
- ApplicationLibCode/ReservoirDataModel/RigSimulationWellCenterLineCalculator.cpp
- ApplicationLibCode/ReservoirDataModel/RigWellResultFrame.cpp
- Fwk/AppFwk/CommonCode/cvfStructGrid.h
Closes #228
First version, LGR support disabled when loading only active cells
> Support for loading only active cell geometry

- ApplicationLibCode/ProjectDataModel/AnalysisPlots/RimAnalysisPlotDataEntry.cpp
Avoid assert, and return empty curve definition if both summary case and ensemble is undefined.
> Improve robustness when importing incomplete project file

- ApplicationLibCode/FileInterface/RifEclipseInputFileTools.cpp
- ApplicationLibCode/UnitTests/TestData/RifEclipseInputFileTools/pflotran/include/ccs_3df_kh.grdecl
The include statements can optionally have a `/` at the end of the line. Make sure the parsing handles this correctly.
> Improve robustness when parsing PFLOTRAN files

- GrpcInterface/Python/rips/tests/test_cases.py
- GrpcInterface/Python/rips/tests/test_object_lifetime.py
- GrpcInterface/Python/rips/tests/test_project.py
Using `is` in this way has been triggering a SyntaxWarning since Python 3.8
> Solve Python SyntaxWarning when running tests

- ApplicationLibCode/UserInterface/RiuRelativePermeabilityPlotPanel.cpp
Changed names from buttonClicked to idClicked.
> Qt6: update to changed name of QButtonGroup signal.

- ApplicationExeCode/RiaMain.cpp
To be replaced by proper fix late (ref #11745)
> Fix incorrect opengl viewport size on Windows if scaling != 100%. 

- .github/workflows/ResInsightWithCache.yml
- GrpcInterface/Python/build-requirements.txt
- GrpcInterface/Python/setup.py.cmake
Closes #11772
`ortools` will be installed in the same environment as `rips.` Use same pinning to make sure compability between `rips` and `ortool.`
The main point is to make sure we do not use `libprotoc` 27 or newer, as this causes issues when importing the `rips` module.
https://developers.google.com/optimization
> Python: Add pinning to be compatible with ortools

- ApplicationLibCode/ReservoirDataModel/RigCellGeometryTools.cpp
- ApplicationLibCode/UnitTests/RigCellGeometryTools-Test.cpp
When converting a cvf::Vec3d to an integer vector, the platform int type was used as an intermediate variable. This caused overflow for large double values.
Closes #11798
Closes #11243
> Use type definition from ClipperLib to avoid overflow

- ApplicationLibCode/Application/Tools/Cloud/RiaSumoConnector.cpp
- ApplicationLibCode/FileInterface/RifSummaryReaderInterface.cpp
- ApplicationLibCode/FileInterface/RifSummaryReaderInterface.h
- ApplicationLibCode/ProjectDataModel/Summary/Sumo/RimSummaryCaseSumo.cpp
> Align the search expression with sumo explorer

- ApplicationLibCode/Application/Tools/RiaTextStringTools.cpp
- ApplicationLibCode/Application/Tools/RiaTextStringTools.h
```
/home/akva/kode/opm/ResInsight/ApplicationLibCode/Application/Tools/RiaTextStringTools.cpp:212:22: error: redefinition of ‘std::strong_ordering operator<=>(const QString&, const QString&)’
212 | std::strong_ordering operator<=>( const QString& lhs, const QString& rhs )
|                      ^~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt6/QtCore/qglobal.h:63,
from /usr/include/x86_64-linux-gnu/qt6/QtCore/qregularexpression.h:9,
from /usr/include/x86_64-linux-gnu/qt6/QtCore/QRegularExpression:1,
from /home/akva/kode/opm/ResInsight/ApplicationLibCode/Application/Tools/RiaTextStringTools.h:21,
from /home/akva/kode/opm/ResInsight/ApplicationLibCode/Application/Tools/RiaTextStringTools.cpp:19:
/usr/include/x86_64-linux-gnu/qt6/QtCore/qstring.h:777:5: note: …
```
> fixed: build against QT 6.8

- ApplicationLibCode/Commands/CellFilterCommands/RicNewPolygonFilterFeature.cpp
- ApplicationLibCode/Commands/CrossSectionCommands/RicNewPolygonIntersectionFeature.cpp
- ApplicationLibCode/Commands/CrossSectionCommands/RicNewPolygonIntersectionFeature.h
- ApplicationLibCode/Commands/PolygonCommands/CMakeLists_files.cmake
- ApplicationLibCode/Commands/PolygonCommands/RicBasicPolygonFeature.cpp
- ApplicationLibCode/Commands/PolygonCommands/RicBasicPolygonFeature.h
- ApplicationLibCode/Commands/PolygonCommands/RicDuplicatePolygonFeature.cpp
- ApplicationLibCode/Commands/PolygonCommands/RicDuplicatePolygonFeature.h
- ApplicationLibCode/Commands/PolygonCommands/RicExportPolygonCsvFeature.cpp
- ApplicationLibCode/Commands/PolygonCommands/RicExportPolygonCsvFeature.h
- ApplicationLibCode/Commands/PolygonCommands/RicExportPolygonPolFeature.cpp
- ApplicationLibCode/Commands/PolygonCommands/RicExportPolygonPolFeature.h
- ApplicationLibCode/Commands/PolygonCommands/RicReloadPolygonFileFeature.cpp
- ApplicationLibCode/Commands/PolygonCommands/RicSimplifyPolygonFeature.cpp
- ApplicationLibCode/Commands/PolygonCommands/RicSimplifyPolygonFeature.h
- ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonFile.cpp
- ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonTools.cpp
- ApplicationLibCode/ProjectDataModel/Polygons/RimPolygonTools.h
> Polygon command updates

- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryEnsembleTools.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryEnsembleTools.h
- ApplicationLibCode/UserInterface/RiuQwtPlotWidget.cpp
- ResInsightVersion.cmake
#11771 introduced support for highlighting of curves belonging to the same realization. This change introduced a bug making it impossible to highlight curves for a single summary file.
> Fix curve highlight for non-ensemble curves

- ApplicationLibCode/UserInterface/RiuRelativePermeabilityPlotPanel.cpp
- ApplicationLibCode/UserInterface/RiuRelativePermeabilityPlotPanel.h
> Rel perm plot legend adjustments

- ApplicationExeCode/CMakeLists.txt
- GrpcInterface/CMakeLists.txt
- vcpkg-configuration.json
- vcpkg.json
A `msys` package was removed from the upstream distribution server, causing a new build on a blank system to fail. The issue is not seen if the binary is cached locally by `vcpkg`. To fix this, a newer `vcpkg.exe` was required. When this was done, several other issues appeared.
Baseline for `vcpkg` is now set to `2025.01.11`
- Use `fmt 10.1.1` to avoid compile bug on `MSVC`
- Avoid pinning of `Protobuf`
- Remove obsolete `Protobuf` at top level
https://github.com/apache/arrow/issues/42027
https://github.com/microsoft/vcpkg/issues/42965
https://github.com/microsoft/vcpkg-tool/releases/tag/2025-01-11
> Bump vcpkg

- .github/workflows/ResInsightWithCache.yml
- vcpkg_no_grpc.json
The grpc package installed as part of vcpkg is huge, and is rejected from the build cache on GitHub Action. This causes a very long build time.
Temporarily disable build of grpc on GitHub Actions
> GHA: Disable install and use of grpc on GitHub Actions

- ApplicationLibCode/Application/Tools/Summary/RiaSummaryAddressAnalyzer.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlotSourceStepping.cpp
Avoid stripping extension H/_DIFF during summary address analysis. Strip extension only for plot title and source stepping in toolbar.
> #9925 Use stripped vector name for stepping and title

- Fwk/AppFwk/cafUserInterface/cafPdmUiFilePathEditor.h
This ensures all files are shown, also those without extension on Linux
> Use single * as default "all files" filter 

- ApplicationLibCode/Application/RiaApplication.cpp
- ApplicationLibCode/Application/Tools/RiaEnsembleNameTools.cpp
- ApplicationLibCode/Application/Tools/RiaEnsembleNameTools.h
- ApplicationLibCode/Application/Tools/Summary/RiaSummaryStringTools.cpp
- ApplicationLibCode/Application/Tools/Summary/RiaSummaryTools.cpp
- ApplicationLibCode/Application/Tools/Summary/RiaSummaryTools.h
- ApplicationLibCode/Commands/RicDeleteSummaryCaseCollectionFeature.cpp
- ApplicationLibCode/Commands/RicImportEnsembleFeature.cpp
- ApplicationLibCode/Commands/SummaryPlotCommands/RicNewDerivedEnsembleFeature.cpp
- ApplicationLibCode/Commands/SummaryPlotCommands/RicReplaceSummaryEnsembleFeature.cpp
- ApplicationLibCode/ProjectDataModel/Cloud/RimCloudDataSourceCollection.cpp
- ApplicationLibCode/ProjectDataModel/RimProject.cpp
- ApplicationLibCode/ProjectDataModel/RimSummaryCalculationCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimDeltaSummaryEnsemble.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCaseMainCollection.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryEnsemble.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryEnsemble.h
- ApplicationLibCode/ProjectDataModel/Summary/Sumo/RimSummaryEnsembleSumo.cpp
- ApplicationLibCode/UserInterface/RiuSummaryVectorSelectionUi.cpp
Closes #12282
Renaming to use the term `ensemble` instead of `summaryCaseCollection`
> Improve auto naming to avoid ensembles with identical names

- ThirdParty/Ert/lib/ecl/ecl_grid.cpp
> Bugfix: avoid keeping init file open when using resdata reader

- .github/workflows/ResInsightWithCache.yml
Make the trigger for publish to PyPi more general
Closes #12354
> GHA: Skip check on event_name

- ApplicationLibCode/Application/Tools/RiaCurveMerger.h
- ApplicationLibCode/Application/Tools/RiaCurveMerger.inl
- ApplicationLibCode/FileInterface/RifReaderEnsembleStatisticsRft.cpp
- ApplicationLibCode/ProjectDataModel/RimSummaryCalculation.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimDeltaSummaryCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimEnsembleStatisticsCase.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurve.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurvesData.cpp
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryCurvesData.h
- ApplicationLibCode/ProjectDataModel/Summary/RimSummaryPlot.cpp
- ApplicationLibCode/ProjectDataModel/WellLog/RimEnsembleWellLogStatistics.cpp
- ApplicationLibCode/UnitTests/RigTimeCurveHistoryMerger-Test.cpp
A performance fix for resampling was introduced in 118ecf941adc4214fe764afc55875fc04103bbeb. This fix revealed a weakness in the code used to create the values for P90/P10/mean curves in `Show Plot Data`. To mitigate this issue, the `RiaCurveMerger` has learned how to interpolate using linear, step right or step left.
When the fix for this issue is used, comparing with Excel now gives identical results for mean. P10 and P90 has still some (small) difference compared to Excel, and this is probably due to individual resampling of each curve. These differences were also present before the performance fix.
The resampling in `Show Plot Data` is based on values in each individual curve. The resampling operation happens in the text producing code, and is independent to the other curves. The …
> Fix resampling issue for statistics curves
